/*
	Incident No.	: ONE-11702
	Responsible		: Hörður Kristjánsson
	Sprint			: Akita
	Date created	: 19.03.2020

	Description		: Adding all missing KDS update scripts into one. KDS scripts 00611-01 - 00642-00

	Skipped scripts:
		* 00613-00: We want to keep bool columns as bit, not change them to another data type
		* 00613-01: Same as above
		* 00613-02: Same as above
		* 00613-03: Same as above
		* 00613-04: Same as above
		* 00613-05: Same as above
		* 00614-00: Same as above
		* 00620-00: This script is only adding a "RecId" which is only relevant for LS First
		* 00630-00: The tables created in this script are dropped and re-created in 00631-00
		* 00632-00: Merged into the changes from 00631-00, since this script was just modifying the columns we just created

	Modified scripts:
		* 00631-00: Skipped adding "RecId" columns. Skipped dropping tables since we don't create them in the first place (script 00630-00 is skipped)
*/

USE LSPOSNET
GO

/*
	KDS Script		: 00611-01
	Incident No.	: N/A
	Responsible		: Hörður Kristjánsson
	Sprint			: N/A
	Date created	: 08.04.2015

	Description		: Adding new column to KITCHENDISPLAYPRINTER
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYPRINTER' AND COLUMN_NAME = 'CUTPAPER')
BEGIN
	ALTER TABLE KITCHENDISPLAYPRINTER ADD CUTPAPER bit
END
GO

/*
	KDS Script		: 00611-02
	Incident No.	: N/A
	Responsible		: Sigurður Ragnarsson
	Sprint			: N/A
	Date created	: 08.04.2015

	Description		: Adding new column to KITCHENDISPLAYPRINTER
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYPRINTER' AND COLUMN_NAME = 'OPOSMAXCHARS')
BEGIN
	ALTER TABLE KITCHENDISPLAYPRINTER ADD OPOSMAXCHARS int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYPRINTER' AND COLUMN_NAME = 'OPOSFONTSIZEV')
BEGIN
	ALTER TABLE KITCHENDISPLAYPRINTER ADD OPOSFONTSIZEV int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYPRINTER' AND COLUMN_NAME = 'OPOSFONTSIZEH')
BEGIN
	ALTER TABLE KITCHENDISPLAYPRINTER ADD OPOSFONTSIZEH int
END
GO

/*
	KDS Script		: 00612-00
	Incident No.	: XXX
	Responsible		: Kristjan Asvaldsson
	Sprint			: LS ONE 2015
	Date created	: 09.07.2015

	Description		: Add new table for Kitchen Device status

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: KITCHENDEVICESTATUS
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'ROUTETOSTATIONID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD ROUTETOSTATIONID NVARCHAR(20)
END
GO


/*
	KDS script		: 00615-00
	Incident No.	: NAV-3685
	Responsible		: Sigurður Ragnarsson
	Sprint			: Hurricane
	Date created	: 08.03.2016

	Description		: Modifying KITCHENDISPLAYSTYLEPROFILE to support requirements from AAFES
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'HEAVYITEMMODIFIERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD HEAVYITEMMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'LIGHTITEMMODIFIERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD LIGHTITEMMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERHEAVYPREFIX')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD ITEMMODIFIERHEAVYPREFIX  nvarchar(30) NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERLIGHTPREFIX')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD ITEMMODIFIERLIGHTPREFIX  nvarchar(30) NULL
END
GO

/*
	KDS script		: 00616-00
	Incident No.	: NAV-4021
	Responsible		: Sigurður Ragnarsson
	Sprint			: Mustang
	Date created	: 28.04.2016

	Description		: Modifying KITCHENDISPLAYSTYLEPROFILE and KITCHENDISPLAYVISUALPROFILE to support itemmodifier requirements from AAFES
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ONLYITEMMODIFIERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ONLYITEMMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERONLYPREFIX')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD ITEMMODIFIERONLYPREFIX  nvarchar(30) NULL
END
GO


/*
	KDS script		: 00617-00
	Incident No.	: NAV-4024
	Responsible		: Sigurður Ragnarsson
	Sprint			: Mustang
	Date created	: 06.06.2016

	Description		: Add new field for new Chit header style (Transaction Comment line)
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'TRANSACTCOMMENTSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD TRANSACTCOMMENTSTYLEID UNIQUEIDENTIFIER
END

/*
	KDS script		: 00618-00
	Incident No.	: NAV-4378
	Responsible		: Arnþór Magnússon
	Date created	: 22.06.2016

	Description		: Add new table to assign display station to store.
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYSTATIONSTORE')
BEGIN
	CREATE TABLE KITCHENDISPLAYSTATIONSTORE(
	ID uniqueidentifier NOT NULL DEFAULT (newid()),
	KITCHENDISPLAYSTATIONID nvarchar(20) NOT NULL,
	STOREID nvarchar(1024) NOT NULL,
	DATAAREAID nvarchar(4) NOT NULL,
	CONSTRAINT [PK_KITCHENDISPLAYSTATIONSTORE] PRIMARY KEY CLUSTERED 
	(
		ID ASC,
		DATAAREAID ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

/*
	KDS script		: 00619-00
	Incident No.	: KDS-24
	Responsible		: Sigurður Ragnarsson
	Date created	: 12.08.2016

	Description		: Add new field in table KITCHENDISPLAYPRINTER
						
*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYPRINTER' AND COLUMN_NAME = 'STATIONTYPE')
BEGIN
	ALTER TABLE KITCHENDISPLAYPRINTER ADD STATIONTYPE TINYINT NULL
END
GO


/*

	KDS script		: 00621-00
	Incident No.	: KDS-45
	Responsible		: Kári Mímisson
	Sprint			: Destroyer
	Date created	: 3.10.2016

	Description		: Add setup columns for printer
	
	
	--Tables affected	: KITCHENDISPLAYPRINTER
						
*/
IF NOT EXISTS (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'KITCHENDISPLAYPRINTER ' and COLUMN_NAME = 'LAYOUTTYPE' )
BEGIN
	  ALTER TABLE KITCHENDISPLAYPRINTER ADD LAYOUTTYPE TINYINT
END
IF NOT EXISTS (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'KITCHENDISPLAYPRINTER ' and COLUMN_NAME = 'TOPSPACES' )
BEGIN
	  ALTER TABLE KITCHENDISPLAYPRINTER ADD TOPSPACES INT
END
IF NOT EXISTS (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'KITCHENDISPLAYPRINTER ' and COLUMN_NAME = 'BOTTOMSPACES' )
BEGIN
	  ALTER TABLE KITCHENDISPLAYPRINTER ADD BOTTOMSPACES INT
END	
GO


/*
	KDS script		: 00622-00
	Incident No.	: KDS-45
	Responsible		: Sigurður Ragnarsson
	Sprint			: Destroyer
	Date created	: 03.10.2016

	Description		: Add column to control whether output is directed to logfile or printer

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: KITCHENDISPLAYPRINTER
                     

*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYPRINTER' AND COLUMN_NAME = 'DIRECTTOLOGFILE')
BEGIN
	ALTER TABLE KITCHENDISPLAYPRINTER ADD DIRECTTOLOGFILE TINYINT;
END

GO



/*
	KDS script		: 00623-00
	Incident No.	: KDS-64 and KDS-59
	Responsible		: Kári Mímisson
	Sprint			: Airbush 380
	Date created	: 10.10.2016

	Description		: Modifying KITCHENDISPLAYVISUALPROFILE to support itemmodifier requirements from AAFES
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERDONEPREFIX')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD ITEMMODIFIERDONEPREFIX  NVARCHAR(30) NULL
END




/*
	KDS script		: 00624-00
	Incident No.	: KDS-64 and KDS-59
	Responsible		: Kári Mímisson
	Sprint			: Airbush 380
	Date created	: 10.10.2016

	Description		: Modifying KITCHENDISPLAYVISUALPROFILE to support itemmodifier requirements from AAFES
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMRUSHSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ITEMRUSHSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DONEITEMMODIFIERUISTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD DONEITEMMODIFIERUISTYLEID UNIQUEIDENTIFIER
END
GO


/*
	KDS script		: 00626-00
	Incident No.	: KDS-93
	Responsible		: Sigurður Ragnarsson
	Sprint			: Apache
	Date created	: 09.12.2016

	Description		: Added style ID for background color of chit when marked for alert (allergy)
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ALERTSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ALERTSTYLEID UNIQUEIDENTIFIER
END
GO


/*
	KDS script		: 00627-00
	Incident No.	: KDS-95
	Responsible		: Sigurður Ragnarsson
	Sprint			: 
	Date created	: 27.01.2017

	Description		: Added filemax for files kept in archive folder on display stations. Default is 100;
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'RECALLFILESMAX')
BEGIN
	alter table KITCHENDISPLAYSTATION ADD RECALLFILESMAX int default 100;
END
GO


/*
	KDS script		: 00628-00
	Incident No.	: KDS-95
	Responsible		: Sigurður Ragnarsson
	Sprint			: 
	Date created	: 27.01.2017

	Description		: Added filemax for files kept in archive folder on display stations. Default is 100;
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILE' AND COLUMN_NAME = 'DONEORDERSAPPEAR')
BEGIN
	alter table KITCHENDISPLAYFUNCTIONALPROFILE ADD DONEORDERSAPPEAR int default 0;
END


/*
	KDS script		: 00629-00
	Incident No.	: KDS-154
	Responsible		: Sigurður Ragnarsson
	Sprint			: 
	Date created	: 09.02.2017

	Description		: Added enum value for type of overlay when chit is Done (0 = The good old Beziercurve)
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DONECHIT_OVERLAYTYPE')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD DONECHIT_OVERLAYTYPE int default 0
END


/*
	KDS script		: 00631-00
	Incident No.	: KDS-158
	Responsible		: Sigurður Ragnarsson
	Sprint			: Paris Brest
	Date created	: 17.02.2017

	Description		: Add new tables for chit- and linedisplay header/footer configuration
						
*/
--Clean up from script 00630-00.sql (redesigned in this script)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'DISPLAYPROFILEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD DISPLAYPROFILEID uniqueidentifier
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYPROFILE')
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYPROFILE (
		[ID] uniqueidentifier NOT NULL DEFAULT (newid()),
		[DISPLAYMODE] int,
		[NAME] varchar(100),
		[DATAAREAID] nvarchar(4) NOT NULL		
		CONSTRAINT [PK_KITCHENDISPLAYPROFILE] PRIMARY KEY CLUSTERED 
		(
			[ID],
			[DATAAREAID]
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
		) ON [PRIMARY]
		
	END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYLINE')
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYLINE (
		[ID] uniqueidentifier NOT NULL DEFAULT (newid()),
		[DATAAREAID] nvarchar(4) NOT NULL,
		[DISPLAYPROFILEID] uniqueidentifier NOT NULL,
		[LINETYPE] int,
		[LINENUMBER] int
		CONSTRAINT [PK_KITCHENDISPLAYLINE] PRIMARY KEY CLUSTERED 
		(
		    [ID],
			[DATAAREAID]
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
		) ON [PRIMARY]
		
	END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYLINECOLUMN')
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYLINECOLUMN (
		[ID] uniqueidentifier NOT NULL DEFAULT (newid()),
		[LINENUMBERID] uniqueidentifier NOT NULL,
		[COLUMNNUMBER] int,
		[COLUMNTYPE] int,
		[ORDERPROPERTY] int,   
		[CAPTION] nvarchar(50) NULL,
		[MAPPINGKEY] nvarchar(1024),
		[ALIGNMENT] int,
		[RELATIVESIZE] [int] NULL,
		[STYLEID] uniqueidentifier		
		CONSTRAINT [PK_KITCHENDISPLAYLINECOLUMN] PRIMARY KEY CLUSTERED 
		(
		    [ID],
			[LINENUMBERID]
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
		) ON [PRIMARY]
		
	END
GO

-- This replaces the DISPLAYMODE column in the KITCHENDISPLAYSTATION table with the DISPLAYPROFILEID
DECLARE @chitguid uniqueidentifier;
DECLARE @lineguid uniqueidentifier;
DECLARE @dataarea nvarchar(4);
SET @dataarea = (select top(1) DATAAREAID from KITCHENDISPLAYSTATION);
set @chitguid = newid();
set @lineguid = newid();

UPDATE KITCHENDISPLAYSTATION SET DISPLAYPROFILEID = @lineguid WHERE [DISPLAYMODE] <> 0;
UPDATE KITCHENDISPLAYSTATION SET DISPLAYPROFILEID = @chitguid WHERE [DISPLAYMODE] = 0;

IF @dataarea > ''
BEGIN
  INSERT INTO [dbo].KITCHENDISPLAYPROFILE ([ID],[DISPLAYMODE],[NAME],[DATAAREAID])
    values (@chitguid,0,'Chitdisplay',@dataarea);
  INSERT INTO [dbo].KITCHENDISPLAYPROFILE ([ID],[DISPLAYMODE],[NAME],[DATAAREAID])
    values (@lineguid,1,'Linedisplay',@dataarea);
END
GO
-- Keep this column for AX data-replication tool.  Column will be removed
--IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'DISPLAYMODE')
--BEGIN
--	ALTER TABLE KITCHENDISPLAYSTATION DROP COLUMN DISPLAYMODE
--END
--GO


/*
	KDS script		: 00633-00
	Incident No.	: KDS-253
	Responsible		: Sigurður Ragnarsson
	Sprint			: Haribo
	Date created	: 14.11.2017

	Description		: Add DATAAREAID column in KITCHENDISPLAYLINECOLUMN table
						
*/
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYLINECOLUMN')
  BEGIN
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYLINECOLUMN' AND COLUMN_NAME = 'DATAAREAID')
	  BEGIN
	    ALTER TABLE [dbo].[KITCHENDISPLAYLINECOLUMN] ADD DATAAREAID nvarchar(30);
	  END
  END
GO


/*
	KDS script		: 00634-00
	Incident No.	: NAV-8491
	Responsible		: Sigurður Ragnarsson
	Sprint			: Hangikjöt
	Date created	: 03.01.2018

	Description		: Add new columns in KITCHENDISPLAYLINECOLUMM
						
*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYLINECOLUMN' AND COLUMN_NAME = 'COLORSTYLE')
BEGIN
	ALTER TABLE [dbo].KITCHENDISPLAYLINECOLUMN ADD COLORSTYLE NVARCHAR(250);
END
GO


/*
	KDS script		: 00635-00
	Incident No.	: NAV-9316
	Responsible		: Sigurður Ragnarsson
	Sprint			: Taboulet
	Date created	: 20.04.2018

	Description		: Add Items started style ID
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMSTARTEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ITEMSTARTEDSTYLEID UNIQUEIDENTIFIER
END
GO


/*
	KDS script		: 00635-01
	Incident No.	: NAV-9474
	Responsible		: Sigurður Ragnarsson
	Sprint			: écler caramel
	Date created	: 19.06.2018

	Description		: Add GroupBySeat number columns
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'GROUPBYSEATNO')
BEGIN
	alter table KITCHENDISPLAYSTATION ADD GROUPBYSEATNO tinyint
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'SEATNOGROUPTEXT')
BEGIN
	alter table KITCHENDISPLAYSTATION ADD SEATNOGROUPTEXT nvarchar(30)
END
GO


/*
	KDS script		: 00636-00
	Incident No.	: KDS-279
	Responsible		: Harpa María Grétarsdóttir
	Sprint			: 
	Date created	: Pantagruel 04.06.2018

	Description		: Add Items served style ID
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMSERVEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ITEMSERVEDSTYLEID UNIQUEIDENTIFIER
END
GO


/*
	KDS script		: 00636-01
	Incident No.	: KDS-273
	Responsible		: Sigurður Ragnarsson
	Sprint			: Snickers
	Date created	: 06.06.2018

	Description		: Add new field in table KITCHENDISPLAYSTATION + cleanup and missing column in Style Profile table
						
*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'SHOWONLYWHENBUMPEDONPRIOR')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD SHOWONLYWHENBUMPEDONPRIOR tinyint
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYLINECOLUMN' AND COLUMN_NAME = 'STYLEID')
BEGIN
	ALTER TABLE [dbo].KITCHENDISPLAYLINECOLUMN DROP COLUMN STYLEID
END
GO


/*
	KSD script		: 00637-00
	Incident No.	: KDS-284
	Responsible		: Sigurður Ragnarsson
	Sprint			: Snickers
	Date created	: 12.06.2018

	Description		: Add Transfer Station ID column to KITCHENDISPLAYSTATION table
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'TRANSFERTOSTATIONID')
BEGIN
	alter table KITCHENDISPLAYSTATION ADD TRANSFERTOSTATIONID NVARCHAR(20)
END
GO


/*
	KDS script		: 00638-00
	Incident No.	: KDS-272
	Responsible		: Sigurður Ragnarsson
	Sprint			: éclair caramel
	Date created	: 19.06.2018

	Description		: Add Aggregate tables
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'USEAGGREGATEGROUPS')
BEGIN
	alter table KITCHENDISPLAYSTATION ADD USEAGGREGATEGROUPS tinyint
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'AGGREGATEPROFILEID')
BEGIN
	alter table KITCHENDISPLAYSTATION ADD AGGREGATEPROFILEID nvarchar(20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND COLUMN_NAME = 'PERCENTCOOKTIME')
BEGIN
	alter table KITCHENDISPLAYTIMESTYLE ADD PERCENTCOOKTIME decimal(38,20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND COLUMN_NAME = 'LINEID')
BEGIN
	alter table KITCHENDISPLAYTIMESTYLE ADD LINEID int
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND COLUMN_NAME = 'LINEID')
BEGIN
	DECLARE @incvalue int
	SET @incvalue = 0
	UPDATE KITCHENDISPLAYTIMESTYLE SET LINEID = @incvalue,@incvalue=@incvalue+100

	alter table KITCHENDISPLAYTIMESTYLE ALTER COLUMN LINEID int not null
END
GO

-- Drop old primary key
IF EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND CONSTRAINT_NAME = 'PK_KITCHENDISPLAYTIMESTYLE')
Begin
	Alter Table KITCHENDISPLAYTIMESTYLE
	DROP CONSTRAINT PK_KITCHENDISPLAYTIMESTYLE
End
GO

-- Create the new primary key
IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND CONSTRAINT_NAME = 'PK_KITCHENDISPLAYTIMESTYLE')
Begin
	ALTER TABLE KITCHENDISPLAYTIMESTYLE
	ADD CONSTRAINT PK_KITCHENDISPLAYTIMESTYLE PRIMARY KEY (KDSTYLEPROFILEID, LINEID, DATAAREAID)
End
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYAGGREGATEPROFILE')
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYAGGREGATEPROFILE (
			[PROFILEID] nvarchar(20) NOT NULL,
			[DESCRIPTION] nvarchar(30),
			[TIMEHORIZON] int,
			[DATAAREAID] nvarchar(30) NOT NULL,
			CONSTRAINT [PK_KITCHENDISPLAYAGGREGATEPROFILE] PRIMARY KEY CLUSTERED 
			(
				[PROFILEID] ASC,
				[DATAAREAID]
			) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		) ON [PRIMARY]
	END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYAGGREGATEPROFILEGROUP')
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYAGGREGATEPROFILEGROUP (
			[PROFILEID] nvarchar(20) NOT NULL DEFAULT '',
			[GROUPID] nvarchar(20) NOT NULL,
			[DATAAREAID] nvarchar(30) NOT NULL,
			[GROUPDESCRIPTION] nvarchar(30),
			[USETIMEHORIZON] tinyint,
			CONSTRAINT [PK_KITCHENDISPLAYAGGREGATEPROFILEGROUP] PRIMARY KEY CLUSTERED 
			(
				[PROFILEID] ASC,
				[GROUPID],
				[DATAAREAID]
			) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		) ON [PRIMARY]
	END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYAGGREGATEGROUPITEM')
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYAGGREGATEGROUPITEM (
			[ITEMID] nvarchar(30) NOT NULL,
			[GROUPID] nvarchar(20) NOT NULL,
			[DATAAREAID] nvarchar(30) NOT NULL,
			[ITEMDESCRIPTION] nvarchar(240),
			CONSTRAINT [PK_KITCHENDISPLAYAGGREGATEGROUPITEM] PRIMARY KEY CLUSTERED 
			(
				[ITEMID] ASC,
				[GROUPID],
				[DATAAREAID]
			) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		) ON [PRIMARY]
	END
GO


/*
	KDS script		: 00639-00
	Incident No.	: KDS-310
	Responsible		: Harpa María Grétarsdóttir
	Sprint			: Kouign amann
	Date created	: 11.10.2018

	Description		: Add Aggregate fields to VisualProfile and StyleProfile
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEWIDTH')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD AGGREGATEPANEWIDTH decimal
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEHEIGHT')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD AGGREGATEPANEHEIGHT decimal
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEX')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD AGGREGATEPANEX decimal
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEY')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD AGGREGATEPANEY decimal
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEVISIBLE')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD AGGREGATEPANEVISIBLE tinyint
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANENUMBEROFCOLUMNS')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD AGGREGATEPANENUMBEROFCOLUMNS int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEPOSITION')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD AGGREGATEPANEPOSITION int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'AGGREGATEHEADERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD AGGREGATEHEADERSTYLEID UNIQUEIDENTIFIER
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'AGGREGATEBODYSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD AGGREGATEBODYSTYLEID UNIQUEIDENTIFIER
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'AGGREGATEPANESTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD AGGREGATEPANESTYLEID UNIQUEIDENTIFIER
END
GO


/*
	KDS script		: 00640-00
	Incident No.	: KDS-317
	Responsible		: Sigurður Ragnarsson
	Sprint			: Kouign amann
	Date created	: 11.10.2018

	Description		: Add field for backup station in KITCHENDISPLAYSTATION
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'FALLBACKSTATIONID')
BEGIN
	alter table KITCHENDISPLAYSTATION ADD FALLBACKSTATIONID nvarchar(20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYLOG' AND COLUMN_NAME = 'PRINTERSTATUS')
BEGIN
	alter table KITCHENDISPLAYLOG ADD PRINTERSTATUS int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYLOG' AND COLUMN_NAME = 'PRINTERNAME')
BEGIN
	alter table KITCHENDISPLAYLOG ADD PRINTERNAME nvarchar(30)
END
GO


/*
	KDS script		: 00641-00
	Incident No.	: KDS-352
	Responsible		: Sigurður Ragnarsson
	Sprint			: Roast leg of lamb with basil &
	Date created	: 16.04.2019

	Description		: Add field for cell to bump from if Chit is present
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'CELLNUMBER')
BEGIN
	alter table POSMENULINE ADD CELLNUMBER int
END
GO



/*
	KDS	script		: 00642-00
	Incident No.	: KDS-379
	Responsible		: Sigurður Ragnarsson
	Sprint			: BEER-BRAISED PORK KNUCKLES
	Date created	: 05.02.2020

	Description		: Add fields which have been added since last time
						
*/
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'CHITSIZE')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD CHITSIZE int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HISTORYPANEWIDTH')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD HISTORYPANEWIDTH decimal(38,20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HISTORYPANEHEIGHT')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD HISTORYPANEHEIGHT decimal(38,20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HISTORYPANEX')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD HISTORYPANEX decimal(38,20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HISTORYPANEY')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD HISTORYPANEY decimal(38,20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HISTORYPANEVISIBLE')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD HISTORYPANEVISIBLE tinyint
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HISTORYPANEPOSITION')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD HISTORYPANEPOSITION int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HISTORYMAXSUMMARYLINES')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD HISTORYMAXSUMMARYLINES int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HISTORYMAXLASTBUMPEDLINES')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD HISTORYMAXLASTBUMPEDLINES int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HISTORYLIFESPAN')
BEGIN
	alter table KITCHENDISPLAYVISUALPROFILE ADD HISTORYLIFESPAN int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILE' AND COLUMN_NAME = 'TIMEUNTILFORCEBUMPFROMSTATION')
BEGIN
	alter table KITCHENDISPLAYFUNCTIONALPROFILE ADD TIMEUNTILFORCEBUMPFROMSTATION int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'EXPEDITORBUMPSTATIONID')
BEGIN
	alter table KITCHENDISPLAYSTATION ADD EXPEDITORBUMPSTATIONID nvarchar(20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'HISTORYHEADERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD HISTORYHEADERSTYLEID uniqueidentifier
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'HISTORYBODYSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD HISTORYBODYSTYLEID uniqueidentifier
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'HISTORYPANESTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD HISTORYPANESTYLEID uniqueidentifier
END
GO
