/*
	Incident No.	: ONE-12498
	Responsible		: Hörður Kristjánsson
	Sprint			: Pizza Hut
	Date created	: 18.08.2020

	Description		: Added TERMINALID and STOREID since terminals have a composite key. Increased size of CONNECTIONVALUE to reflect this change.
*/

USE LSPOSNET

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTERMINALCONNECTION' AND COLUMN_NAME = 'CONNECTIONVALUE' AND CHARACTER_MAXIMUM_LENGTH < 50)
    BEGIN
        ALTER TABLE KITCHENDISPLAYTERMINALCONNECTION ALTER COLUMN CONNECTIONVALUE NVARCHAR(50) NOT NULL
        EXECUTE spDB_SetFieldDescription_1_0 'KITCHENDISPLAYTERMINALCONNECTION', 'CONNECTIONVALUE', 'The routing connection ID. For the terminal it is a combination STOREID and TERMINALID.'
    END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTERMINALCONNECTION' AND COLUMN_NAME = 'TERMINALID')
    BEGIN
        ALTER TABLE KITCHENDISPLAYTERMINALCONNECTION ADD TERMINALID NVARCHAR(20) NOT NULL DEFAULT ''
        EXECUTE spDB_SetFieldDescription_1_0 'KITCHENDISPLAYTERMINALCONNECTION', 'TERMINALID', 'The terminal ID for the terminal routing.'
    END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTERMINALCONNECTION' AND COLUMN_NAME = 'STOREID')
    BEGIN
        ALTER TABLE KITCHENDISPLAYTERMINALCONNECTION ADD STOREID NVARCHAR(20) NOT NULL DEFAULT ''
        EXECUTE spDB_SetFieldDescription_1_0 'KITCHENDISPLAYTERMINALCONNECTION', 'STOREID', 'The store ID for the terminal routing.'
    END
GO