/*
	Incident No.	: ONE-12211
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Corgi
	Date created	: 27.05.2020

	Description		: Adding new table KITCHENDISPLAYPRODUCTIONSECTION for KDS routing configuration
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYPRODUCTIONSECTION')
BEGIN
	CREATE TABLE KITCHENDISPLAYPRODUCTIONSECTION (
		[ID] UNIQUEIDENTIFIER PRIMARY KEY,
		[CODE] NVARCHAR(30) UNIQUE NOT NULL,
		[DESCRIPTION] NVARCHAR(30) DEFAULT ''
	)

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYPRODUCTIONSECTION', 'ID', 'KDS production section id';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYPRODUCTIONSECTION', 'CODE', 'Code name for production section';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYPRODUCTIONSECTION', 'DESCRIPTION', 'Description of the production section';

END
GO


/*
	Incident No.	: ONE-12212
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Chihuahua
	Date created	: 29.05.2020

	Description		: Adding new table KITCHENDISPLAYITEMSECTIONROUTING for KDS routing configuration
*/

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYITEMSECTIONROUTING')
BEGIN
	CREATE TABLE KITCHENDISPLAYITEMSECTIONROUTING (
		[ID] UNIQUEIDENTIFIER PRIMARY KEY,
		[ITEMTYPE] TINYINT NOT NULL,
		[ITEMMASTERID] UNIQUEIDENTIFIER NOT NULL,
		[SECTIONID] UNIQUEIDENTIFIER,
	)

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYITEMSECTIONROUTING', 'ID', 'ID of the routing line';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYITEMSECTIONROUTING', 'ITEMTYPE', 'Routing can be from retail group, special group or item';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYITEMSECTIONROUTING', 'ITEMMASTERID', 'Master ID of the item/group';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYITEMSECTIONROUTING', 'SECTIONID', 'ID of the production section';

END
GO


/*
	Incident No.	: ONE-12219
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Chihuahua
	Date created	: 05.06.2020

	Description		: Adding new table KITCHENDISPLAYSECTIONSTATIONROUTING for KDS routing configuration
*/

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYSECTIONSTATIONROUTING')
BEGIN
	CREATE TABLE KITCHENDISPLAYSECTIONSTATIONROUTING (
		[ID] UNIQUEIDENTIFIER PRIMARY KEY,
		[RESTAURANTID] NVARCHAR(20),
		[SECTIONID] UNIQUEIDENTIFIER,
		[HOSPITALITYTYPESEQUENCE] INT,
		[HOSPITALITYTYPESALESTYPE] NVARCHAR(20),
		[STATIONTYPE] TINYINT,
		[STATIONID] NVARCHAR(20)
	)

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYSECTIONSTATIONROUTING', 'ID', 'ID of the routing line';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYSECTIONSTATIONROUTING', 'RESTAURANTID', 'ID of the restaurant the routing applies to. Part of the hospitality type primary key';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYSECTIONSTATIONROUTING', 'SECTIONID', 'ID of the section the routing applies to';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYSECTIONSTATIONROUTING', 'HOSPITALITYTYPESEQUENCE', 'Part of the hospitality type primary key';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYSECTIONSTATIONROUTING', 'HOSPITALITYTYPESALESTYPE', 'Part of the hospitality type primary key';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYSECTIONSTATIONROUTING', 'STATIONTYPE', 'Either display or printing station';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYSECTIONSTATIONROUTING', 'STATIONID', 'ID of the kitchen station';

END
GO


/*
	Incident No.	: ONE-12290
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Chihuahua
	Date created	: 12.06.2020

	Description		: Adding a field PRODUCTIONTIME for KDS configuration
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'PRODUCTIONTIME')
BEGIN
	ALTER TABLE RETAILITEM ADD PRODUCTIONTIME INT NOT NULL DEFAULT 0;

	EXEC spDB_SetFieldDescription_1_0 'RETAILITEM', 'PRODUCTIONTIME', 'The production time of an item. This tells how long it takes to cook and prepare the item.';
END
GO


/*
	Incident No.	: ONE-12363
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Westie
	Date created	: 22.06.2020

	Description		: Adding a field INCLUDEEXCLUDE in KDS routing tables
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYITEMCONNECTION' AND COLUMN_NAME = 'INCLUDEEXCLUDE')
BEGIN
	ALTER TABLE KITCHENDISPLAYITEMCONNECTION ADD INCLUDEEXCLUDE TINYINT NOT NULL DEFAULT 0;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYITEMCONNECTION', 'INCLUDEEXCLUDE', 'Tells if this routing line should be included or excluded';
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTERMINALCONNECTION' AND COLUMN_NAME = 'INCLUDEEXCLUDE')
BEGIN
	ALTER TABLE KITCHENDISPLAYTERMINALCONNECTION ADD INCLUDEEXCLUDE TINYINT NOT NULL DEFAULT 0;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYTERMINALCONNECTION', 'INCLUDEEXCLUDE', 'Tells if this routing line should be included or excluded';
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYHOSPITALITYTYPECONNECTION' AND COLUMN_NAME = 'INCLUDEEXCLUDE')
BEGIN
	ALTER TABLE KITCHENDISPLAYHOSPITALITYTYPECONNECTION ADD INCLUDEEXCLUDE TINYINT NOT NULL DEFAULT 0;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHOSPITALITYTYPECONNECTION', 'INCLUDEEXCLUDE', 'Tells if this routing line should be included or excluded';
END
GO



/*
	Incident No.	: ONE-12332
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Westie
	Date created	: 02.07.2020

	Description		: Changing all style columns of KITCHENDISPLAYSTYLEPROFILE to nvarchar
*/

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMONTIMESTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMONTIMESTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMVOIDEDSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMVOIDEDSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DEFAULTFOOTERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN DEFAULTFOOTERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DEFAULTHEADERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN DEFAULTHEADERSTYLEID NVARCHAR(20);
END
GO


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'COMMENTMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN COMMENTMODIFIERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERMODIFIEDSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMMODIFIERMODIFIEDSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERVOIDEDSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMMODIFIERVOIDEDSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERGLYPHSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMMODIFIERGLYPHSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DEALHEADERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN DEALHEADERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DEALHEADERVOIDEDSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN DEALHEADERVOIDEDSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ORDERPANESTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ORDERPANESTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ORDERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ORDERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMDEFAULTSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMDEFAULTSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMDONESTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMDONESTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMMODIFIEDSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMMODIFIEDSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'NORMALITEMMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN NORMALITEMMODIFIERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'INCREASEITEMMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN INCREASEITEMMODIFIERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DECREASEITEMMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN DECREASEITEMMODIFIERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'HEAVYITEMMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN HEAVYITEMMODIFIERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'LIGHTITEMMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN LIGHTITEMMODIFIERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ONLYITEMMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ONLYITEMMODIFIERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'TRANSACTCOMMENTSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN TRANSACTCOMMENTSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMRUSHSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMRUSHSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DONEITEMMODIFIERUISTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN DONEITEMMODIFIERUISTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ALERTSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ALERTSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMSTARTEDSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMSTARTEDSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMSERVEDSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN ITEMSERVEDSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'AGGREGATEHEADERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN AGGREGATEHEADERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'AGGREGATEBODYSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN AGGREGATEBODYSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'AGGREGATEPANESTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN AGGREGATEPANESTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'HISTORYHEADERSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN HISTORYHEADERSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'HISTORYBODYSTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN HISTORYBODYSTYLEID NVARCHAR(20);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'HISTORYPANESTYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTYLEPROFILE
	ALTER COLUMN HISTORYPANESTYLEID NVARCHAR(20);
END
GO



/*
	Incident No.	: ONE-12461
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Westie
	Date created	: 07.07.2020

	Description		: Add fields to identify hospitality type in table KITCHENDISPLAYHOSPITALITYTYPECONNECTION
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYHOSPITALITYTYPECONNECTION' AND COLUMN_NAME = 'RESTAURANT')
BEGIN
	ALTER TABLE KITCHENDISPLAYHOSPITALITYTYPECONNECTION ADD RESTAURANT NVARCHAR(20) NOT NULL;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHOSPITALITYTYPECONNECTION', 'RESTAURANT', 'Restaurant id of the connected hospitality type';
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYHOSPITALITYTYPECONNECTION' AND COLUMN_NAME = 'SALESTYPE')
BEGIN
	ALTER TABLE KITCHENDISPLAYHOSPITALITYTYPECONNECTION ADD SALESTYPE NVARCHAR(20) NOT NULL;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHOSPITALITYTYPECONNECTION', 'SALESTYPE', 'Sales type id of the connected hospitality type';
END
GO



/*
	Incident No.	: ONE-12477
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: MotorRockBistro
	Date created	: 16.07.2020

	Description		: Change STYLEID column from guid to nvarchar in the table KITCHENDISPLAYTIMESTYLE
*/

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND COLUMN_NAME = 'STYLEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYTIMESTYLE
	ALTER COLUMN STYLEID NVARCHAR(20);
END
GO



/*
	Incident No.	: ONE-12504
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Kol
	Date created	: 08.10.2020

	Description		: Adding a field for kitchen status on dining tables
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISHOSPITALITYDININGTABLES' AND COLUMN_NAME = 'KITCHENSTATUS')
BEGIN
	ALTER TABLE POSISHOSPITALITYDININGTABLES ADD KITCHENSTATUS TINYINT NOT NULL DEFAULT 0;

	EXEC spDB_SetFieldDescription_1_0 'POSISHOSPITALITYDININGTABLES', 'KITCHENSTATUS', 'Status of the order in the kitchen';
END
GO



/*
	Incident No.	: ONE-12441
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Kol
	Date created	: 11.08.2020

	Description		: Adding new table for KDS header panes
*/

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYHEADERPANE')
BEGIN
	CREATE TABLE KITCHENDISPLAYHEADERPANE (
		[ID] UNIQUEIDENTIFIER PRIMARY KEY,
		[NAME] NVARCHAR(30) DEFAULT ''
	)

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANE', 'ID', 'ID of the header pane';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANE', 'NAME', 'Name description of the header pane';
END
GO



/*
	Incident No.	: ONE-12442
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Kol
	Date created	: 11.08.2020

	Description		: Adding new table for KDS header pane lines
*/

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYHEADERPANELINE')
BEGIN
	CREATE TABLE KITCHENDISPLAYHEADERPANELINE (
		[ID] UNIQUEIDENTIFIER,
		[HEADERPANEID] UNIQUEIDENTIFIER NOT NULL,
		[LINENUMBER] INT NOT NULL,
		PRIMARY KEY (HEADERPANEID, LINENUMBER)
	)

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINE', 'ID', 'Unique identifier of the line (not displayed)';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINE', 'HEADERPANEID', 'ID of the connected header pane';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINE', 'LINENUMBER', 'The number of the line = the order in which it is displayed';
END
GO



/*
	Incident No.	: ONE-12443
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Piazza Hut
	Date created	: 12.08.2020

	Description		: Adding new table for KDS header pane line colums
*/

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYHEADERPANELINECOLUMN')
BEGIN
	CREATE TABLE KITCHENDISPLAYHEADERPANELINECOLUMN (
		[COLUMNNUMBER] INT,
		[LINEID] UNIQUEIDENTIFIER,
		[HEADERPANEID] UNIQUEIDENTIFIER NOT NULL,
		[COLUMNTYPE] TINYINT DEFAULT 0,
		[DESCRIPTION] NVARCHAR(30) DEFAULT '',
		[COLUMNALIGNMENT] TINYINT DEFAULT 0,
		[STYLEID] NVARCHAR(20) NOT NULL,
		PRIMARY KEY (COLUMNNUMBER, LINEID)
	)

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINECOLUMN', 'COLUMNNUMBER', 'Number of the column in the corresponding line';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINECOLUMN', 'LINEID', 'ID of the connected header pane line';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINECOLUMN', 'HEADERPANEID', 'ID of the connected header pane';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINECOLUMN', 'COLUMNTYPE', 'Type of the column';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINECOLUMN', 'DESCRIPTION', 'Description text of the column';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINECOLUMN', 'COLUMNALIGNMENT', 'Enum that defines the alignment';
	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYHEADERPANELINECOLUMN', 'STYLEID', 'ID of the connected POS Style';
END
GO



/*
	Incident No.	: ONE-12542
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Pizza Hut
	Date created	: 18.08.2020

	Description		: Adding a field to connect header profile to visual profile
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HEADERPANEID')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE ADD HEADERPANEID UNIQUEIDENTIFIER;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYVISUALPROFILE', 'HEADERPANEID', 'ID of the connected header pane';
END
GO



/*
	Incident No.	: ONE-12542
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Pizza Hut
	Date created	: 20.08.2020

	Description		: Adding a field for header pane height in visual profile
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HEADERPANEHEIGHT')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE ADD HEADERPANEHEIGHT DECIMAL(3,2);

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYVISUALPROFILE', 'HEADERPANEHEIGHT', 'Height of the header pane';
END
GO



/*
	Incident No.	: ONE-12216
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Big Belly
	Date created	: 27.08.2020

	Description		: Adding a field for item relation type in aggregate group item
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYAGGREGATEGROUPITEM' AND COLUMN_NAME = 'TYPE')
BEGIN
	ALTER TABLE KITCHENDISPLAYAGGREGATEGROUPITEM ADD TYPE TINYINT NOT NULL DEFAULT 0;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYAGGREGATEGROUPITEM', 'TYPE', 'The item relation type.';
END
GO



/*
	Incident No.	: ONE-12315
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Big Belly
	Date created	: 03.09.2020

	Description		: Change aggregate columns type in visual profile table
*/

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEWIDTH')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE
	ALTER COLUMN AGGREGATEPANEWIDTH NUMERIC(24,6);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEHEIGHT')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE
	ALTER COLUMN AGGREGATEPANEHEIGHT NUMERIC(24,6);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEX')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE
	ALTER COLUMN AGGREGATEPANEX NUMERIC(24,6);
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'AGGREGATEPANEY')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE
	ALTER COLUMN AGGREGATEPANEY NUMERIC(24,6);
END
GO



/*
	Incident No.	: ONE-11703
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Hlölli
	Date created	: 11.09.2020

	Description		: Adding a field for button pane position
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'BUTTONPANEPOSITION')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE ADD BUTTONPANEPOSITION TINYINT NOT NULL DEFAULT 0;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYVISUALPROFILE', 'BUTTONPANEPOSITION', 'Postion of the button pane';
END
GO



/*
	Incident No.	: ONE-11703
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Hlölli
	Date created	: 16.09.2020

	Description		: Adding a fields for header postition
*/

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HEADERPANEX')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE ADD HEADERPANEX NUMERIC(24,6) NOT NULL DEFAULT 0;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYVISUALPROFILE', 'HEADERPANEX', 'X coordinate of the header pane';
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'HEADERPANEY')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE ADD HEADERPANEY NUMERIC(24,6) NOT NULL DEFAULT 0;

	EXEC spDB_SetFieldDescription_1_0 'KITCHENDISPLAYVISUALPROFILE', 'HEADERPANEY', 'Y coordinate of the header pane';
END
GO



/*
	Incident No.	: ONE-12507
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Saffran
	Date created	: 13.10.2020

	Description		: Add field for font striketrough
*/

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSSTYLE' AND COLUMN_NAME = 'FONTSTRIKETHROUGH')
BEGIN
	ALTER TABLE POSSTYLE ADD FONTSTRIKETHROUGH TINYINT NOT NULL DEFAULT 0;

    EXEC spDB_SetFieldDescription_1_0 'POSSTYLE', 'FONTSTRIKETHROUGH', 'Flag to set strikethrough in the font style';
END
GO




/*
	Incident No.	: ONE-12729
	Responsible		: Davíð Phuong Xuan Nguyen
	Sprint			: Saffran
	Date created	: 15.10.2020

	Description		: Add fields for button styles
*/

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONDEFAULTSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONDEFAULTSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONNEXTSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONNEXTSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONPREVIOUSSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONPREVIOUSSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONBUMPSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONBUMPSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONSTARTSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONSTARTSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONNEXTSCREENSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONNEXTSCREENSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONPREVIOUSSCREENSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONPREVIOUSSCREENSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONSELECTSTARTSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONSELECTSTARTSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONSELECTBUMPSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONSELECTBUMPSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONRECALLSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONRECALLSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONHOMESTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONHOMESTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONENDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONENDSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONMARKSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONMARKSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONSERVESTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONSERVESTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONTRANSFERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONTRANSFERSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONRUSHSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD BUTTONRUSHSTYLEID NVARCHAR(20) NOT NULL DEFAULT ''
END
GO