//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding loyalty card to transaction.
        /// </summary>
        internal static string AddingLoyaltyCardToTransaction {
            get {
                return ResourceManager.GetString("AddingLoyaltyCardToTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amounts.
        /// </summary>
        internal static string Amounts {
            get {
                return ResourceManager.GetString("Amounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card:.
        /// </summary>
        internal static string CardID {
            get {
                return ResourceManager.GetString("CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checkmark_white_32px {
            get {
                object obj = ResourceManager.GetObject("Checkmark_white_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please conclude the transaction with cash.
        /// </summary>
        internal static string ConcludeTransactionWithCash {
            get {
                return ResourceManager.GetString("ConcludeTransactionWithCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Site Service.
        /// </summary>
        internal static string CouldNotConnectToStoreServer {
            get {
                return ResourceManager.GetString("CouldNotConnectToStoreServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is blocked and cannot use loyalty points.  Selet a different card or payment method..
        /// </summary>
        internal static string CusotmerIsBlockedAndCannotUsePoints {
            get {
                return ResourceManager.GetString("CusotmerIsBlockedAndCannotUsePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer cannot be cleared since the sale is a return sale.
        /// </summary>
        internal static string CustomerCannotBeClearedTransactionIsAReturn {
            get {
                return ResourceManager.GetString("CustomerCannotBeClearedTransactionIsAReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is blocked and cannot be added to loyalty card, please select a different customer..
        /// </summary>
        internal static string CustomerIsBlockedAndCannotBeAdded {
            get {
                return ResourceManager.GetString("CustomerIsBlockedAndCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer order.
        /// </summary>
        internal static string CustomerOrderLowCase {
            get {
                return ResourceManager.GetString("CustomerOrderLowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogMessage_48 {
            get {
                object obj = ResourceManager.GetObject("DialogMessage_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current points discount is over the use limit (#1%) on the loyalty card. The discounts has been updated to be #2.
        /// </summary>
        internal static string DiscountOverUsePointsLimit {
            get {
                return ResourceManager.GetString("DiscountOverUsePointsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty card #1 from customer #2 has already been added to the sale. Do you want to replace this loyalty card with another?.
        /// </summary>
        internal static string DoYouWantToOverwriteTheLoyaltyRecord {
            get {
                return ResourceManager.GetString("DoYouWantToOverwriteTheLoyaltyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a loyalty number.
        /// </summary>
        internal static string EnterLoyaltyNumber {
            get {
                return ResourceManager.GetString("EnterLoyaltyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client is not a loyalty customer.
        /// </summary>
        internal static string ErrClientNotLoyaltyCustomer {
            get {
                return ResourceManager.GetString("ErrClientNotLoyaltyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert/Update error.
        /// </summary>
        internal static string ErrInsertUpdate {
            get {
                return ResourceManager.GetString("ErrInsertUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty card is already assigned to another customer.
        /// </summary>
        internal static string ErrLoyaltyCardAlreadyAssigned {
            get {
                return ResourceManager.GetString("ErrLoyaltyCardAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty card is blocked.
        /// </summary>
        internal static string ErrLoyaltyCardBlocked {
            get {
                return ResourceManager.GetString("ErrLoyaltyCardBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty card is does not allow payment with points.
        /// </summary>
        internal static string ErrLoyaltyCardIsNoTenderCard {
            get {
                return ResourceManager.GetString("ErrLoyaltyCardIsNoTenderCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty card could not be found.
        /// </summary>
        internal static string ErrLoyaltyCardNotFound {
            get {
                return ResourceManager.GetString("ErrLoyaltyCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty customer not found.
        /// </summary>
        internal static string ErrLoyaltyCustomerNotFound {
            get {
                return ResourceManager.GetString("ErrLoyaltyCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty card has not been activated.
        /// </summary>
        internal static string ErrLoyaltyIsNotActivated {
            get {
                return ResourceManager.GetString("ErrLoyaltyIsNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough loyalty points.
        /// </summary>
        internal static string ErrNotEnoughLoyaltyPoints {
            get {
                return ResourceManager.GetString("ErrNotEnoughLoyaltyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured connecting with the loyalty server.
        /// </summary>
        internal static string ErrorConnectingToLoyaltyServer {
            get {
                return ResourceManager.GetString("ErrorConnectingToLoyaltyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty points functionality has not been implemented and cannot be used.
        /// </summary>
        internal static string FunctionalityImplementationNotFinished {
            get {
                return ResourceManager.GetString("FunctionalityImplementationNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has not been implemented and cannot be used.
        /// </summary>
        internal static string ImplementationNotFinished {
            get {
                return ResourceManager.GetString("ImplementationNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty card cannot be added to a {0}.
        /// </summary>
        internal static string LoyaltyCardCannotBeAddedToAQuote {
            get {
                return ResourceManager.GetString("LoyaltyCardCannotBeAddedToAQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty card cannot be used to return payment on the current sale.
        /// </summary>
        internal static string LoyaltyCardCannotBeAddedToReturnSale {
            get {
                return ResourceManager.GetString("LoyaltyCardCannotBeAddedToReturnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty card information.
        /// </summary>
        internal static string LoyaltyCardInformation {
            get {
                return ResourceManager.GetString("LoyaltyCardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty points discount.
        /// </summary>
        internal static string LoyaltyDiscount {
            get {
                return ResourceManager.GetString("LoyaltyDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amount for discount is #1.
        /// </summary>
        internal static string MaximumDiscountAllowed {
            get {
                return ResourceManager.GetString("MaximumDiscountAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amount for payment is #1.
        /// </summary>
        internal static string MaximumPaymentAllowed {
            get {
                return ResourceManager.GetString("MaximumPaymentAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum amount for payment is #1.
        /// </summary>
        internal static string MinimumDiscountAllowed {
            get {
                return ResourceManager.GetString("MinimumDiscountAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum amount for payment is #1.
        /// </summary>
        internal static string MinimumPaymentAllowed {
            get {
                return ResourceManager.GetString("MinimumPaymentAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative points payments cannot be go below the the balance amount.
        /// </summary>
        internal static string NegativePaymentsNotBelowBalance {
            get {
                return ResourceManager.GetString("NegativePaymentsNotBelowBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POS is in training mode. The customer cannot be connected to the loyalty card.
        /// </summary>
        internal static string NoCustomerConnectionOnTraining {
            get {
                return ResourceManager.GetString("NoCustomerConnectionOnTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customer has been selected..
        /// </summary>
        internal static string NoCustomerHasBeenSelected {
            get {
                return ResourceManager.GetString("NoCustomerHasBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to discount.
        /// </summary>
        internal static string NoItemsOnSale {
            get {
                return ResourceManager.GetString("NoItemsOnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items in the sale can be given a discount using loyalty points.
        /// </summary>
        internal static string NoItemsToDiscount {
            get {
                return ResourceManager.GetString("NoItemsToDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items suitable for discount.
        /// </summary>
        internal static string NoItemToDiscountDlg {
            get {
                return ResourceManager.GetString("NoItemToDiscountDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No loyalty card number has been entered..
        /// </summary>
        internal static string NoLoyaltyCardHasBeenEntered {
            get {
                return ResourceManager.GetString("NoLoyaltyCardHasBeenEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No loyalty information available.
        /// </summary>
        internal static string NoLoyaltyInformationAvailable {
            get {
                return ResourceManager.GetString("NoLoyaltyInformationAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Loyalty points calculated or added to card. The POS is in training mode.
        /// </summary>
        internal static string NoLoyaltyPointsOnTraining {
            get {
                return ResourceManager.GetString("NoLoyaltyPointsOnTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current loyalty card cannot be used for another loyalty payment..
        /// </summary>
        internal static string NoMoreLoyaltyPaymentLinesAllowed {
            get {
                return ResourceManager.GetString("NoMoreLoyaltyPaymentLinesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment information included on button. Payment operation cannot continue.
        /// </summary>
        internal static string NoPaymentInformationOnButton {
            get {
                return ResourceManager.GetString("NoPaymentInformationOnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No point deduction rule exists.
        /// </summary>
        internal static string NoPointDeductionRuleExists {
            get {
                return ResourceManager.GetString("NoPointDeductionRuleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card doesn&apos;t allow discounts with loyalty points.
        /// </summary>
        internal static string NoTenderRuleForLoyaltyDiscountExists {
            get {
                return ResourceManager.GetString("NoTenderRuleForLoyaltyDiscountExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card doesn&apos;t allow payment with loyalty points.
        /// </summary>
        internal static string NoTenderRuleForLoyaltyPaymentExists {
            get {
                return ResourceManager.GetString("NoTenderRuleForLoyaltyPaymentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough points available.
        /// </summary>
        internal static string NotEnoughPoints {
            get {
                return ResourceManager.GetString("NotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough points exist on this loyalty card.
        /// </summary>
        internal static string NotEnoughPointsOnCard {
            get {
                return ResourceManager.GetString("NotEnoughPointsOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only negative points payments are allowed.
        /// </summary>
        internal static string OnlyNegativeAmountsAllowed {
            get {
                return ResourceManager.GetString("OnlyNegativeAmountsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtendering is not allowed when returning.
        /// </summary>
        internal static string OvertenderingNotAllowedWhenReturning {
            get {
                return ResourceManager.GetString("OvertenderingNotAllowedWhenReturning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is not allowed with this loyalty card.
        /// </summary>
        internal static string PaymentNotAllowedWithCard {
            get {
                return ResourceManager.GetString("PaymentNotAllowedWithCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current payment is over the use limit (#1%) on the loyalty card. The payment has been updated to be #2.
        /// </summary>
        internal static string PaymentOverUsePointsLimit {
            get {
                return ResourceManager.GetString("PaymentOverUsePointsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a loyalty card number.
        /// </summary>
        internal static string PleaseEnterLoyaltyCardNumber {
            get {
                return ResourceManager.GetString("PleaseEnterLoyaltyCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string PointBalanceNotAvailable {
            get {
                return ResourceManager.GetString("PointBalanceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points due: #1.
        /// </summary>
        internal static string PointsDue {
            get {
                return ResourceManager.GetString("PointsDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points to be returned: #1.
        /// </summary>
        internal static string PointsToBeReturned {
            get {
                return ResourceManager.GetString("PointsToBeReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quote.
        /// </summary>
        internal static string QuoteLowCase {
            get {
                return ResourceManager.GetString("QuoteLowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loyalty points discount needs to be recalculated before the payment can be finalised.
        /// </summary>
        internal static string RecalculationOfLoyaltyDiscount {
            get {
                return ResourceManager.GetString("RecalculationOfLoyaltyDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving loyalty status.
        /// </summary>
        internal static string RetrievingLoyaltyStatus {
            get {
                return ResourceManager.GetString("RetrievingLoyaltyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loyalty points discount cannot be updated during a return transaction.
        /// </summary>
        internal static string ReturnSaleCannotUpdateLoyaltyPointDisc {
            get {
                return ResourceManager.GetString("ReturnSaleCannotUpdateLoyaltyPointDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum discount allowed on the card is #1.
        /// </summary>
        internal static string SchemeMinDiscountIs {
            get {
                return ResourceManager.GetString("SchemeMinDiscountIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum payment on the card is #1.
        /// </summary>
        internal static string SchemeMinPaymentIs {
            get {
                return ResourceManager.GetString("SchemeMinPaymentIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string SchemeNotFound {
            get {
                return ResourceManager.GetString("SchemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select loyalty card for discount.
        /// </summary>
        internal static string SelectLoyaltyCardForDiscount {
            get {
                return ResourceManager.GetString("SelectLoyaltyCardForDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select loyalty card for payment.
        /// </summary>
        internal static string SelectLoyaltyCardForPayment {
            get {
                return ResourceManager.GetString("SelectLoyaltyCardForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty points discount is not permitted as the sale already has a loyalty payment.
        /// </summary>
        internal static string TransactionAlreadyHasLoyaltyPayment {
            get {
                return ResourceManager.GetString("TransactionAlreadyHasLoyaltyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty payment is not permitted as the sale already has loyalty points discount.
        /// </summary>
        internal static string TransactionAlreadyHasLoyaltyPoints {
            get {
                return ResourceManager.GetString("TransactionAlreadyHasLoyaltyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update loyalty card customer.
        /// </summary>
        internal static string UpdateLoyaltyCardCustomerID {
            get {
                return ResourceManager.GetString("UpdateLoyaltyCardCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating issued loyalty points.
        /// </summary>
        internal static string UpdatingIssuedLoyaltyPoints {
            get {
                return ResourceManager.GetString("UpdatingIssuedLoyaltyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating used loyalty points.
        /// </summary>
        internal static string UpdatingUsedLoyaltyPoints {
            get {
                return ResourceManager.GetString("UpdatingUsedLoyaltyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = #1 points.
        /// </summary>
        internal static string ValueOfPoints {
            get {
                return ResourceManager.GetString("ValueOfPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whitesearch32px {
            get {
                object obj = ResourceManager.GetObject("Whitesearch32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
