
/*

	Incident No.	: ONE-5319
	Responsible		: Frentiu Florin
	Sprint			: Salt 3.11- 17.11
	Date created	: 27.10.2016

	Description		: Create RETAILITEMSERIALNUMBERS table, add column to POSTRANSACTIONSERVICEPROFILE
	
	
	Tables affected	: RETAILITEMSERIALNUMBERS,POSTRANSACTIONSERVICEPROFILE
						
*/


USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('RETAILITEMSERIALNUMBERS') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[RETAILITEMSERIALNUMBERS](
	[ID] [uniqueidentifier] NOT NULL,
	[ITEMMASTERID] [uniqueidentifier] NOT NULL,
	[SERIALNUMBER] [nvarchar](300) NOT NULL,
	[TYPEOFSERIAL] [tinyint] NOT NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[USEDDATE] [datetime] NULL,
	[REFERENCE] [nvarchar](50) NULL,
	[MANUALENTRY] [bit] NOT NULL,
 CONSTRAINT [PK_RETAILITEMSERIALNUMBERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

ALTER TABLE [dbo].[RETAILITEMSERIALNUMBERS] ADD  CONSTRAINT [DF_RETAILITEMSERIALNUMBERS_MANUALENTRY]  DEFAULT ((0)) FOR [MANUALENTRY]
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSTRANSACTIONSERVICEPROFILE' AND COLUMN_NAME = 'USESERIALNUMBERS')
BEGIN
ALTER TABLE dbo.POSTRANSACTIONSERVICEPROFILE ADD
	USESERIALNUMBERS bit NOT NULL CONSTRAINT DF_POSTRANSACTIONSERVICEPROFILE_USESERIALNUMBERS DEFAULT 0
END

GO
