/*

	Incident No.	: ONE-4639
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Pepper

	Description		: Adding a column for receipt email configuration in site service
	
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSTRANSACTIONSERVICEPROFILE' AND COLUMN_NAME = 'SENDRECEIPTEMAIL')
BEGIN
	ALTER TABLE dbo.POSTRANSACTIONSERVICEPROFILE ADD SENDRECEIPTEMAIL int NOT NULL CONSTRAINT DF_POSTRANSACTIONSERVICEPROFILE_SENDRECEIPTEMAIL DEFAULT 3
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'POSMENULINE' AND COLUMN_NAME = 'PARAMETER' AND CHARACTER_MAXIMUM_LENGTH < 51)
BEGIN
	ALTER TABLE dbo.POSMENULINE ALTER COLUMN PARAMETER NVARCHAR(500)
END	
GO

IF NOT EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 1901)
BEGIN
  INSERT INTO POSISOPERATIONS ( OPERATIONID, OPERATIONNAME, PERMISSIONID, PERMISSIONID2, CHECKUSERACCESS, USEROPERATION,DATAAREAID,LOOKUPTYPE)
  VALUES (1901, 'Send an email receipt', NULL, NULL, 1, 1,'LSR', 21)
END
GO
