/*

	Incident No.	: ONE-5319
	Responsible		: Frentiu Florin
	Sprint			: Salt 3.11- 17.11
	Date created	: 16.11.2016

	Description		: Change SERIALNUMBER column type to nvarchar(300), create unique index, add HASHEADERS column to import profile
	
	
	Tables affected	: RETAILITEMSERIALNUMBERS,IMPORTPROFILE
						
*/

USE LSPOSNET
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMSERIALNUMBERS' AND COLUMN_NAME = 'SERIALNUMBER')
BEGIN
ALTER TABLE dbo.RETAILITEMSERIALNUMBERS ALTER COLUMN SERIALNUMBER NVARCHAR(300) NOT NULL
END

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='UX_RETAILITEMSERIALNUMBERS' AND object_id = OBJECT_ID('RETAILITEMSERIALNUMBERS'))
BEGIN
CREATE UNIQUE NONCLUSTERED INDEX UX_RETAILITEMSERIALNUMBERS ON dbo.RETAILITEMSERIALNUMBERS
	(
	ITEMMASTERID,
	SERIALNUMBER
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IMPORTPROFILE' AND COLUMN_NAME = 'HASHEADERS')
BEGIN
ALTER TABLE dbo.IMPORTPROFILE ADD
	HASHEADERS bit NOT NULL CONSTRAINT DF_IMPORTPROFILE_HASHEADERS DEFAULT 1
END

GO