/*

	Incident No.	: ONE-5450
	Responsible		: Frentiu Florin
	Sprint			: Sumac 18.11- 1.12
	Date created	: 23.11.2016

	Description		: Change RFIDTAGID, INVENTSERIALID columns type to nvarchar(300)
	
	
	Tables affected	: RBOTRANSACTIONSALESTRANS
						
*/

USE LSPOSNET
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'RFIDTAGID' AND CHARACTER_MAXIMUM_LENGTH < 25)
BEGIN
ALTER TABLE dbo.RBOTRANSACTIONSALESTRANS ALTER COLUMN RFIDTAGID NVARCHAR(300) NOT NULL
END

GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'INVENTSERIALID' AND CHARACTER_MAXIMUM_LENGTH < 25)
BEGIN
ALTER TABLE dbo.RBOTRANSACTIONSALESTRANS ALTER COLUMN INVENTSERIALID NVARCHAR(300) NOT NULL
END

GO
