/*

	Incident No.	: ONE-5296
	Responsible		: Frentiu Florin
	Sprint			: Majoram 21.10-4.11
	Date created	: 27.10.2016

	Description		: Add Style Type column to POSSTYLE table
	
	
	Tables affected	: POSSTYLE
						
*/
USE LSPOSNET
GO
  
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'POSSTYLE' AND COLUMN_NAME = 'STYLETYPE'  )
BEGIN
ALTER TABLE dbo.POSSTYLE ADD
	STYLETYPE int NOT NULL CONSTRAINT DF_POSSTYLE_STYLETYPE DEFAULT 0
END	
GO

UPDATE  POSSTYLE SET STYLETYPE = 0 WHERE SYSTEMSTYLE = 0
GO

IF EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotal')
BEGIN
UPDATE  POSSTYLE SET STYLETYPE = 1 WHERE NAME = 'DualDisplayTotal'
END
GO

IF EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayLine')
BEGIN
UPDATE  POSSTYLE SET STYLETYPE = 2 WHERE NAME = 'DualDisplayLine'
END

IF EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayLineSub')
BEGIN
UPDATE  POSSTYLE SET STYLETYPE = 3 WHERE NAME = 'DualDisplayLineSub'
END

IF EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsLabels')
BEGIN
UPDATE  POSSTYLE SET STYLETYPE = 4 WHERE NAME = 'PosTotalsLabels'
END

IF EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsValues')
BEGIN
UPDATE  POSSTYLE SET STYLETYPE = 5 WHERE NAME = 'PosTotalsValues'
END

IF EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsBalanceValue')
BEGIN
UPDATE  POSSTYLE SET STYLETYPE = 6 WHERE NAME = 'PosTotalsBalanceValue'
END

IF EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'SystemNumPadButtonStyle')
BEGIN
UPDATE  POSSTYLE SET STYLETYPE = 7 WHERE NAME = 'SystemNumPadButtonStyle'
END

IF EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'SystemNumPadDigitButtonStyle')
BEGIN
UPDATE  POSSTYLE SET STYLETYPE = 8 WHERE NAME = 'SystemNumPadDigitButtonStyle'
END
 
GO

