
/*

	Incident No.	: ONE-5198
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: Basil

	Description		: Adding a column for default Issued in RBOGIFTCARDTABLE
	
						
*/

USE LSPOSNET
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOGIFTCARDTABLE' AND COLUMN_NAME = 'ISSUED')
BEGIN
	ALTER TABLE [dbo].[RBOGIFTCARDTABLE] ADD ISSUED TINYINT NOT NULL DEFAULT (1)
END
GO

UPDATE RBOGIFTCARDTABLE
SET ISSUED = 1
WHERE ISSUED IS NULL
GO
