/*

	Incident No.	: ONE-5632
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Garlic - 02.12
	Date created	: 02.12.16

	Description		: Operation Customer transactions set to be a non-user operation
	
	
	Tables affected	: POSISOPERATIONS
						
*/

USE LSPOSNET
GO

IF EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 609)
BEGIN
  UPDATE POSISOPERATIONS
  SET USEROPERATION = 0
  WHERE OPERATIONID = 609
END
GO

IF EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 610)
BEGIN
  UPDATE POSISOPERATIONS
  SET USEROPERATION = 0
  WHERE OPERATIONID = 610
END
GO

IF EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 611)
BEGIN
  UPDATE POSISOPERATIONS
  SET USEROPERATION = 0
  WHERE OPERATIONID = 611
END
GO
