/*

	Incident No.	: ONE-4639
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Turmeric 1.12 - 15.12
	Date created	: 12.12.2016

	Description		: Adding new configurations for windows printing to the hardware profile
	
	
	Tables affected	: POSHARDWAREPROFILE
						
*/

USE LSPOSNET
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'WINPRINT_LEFTMARGIN')
BEGIN
	ALTER TABLE dbo.POSHARDWAREPROFILE ADD WINPRINT_LEFTMARGIN INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'WINPRINT_RIGHTMARGIN')
BEGIN
	ALTER TABLE dbo.POSHARDWAREPROFILE ADD WINPRINT_RIGHTMARGIN INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'WINPRINT_FONTSIZE')
BEGIN
	ALTER TABLE dbo.POSHARDWAREPROFILE ADD WINPRINT_FONTSIZE INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'WINPRINT_PRINTDESIGNBOXES')
BEGIN
	ALTER TABLE dbo.POSHARDWAREPROFILE ADD WINPRINT_PRINTDESIGNBOXES tinyint NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'WINPRINT_FOLDERLOCATION')
BEGIN
	ALTER TABLE dbo.POSHARDWAREPROFILE ADD WINPRINT_FOLDERLOCATION nvarchar(500) NULL
END
GO
