/*

	Incident No.	: ONE-5481
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Muskat 
	Date created	: 03.01.2017

	Description		: Adding top and bottom margin fields to Hardware profile
	
	
	Tables affected	: POSHARDWAREPROFILE
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'WINPRINT_TOPMARGIN')
BEGIN
	ALTER TABLE dbo.POSHARDWAREPROFILE ADD WINPRINT_TOPMARGIN INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'WINPRINT_BOTTOMMARGIN')
BEGIN
	ALTER TABLE dbo.POSHARDWAREPROFILE ADD WINPRINT_BOTTOMMARGIN INT NULL
END
GO