/*

	Incident No.	: ONE-5769
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: Nutmeg 18.11- 1.12
	Date created	: 19.12.2016

	Description		: Implement Omni licensing for LS One
	
	
	Tables affected	: New table added OMNIAPPLICENSES
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'OMNIAPPLICENSES')
BEGIN
	CREATE TABLE [dbo].[OMNIAPPLICENSES](
		[APPID] [nvarchar](10) NOT NULL,
		[DEVICEID] [nvarchar](80) NOT NULL,
		[TERMINALID] [nvarchar](20) NOT NULL,
		[STOREID] [nvarchar](20) NOT NULL,
		[LICENSEKEY] [nvarchar](80) NOT NULL CONSTRAINT [DF_OMNIAPPLICENSES_LICENSEKEY]  DEFAULT (''),
		[ID] [uniqueidentifier] NOT NULL,
	 CONSTRAINT [PK_OMNIAPPLICENSES] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[OMNIAPPLICENSES] ADD  CONSTRAINT [DF_OMNIAPPLICENSES_ID]  DEFAULT (newid()) FOR [ID]

	CREATE UNIQUE NONCLUSTERED INDEX [IX_OMNIAPPLICENSES] ON [dbo].[OMNIAPPLICENSES]
	(
		[APPID] ASC,
		[DEVICEID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

END
GO