/*

	Incident No.	: ONE-2455
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Muskat 
	Date created	: 04.01.2017

	Description		: Creating new table, adding a new column to sales transaction table
	
	Tables affected	: RBOSTORETENDERTYPEPAYMENTLIMITATIONTABLE, RBOTRANSACTIONSALESTRANS
						
*/

USE LSPOSNET
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RBOSTORETENDERTYPEPAYMENTLIMITATIONTABLE')
BEGIN
	CREATE TABLE [dbo].[RBOSTORETENDERTYPEPAYMENTLIMITATIONTABLE](
		[STOREID] [nvarchar](20) NOT NULL,
		[TENDERTYPEID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[LIMITATIONMASTERID] [uniqueidentifier] NOT NULL,
	 CONSTRAINT [PK_RBOSTORETENDERTYPEPAYMENTLIMITATIONTABLE] PRIMARY KEY CLUSTERED 
	(
		[STOREID] ASC,
		[TENDERTYPEID] ASC,
		[DATAAREAID] ASC,
		[LIMITATIONMASTERID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'LIMITATIONMASTERID')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONSALESTRANS ADD LIMITATIONMASTERID uniqueidentifier NULL
END
GO

