/*
	Incident No.	: ONE-11382
	Responsible		: Adrian Chiorean
	Sprint			: Bichon
	Date created	: 15.01.2020

	Description		: Add column TEXTPOSITION to POSMENUHEADER, POSMENULINE, POSSTYLE
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADER' AND COLUMN_NAME = 'TEXTPOSITION')
BEGIN
	ALTER TABLE POSMENUHEADER ADD TEXTPOSITION INT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENUHEADER', 'TEXTPOSITION', 'Alignment of text in a button. Default is center.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'TEXTPOSITION')
BEGIN
	ALTER TABLE POSMENULINE ADD TEXTPOSITION INT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'TEXTPOSITION', 'Alignment of text in a button. Default is center.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSSTYLE' AND COLUMN_NAME = 'TEXTPOSITION')
BEGIN
	ALTER TABLE POSSTYLE ADD TEXTPOSITION INT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'POSSTYLE', 'TEXTPOSITION', 'Alignment of text in a button. Default is center.';
END
GO