/*
	Incident No.	: ONE-11362
	Responsible		: Adrian Chiorean
	Sprint			: Bichon
	Date created	: 14.01.2020

	Description		: Add column BORDERCOLOR, BORDERWIDTH and MARGIN to POSMENUHEADER 
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADER' AND COLUMN_NAME = 'BORDERCOLOR')
BEGIN
	ALTER TABLE POSMENUHEADER ADD BORDERCOLOR INT NOT NULL DEFAULT -3352871
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENUHEADER', 'BORDERCOLOR', 'Color of the border of each button in the menu header. Default is #CCD6D9.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADER' AND COLUMN_NAME = 'BORDERWIDTH')
BEGIN
	ALTER TABLE POSMENUHEADER ADD BORDERWIDTH INT NOT NULL DEFAULT 1
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENUHEADER', 'BORDERWIDTH', 'Width of the border of each button in the menu header. Default is 1.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADER' AND COLUMN_NAME = 'MARGIN')
BEGIN
	ALTER TABLE POSMENUHEADER ADD MARGIN INT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENUHEADER', 'MARGIN', 'Margin of each button in the menu header. Default is 0.';
END
GO