/*
	Incident No.	: ONE-11400 
	Responsible		: Adrian Chiorean
	Sprint			: Bichon
	Date created	: 10.01.2020

	Description		: Add column EMAILWINDOWSPRINTERCONFIGURATIONID to POSTRANSACTIONSERVICEPROFILE
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSTRANSACTIONSERVICEPROFILE' AND COLUMN_NAME = 'EMAILWINDOWSPRINTERCONFIGURATIONID')
BEGIN
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ADD EMAILWINDOWSPRINTERCONFIGURATIONID NVARCHAR(40) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSTRANSACTIONSERVICEPROFILE', 'EMAILWINDOWSPRINTERCONFIGURATIONID', 'ID of a windows printer configuration to be used when sending emails.';
END
GO