/*
	Incident No.	: ONE-11374
	Responsible		: Adrian Chiorean
	Sprint			: Akita
	Date created	: 27.03.2020

	Description		: Rename columns SAFEDROPUSESNUMPAD, SAFEDROPREVUSESNUMPAD, BANKDROPUSESNUMPAD, BANKDROPREVUSESNUMPAD, TENDERDECLUSESNUMPAD to
					  SAFEDROPUSESDENOMINATION, SAFEDROPREVUSESDENOMINATION, BANKDROPUSESDENOMINATION, BANKDROPREVUSESDENOMINATION, TENDERDECLUSESDENOMINATION in POSFUNCTIONALITYPROFILE
*/

USE LSPOSNET

CREATE TABLE #tempVariables
(
	SD BIT NOT NULL,
	SDR BIT NOT NULL,
	BD BIT NOT NULL,
	BDR BIT NOT NULL,
	TD BIT NOT NULL,
)
GO

INSERT INTO #tempVariables VALUES (0, 0, 0, 0, 0)
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'SAFEDROPUSESNUMPAD')
BEGIN

	IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSFUNCTIONALITYPROFILE_SAFEDROPUSESNUMPAD]') AND type = 'D')
		ALTER TABLE [dbo].[POSFUNCTIONALITYPROFILE] DROP CONSTRAINT [DF_POSFUNCTIONALITYPROFILE_SAFEDROPUSESNUMPAD]

	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILE.SAFEDROPUSESNUMPAD', 'SAFEDROPUSESDENOMINATION', 'COLUMN';
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_SAFEDROPUSESDENOMINATION DEFAULT 1 FOR SAFEDROPUSESDENOMINATION
	UPDATE #tempVariables SET SD = 1
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'SAFEDROPREVUSESNUMPAD')
BEGIN

	IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSFUNCTIONALITYPROFILE_SAFEDROPREVUSESNUMPAD]') AND type = 'D')
		ALTER TABLE [dbo].[POSFUNCTIONALITYPROFILE] DROP CONSTRAINT [DF_POSFUNCTIONALITYPROFILE_SAFEDROPREVUSESNUMPAD]

	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILE.SAFEDROPREVUSESNUMPAD', 'SAFEDROPREVUSESDENOMINATION', 'COLUMN';
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_SAFEDROPREVUSESDENOMINATION DEFAULT 1 FOR SAFEDROPREVUSESDENOMINATION
	UPDATE #tempVariables SET SDR = 1
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'BANKDROPUSESNUMPAD')
BEGIN

	IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSFUNCTIONALITYPROFILE_BANKDROPUSESNUMPAD]') AND type = 'D')
		ALTER TABLE [dbo].[POSFUNCTIONALITYPROFILE] DROP CONSTRAINT [DF_POSFUNCTIONALITYPROFILE_BANKDROPUSESNUMPAD]

	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILE.BANKDROPUSESNUMPAD', 'BANKDROPUSESDENOMINATION', 'COLUMN';
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_BANKDROPUSESDENOMINATION DEFAULT 1 FOR BANKDROPUSESDENOMINATION
	UPDATE #tempVariables SET BD = 1
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'BANKDROPREVUSESNUMPAD')
BEGIN

	IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSFUNCTIONALITYPROFILE_BANKDROPREVUSESNUMPAD]') AND type = 'D')
		ALTER TABLE [dbo].[POSFUNCTIONALITYPROFILE] DROP CONSTRAINT [DF_POSFUNCTIONALITYPROFILE_BANKDROPREVUSESNUMPAD]

	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILE.BANKDROPREVUSESNUMPAD', 'BANKDROPREVUSESDENOMINATION', 'COLUMN';
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_BANKDROPREVUSESDENOMINATION DEFAULT 1 FOR BANKDROPREVUSESDENOMINATION
	UPDATE #tempVariables SET BDR = 1
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'TENDERDECLUSESNUMPAD')
BEGIN

	IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSFUNCTIONALITYPROFILE_TENDERDECLUSESNUMPAD]') AND type = 'D')
		ALTER TABLE [dbo].[POSFUNCTIONALITYPROFILE] DROP CONSTRAINT [DF_POSFUNCTIONALITYPROFILE_TENDERDECLUSESNUMPAD]

	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILE.TENDERDECLUSESNUMPAD', 'TENDERDECLUSESDENOMINATION', 'COLUMN';
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_TENDERDECLUSESDENOMINATION DEFAULT 1 FOR TENDERDECLUSESDENOMINATION
	UPDATE #tempVariables SET TD = 1
END
GO

IF EXISTS(SELECT 1 FROM sys.triggers WHERE name = 'Update_POSFUNCTIONALITYPROFILE' AND type = 'TR')
BEGIN
	;DISABLE TRIGGER POSFUNCTIONALITYPROFILE.Update_POSFUNCTIONALITYPROFILE ON POSFUNCTIONALITYPROFILE
END
GO

-- Invert values for renamed columns
IF EXISTS (SELECT 1 FROM #tempVariables where SD = 1)
BEGIN
	UPDATE POSFUNCTIONALITYPROFILE SET SAFEDROPUSESDENOMINATION = CASE WHEN SAFEDROPUSESDENOMINATION = 0 THEN 1 ELSE 0 END
END
GO

IF EXISTS (SELECT 1 FROM #tempVariables where SDR = 1)
BEGIN
	UPDATE POSFUNCTIONALITYPROFILE SET SAFEDROPREVUSESDENOMINATION = CASE WHEN SAFEDROPREVUSESDENOMINATION = 0 THEN 1 ELSE 0 END
END
GO

IF EXISTS (SELECT 1 FROM #tempVariables where BD = 1)
BEGIN
	UPDATE POSFUNCTIONALITYPROFILE SET BANKDROPUSESDENOMINATION = CASE WHEN BANKDROPUSESDENOMINATION = 0 THEN 1 ELSE 0 END
END
GO

IF EXISTS (SELECT 1 FROM #tempVariables where BDR = 1)
BEGIN
	UPDATE POSFUNCTIONALITYPROFILE SET BANKDROPREVUSESDENOMINATION = CASE WHEN BANKDROPREVUSESDENOMINATION = 0 THEN 1 ELSE 0 END
END
GO

IF EXISTS (SELECT 1 FROM #tempVariables where TD = 1)
BEGIN
	UPDATE POSFUNCTIONALITYPROFILE SET TENDERDECLUSESDENOMINATION = CASE WHEN TENDERDECLUSESDENOMINATION = 0 THEN 1 ELSE 0 END
END
GO
IF EXISTS(SELECT 1 FROM sys.triggers WHERE name = 'Update_POSFUNCTIONALITYPROFILE' AND type = 'TR')
BEGIN
	;ENABLE TRIGGER POSFUNCTIONALITYPROFILE.Update_POSFUNCTIONALITYPROFILE ON POSFUNCTIONALITYPROFILE
END
GO

DROP TABLE #tempVariables
GO