/*
	Incident No.	: ONE-11383
	Responsible		: Adrian Chiorean
	Sprint			: Labradoodle 
	Date created	: 04.02.2020

	Description		: Add column USEIMAGEFONT, IMAGEFONTTEXT, IMAGEFONTNAME, IMAGEFONTSIZE, IMAGEFONTBOLD, IMAGEFONTITALIC, IMAGEFONTUNDERLINE, IMAGEFONTSTRIKETHROUGH, IMAGEFONTCHARSET, IMAGEFONTCOLOR to POSMENULINE
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'USEIMAGEFONT')
BEGIN
	ALTER TABLE POSMENULINE ADD USEIMAGEFONT BIT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'USEIMAGEFONT', 'True if a font with symbols should be used instead of the image. Default is false.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'IMAGEFONTTEXT')
BEGIN
	ALTER TABLE POSMENULINE ADD IMAGEFONTTEXT NVARCHAR(80) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'IMAGEFONTTEXT', 'The text to be displayed using the image font instead of an image.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'IMAGEFONTNAME')
BEGIN
	ALTER TABLE POSMENULINE ADD IMAGEFONTNAME NVARCHAR(32) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'IMAGEFONTNAME', 'The font name for the image font.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'IMAGEFONTSIZE')
BEGIN
	ALTER TABLE POSMENULINE ADD IMAGEFONTSIZE INT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'IMAGEFONTSIZE', 'The font size for the image font.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'IMAGEFONTBOLD')
BEGIN
	ALTER TABLE POSMENULINE ADD IMAGEFONTBOLD BIT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'IMAGEFONTBOLD', 'True if the image font should be bold.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'IMAGEFONTITALIC')
BEGIN
	ALTER TABLE POSMENULINE ADD IMAGEFONTITALIC BIT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'IMAGEFONTITALIC', 'True if the image font should be italic.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'IMAGEFONTUNDERLINE')
BEGIN
	ALTER TABLE POSMENULINE ADD IMAGEFONTUNDERLINE BIT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'IMAGEFONTUNDERLINE', 'True if the image font should be underlined.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'IMAGEFONTSTRIKETHROUGH')
BEGIN
	ALTER TABLE POSMENULINE ADD IMAGEFONTSTRIKETHROUGH BIT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'IMAGEFONTSTRIKETHROUGH', 'True if the image font should be strikethrough.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'IMAGEFONTCHARSET')
BEGIN
	ALTER TABLE POSMENULINE ADD IMAGEFONTCHARSET INT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'IMAGEFONTCHARSET', 'The charset used for the image font.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENULINE' AND COLUMN_NAME = 'IMAGEFONTCOLOR')
BEGIN
	ALTER TABLE POSMENULINE ADD IMAGEFONTCOLOR INT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSMENULINE', 'IMAGEFONTCOLOR', 'The color used for the image font.';
END
GO