/*
	Incident No.	: ONE-11660
	Responsible		: Adrian Chiorean
	Sprint			: Akita
	Date created	: 23.03.2020

	Description		: Add column RECEIPTRETURNBACKGROUNDIMAGEID, RECEIPTRETURNBACKGROUNDIMAGELAYOUT, RECEIPTRETURNBORDERCOLOR to POSVISUALPROFILE
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTRETURNBACKGROUNDIMAGEID' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD RECEIPTRETURNBACKGROUNDIMAGEID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'RECEIPTRETURNBACKGROUNDIMAGEID', 'ID of the image from the image bank to use as the background of the receipt control when in return mode.'
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTRETURNBACKGROUNDIMAGELAYOUT' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD RECEIPTRETURNBACKGROUNDIMAGELAYOUT INT NOT NULL DEFAULT 1 -- Default tiled
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'RECEIPTRETURNBACKGROUNDIMAGELAYOUT', 'Represents how the return receipt background image is drawn (None, Tile, Center, Stretch, Zoom).'
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTRETURNBORDERCOLOR' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD RECEIPTRETURNBORDERCOLOR INT NOT NULL DEFAULT -1027247
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'RECEIPTRETURNBORDERCOLOR', 'Represents the receipt item border color when it is in return mode.'
END
GO