/*
	Incident No.	: ONE-11556
	Responsible		: Simona Avornicesei
	Sprint			: Tamaskan 
	Date created	: 16.04.2020

	Description		: Adding columns to POSFUNCTIONALITYPROFILE table to configure offline functionality in mobile POS.
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OMNIALLOWOFFLINETRANS' AND TABLE_NAME = 'POSFUNCTIONALITYPROFILE')
    BEGIN
        ALTER TABLE POSFUNCTIONALITYPROFILE ADD OMNIALLOWOFFLINETRANS BIT;
        ALTER TABLE POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFP_OMNIAOT DEFAULT 0 FOR OMNIALLOWOFFLINETRANS
        
        EXECUTE spDB_SetFieldDescription_1_0 'POSFUNCTIONALITYPROFILE', 'OMNIALLOWOFFLINETRANS', 'Determines if mobile POS can function in offline mode.'
    END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OMNISHOWMINVENTORY' AND TABLE_NAME = 'POSFUNCTIONALITYPROFILE')
    BEGIN
        ALTER TABLE POSFUNCTIONALITYPROFILE ADD OMNISHOWMINVENTORY BIT
        ALTER TABLE POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFP_OMNISHI DEFAULT 0 FOR OMNISHOWMINVENTORY
        
        EXECUTE spDB_SetFieldDescription_1_0 'POSFUNCTIONALITYPROFILE', 'OMNISHOWMINVENTORY', 'Determines if a shortcut to mobile Inventory will be displayed in mobile POS.'
    END
GO