/*
	Incident No.	: ONE-11528
	Responsible		: Helgi Runar Gunnarsson
	Sprint			: Chihuahua 
	Date created	: 28.05.2020

	Description		: Adding UNIT column to POSFUNCTIONALITYPROFILE table and update TARGETID column in PERIODICDISCOUNTLINE.
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'UNIT' AND TABLE_NAME = 'PERIODICDISCOUNTLINE')
    BEGIN
        ALTER TABLE PERIODICDISCOUNTLINE ADD UNIT NVARCHAR(30) NULL
        EXECUTE spDB_SetFieldDescription_1_0 'PERIODICDISCOUNTLINE', 'UNIT', 'Determines witch unit the dicount is valid for.'
    END
GO

BEGIN
    UPDATE
        PL
    SET
        PL.UNIT = R.SALESUNITID
    FROM
	    PERIODICDISCOUNTLINE PL
	    JOIN PERIODICDISCOUNT P ON PL.OFFERID = P.OFFERID
	    JOIN RETAILITEM R ON R.MASTERID = PL.TARGETMASTERID
    WHERE P.PDTYPE = 0
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'TARGETID' AND TABLE_NAME = 'PERIODICDISCOUNTLINE')
    BEGIN
        ALTER TABLE PERIODICDISCOUNTLINE ALTER COLUMN TARGETID NVARCHAR(60)
    END
GO