/*
	Incident No.	: ONE-11701
	Responsible		: Hörður Kristjánsson
	Sprint			: Akita
	Date created	: 27.03.2020

	Description		: Adding columns to POSVISUALPROFILE so users can control the colors of buttons in the POS
*/

USE LSPOSNET

-- CONFIRMBUTTONTHEMECOLOR
-- CONFIRMBUTTONTHEMECOLOR

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'CONFIRMBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD CONFIRMBUTTONSTYLEID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'CONFIRMBUTTONSTYLEID', 'The ID of the style that should be applied for confirm(OK, Yes) buttons in the POS.'
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'CANCELBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD CANCELBUTTONSTYLEID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'CANCELBUTTONSTYLEID', 'The ID of the style that should be applied for cancellation buttons(Cancel, Close, No) in the POS.'
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ACTIONBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD ACTIONBUTTONSTYLEID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'ACTIONBUTTONSTYLEID', 'The ID of the style that should be applied for action buttons in the POS.'
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'NORMALBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD NORMALBUTTONSTYLEID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'NORMALBUTTONSTYLEID', 'The ID of the style that should be applied for normal buttons in the POS.'
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OTHERBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD OTHERBUTTONSTYLEID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'OTHERBUTTONSTYLEID', 'The ID of the style that should be applied for other/default buttons in the POS.'
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OVERRIDEPOSCONTROLBORDERCOLOR' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD OVERRIDEPOSCONTROLBORDERCOLOR BIT NOT NULL DEFAULT(0)
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'OVERRIDEPOSCONTROLBORDERCOLOR', 'If true then the value in POSCONTROLBORDERCOLOR is used for the border color of POS controls.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'POSCONTROLBORDERCOLOR' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD POSCONTROLBORDERCOLOR INT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'POSCONTROLBORDERCOLOR', 'The color to use for control borders. This is only used if OVERRIDEPOSCONTROLBORDERCOLOR is set to true.';
END
GO