/*
	Incident No.	: ONE-11804
	Responsible		: Adrian Chiorean
	Sprint			: Tamaskan 
	Date created	: 05.05.2020

	Description		: Increase size of address fields for TOURIST table
*/

USE LSPOSNET

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TOURIST' AND COLUMN_NAME = 'ADDRESS' AND CHARACTER_MAXIMUM_LENGTH < 250)
BEGIN
	ALTER TABLE TOURIST ALTER COLUMN [ADDRESS] NVARCHAR(250) NULL
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TOURIST' AND COLUMN_NAME = 'STREET' AND CHARACTER_MAXIMUM_LENGTH < 250)
BEGIN
	ALTER TABLE TOURIST ALTER COLUMN STREET NVARCHAR(250) NULL
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TOURIST' AND COLUMN_NAME = 'CITY' AND CHARACTER_MAXIMUM_LENGTH < 250)
BEGIN
	ALTER TABLE TOURIST ALTER COLUMN CITY NVARCHAR(250) NULL
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TOURIST' AND COLUMN_NAME = 'STATE' AND CHARACTER_MAXIMUM_LENGTH < 250)
BEGIN
	ALTER TABLE TOURIST ALTER COLUMN [STATE] NVARCHAR(250) NULL
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TOURIST' AND COLUMN_NAME = 'COUNTY' AND CHARACTER_MAXIMUM_LENGTH < 250)
BEGIN
	ALTER TABLE TOURIST ALTER COLUMN COUNTY NVARCHAR(250) NULL
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TOURIST' AND COLUMN_NAME = 'COUNTRY' AND CHARACTER_MAXIMUM_LENGTH < 250)
BEGIN
	ALTER TABLE TOURIST ALTER COLUMN COUNTRY NVARCHAR(250) NULL
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TOURIST' AND COLUMN_NAME = 'ZIPCODE' AND CHARACTER_MAXIMUM_LENGTH < 20)
BEGIN
	ALTER TABLE TOURIST ALTER COLUMN ZIPCODE NVARCHAR(20) NULL
END
GO