
/*

	Incident No.	: 6089
	Responsible		: GuÃ°bjÃ¶rn Einarsson
	Sprint			: DotNetPM\LS POS 2010.1\Dot Net Stream\Sprint 03\Dot Net Team
	Date created	: 11.10.2010
	
	Description		: Adding a table structure for statements and statement lines

	Logic scripts   : No stored procedures added or changed
	
	Tables affected:  RBOSTATEMENTTABLE and RBOSTATEMENTLINE
						
*/

Use LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[RBOSTATEMENTTABLE]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE dbo.RBOSTATEMENTTABLE
		(
			STATEMENTID nvarchar(20) NOT NULL,
			STOREID nvarchar(60) NOT NULL,
			CALCULATEDTIME DateTime NULL,
			POSTINGDATE Date NOT NULL,
			PERIODSTARTINGTIME DateTime NOT NULL,
			PERIODENDINGTIME DateTime NOT NULL,
			POSTED tinyInt NOT NULL,
			CALCULATED tinyInt NOT NULL,
			DATAAREAID nvarchar(4) NOT NULL
		)  ON [PRIMARY]

	ALTER TABLE [dbo].RBOSTATEMENTTABLE ADD  CONSTRAINT [DF__RBOSTATEMENTTABLE__DATAAREAID]  DEFAULT ('LSR') FOR DATAAREAID


	ALTER TABLE dbo.RBOSTATEMENTTABLE ADD CONSTRAINT PK_RBOSTATEMENTTABLE
	PRIMARY KEY CLUSTERED (STATEMENTID ,DATAAREAID) ON [PRIMARY]

END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[RBOSTATEMENTLINE]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE dbo.RBOSTATEMENTLINE
		(
			STATEMENTID nvarchar(20) NOT NULL,
			LINENUMBER nvarchar(20) NOT NULL,
			STAFFID nvarchar(10) NULL,
			TERMINALID nvarchar(10) NULL,
			CURRENCYCODE nvarchar(10) NOT NULL,
			TENDERID nvarchar(60) NOT NULL,
			TRANSACTIONAMOUNT decimal(24,6) NOT NULL,
			BANKEDAMOUNT decimal(24,6) NOT NULL,
			SAFEAMOUNT decimal(24,6) NOT NULL,
			COUNTEDAMOUNT decimal(24,6) NOT NULL,
			DIFFERENCE decimal(24,6) NOT NULL,
			DATAAREAID nvarchar(4) NOT NULL
		)  ON [PRIMARY]

	ALTER TABLE [dbo].RBOSTATEMENTLINE ADD  CONSTRAINT [DF__RBOSTATEMENTLINE__DATAAREAID]  DEFAULT ('LSR') FOR DATAAREAID


	ALTER TABLE dbo.RBOSTATEMENTLINE ADD CONSTRAINT PK_RBOSTATEMENTLINE
	PRIMARY KEY CLUSTERED (STATEMENTID, LINENUMBER, DATAAREAID) ON [PRIMARY]
	 
END
GO