
/*

	Incident No.	: N/A
	Responsible		: BjÃ¶rn EirÃ­ksson
	Sprint			: DotNetPM\LS POS 2010.1\Dot Net Stream\Sprint 03\Dot Net Team
	Date created	: 10.10.2010
	
	Description		: Adding a table structure for vendors

	Logic scripts   : No stored procedures added or changed
	
	Tables affected:  VENDTABLE 
						
*/

Use LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[VENDTABLE]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE dbo.VENDTABLE
		(
		[ACCOUNTNUM] nvarchar(20) NOT NULL,
		[NAME] nvarchar(60) NOT NULL,
		[ADDRESS] [nvarchar](250) NULL,
		[STREET] [nvarchar](250) NULL,
		[ZIPCODE] [nvarchar](10) NULL,
		[CITY] [nvarchar](60) NULL,
		[COUNTY] [nvarchar](10) NULL,
		[STATE] [nvarchar](10) NULL,
		[COUNTRY] [nvarchar](10) NULL,
		[PHONE] nvarchar(20) NULL,
		[EMAIL] nvarchar(80) NULL,
		[FAX] nvarchar(20) NULL,
		[DEFAULTCONTACTID] nvarchar(20) NULL,
		[LANGUAGEID] nvarchar(7) NULL,
		[CURRENCY] nvarchar(3) NOT NULL,
		[MEMO] ntext NULL,
		DATAAREAID nvarchar(4) NOT NULL
		)  ON [PRIMARY]

	ALTER TABLE [dbo].VENDTABLE ADD  CONSTRAINT [DF__VENDTABLE__DATAAREAID]  DEFAULT ('LSR') FOR [DATAAREAID]


	ALTER TABLE dbo.VENDTABLE ADD CONSTRAINT PK_VENDTABLE
	PRIMARY KEY CLUSTERED ([ACCOUNTNUM],DATAAREAID) ON [PRIMARY]

END
GO


IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[NUMBERSEQUENCETABLE]') AND TYPE IN ('U'))
BEGIN
	IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[NUMBERSEQUENCETABLE]') AND NAME='EMBEDSTOREID')
	BEGIN
		ALTER TABLE dbo.NUMBERSEQUENCETABLE ADD EMBEDSTOREID [tinyint] NULL
		ALTER TABLE dbo.NUMBERSEQUENCETABLE ADD STOREID [nvarchar](10) NULL
	END
END
GO

if Exists(Select 'x' from dbo.NUMBERSEQUENCETABLE where EMBEDSTOREID is null)
begin
update dbo.NUMBERSEQUENCETABLE set FORMAT = 'VN######', EMBEDSTOREID = 1,STOREID = 'HO'
where NUMBERSEQUENCE = 'Variant_1'

		update dbo.NUMBERSEQUENCETABLE set EMBEDSTOREID = 0,STOREID = 'HO'
		where NUMBERSEQUENCE = 'R-STORE'

		update dbo.NUMBERSEQUENCETABLE set EMBEDSTOREID = 1,STOREID = 'HO'
		where NUMBERSEQUENCE = 'ITEM'

		update dbo.NUMBERSEQUENCETABLE set EMBEDSTOREID = 1,STOREID = 'HO'
		where NUMBERSEQUENCE = 'INV_3'

		update dbo.NUMBERSEQUENCETABLE set FORMAT = 'D######', EMBEDSTOREID = 1,STOREID = 'HO'
		where NUMBERSEQUENCE = 'R-DISCO'

		update dbo.NUMBERSEQUENCETABLE set FORMAT = '#######', EMBEDSTOREID = 1,STOREID = 'HO'
		where NUMBERSEQUENCE = 'R-MULT-G'

		update dbo.NUMBERSEQUENCETABLE set FORMAT = 'MM######', EMBEDSTOREID = 1,STOREID = 'HO'
		where NUMBERSEQUENCE = 'R-MIXM'

		ALTER TABLE NUMBERSEQUENCETABLE
		DROP CONSTRAINT I_273SERIESIDX

		ALTER TABLE NUMBERSEQUENCETABLE ALTER COLUMN EMBEDSTOREID [tinyint] NOT NULL
		ALTER TABLE NUMBERSEQUENCETABLE ALTER COLUMN STOREID [nvarchar](10) NOT NULL

		ALTER TABLE dbo.NUMBERSEQUENCETABLE ADD CONSTRAINT PK_NUMBERSEQUENCETABLE
		PRIMARY KEY CLUSTERED ([NUMBERSEQUENCE],[STOREID],DATAAREAID) ON [PRIMARY]
end

GO