/*

	Incident No.	: [TFS incident no]
	Responsible		: Tobias Helmer
	Sprint			: LS Retail .NET v 2010 - Sprint 1
	Date created	: 28.10.2010
	
	Description		: Journal Table creation script for inventory adjustments

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: InventJournalTable (creation)
					  InventJournalTrans (creation)
					  InventTransReason  (creation)
						
*/

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[INVENTJOURNALTABLE]') AND TYPE IN ('U'))
BEGIN

CREATE TABLE [dbo].[INVENTJOURNALTABLE](
	[JOURNALID] [nvarchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](60) NOT NULL,
	[POSTED] [int] NOT NULL,	
	[POSTEDDATETIME] [datetime] NOT NULL,
	[JOURNALTYPE] [int] NOT NULL,
	[JOURNALNAMEID] [nvarchar](10) NOT NULL,
	[EMPLID] [uniqueidentifier] NOT NULL,	
	[POSTEDUSERID] [nvarchar](5) NOT NULL,
	[NUMOFLINES] [int] NOT NULL,
	[DELETEPOSTEDLINES] [int] NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	
 CONSTRAINT [I_154JOURNALIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[JOURNALID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVENTJOURNALTABLE] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [POSTEDDATETIME]
ALTER TABLE [dbo].[INVENTJOURNALTABLE] ADD  DEFAULT ((0)) FOR [JOURNALTYPE]
ALTER TABLE [dbo].[INVENTJOURNALTABLE] ADD  DEFAULT ('') FOR [JOURNALNAMEID]
ALTER TABLE [dbo].[INVENTJOURNALTABLE] ADD  DEFAULT ('LSR') FOR [DATAAREAID]
ALTER TABLE [dbo].[INVENTJOURNALTABLE] ADD  DEFAULT ((0)) FOR [DELETEPOSTEDLINES]
ALTER TABLE [dbo].[INVENTJOURNALTABLE] ADD  DEFAULT ('') FOR [POSTEDUSERID]
ALTER TABLE [dbo].[INVENTJOURNALTABLE] ADD  DEFAULT ((0)) FOR [NUMOFLINES]

END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[INVENTJOURNALTRANS]') AND TYPE IN ('U'))
BEGIN

CREATE TABLE [dbo].[INVENTJOURNALTRANS](
	[JOURNALID] [nvarchar](10) NOT NULL,
	[LINENUM] [numeric](28, 12) NOT NULL,
	[TRANSDATE] [datetime] NOT NULL,
	[VOUCHER] [nvarchar](20) NOT NULL,
	[JOURNALTYPE] [int] NOT NULL,
	[ITEMID] [nvarchar](20) NOT NULL,
	[QTY] [numeric](28, 12) NOT NULL,
	[COSTPRICE] [numeric](28, 12) NOT NULL,
	[PRICEUNIT] [numeric](28, 12) NOT NULL,
	[COSTMARKUP] [numeric](28, 12) NOT NULL,
	[COSTAMOUNT] [numeric](28, 12) NOT NULL,
	[SALESAMOUNT] [numeric](28, 12) NOT NULL,	
	[INVENTONHAND] [numeric](28, 12) NOT NULL,
	[COUNTED] [numeric](28, 12) NOT NULL,
	[DIMENSION] [nvarchar](10) NOT NULL,
	[DIMENSION2_] [nvarchar](10) NOT NULL,
	[DIMENSION3_] [nvarchar](10) NOT NULL,
	[REASONID][nvarchar](10) NOT NULL,
	[INVENTDIMID] [nvarchar](20) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,	
 CONSTRAINT [I_155LINEIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[JOURNALID] ASC,
	[LINENUM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('') FOR [JOURNALID]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [LINENUM]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [TRANSDATE]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('') FOR [VOUCHER]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [JOURNALTYPE]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('') FOR [ITEMID]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [QTY]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [COSTPRICE]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [PRICEUNIT]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [COSTMARKUP]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [COSTAMOUNT]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [SALESAMOUNT]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [INVENTONHAND]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ((0)) FOR [COUNTED]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('') FOR [DIMENSION]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('') FOR [DIMENSION2_]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('') FOR [DIMENSION3_]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('') FOR [REASONID]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('') FOR [INVENTDIMID]
ALTER TABLE [dbo].[INVENTJOURNALTRANS] ADD  DEFAULT ('LSR') FOR [DATAAREAID]

END 
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[INVENTTRANSREASON]') AND TYPE IN ('U'))
BEGIN

CREATE TABLE [dbo].[INVENTTRANSREASON](
	[REASONID] [nvarchar](10) NOT NULL,
	[REASONTEXT] [nvarchar](60) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	
 CONSTRAINT [I_REASONIDX] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[REASONID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVENTTRANSREASON] ADD  DEFAULT ('LSR') FOR [DATAAREAID]
ALTER TABLE [dbo].[INVENTTRANSREASON] ADD  DEFAULT ('') FOR [REASONTEXT]

END
GO