/*

	Incident No.	: N/A
	Responsible		: Guðbjörn Einarsson
	Sprint			: 
	Date created	: 17.11.2010
	
	Description		: Adding purchase orders tables

	Logic scripts   : No stored procedures added or changed
	
	Tables affected:  PURCHASEORDERS, PURCHASEORDERLINE
						
*/

Use LSPOSNET


BEGIN
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[PURCHASEORDERS]') AND TYPE IN ('U'))
	BEGIN
	CREATE TABLE [dbo].PURCHASEORDERS(
		PURCHASEORDERID nvarchar(20) NOT NULL,
		VENDORID nvarchar(20) NOT NULL,
		CONTACTID nvarchar(20) NULL,
		PURCHASESTATUS int NOT NULL,
		DELIVERYDATE DateTime NOT NULL,
		CURRENCYCODE nvarchar(20) NOT NULL,
		CREATEDDATE DateTime NOT NULL,
		ORDERER nvarchar(20) NOT NULL,
		DELIVERYNAME nvarchar(250) NOT NULL,
		DELIVERYADDRESS nvarchar(250) NOT NULL,
		DELIVERYSTREET nvarchar(250) NOT NULL,
		DELIVERYZIPCODE nvarchar(250) NOT NULL,
		DELIVERYCITY nvarchar(250) NOT NULL,
		DELIVERYCOUNTY nvarchar(250) NOT NULL,
		DELIVERYSTATE nvarchar(250) NOT NULL,
		DELIVERYCOUNTRY nvarchar(250) NOT NULL,
		DATAAREAID nvarchar(4) NOT NULL
		)
	
		alter table dbo.PURCHASEORDERS add constraint PK_PURCHASEORDERS
		primary key clustered (PURCHASEORDERID,DATAAREAID) on [PRIMARY]
	END
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[PURCHASEORDERLINE]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].PURCHASEORDERLINE(
	PURCHASEORDERID nvarchar(20) NOT NULL,
	LINENUMBER nvarchar(20) NOT NULL,
	RETAILITEMID nvarchar(20) NOT NULL,
	VENDORITEMID nvarchar(40) NOT NULL,
	VARIANTID nvarchar(20) NULL,
	UNITID nvarchar(20) NOT NULL,
	QUANTITY decimal(24,6) NOT NULL,
	PRICE decimal(24,6) NOT NULL,
	DATAAREAID nvarchar(4) NOT NULL
	)
	
	alter table dbo.PURCHASEORDERLINE add constraint PK_PURCHASEORDERLINE
	primary key clustered (PURCHASEORDERID,LINENUMBER,DATAAREAID) on [PRIMARY]
END
GO
