
/*

	Incident No.	: [TFS incident no]
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: [N/A]
	Date created	: [12.11.2010]

	Description		: Tables and data needed for Hospitality functionality in LS POS

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: POSMenuHeader					- New table
					  POSMenuLine					- New table
					  POSParameterSetup				- New table, Operation data added to table
					  POSISHospitalityOperations	- New table, Operation data added to table
					  POSISOperations				- Operation added					
						
*/

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[POSMENUHEADER]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[POSMENUHEADER](
		[MENUID] [nvarchar](20) NOT NULL,
		[DESCRIPTION] [nvarchar](30) NULL,
		[COLUMNS] [int] NULL,
		[ROWS] [int] NULL,
		[MENUCOLOR] [int] NULL,
		[FONTNAME] [nvarchar](32) NULL,
		[FONTSIZE] [int] NULL,
		[FONTBOLD] [tinyint] NULL,
		[FORECOLOR] [int] NULL,
		[BACKCOLOR] [int] NULL,
		[FONTITALIC] [tinyint] NULL,
		[FONTCHARSET] [int] NULL,
		[USENAVOPERATION] [tinyint] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_RBOMENUHEADER] PRIMARY KEY CLUSTERED 
	(
		[MENUID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[POSMENUHEADER] ADD  CONSTRAINT [DF_RBOMENUHEADER_DATAAREAID]  DEFAULT (N'LSR') FOR [DATAAREAID]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[POSMENULINE]') AND TYPE IN ('U'))
BEGIN

	CREATE TABLE [dbo].[POSMENULINE](
		[MENUID] [nvarchar](20) NOT NULL,
		[SEQUENCE] [nvarchar](20) NOT NULL,
		[KEYNO] [int] NOT NULL,
		[DESCRIPTION] [nvarchar](80) NULL,
		[OPERATION] [int] NULL,
		[PARAMETER] [nvarchar](50) NULL,
		[PARAMETERTYPE] [int] NULL,
		[APPLIESTO] [int] NULL,
		[FONTNAME] [nvarchar](32) NULL,
		[FONTSIZE] [int] NULL,
		[FONTBOLD] [tinyint] NULL,
		[FORECOLOR] [int] NULL,
		[BACKCOLOR] [int] NULL,
		[FONTITALIC] [tinyint] NULL,
		[FONTCHARSET] [int] NULL,
		[DISABLED] [tinyint] NULL,
		[PICTURE] [image] NULL,
		[PICTUREFILE] [nvarchar](200) NULL,
		[HIDEDESCRONPICTURE] [tinyint] NULL,
		[FONTSTRIKETHROUGH] [tinyint] NULL,
		[FONTUNDERLINE] [tinyint] NULL,
		[COLUMNSPAN] [int] NULL,
		[ROWSPAN] [int] NULL,
		[NAVOPRATION] [nvarchar](20) NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_POSMENULINE] PRIMARY KEY CLUSTERED 
	(
		[MENUID] ASC,
		[SEQUENCE] ASC,		
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

	ALTER TABLE [dbo].[POSMENULINE] ADD  CONSTRAINT [DF_POSMENULINE_DISABLED]  DEFAULT ((0)) FOR [DISABLED]
	ALTER TABLE [dbo].[POSMENULINE] ADD  CONSTRAINT [DF_POSMENULINE_APPLIESTO]  DEFAULT ((0)) FOR [APPLIESTO]
	ALTER TABLE [dbo].[POSMENULINE] ADD  CONSTRAINT [DF_POSMENULINE_COLUMNSPAN]  DEFAULT ((1)) FOR [COLUMNSPAN]
	ALTER TABLE [dbo].[POSMENULINE] ADD  CONSTRAINT [DF_POSMENULINE_ROWSPAN]  DEFAULT ((1)) FOR [ROWSPAN]
	ALTER TABLE [dbo].[POSMENULINE] ADD  CONSTRAINT [DF_POSMENULINE_DATAAREAID]  DEFAULT (N'LSR') FOR [DATAAREAID]
	
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[POSISHOSPITALITYOPERATIONS]') AND TYPE IN ('U'))
BEGIN

	CREATE TABLE [dbo].[POSISHOSPITALITYOPERATIONS](
		[OPERATIONID] [int] NOT NULL,
		[OPERATIONNAME] [nvarchar](50) NULL,
		[PERMISSIONID] [int] NULL,
		[CHECKUSERACCESS] [tinyint] NULL,
		[ALLOWPARAMETER] [tinyint] NULL,		
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_POSISHOSPITALITYOPERATIONS] PRIMARY KEY CLUSTERED 
	(
		[OPERATIONID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[POSISHOSPITALITYOPERATIONS] ADD  CONSTRAINT [DF_POSISHOSPITALITYOPERATIONS_ALLOWPARAMETER]  DEFAULT ((0)) FOR [ALLOWPARAMETER]	
	ALTER TABLE [dbo].[POSISHOSPITALITYOPERATIONS] ADD  CONSTRAINT [DF_POSISHOSPITALITYOPERATIONS_DATAAREAID]  DEFAULT (N'LSR') FOR [DATAAREAID]

END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[POSPARAMETERSETUP]') AND TYPE IN ('U'))
BEGIN

	CREATE TABLE [dbo].[POSPARAMETERSETUP](
		[OPERATIONID] [int] NOT NULL,
		[PARAMETERCODE] [nvarchar](20) NOT NULL,
		[DESCRIPTION] [nvarchar](80) NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_POSPARAMETERSETUP] PRIMARY KEY CLUSTERED 
	(
		[OPERATIONID] ASC,
		[PARAMETERCODE] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]	

	ALTER TABLE [dbo].[POSPARAMETERSETUP] ADD  CONSTRAINT [DF_POSPARAMETERSETUP_DATAAREAID]  DEFAULT (N'LSR') FOR [DATAAREAID]
	
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[POSISHOSPITALITYTRANSTABLE]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[POSISHOSPITALITYTRANSTABLE](
		[TRANSACTIONID] [nvarchar](10) NOT NULL,
		[STOREID] [nvarchar](10) NOT NULL,
		[TERMINALID] [nvarchar](10) NOT NULL,
		[TABLEID] [nvarchar](10) NOT NULL,
		[GUEST] [int] NOT NULL,
		[HOSPITALITYTYPE] [nvarchar](20) NOT NULL,
		[TRANSACTIONXML] [xml] NULL,
		[CREATEDBY] [int] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_POSISHOSPITALITYTRANSTABLE_1] PRIMARY KEY CLUSTERED 
	(
		[STOREID] ASC,
		[TERMINALID] ASC,
		[TRANSACTIONID] ASC,
		[TABLEID] ASC,
		[GUEST] ASC,
		[HOSPITALITYTYPE] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

-- Add new POS operation
IF NOT EXISTS (SELECT * FROM [POSISOPERATIONS] WHERE [OPERATIONID] = 1300 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [PERMISSIONID], [PERMISSIONID2], [CHECKUSERACCESS],[USEROPERATION],[DATAAREAID]) VALUES (1300,'Split Bill',NULL,NULL,1,1,'LSR')
GO

-- Add Hospitality POS operations
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 0 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER,DATAAREAID) VALUES('0','None','0','0','0','LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 100 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [DATAAREAID]) VALUES (100,'Line Up', 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 101 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [DATAAREAID]) VALUES (101,'Line Down', 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 102 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [DATAAREAID]) VALUES (102,'Page Up', 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 103 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [DATAAREAID]) VALUES (103,'Page Down', 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 104 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [DATAAREAID]) VALUES (104,'First', 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 105 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [DATAAREAID]) VALUES (105,'Last', 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 106 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [DATAAREAID]) VALUES (106,'Mark All', 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 107 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [DATAAREAID]) VALUES (107,'Mark Split', 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 108 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [DATAAREAID]) VALUES (108,'Unmark All', 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 109 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME],  [ALLOWPARAMETER], [DATAAREAID]) VALUES (109,'Mark Guest', 1, 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 200 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [ALLOWPARAMETER], [DATAAREAID]) VALUES (200,'Split', 1, 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 201 and [DATAAREAID] = 'LSR')
INSERT INTO [POSISHOSPITALITYOPERATIONS] ([OPERATIONID], [OPERATIONNAME], [ALLOWPARAMETER], [DATAAREAID]) VALUES (201,'Move item', 1, 'LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 300 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER,DATAAREAID) VALUES('300','Pay Guest','0','0','0','LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 301 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER,DATAAREAID) VALUES('301','Print Split','0','0','1','LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 400 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER,DATAAREAID) VALUES('400','OK','0','0','0','LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 401 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER,DATAAREAID) VALUES('401','Cancel','0','0','0','LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 500 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER,DATAAREAID) VALUES('500','Guests','0','0','0','LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 501 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER,DATAAREAID) VALUES('501','Next Guest','0','0','1','LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 600 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER, DATAAREAID) VALUES('600','Submenu','0','0','1','LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 700 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER,DATAAREAID) VALUES('700','Transfer Table','0','0','1','LSR')
IF NOT EXISTS (SELECT * FROM [POSISHOSPITALITYOPERATIONS] WHERE [OPERATIONID] = 701 and [DATAAREAID] = 'LSR')
INSERT POSISHOSPITALITYOPERATIONS(OPERATIONID,OPERATIONNAME,PERMISSIONID,CHECKUSERACCESS,ALLOWPARAMETER,DATAAREAID) VALUES('701','Transfer Line','0','0','1','LSR')
GO


-- Insert new textid necessary for the functionality
--Split Bill operation:
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4600)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4600','The POS has not been configured for hospitality functionality.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'The POS has not been configured for hospitality functionality.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4600
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4600)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4600','The POS has not been configured for hospitality functionality.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'The POS has not been configured for hospitality functionality.', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4600
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4600)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4600','Kassinn hefur ekki verið stilltur til að not veitingastaða virkni.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Kassinn hefur ekki verið stilltur til að not veitingastaða virkni.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4600
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4601)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4601','There are no items to split',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'There are no items to split', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4601
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4601)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4601','There are not items to split',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'There are not items to split', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4601
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4601)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4601','Það eru engar vörur til að skipta upp',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Það eru engar vörur til að skipta upp', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4601
GO

-- Hospitality service:
-- LanguageID's new for versions ('7.0.0.0')
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66000)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66000','Operation has not been implemented',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Operation has not been implemented', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66000
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66000)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66000','Operation has not been implemented',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Operation has not been implemented', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66000
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66000)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66000','Aðgerðin hefur ekki verið útfærð',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Aðgerðin hefur ekki verið útfærð', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66000
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66001)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66001','Operation cannot apply to guest grid',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Operation cannot apply to guest grid', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66001
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66001)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66001','Operation cannot apply to guest grid',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Operation cannot apply to guest grid', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66001
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66001)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66001','Ekki er hægt að framkvæma þessa aðgerð á þessum lista',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ekki er hægt að framkvæma þessa aðgerð á þessum lista', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66001
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66002)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66002','No items selected',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'No items selected', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66002
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66002)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66002','No items selected',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'No items selected', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66002
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66002)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66002','Engar línur valdar',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Engar línur valdar', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66002
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66003)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66003','Are you sure you want to split evenly into %1 parts?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to split evenly into %1 parts?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66003
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66003)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66003','Are you sure you want to split evenly into %1 parts?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to split evenly into %1 parts?', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66003
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66003)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66003','Ertu viss um að þú viljir skipta línunum jafnt upp í %1 hluta?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ertu viss um að þú viljir skipta línunum jafnt upp í %1 hluta?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66003
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66004)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66004','Are you sure you want to unsplit all lines and move them to guest 1?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to unsplit all lines and move them to guest 1?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66004
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66004)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66004','Are you sure you want to unsplit all lines and move them to guest 1?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to unsplit all lines and move them to guest 1?', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66004
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66004)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66004','Ertu viss um að þú viljir hætta við að skipta upp línunum?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ertu viss um að þú viljir hætta við að skipta upp línunum?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66004
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66005)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66005','Parameter not implemented',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Parameter not implemented', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66005
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66006)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66006','Split operation is not valid',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Split operation is not valid', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66006
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66006)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66006','Split operation is not valid',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Split operation is not valid', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66006
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66006)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66006','Ekki er hægt að skipta upp línunum?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ekki er hægt að skipta upp línunum?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66006
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66007)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66007','Maximum split is %1. Split cannot be performed',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Maximum split is %1. Split cannot be performed', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66007
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66007)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66007','Maximum split is %1. Split cannot be performed',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Maximum split is %1. Split cannot be performed', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66007
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66007)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66007','Hæsta mögulega skipting er %1. Ekki er hægt að skipta völdum línum',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Hæsta mögulega skipting er %1. Ekki er hægt að skipta völdum línum', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66007
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66008)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66008','Split by?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Split by?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66008
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66008)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66008','Split by?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Split by?', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66008
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66008)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66008','Skipta í hversu marga hluta?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Skipta í hversu marga hluta?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66008
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66009)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66009','Split by amount?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Split by amount?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66009
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66009)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66009','Split by amount?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Split by amount?', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66009
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66009)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66009','Skipta eftir upphæð?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Skipta eftir upphæð?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66009
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66010)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66010','Amount selected is larger then total amount of items. Items cannot be split',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Amount selected is larger then total amount of items. Items cannot be split', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66010
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66010)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66010','Amount selected is larger then total amount of items. Items cannot be split',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Amount selected is larger then total amount of items. Items cannot be split', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66010
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66010)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66010','Upphæðin er hærri en samtals upphæð línanna. Ekki er hægt að skipta völdum línum',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Upphæðin er hærri en samtals upphæð línanna. Ekki er hægt að skipta völdum línum', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66010
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66011)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66011','Do you want to combine these lines with the existing split parts of guest %1',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Do you want to combine these lines with the existing split parts of guest %1', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66011
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66011)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66011','Do you want to combine these lines with the existing split parts of guest %1',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Do you want to combine these lines with the existing split parts of guest %1', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66011
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66011)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66011','Viltu sameina þessar línur við línurnar hjá gesti nr. %1',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Viltu sameina þessar línur við línurnar hjá gesti nr. %1', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66011
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66012)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66012','Do you want to combine %1 with the existing split part of guest %2',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Do you want to combine %1 with the existing split part of guest %2', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66012
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66012)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66012','Do you want to combine %1 with the existing split part of guest %2',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Do you want to combine %1 with the existing split part of guest %2', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66012
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66012)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66012','Viltu sameina %1 við línurnar hjá gesti nr. %2',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Viltu sameina %1 við línurnar hjá gesti nr. %2', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66012
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66013)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66013','Table: %1',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Table: %1', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66013
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66013)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66013','Table: %1',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Table: %1', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66013
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66013)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66013','Borð: %1',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Borð: %1', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66013
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66014)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66014','Total Amount for Table: %1',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Total Amount for Table: %1', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66014
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66014)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66014','Total Amount for Table: %1',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Total Amount for Table: %1', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66014
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66014)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66014','Samtals upphærð fyrir borð: %1',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Samtals upphærð fyrir borð: %1', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66014
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66015)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66015','TRANSFER: From Table %1 - Amt. %2',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'TRANSFER: From Table %1 - Amt. %2', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66015
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66015)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66015','TRANSFER: From Table %1 - Amt. %2',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'TRANSFER: From Table %1 - Amt. %2', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66015
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66015)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66015','FÆRSLA: Frá borði %1 - Upph. %2',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'FÆRSLA: Frá borði %1 - Upph. %2', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66015
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 66016)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '66016','To Table %1 - Amt. %2',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'To Table %1 - Amt. %2', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 66016
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 66016)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '66016','To Table %1 - Amt. %2',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'To Table %1 - Amt. %2', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 66016
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 66016)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '66016','Til borðs %1 - Upph. %2',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Til borðs %1 - Upph. %2', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 66016
GO

