
/*

	Incident No.	: N/A
	Responsible		: Hörður Kristjánsson
	Sprint			: DotNetPM\LS POS 2010.1\Dot Net Stream\Sprint 03\Dot Net Team
	Date created	: 17.11.2010
	
	Description		: Add missing fields to the HOSPITALITYTYPE table and drop fields that are no longer needed

	Logic scripts   : No stored procedures added or changed
	
	Tables affected:	HOSPITALITYTYPE		- Renamed: VisualProfileID to LayoutID
						HOSPITALITYTYPE		- Added: DiningTableLayoutID NVarChar(20)
						HOSPITALITYTYPE		- Added: AutomaticJoiningCheck TinyInt
						HOSPITALITYTYPE		- Dropped: DineInTableRows 
						HOSPITALITYTYPE		- Dropped: DineInTableColumns 
						HOSPITALITYTYPE		- Dropped: SplitMainFuncPosMenuID 
						HOSPITALITYTYPE		- Dropped: SplitGrid1BottPosMenuID
						HOSPITALITYTYPE		- Dropped: SplitGrid1RightPosMenuID
						HOSPITALITYTYPE		- Dropped: SplitGrid2RightPosMenuID
						HOSPITALITYTYPE		- Dropped: SplitCaptionPosMenuID
						HOSPITALITYTYPE		- Dropped: SplitInfoPosMenuID
						HOSPITALITYTYPE		- Dropped: StartingTableNo
					 					
						
*/

Use LSPOSNET

GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='VISUALPROFILEID')
	BEGIN
	EXEC sp_rename 'DBO.HOSPITALITYTYPE.VISUALPROFILEID' , 'LAYOUTID', 'COLUMN'
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='DININGTABLELAYOUTID')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] add [DININGTABLELAYOUTID] nvarchar(20) NULL
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='AUTOMATICJOININGCHECK')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] add [AUTOMATICJOININGCHECK] tinyint NULL
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='DINEINTABLEROWS')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] drop column [DINEINTABLEROWS]
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='DINEINTABLECOLUMNS')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] drop column [DINEINTABLECOLUMNS]
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='STARTINGTABLENO')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] drop column [STARTINGTABLENO]
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='SPLITMAINFUNCPOSMENUID')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] drop column [SPLITMAINFUNCPOSMENUID]
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='SPLITGRID1BOTTPOSMENUID')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] drop column [SPLITGRID1BOTTPOSMENUID]
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='SPLITGRID1RIGHTPOSMENUID')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] drop column [SPLITGRID1RIGHTPOSMENUID]
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='SPLITGRID2RIGHTPOSMENUID')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] drop column [SPLITGRID2RIGHTPOSMENUID]
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='SPLITCAPTIONPOSMENUID')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] drop column [SPLITCAPTIONPOSMENUID]
	END
END
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[HOSPITALITYTYPE]') AND NAME='SPLITINFOPOSMENUID')
	BEGIN
	    Alter table [DBO].[HOSPITALITYTYPE] drop column [SPLITINFOPOSMENUID]
	END
END
GO