
/*

	Incident No.	: 6767 / 6742
	Responsible		: Guðbjörn Einarsson \ Björn Eiríksson
	Sprint			: DotNetPM\LS POS 2010.1\Dot Net Stream\Sprint 03\Dot Net Team
	Date created	: 18.11.2010
	
	Description		: Changing the length of the primary key of table NUMBERSEQUENCETABLE from 10 to 20

	Logic scripts   : No stored procedures added or changed
	
	Tables affected:	NUMBERSEQUENCETABLE	- Column edited, Added VendorItems
					 					
						
*/

Use LSPOSNET

GO

IF EXISTS(SELECT 'x' FROM information_schema.columns WHERE TABLE_NAME = 'NUMBERSEQUENCETABLE' AND COLUMN_NAME = 'NUMBERSEQUENCE' AND CHARACTER_MAXIMUM_LENGTH = 10)
Begin
	ALTER TABLE NUMBERSEQUENCETABLE ALTER COLUMN NUMBERSEQUENCE nvarchar(20) NOT NULL
END

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[VENDORITEMS]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE dbo.VENDORITEMS
		(
		[INTERNALID] nvarchar(20) NOT NULL,
		[VENDORITEMID] nvarchar(30) NOT NULL,
		[RETAILITEMID] nvarchar(20) NOT NULL,
		[VARIANTID] nvarchar(20) NOT NULL,
		[UNITID] nvarchar(20) NOT NULL,
		[VENDORID] nvarchar(20) NOT NULL,
		DATAAREAID nvarchar(4) NOT NULL
		)  ON [PRIMARY]

	ALTER TABLE [dbo].VENDORITEMS ADD  CONSTRAINT [DF__VENDORITEMS__DATAAREAID]  DEFAULT ('LSR') FOR [DATAAREAID]


	ALTER TABLE dbo.VENDORITEMS ADD CONSTRAINT PK_VENDORITEMS
	PRIMARY KEY CLUSTERED ([INTERNALID],DATAAREAID) ON [PRIMARY]

	CREATE INDEX IX_VENDORITEMS_VENDORITEMID
	ON dbo.VENDORITEMS (VENDORITEMID)

	CREATE INDEX IX_VENDORITEMS_RETAILITEMID
	ON dbo.VENDORITEMS (RETAILITEMID)

	CREATE INDEX IX_VENDORITEMS_VENDORID
	ON dbo.VENDORITEMS (VENDORID)

	CREATE INDEX IX_VENDORITEMS_UNITID
	ON dbo.VENDORITEMS (UNITID)
END

GO

if not Exists(SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[INVENTDIMCOMBINATION]') AND name = N'IX_INVENTDIMCOMBINATION_VENDORITEMID')
begin
	CREATE INDEX IX_INVENTDIMCOMBINATION_VENDORITEMID
	ON dbo.INVENTDIMCOMBINATION (RBOVARIANTID)
end

GO



