
/*

	Incident No.	: 7224
	Responsible		: Hörður Kristjánsson
	Sprint			: DotNetPM\LS POS 2010.1\Dot Net Stream\Sprint 03\SC Team
	Date created	: 09.12.2010

	Description		: Adding dispense printing tables

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	:	RestaurantStation		- table created
						StationSelection		- table created
						StationPrintingRoutes	- table created
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[RESTAURANTSTATION]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[RESTAURANTSTATION](
		[ID] [nvarchar](20) NOT NULL,
		[STATIONNAME] [nvarchar](30) NULL,
		[WINDOWSPRINTER] [nvarchar](50) NULL,
		[OUTPUTLINES] [int] NULL,
		[CHECKPRINTING] [int] NULL,
		[POSEXTERNALPRINTERID] [nvarchar](20) NULL,
		[PRINTING] [int] NULL,
		[STATIONFILTER] [nvarchar](70) NULL,
		[STATIONCHECKMINUTES] [int] NULL,
		[COMPRESSBOMRECEIPT] [int] NULL,
		[EXCLUDEFROMCOMPRESSION] [nvarchar](100) NULL,
		[STATIONTYPE] [int] NULL,
		[PRINTINGPRIORITY] [int] NULL,
		[ENDTURNSREDAFTERMIN] [int] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_RESTAURANTSTATION] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[STATIONSELECTION]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[STATIONSELECTION](
		[TYPE] [int] NOT NULL,
		[CODE] [nvarchar](20) NOT NULL,
		[STATIONID] [nvarchar](20) NOT NULL,
		[SALESTYPE] [nvarchar](20) NOT NULL,
		[RESTAURANTID] [nvarchar](20) NOT NULL,
		[ROUTEID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](20) NOT NULL,
	 CONSTRAINT [PK_STATIONSELECTION] PRIMARY KEY CLUSTERED 
	(
		[TYPE] ASC,
		[CODE] ASC,
		[STATIONID] ASC,
		[SALESTYPE] ASC,
		[RESTAURANTID] ASC,
		[ROUTEID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[STATIONPRINTINGROUTES]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[STATIONPRINTINGROUTES](
		[ID] [nvarchar](20) NOT NULL,
		[ROUTEDESCRIPTION] [nvarchar](30) NULL,
		[RESTAURANTID] [nvarchar](20) NOT NULL,
		[PASSWORD] [nvarchar](20) NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_STATIONPRINTINGROUTES] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[RESTAURANTID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
