

/*

	Incident No.	: [TFS incident no]
	Responsible		: HrÃ³lfur Gestsson
	Sprint			: [N/A]
	Date created	: [09.12.2010]

	Description		: Data needed for Tender declaration in LS POS

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	:	SCTENDERDECLARATIONS - Created
				SCTENDERDECLARATIONLINES - Created
						
*/


USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[SCTENDERDECLARATIONS]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[SCTENDERDECLARATIONS](
		[COUNTEDDATETIME] [datetime] NOT NULL,
		[STOREID] [nvarchar](20) NULL,
		[TERMINALID] [nvarchar](20) NULL,
		[STATEMENTID] [nvarchar](20) NULL,
		[STAFFID] [uniqueidentifier] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_SCTENDERDECLARATIONS] PRIMARY KEY CLUSTERED 
	(
		[COUNTEDDATETIME] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[SCTENDERDECLARATIONLINES]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[SCTENDERDECLARATIONLINES](
		[COUNTEDDATETIME] [datetime] NOT NULL,
		[PAYMENTID] [nvarchar](60) NOT NULL,
		[CURRENCYCODE] [nvarchar](20) NOT NULL,
		[DENOMINATORAMOUNT] [decimal](24, 6) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[ISLOCALCURRENCY] [int] NULL,
		[QUANTITY] [int] NULL,
		[CASHTYPE] [int] NULL,
	 CONSTRAINT [PK_SCTENDERDECLARATIONSLINES] PRIMARY KEY CLUSTERED 
	(
		[COUNTEDDATETIME] ASC,
		[PAYMENTID] ASC,
		[CURRENCYCODE] ASC,
		[DENOMINATORAMOUNT] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

GO

