
/*

	Incident No.	: 6977
	Responsible		: Hörður Kristjánsson
	Sprint			: DotNetPM\LS POS 2010.1\Dot Net Stream\Sprint 03\SC Team
	Date created	: 30.11.2010

	Description		: Adding additional tables for creating and using dining table layouts

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: 	RestaurantDiningTable		- created
						RestaurantDiningTableDesign	- created
						DiningTableLayoutScreen 	- created
						
*/

use LSPOSNET

go

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[RESTAURANTDININGTABLE]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[RESTAURANTDININGTABLE](
		[RESTAURANTID] [nvarchar](20) NOT NULL,
		[SALESTYPE] [nvarchar](20) NOT NULL,
		[DINEINTABLENO] [int] NOT NULL,
		[DESCRIPTION] [nvarchar](30) NULL,
		[TYPE] [int] NULL,
		[NONSMOKING] [tinyint] NULL,
		[NOOFGUESTS] [int] NULL,
		[JOINEDTABLE] [int] NULL,
		[X1POSITION] [int] NULL,
		[X2POSITION] [int] NULL,
		[Y1POSITION] [int] NULL,
		[Y2POSITION] [int] NULL,
		[LINKEDTODINEINTABLE] [int] NULL,
		[DININGTABLESJOINED] [tinyint] NULL,
		[SEQUENCE] [int] NOT NULL,
		[AVAILABILITY] [int] NULL,
		[DININGTABLELAYOUTID] [nvarchar](20) NOT NULL,
		[LAYOUTSCREENNO] [int] NULL,
		[DESCRIPTIONONBUTTON] [nvarchar](30) NULL,
		[SHAPE] [int] NULL,
		[X1POSITIONDESIGN] [int] NULL,
		[X2POSITIONDESIGN] [int] NULL,
		[Y1POSITIONDESIGN] [int] NULL,
		[Y2POSITIONDESIGN] [int] NULL,
		[LAYOUTSCREENNODESIGN] [int] NULL,
		[JOINEDTABLEDESIGN] [int] NULL,
		[DININGTABLESJOINEDDESIGN] [tinyint] NULL,
		[DELETEINOTHERLAYOUTS] [tinyint] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_RESTAURANTDININGTABLE] PRIMARY KEY CLUSTERED 
	(
		[RESTAURANTID] ASC,
		[SALESTYPE] ASC,
		[DINEINTABLENO] ASC,
		[SEQUENCE] ASC,
		[DININGTABLELAYOUTID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[RESTAURANTDININGTABLEDESIGN]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[RESTAURANTDININGTABLEDESIGN](
		[RESTAURANTID] [nvarchar](20) NOT NULL,
		[SALESTYPE] [nvarchar](20) NOT NULL,
		[DININGTABLENO] [int] NOT NULL,
		[SEQUENCE] [int] NOT NULL,
		[DININGTABLELAYOUTID] [nvarchar](20) NOT NULL,
		[X1POSITIONDESIGN] [int] NULL,
		[X2POSITIONDESIGN] [int] NULL,
		[Y1POSITIONDESIGN] [int] NULL,
		[Y2POSITIONDESIGN] [int] NULL,
		[LAYOUTSCREENNODESIGN] [int] NULL,
		[JOINEDTABLEDESIGN] [int] NULL,
		[DININGTABLESJOINEDDESIGN] [tinyint] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_RESTAURANTDININGTABLEDESIGN] PRIMARY KEY CLUSTERED 
	(
		[RESTAURANTID] ASC,
		[SALESTYPE] ASC,
		[DININGTABLENO] ASC,
		[SEQUENCE] ASC,
		[DININGTABLELAYOUTID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[DININGTABLELAYOUTSCREEN]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[DININGTABLELAYOUTSCREEN](
		[RESTAURANTID] [nvarchar](20) NOT NULL,
		[SEQUENCE] [int] NOT NULL,
		[SALESTYPE] [nvarchar](20) NOT NULL,
		[LAYOUTID] [nvarchar](20) NOT NULL,
		[SCREENNO] [int] NOT NULL,
		[SCREENDESCRIPTION] [nvarchar](30) NULL,
		[BACKGROUNDIMAGE] [image] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_DININGTABLELAYOUTSCREEN] PRIMARY KEY CLUSTERED 
	(
		[RESTAURANTID] ASC,
		[SEQUENCE] ASC,
		[SALESTYPE] ASC,
		[LAYOUTID] ASC,
		[SCREENNO] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO

