
/*

	Incident No.	: N/A
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: N/A
	Date created	: 10.12.2010

	Description		: Text ids for operation Change Item Comments
					  Operation Change Item Comments added

	Logic scripts   : No stored procedures added or changed
	
-- 	Tables affected	: PosisLanguageText	- data added
					  PosisOperations - data added
						
*/


IF NOT EXISTS (SELECT * FROM [POSISOPERATIONS] WHERE [OPERATIONID] = 131 and [DATAAREAID] = 'LSR')
INSERT POSISOPERATIONS(OPERATIONID,OPERATIONNAME,CHECKUSERACCESS,USEROPERATION,DATAAREAID) VALUES('131','Change Item Comments','1','1','LSR')
GO

-- LanguageID's for Change Item Comments operation
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4620)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4620','No items selected',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'No items selected', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4620
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4620)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4620','No items selected',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'No items selected', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4620
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4620)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4620','Engin vara hefur verið valin',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Engin vara hefur verið valin', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4620
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4621)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4621','There are no comments on the item',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'There are no comments on the item', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4621
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4621)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4621','There are no comments on the item',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'There are no comments on the item', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4621
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4621)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4621','Það eru engar athugasemdir á vörunni',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Það eru engar athugasemdir á vörunni', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4621
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4622)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4622','Change comments',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Change comments', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4622
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4622)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4622','Change comments',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Change comments', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4622
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4622)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4622','Breyta athugasemdum',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Breyta athugasemdum', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4622
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4623)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4623','Page Up',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Page Up', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4623
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4623)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4623','Page Up',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Page Up', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4623
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4623)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4623','Bl Up',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Bl Up', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4623
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4624)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4624','Page Dwn',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Page Dwn', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4624
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4624)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4624','Page Dwn',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Page Dwn', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4624
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4624)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4624','Bl Nidur',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Bl Nidur', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4624
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4625)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4625','Up',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Up', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4625
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4625)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4625','Up',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Up', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4625
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4625)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4625','Upp',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Upp', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4625
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4626)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4626','Down',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Down', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4626
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4626)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4626','Down',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Down', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4626
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4626)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4626','Niður',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Niður', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4626
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4627)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4627','Delete',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Delete', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4627
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4627)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4627','Delete',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Delete', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4627
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4627)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4627','Eyða út',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Eyða út', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4627
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4628)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4628','Change',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Change', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4628
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4628)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4628','Change',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Change', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4628
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4628)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4628','Breyta',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Breyta', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4628
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4629)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4629','Close',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Close', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4629
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4629)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4629','Close',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Close', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4629
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4629)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4629','Loka',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Loka', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4629
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4630)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4630','Cancel',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Cancel', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4630
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4630)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4630','Cancel',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Cancel', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4630
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4630)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4630','Hætta við',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Hætta við', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4630
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4631)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4631','Are you sure you want to delete the comment?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to delete the comment?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4631
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4631)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4631','Are you sure you want to delete the comment?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to delete the comment?', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4631
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4631)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4631','Ertu viss um að þú viljir eyða út athugasemdinni?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ertu viss um að þú viljir eyða út athugasemdinni?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4631
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4632)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4632','Add',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Add', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4632
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4632)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4632','Add',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Add', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4632
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4632)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4632','Ný aths',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ný aths', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4632
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4633)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4633','Change comment line:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Change comment line:', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4633
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4633)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4633','Change comment line:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Change comment line:', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4633
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4633)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4633','Breyta athugasemd:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Breyta athugasemd:', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4633
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4634)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4634','Add new comment:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Add new comment:', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4634
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 4634)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '4634','Add new comment:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Add new comment:', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 4634
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4634)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4634','Ný athugasemd:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ný athugasemd:', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4634
GO



