/*

	Incident No.	: N/A
	Responsible		: HrÃ³lfur Gestsson		
	Sprint			: N/A
	Date created	: 20.12.2010

	Description		: INVENTTRANS - column added

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: INVENTTRANS, INVENTJOURNALTRANS - columns added

						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('INVENTJOURNALTRANS') AND NAME='UNITID')
ALTER TABLE dbo.INVENTJOURNALTRANS ADD UNITID nvarchar(20) NOT NULL CONSTRAINT DF_INVENTJOURNALTRANS_UNITID DEFAULT N''

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('INVENTTRANS') AND NAME='ADJUSTMENTININVENTORYUNIT')
ALTER TABLE dbo.INVENTTRANS ADD ADJUSTMENTININVENTORYUNIT numeric(28,12) NOT NULL CONSTRAINT DF_INVENTJOURNALTRANS_ADJINVUNIT DEFAULT 0

