
/*

	Incident No.	: [TFS incident no]
	Responsible		: Hrolfur Gestsson
	Sprint			: [Sprint number/ID]
	Date created	: 13.12.2010

	Description		: [Short description]

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: INVENTJOURNALTRANS, INVENTTRANS
						
*/
USE LSPOSNET

GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[INVENTJOURNALTRANS]') AND TYPE IN ('U'))
BEGIN
	if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
	WHERE TABLE_NAME = 'INVENTJOURNALTRANS' AND COLUMN_NAME = 'JOURNALID') = 10)
	begin
		drop table INVENTJOURNALTRANS
	end
END


IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[INVENTJOURNALTRANS]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[INVENTJOURNALTRANS](
	[JOURNALID] [nvarchar](20) NOT NULL,
	[LINENUM] [nvarchar](20) NOT NULL,
	[ORIGIN] [nvarchar](20) NOT NULL,
	[TRANSDATE] [datetime] NULL,
	[VOUCHER] [nvarchar](20) NULL,
	[JOURNALTYPE] [int] NULL,
	[ITEMID] [nvarchar](20) NULL,
	[ADJUSTMENT] [numeric](28, 12) NULL,
	[COSTPRICE] [numeric](28, 12) NULL,
	[PRICEUNIT] [numeric](28, 12) NULL,
	[COSTMARKUP] [numeric](28, 12) NULL,
	[COSTAMOUNT] [numeric](28, 12) NULL,
	[SALESAMOUNT] [numeric](28, 12) NULL,
	[INVENTONHAND] [numeric](28, 12) NULL,
	[COUNTED] [numeric](28, 12) NULL,
	[DIMENSION] [nvarchar](10) NULL,
	[DIMENSION2_] [nvarchar](10) NULL,
	[DIMENSION3_] [nvarchar](10) NULL,
	[REASONREFRECID] [nvarchar](20) NULL,
	[VARIANTID] [nvarchar](20) NULL,
	[POSTED] [int] NULL,
	[POSTEDDATETIME] [datetime] NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL
 CONSTRAINT [PK_INVENTJOURNALTRANS] PRIMARY KEY CLUSTERED 
(
	[JOURNALID] ASC,
	[LINENUM] ASC,
	[ORIGIN] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
end

GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[INVENTTRANS]') AND TYPE IN ('U'))
BEGIN
	if exists (SELECT COLUMN_NAME FROM information_schema.columns
		WHERE TABLE_NAME = 'INVENTTRANS' and COLUMN_NAME = 'QUANTITY')
	begin
		drop table INVENTTRANS
	end
END

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[INVENTTRANS]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[INVENTTRANS](
		[POSTINGDATE] [datetime] NOT NULL,
		[ITEMID] [nvarchar](20) NOT NULL,
		[VARIANTID] [nvarchar](20) NOT NULL,
		[STOREID] [nvarchar](20) NOT NULL,
		[ADJUSTMENT] [numeric](28, 12) NOT NULL,
		[TYPE] [int] NOT NULL,
		[OFFERID] [nvarchar](20) NOT NULL,
		[COSTPRICEPERITEM] [numeric](28, 12) NULL,
		[SALESPRICEWITHOUTTAXPERITEM] [numeric](28, 12) NULL,
		[SALESPRICEWITHTAXPERITEM] [numeric](28, 12) NULL,
		[REASONCODE] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[DISCOUNTAMOUNTPERITEM] [numeric](28, 12) NULL,
		[OFFERDISCOUNTAMOUNTPERITEM] [numeric](28, 12) NULL,
		[GUID] [uniqueidentifier] NOT NULL,
		[UNITID] [nvarchar](20) NOT NULL,
	PRIMARY KEY CLUSTERED 
	(
		[GUID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END