
/*

	Incident No.	: N/A
	Responsible		: Hörður Kristjánsson
	Sprint			: N/A
	Date created	: 22.12.2010

	Description		: Adding fields to posishospitalityoperations and adding a lot of fields to posmenuline to configure the basics of the menubutton control

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: PosisHospitalityOperations - fields added
					  PosMenuLine			     - fields added and renamed					  
						
*/

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSISHOSPITALITYOPERATIONS') AND NAME='NAVOPERATION')
BEGIN
	ALTER TABLE [dbo].[POSISHOSPITALITYOPERATIONS] ADD NAVOPERATION NVARCHAR(50) NULL
END
GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='NAVOPRATION')
BEGIN 
	EXEC sp_rename 'DBO.POSMENULINE.NAVOPRATION' , 'NAVOPERATION', 'COLUMN'
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='HIDDEN')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD HIDDEN TINYINT NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='SHADEWHENDISABLED')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD SHADEWHENDISABLED TINYINT NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='BACKGROUNDHIDDEN')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD BACKGROUNDHIDDEN TINYINT NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='TRANSPARENT')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD TRANSPARENT TINYINT NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPH')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPH INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPH2')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPH2 INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPH3')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPH3 INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPH4')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPH4 INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT NVARCHAR(80) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT2')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT2 NVARCHAR(80) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT3')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT3 NVARCHAR(80) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT4')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT4 NVARCHAR(80) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXTFONT')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXTFONT NVARCHAR(32) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT2FONT')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT2FONT NVARCHAR(32) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT3FONT')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT3FONT NVARCHAR(32) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT4FONT')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT4FONT NVARCHAR(32) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXTFONTSIZE')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXTFONTSIZE int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT2FONTSIZE')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT2FONTSIZE int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT3FONTSIZE')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT3FONTSIZE int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT4FONTSIZE')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT4FONTSIZE int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXTFORECOLOR')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXTFORECOLOR int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT2FORECOLOR')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT2FORECOLOR int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT3FORECOLOR')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT3FORECOLOR int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHTEXT4FORECOLOR')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHTEXT4FORECOLOR int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPHOFFSET')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPHOFFSET int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPH2OFFSET')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPH2OFFSET int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPH3OFFSET')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPH3OFFSET int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GLYPH4OFFSET')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GLYPH4OFFSET int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='BACKCOLOR2')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD BACKCOLOR2 int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='GRADIENTMODE')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD GRADIENTMODE int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENULINE') AND NAME='SHAPE')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] ADD SHAPE int NULL
END
GO