
/*

	Incident No.	: N/A
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: N/A
	Date created	: 21.12.2010

	Description		: Add parameterType and update data to PosParameterType

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: PosisHospitalityOperations - new columns, update data					  
						
*/


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSISHOSPITALITYOPERATIONS') AND NAME='PARAMETERTYPE')
BEGIN
	ALTER TABLE [dbo].[POSISHOSPITALITYOPERATIONS] ADD PARAMETERTYPE INT NULL
END
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSISHOSPITALITYOPERATIONS_PARAMETERTYPE]') AND type = 'D')
BEGIN
	ALTER TABLE [dbo].[POSISHOSPITALITYOPERATIONS] DROP CONSTRAINT [DF_POSISHOSPITALITYOPERATIONS_PARAMETERTYPE]
END

ALTER TABLE [dbo].[POSISHOSPITALITYOPERATIONS] ADD  CONSTRAINT [DF_POSISHOSPITALITYOPERATIONS_PARAMETERTYPE]  DEFAULT ((0)) FOR [PARAMETERTYPE]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSMENULINE_APPLIESTO]') AND type = 'D')
BEGIN
	ALTER TABLE [dbo].[POSMENULINE] DROP CONSTRAINT [DF_POSMENULINE_APPLIESTO]
END

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[POSMENULINE]') AND TYPE IN ('U'))
BEGIN
	IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('[DBO].[POSMENULINE]') AND NAME='APPLIESTO')
	BEGIN		
	    Alter table [DBO].[POSMENULINE] drop column [APPLIESTO]
	END
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENUHEADER') AND NAME='APPLIESTO')
BEGIN
	ALTER TABLE [dbo].[POSMENUHEADER] ADD APPLIESTO INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENUHEADER') AND NAME='USENAVOPERATION')
BEGIN
	ALTER TABLE [dbo].[POSMENUHEADER] ADD USENAVOPERATION TINYINT NULL
END
GO



-- Give all previously inserted data the default value
UPDATE POSISHOSPITALITYOPERATIONS 
SET PARAMETERTYPE = 0
GO

-- Update the only operation that has another value than the default
UPDATE POSISHOSPITALITYOPERATIONS 
SET PARAMETERTYPE = 1
WHERE OPERATIONID = 600
GO

-- Update previously inserted data - operation 109 needs to have AllowParamter = 1
UPDATE POSISHOSPITALITYOPERATIONS
SET ALLOWPARAMETER = 1
WHERE OPERATIONID = 109
GO

-- Update previously inserted data - operation 109 needs to have AllowParamter = 1
UPDATE POSISHOSPITALITYOPERATIONS
SET ALLOWPARAMETER = 1
WHERE OPERATIONID = 600
GO

