/*

	Incident No.	: 
	Responsible		: Björn Eiríksson
	Sprint			: LS Retail .NET v 2010 - Sprint 4
	Date created	:21.12.2010
	
	Description		: Change tables to use 20 letter keys for the new sequence manager.

	Logic scripts   : No stored procedures added or changed
	
	Tables affected:	- Most
						
*/

USE LSPOSNET

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'BARCODESETUP' AND COLUMN_NAME = 'BARCODESETUPID') = 10)
begin
	ALTER TABLE BARCODESETUP ALTER COLUMN BARCODESETUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'COMPANYINFO' AND COLUMN_NAME = 'COUNTRYREGIONID') = 10)
begin
	ALTER TABLE COMPANYINFO ALTER COLUMN COUNTRYREGIONID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'CUSTGROUP' AND COLUMN_NAME = 'CUSTGROUP') = 10)
begin
	ALTER TABLE CUSTGROUP ALTER COLUMN CUSTGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'CUSTTABLE' AND COLUMN_NAME = 'CUSTGROUP') = 10)
begin
	ALTER TABLE CUSTTABLE ALTER COLUMN CUSTGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN PAYMTERMID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN CASHDISC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN DIMENSION [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN DIMENSION2_ [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN DIMENSION3_ [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN VENDACCOUNT [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN COUNTRY [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN INVENTLOCATION [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN DLVTERM [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN DLVMODE [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN CLEARINGPERIOD [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN CREDITRATING [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN STATISTICSGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN PAYMMODE [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN BANKACCOUNT [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN CONTACTPERSONID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN SALESPOOLID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN CUSTITEMGROUPID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN NUMBERSEQUENCEGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN PAYMDAYID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN LINEOFBUSINESSID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN DESTINATIONCODEID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN PAYMSPEC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN TAXGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN LINEDISC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN SALESGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN PRICEGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN MULTILINEDISC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN ENDDISC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN MARKUPGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLE ALTER COLUMN COMMISSIONGROUP [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'DECIMALSETTINGS' AND COLUMN_NAME = 'ID') = 10)
begin
	ALTER TABLE DECIMALSETTINGS ALTER COLUMN ID [nvarchar](20) NOT NULL
end

GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[EMPLTABLE]') AND TYPE IN ('U'))
BEGIN
	drop table EMPLTABLE
END

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'HOSPITALITYSETUP' AND COLUMN_NAME = 'SETUP') = 10)
begin
	ALTER TABLE HOSPITALITYSETUP ALTER COLUMN SETUP [nvarchar](20) NOT NULL
	
	ALTER TABLE HOSPITALITYSETUP ALTER COLUMN TABLEFREECOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUP ALTER COLUMN TABLENOTAVAILCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUP ALTER COLUMN TABLELOCKEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUP ALTER COLUMN ORDERPRINTEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUP ALTER COLUMN ORDERSTARTEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUP ALTER COLUMN ORDERFINISHEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUP ALTER COLUMN ORDERCONFIRMEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUP ALTER COLUMN POSTERMINALPRINTPREORDERS [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTDIM' AND COLUMN_NAME = 'WMSLOCATIONID') = 10)
begin
	ALTER TABLE INVENTDIM ALTER COLUMN WMSLOCATIONID [nvarchar](20) NULL
	ALTER TABLE INVENTDIM ALTER COLUMN INVENTLOCATIONID [nvarchar](20) NULL
	ALTER TABLE INVENTDIM ALTER COLUMN INVENTSTYLEID [nvarchar](20) NULL
	ALTER TABLE INVENTDIM ALTER COLUMN INVENTCOLORID [nvarchar](20) NULL
	ALTER TABLE INVENTDIM ALTER COLUMN INVENTSIZEID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTDIMCOMBINATION' AND COLUMN_NAME = 'RBOVARIANTID') = 10)
begin
	ALTER TABLE INVENTDIMCOMBINATION ALTER COLUMN RBOVARIANTID [nvarchar](20) NULL
	ALTER TABLE INVENTDIMCOMBINATION ALTER COLUMN INVENTSIZEID [nvarchar](20) NOT NULL
	ALTER TABLE INVENTDIMCOMBINATION ALTER COLUMN INVENTCOLORID [nvarchar](20) NOT NULL
	ALTER TABLE INVENTDIMCOMBINATION ALTER COLUMN INVENTSTYLEID [nvarchar](20) NOT NULL
	ALTER TABLE INVENTDIMCOMBINATION ALTER COLUMN CONFIGID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTDIMGROUP' AND COLUMN_NAME = 'DIMGROUPID') = 10)
begin
	ALTER TABLE INVENTDIMGROUP ALTER COLUMN DIMGROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTDIMSETUP' AND COLUMN_NAME = 'DIMGROUPID') = 10)
begin
	ALTER TABLE INVENTDIMSETUP ALTER COLUMN DIMGROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTITEMBARCODE' AND COLUMN_NAME = 'BARCODESETUPID') = 10)
begin
	ALTER TABLE INVENTITEMBARCODE ALTER COLUMN BARCODESETUPID [nvarchar](20) NULL
	ALTER TABLE INVENTITEMBARCODE ALTER COLUMN RBOVARIANTID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTITEMGROUP' AND COLUMN_NAME = 'ITEMGROUPID') = 10)
begin
	ALTER TABLE INVENTITEMGROUP ALTER COLUMN ITEMGROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTSUM' AND COLUMN_NAME = 'VARIANTID') = 10)
begin
	ALTER TABLE INVENTSUM ALTER COLUMN VARIANTID [nvarchar](20) NOT NULL
	ALTER TABLE INVENTSUM ALTER COLUMN STOREID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTTABLE' AND COLUMN_NAME = 'ITEMGROUPID') = 10)
begin
	ALTER TABLE INVENTTABLE ALTER COLUMN ITEMGROUPID [nvarchar](20) NOT NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN REQGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN PRIMARYVENDORID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN DIMENSION [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN DIMENSION2_ [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN DIMENSION3_ [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN BATCHNUMGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN PRODPOOLID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN PROPERTYID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN PRODGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN PROJCATEGORYID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN SERIALNUMGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN DIMGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN MODELGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN ITEMBUYERGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLE ALTER COLUMN PBAINVENTITEMGROUPID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTTABLEMODULE' AND COLUMN_NAME = 'UNITID') = 10)
begin
	ALTER TABLE INVENTTABLEMODULE ALTER COLUMN UNITID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULE ALTER COLUMN INVENTLOCATIONID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULE ALTER COLUMN TAXITEMGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULE ALTER COLUMN LINEDISC [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULE ALTER COLUMN MULTILINEDISC [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULE ALTER COLUMN MARKUPGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULE ALTER COLUMN SUPPITEMGROUPID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'NUMBERSEQUENCETABLE' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE NUMBERSEQUENCETABLE ALTER COLUMN STOREID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSCOLOR' AND COLUMN_NAME = 'COLORCODE') = 10)
begin
	ALTER TABLE POSCOLOR ALTER COLUMN COLORCODE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSDISCVALIDATIONPERIOD' AND COLUMN_NAME = 'ID') = 10)
begin
	ALTER TABLE POSDISCVALIDATIONPERIOD ALTER COLUMN ID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'PROFILEID') = 10)
begin
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN PROFILEID [nvarchar](20) NOT NULL
	
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN AMOUNTDECIMALPLACES [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN PRICEDECIMALPLACES [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN NEGATIVEADJUSTMENT [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN VOIDISPRESSED [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN VOIDTRANSACTION [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN VOIDPAYMENT [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN REFUNDSALE [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN MARKDOWN [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN MARKUP [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN OVERRIDEPRICE [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN STARTOFTRANSACTION [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN DISCOUNTATTOTAL [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN TENDERDECLARATION [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN ENDOFTRANSACTION [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN SERIALNUMBER [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN SALESPERSON [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN ITEMNOTONFILE [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN NEGATIVESALESLINE [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN SENDTRANSACTION [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN VOIDPOSTEDTRANSACTION [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN SUSPENDRETRIEVETRANSACTION [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN STAFFVALIDATION [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN CUSTOMER [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN DATAENTRIES [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN FLOATINGCASHIER [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN CUSTOMER2 [nvarchar](20) NULL
	ALTER TABLE POSFUNCTIONALITYPROFILE ALTER COLUMN INVENTORYLOOKUP [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'PROFILEID') = 10)
begin
	ALTER TABLE POSHARDWAREPROFILE ALTER COLUMN PROFILEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISBUTTONGRID' AND COLUMN_NAME = 'BUTTONGRIDID') = 10)
begin
	ALTER TABLE POSISBUTTONGRID ALTER COLUMN BUTTONGRIDID [nvarchar](20) NOT NULL
	ALTER TABLE POSISBUTTONGRID ALTER COLUMN KEYBOARDUSED [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISBUTTONGRIDBUTTONS' AND COLUMN_NAME = 'BUTTONGRIDID') = 10)
begin
	ALTER TABLE POSISBUTTONGRIDBUTTONS ALTER COLUMN BUTTONGRIDID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISCUSTTRANSACTIONS' AND COLUMN_NAME = 'CUSTOMERID') = 10)
begin
	ALTER TABLE POSISCUSTTRANSACTIONS ALTER COLUMN CUSTOMERID [nvarchar](20) NOT NULL
	ALTER TABLE POSISCUSTTRANSACTIONS ALTER COLUMN STORE [nvarchar](20) NOT NULL
	ALTER TABLE POSISCUSTTRANSACTIONS ALTER COLUMN TERMINAL [nvarchar](20) NOT NULL
	ALTER TABLE POSISCUSTTRANSACTIONS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE POSISCUSTTRANSACTIONS ALTER COLUMN RECEIPTID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISHOSPITALITYDININGTABLES' AND COLUMN_NAME = 'STAFFID') = 10)
begin
	ALTER TABLE POSISHOSPITALITYDININGTABLES ALTER COLUMN STAFFID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISHOSPITALITYTRANSTABLE' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE POSISHOSPITALITYTRANSTABLE ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE POSISHOSPITALITYTRANSTABLE ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE POSISHOSPITALITYTRANSTABLE ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL
	ALTER TABLE POSISHOSPITALITYTRANSTABLE ALTER COLUMN TABLEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISINFO' AND COLUMN_NAME = 'ID') = 10)
begin
	ALTER TABLE POSISINFO ALTER COLUMN ID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISKEYBOARDMAPPINGTABLE' AND COLUMN_NAME = 'KEYBOARDMAPPINGID') = 10)
begin
	ALTER TABLE POSISKEYBOARDMAPPINGTABLE ALTER COLUMN KEYBOARDMAPPINGID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISKEYBOARDMAPPINGTRANS' AND COLUMN_NAME = 'KEYBOARDMAPPINGID') = 10)
begin
	ALTER TABLE POSISKEYBOARDMAPPINGTRANS ALTER COLUMN KEYBOARDMAPPINGID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISLICENSE' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE POSISLICENSE ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE POSISLICENSE ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISLOG' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE POSISLOG ALTER COLUMN STOREID [nvarchar](20) NULL
	ALTER TABLE POSISLOG ALTER COLUMN TERMINALID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISRFIDTABLE' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE POSISRFIDTABLE ALTER COLUMN TRANSACTIONID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISSUSPENDEDTRANSACTIONS' AND COLUMN_NAME = 'SUSPENDEDTRANSACTIONID') = 10)
begin
	ALTER TABLE POSISSUSPENDEDTRANSACTIONS ALTER COLUMN SUSPENDEDTRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE POSISSUSPENDEDTRANSACTIONS ALTER COLUMN STAFF [nvarchar](20) NOT NULL
	ALTER TABLE POSISSUSPENDEDTRANSACTIONS ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE POSISSUSPENDEDTRANSACTIONS ALTER COLUMN STOREID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISTENDERRESTRICTIONS' AND COLUMN_NAME = 'TENDERID') = 10)
begin
	ALTER TABLE POSISTENDERRESTRICTIONS ALTER COLUMN TENDERID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISTILLLAYOUT' AND COLUMN_NAME = 'LAYOUTID') = 10)
begin
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN LAYOUTID [nvarchar](20) NOT NULL
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN BUTTONGRID1 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN BUTTONGRID2 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN BUTTONGRID3 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN BUTTONGRID4 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN BUTTONGRID5 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN RECEIPTID [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN TOTALID [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN CUSTOMERLAYOUTID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISTRANSACTION' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE POSISTRANSACTION ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE POSISTRANSACTION ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISTRANSACTIONTABLE' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE POSISTRANSACTIONTABLE ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE POSISTRANSACTIONTABLE ALTER COLUMN STORE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISUPDATEAPPLICATION' AND COLUMN_NAME = 'UPDATEID') = 10)
begin
	ALTER TABLE POSISUPDATEAPPLICATION ALTER COLUMN UPDATEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISUPDATEFILES' AND COLUMN_NAME = 'UPDATEID') = 10)
begin
	ALTER TABLE POSISUPDATEFILES ALTER COLUMN UPDATEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISUPDATESCRIPT' AND COLUMN_NAME = 'UPDATEID') = 10)
begin
	ALTER TABLE POSISUPDATESCRIPT ALTER COLUMN UPDATEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISUPDATESMASTER' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE POSISUPDATESMASTER ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE POSISUPDATESMASTER ALTER COLUMN POSID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISUPGRADES' AND COLUMN_NAME = 'UPGRADEID') = 10)
begin
	ALTER TABLE POSISUPGRADES ALTER COLUMN UPGRADEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSMMLINEGROUPS' AND COLUMN_NAME = 'LINEGROUP') = 10)
begin
	ALTER TABLE POSMMLINEGROUPS ALTER COLUMN LINEGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSPERIODICDISCOUNT' AND COLUMN_NAME = 'DISCVALIDPERIODID') = 10)
begin
	ALTER TABLE POSPERIODICDISCOUNT ALTER COLUMN DISCVALIDPERIODID [nvarchar](20) NULL
	ALTER TABLE POSPERIODICDISCOUNT ALTER COLUMN PRICEGROUP [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSTRANSACTIONSERVICEPROFILE' AND COLUMN_NAME = 'PROFILEID') = 10)
begin
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN PROFILEID [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN COMPANY [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN SENDTRANSACTION [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN VOIDPOSTEDTRANSACTION [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN SUSPENDRETRIEVETRANSACTION [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN CUSTOMER [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN DATAENTRIES [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN STAFFVALIDATION [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN FLOATINGCASHIER [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ALTER COLUMN INVENTORYLOOKUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSVISUALPROFILE' AND COLUMN_NAME = 'PROFILEID') = 10)
begin
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN PROFILEID [nvarchar](20) NOT NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN STARTMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN SALESMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN PAYMENTMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN TENDEROPERATIONMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN NEGATIVEADJUSTMENTMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN PHYSICALINVENTORYMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN NORMALCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN VOIDEDCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN MULTIBUYCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN MIXANDMATCHCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN TOTALDISCOUNTCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN INCOMEEXPENSECOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN COUPONLINECOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN LINESELECTCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN FREETEXTCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN TABLEMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN TOPLINEMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILE ALTER COLUMN JOURNALMENU [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'PRICEDISCGROUP' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE PRICEDISCGROUP ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'PRICEDISCTABLE' AND COLUMN_NAME = 'UNITID') = 10)
begin
	ALTER TABLE PRICEDISCTABLE ALTER COLUMN UNITID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'PRICEGROUP' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE PRICEGROUP ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOBARCODEMASKSEGMENT' AND COLUMN_NAME = 'MASKID') = 10)
begin
	ALTER TABLE RBOBARCODEMASKSEGMENT ALTER COLUMN MASKID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOBARCODEMASKTABLE' AND COLUMN_NAME = 'MASKID') = 10)
begin
	ALTER TABLE RBOBARCODEMASKTABLE ALTER COLUMN MASKID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOCOLORGROUPTABLE' AND COLUMN_NAME = 'COLORGROUP') = 10)
begin
	ALTER TABLE RBOCOLORGROUPTABLE ALTER COLUMN COLORGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOCOLORGROUPTRANS' AND COLUMN_NAME = 'COLORGROUP') = 10)
begin
	ALTER TABLE RBOCOLORGROUPTRANS ALTER COLUMN COLORGROUP [nvarchar](20) NOT NULL
	ALTER TABLE RBOCOLORGROUPTRANS ALTER COLUMN COLOR [nvarchar](20) NOT NULL
	ALTER TABLE RBOCOLORGROUPTRANS ALTER COLUMN NOINBARCODE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOCOLORS' AND COLUMN_NAME = 'COLOR') = 10)
begin
	ALTER TABLE RBOCOLORS ALTER COLUMN COLOR [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOCUSTTABLE' AND COLUMN_NAME = 'ACCOUNTNUM') = 10)
begin
	ALTER TABLE RBOCUSTTABLE ALTER COLUMN ACCOUNTNUM [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBODISCOUNTOFFERLINE' AND COLUMN_NAME = 'OFFERID') = 10)
begin
	ALTER TABLE RBODISCOUNTOFFERLINE ALTER COLUMN OFFERID [nvarchar](20) NOT NULL
	ALTER TABLE RBODISCOUNTOFFERLINE ALTER COLUMN UNIT [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBODISCOUNTOFFERTABLE' AND COLUMN_NAME = 'OFFERID') = 10)
begin
	ALTER TABLE RBODISCOUNTOFFERTABLE ALTER COLUMN OFFERID [nvarchar](20) NOT NULL
	ALTER TABLE RBODISCOUNTOFFERTABLE ALTER COLUMN DISCOUNTVALIDATIONPERIODID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINCOMEEXPENSEACCOUNTTABLE' AND COLUMN_NAME = 'ACCOUNTNUM') = 10)
begin
	ALTER TABLE RBOINCOMEEXPENSEACCOUNTTABLE ALTER COLUMN ACCOUNTNUM [nvarchar](20) NOT NULL
	ALTER TABLE RBOINCOMEEXPENSEACCOUNTTABLE ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINCOMEEXPENSEACCOUNTTABLE ALTER COLUMN LEDGERACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOINCOMEEXPENSEACCOUNTTABLE ALTER COLUMN TAXCODEID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINFOCODETABLE' AND COLUMN_NAME = 'INFOCODEID') = 10)
begin
	ALTER TABLE RBOINFOCODETABLE ALTER COLUMN INFOCODEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINFOCODETABLE ALTER COLUMN LINKEDINFOCODEID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINFOCODETABLESPECIFIC' AND COLUMN_NAME = 'INFOCODEID') = 10)
begin
	ALTER TABLE RBOINFOCODETABLESPECIFIC ALTER COLUMN INFOCODEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINFOCODETABLESPECIFIC ALTER COLUMN UNITOFMEASURE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINFORMATIONSUBCODETABLE' AND COLUMN_NAME = 'INFOCODEID') = 10)
begin
	ALTER TABLE RBOINFORMATIONSUBCODETABLE ALTER COLUMN INFOCODEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINFORMATIONSUBCODETABLE ALTER COLUMN SUBCODEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINFORMATIONSUBCODETABLE ALTER COLUMN VARIANTCODE [nvarchar](20) NULL
	ALTER TABLE RBOINFORMATIONSUBCODETABLE ALTER COLUMN LINKEDINFOCODE [nvarchar](20) NULL
	ALTER TABLE RBOINFORMATIONSUBCODETABLE ALTER COLUMN UNITOFMEASURE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINVENTITEMDEPARTMENT' AND COLUMN_NAME = 'DEPARTMENTID') = 10)
begin
	ALTER TABLE RBOINVENTITEMDEPARTMENT ALTER COLUMN DEPARTMENTID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINVENTITEMDEPARTMENT ALTER COLUMN DISPENSEPRINTERGROUPID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINVENTITEMRETAILGROUP' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN DEPARTMENTID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN SIZEGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN COLORGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN DISPENSEPRINTERGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN BARCODESETUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN STYLEGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN FSHREPLENISHMENTRULEID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN ITEMGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN INVENTLOCATIONIDFORPURCHA16016 [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN INVENTLOCATIONIDFORINVENTORY [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN INVENTLOCATIONIDFORSALESORDER [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN INVENTMODELGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN INVENTDIMGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN SALESTAXITEMGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN PURCHASETAXITEMGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN BASECOMPARISONUNITCODE [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUP ALTER COLUMN LSRCOMMISSIONGROUPID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINVENTLINKEDITEM' AND COLUMN_NAME = 'UNIT') = 10)
begin
	ALTER TABLE RBOINVENTLINKEDITEM ALTER COLUMN UNIT [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINVENTTABLE' AND COLUMN_NAME = 'ITEMGROUP') = 10)
begin
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN ITEMGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN ITEMDEPARTMENT [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN ITEMFAMILY [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN DISPENSEPRINTERGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN BASECOMPARISONUNITCODE [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN BARCODESETUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN COLORGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN SIZEGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN STYLEGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLE ALTER COLUMN GRADEID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOLOCATIONPRICEGROUP' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOLOCATIONPRICEGROUP ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOLOCATIONPRICEGROUP ALTER COLUMN PRICEGROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOLOYALTYCUSTTABLE' AND COLUMN_NAME = 'LOYALTYCUSTID') = 10)
begin
	ALTER TABLE RBOLOYALTYCUSTTABLE ALTER COLUMN LOYALTYCUSTID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOLOYALTYMSRCARDTABLE' AND COLUMN_NAME = 'LINKID') = 10)
begin
	ALTER TABLE RBOLOYALTYMSRCARDTABLE ALTER COLUMN LINKID [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYMSRCARDTABLE ALTER COLUMN LOYALTYSCHEMEID [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYMSRCARDTABLE ALTER COLUMN LOYALTYCUSTID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOLOYALTYMSRCARDTRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOLOYALTYMSRCARDTRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYMSRCARDTRANS ALTER COLUMN RECEIPTID [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYMSRCARDTRANS ALTER COLUMN STOREID [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYMSRCARDTRANS ALTER COLUMN TERMINALID [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYMSRCARDTRANS ALTER COLUMN LOYALTYCUSTID [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYMSRCARDTRANS ALTER COLUMN LOYALTYSCHEMEID [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYMSRCARDTRANS ALTER COLUMN STATEMENTID [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYMSRCARDTRANS ALTER COLUMN STAFFID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOLOYALTYPOINTSTABLE' AND COLUMN_NAME = 'LOYALTYSCHEMEID') = 10)
begin
	ALTER TABLE RBOLOYALTYPOINTSTABLE ALTER COLUMN LOYALTYSCHEMEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOLOYALTYPOINTSTABLE ALTER COLUMN SCHEMERELATION [nvarchar](20) NOT NULL
	ALTER TABLE RBOLOYALTYPOINTSTABLE ALTER COLUMN CUSTOMERGROUP_EDIT [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYPOINTSTABLE ALTER COLUMN CONTACTSEGMENT_EDIT [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOLOYALTYSCHEMESTABLE' AND COLUMN_NAME = 'LOYALTYSCHEMEID') = 10)
begin
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ALTER COLUMN LOYALTYSCHEMEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ALTER COLUMN STARTINGCARDNO_EDIT [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ALTER COLUMN CARDFLITER_EDIT [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ALTER COLUMN LOYALTYTENDERTYPE [nvarchar](20) NULL
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ALTER COLUMN CUSTOMERNOLINK_LINKSTOCUS20017 [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOMSRCARDTABLE' AND COLUMN_NAME = 'LINKID') = 10)
begin
	ALTER TABLE RBOMSRCARDTABLE ALTER COLUMN LINKID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOPARAMETERS' AND COLUMN_NAME = 'LOCALSTOREID') = 10)
begin
	ALTER TABLE RBOPARAMETERS ALTER COLUMN LOCALSTOREID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSIZEGROUPTABLE' AND COLUMN_NAME = 'SIZEGROUP') = 10)
begin
	ALTER TABLE RBOSIZEGROUPTABLE ALTER COLUMN SIZEGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSIZEGROUPTRANS' AND COLUMN_NAME = 'SIZEGROUP') = 10)
begin
	ALTER TABLE RBOSIZEGROUPTRANS ALTER COLUMN SIZEGROUP [nvarchar](20) NOT NULL
	ALTER TABLE RBOSIZEGROUPTRANS ALTER COLUMN SIZE_ [nvarchar](20) NOT NULL
	ALTER TABLE RBOSIZEGROUPTRANS ALTER COLUMN NOINBARCODE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSIZES' AND COLUMN_NAME = 'SIZE_') = 10)
begin
	ALTER TABLE RBOSIZES ALTER COLUMN SIZE_ [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSPECIALGROUP' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE RBOSPECIALGROUP ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSPECIALGROUPITEMS' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE RBOSPECIALGROUPITEMS ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSPECIALGROUPITEMS ALTER COLUMN ITEMID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTAFFPERMISSIONGROUP' AND COLUMN_NAME = 'PERMISSIONGROUPID') = 10)
begin
	ALTER TABLE RBOSTAFFPERMISSIONGROUP ALTER COLUMN PERMISSIONGROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTAFFTABLE' AND COLUMN_NAME = 'STAFFID') = 10)
begin
	ALTER TABLE RBOSTAFFTABLE ALTER COLUMN STAFFID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTAFFTABLE ALTER COLUMN STOREID [nvarchar](20) NULL
	ALTER TABLE RBOSTAFFTABLE ALTER COLUMN PERMISSIONGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOSTAFFTABLE ALTER COLUMN ZREPORTID [nvarchar](20) NULL
	ALTER TABLE RBOSTAFFTABLE ALTER COLUMN LAYOUTID [nvarchar](20) NULL
	ALTER TABLE RBOSTAFFTABLE ALTER COLUMN OPERATORCULTURE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTATEMENTLINE' AND COLUMN_NAME = 'STAFFID') = 10)
begin
	ALTER TABLE RBOSTATEMENTLINE ALTER COLUMN STAFFID [nvarchar](20) NULL
	ALTER TABLE RBOSTATEMENTLINE ALTER COLUMN TERMINALID [nvarchar](20) NULL
	ALTER TABLE RBOSTATEMENTLINE ALTER COLUMN CURRENCYCODE [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTATEMENTLINE ALTER COLUMN TENDERID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTATEMENTTABLE' AND COLUMN_NAME = 'STATEMENTID') = 10)
begin
	ALTER TABLE RBOSTATEMENTTABLE ALTER COLUMN STATEMENTID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTATEMENTTABLE ALTER COLUMN STOREID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTORECASHDECLARATIONTABLE' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOSTORECASHDECLARATIONTABLE ALTER COLUMN STOREID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTORETABLE' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOSTORETABLE ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN MANAGERID [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN DIMENSION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN DIMENSION2_ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN DIMENSION3_ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN INVENTLOCATION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN ROUNDINGACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN STATEMENTNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN FUNCTIONALITYPROFILE [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN TERMINALNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN STAFFNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN ITEMNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN DISCOUNTOFFERNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN MIXANDMATCHNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN MULTIBUYDISCOUNTNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN REMOVEADDTENDER [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN INCOMEEXEPENSEACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN TAXGROUP [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN ROUNDINGTAXACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN CULTURENAME [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN LAYOUTID [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLE ALTER COLUMN DEFAULTCUSTACCOUNT [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTORETENDERTYPECARDTABLE' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOSTORETENDERTYPECARDTABLE ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLE ALTER COLUMN TENDERTYPEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLE ALTER COLUMN CARDTYPEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLE ALTER COLUMN ACCOUNTRELATION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLE ALTER COLUMN DIFFERENCEACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLE ALTER COLUMN DIFFERENCEACCOUNTFORBIGDI20017 [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLE ALTER COLUMN CARDFEEACCOUNT [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTORETENDERTYPETABLE' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOSTORETENDERTYPETABLE ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPETABLE ALTER COLUMN TENDERTYPEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPETABLE ALTER COLUMN LINENUMINTRANSACTION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPETABLE ALTER COLUMN CHANGETENDERID [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPETABLE ALTER COLUMN ABOVEMINIMUMTENDERID [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPETABLE ALTER COLUMN ACCOUNTRELATION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPETABLE ALTER COLUMN DIFFERENCEACCOUNT [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTYLEGROUPTABLE' AND COLUMN_NAME = 'STYLEGROUP') = 10)
begin
	ALTER TABLE RBOSTYLEGROUPTABLE ALTER COLUMN STYLEGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTYLEGROUPTRANS' AND COLUMN_NAME = 'STYLEGROUP') = 10)
begin
	ALTER TABLE RBOSTYLEGROUPTRANS ALTER COLUMN STYLEGROUP [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTYLEGROUPTRANS ALTER COLUMN STYLE [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTYLEGROUPTRANS ALTER COLUMN NOINBARCODE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTYLES' AND COLUMN_NAME = 'STYLE') = 10)
begin
	ALTER TABLE RBOSTYLES ALTER COLUMN STYLE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTENDERTYPECARDNUMBERS' AND COLUMN_NAME = 'CARDTYPEID') = 10)
begin
	ALTER TABLE RBOTENDERTYPECARDNUMBERS ALTER COLUMN CARDTYPEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTENDERTYPECARDTABLE' AND COLUMN_NAME = 'CARDTYPEID') = 10)
begin
	ALTER TABLE RBOTENDERTYPECARDTABLE ALTER COLUMN CARDTYPEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTENDERTYPETABLE' AND COLUMN_NAME = 'TENDERTYPEID') = 10)
begin
	ALTER TABLE RBOTENDERTYPETABLE ALTER COLUMN TENDERTYPEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTERMINALTABLE' AND COLUMN_NAME = 'TERMINALID') = 10)
begin
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN STOREID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN EFTSTOREID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN EFTTERMINALID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN HARDWAREPROFILE [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN VISUALPROFILE [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN LASTZREPORTID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN LAYOUTID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN FUNCTIONALITYPROFILE [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN RECEIPTIDNUMBERSEQUENCE [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN TRANSACTIONSERVICEPROFILE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONBANKEDTENDE20338' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN RECEIPTID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN STATEMENTCODE [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN CARDTYPEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN TENDERTYPE [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN SHIFT [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN STAFF [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN STORE [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN TERMINAL [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN STATEMENTID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN ZREPORTID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONDISCOUNTTRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONDISCOUNTTRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONDISCOUNTTRANS ALTER COLUMN STORE [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONDISCOUNTTRANS ALTER COLUMN TERMINAL [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONFUELTRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONFUELTRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONFUELTRANS ALTER COLUMN STORE [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONFUELTRANS ALTER COLUMN TERMINAL [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONINCOMEEXPEN20158' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN RECEIPTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN INCOMEEXEPENSEACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN STORE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN TERMINAL [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN STAFF [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN STATEMENTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN STATEMENTCODE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN SHIFT [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN ZREPORTID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONINFOCODETRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN INFOCODEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN STORE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN TERMINAL [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN STAFF [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN ITEMTENDER [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN SUBINFOCODEID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN STATEMENTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN STATEMENTCODE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONLOYALTYPOINTTRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN RECEIPTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN STOREID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN TERMINALID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN LOYALTYCUSTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN LOYALTYSCHEMEID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN STATEMENTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN STATEMENTCODE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN STAFFID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONORDERINVOICETRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONORDERINVOICETRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONORDERINVOICETRANS ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONORDERINVOICETRANS ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONORDERINVOICETRANS ALTER COLUMN STATEMENTID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONPAYMENTTRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN RECEIPTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN STATEMENTCODE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN CARDTYPEID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN TENDERTYPE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN SHIFT [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN STORE [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN TERMINAL [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN STATEMENTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN ZREPORTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN GIFTORCREDITID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONSAFETENDERTRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN RECEIPTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN STATEMENTCODE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN CARDTYPEID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN TENDERTYPE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN SHIFT [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN STAFF [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN STORE [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN TERMINAL [nvarchar](20) NOT NULL
	
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS
	DROP CONSTRAINT I_20379TRANSACTIONLINEIDX
	
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN STATEMENTID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN ZREPORTID [nvarchar](20) NULL
	
	ALTER TABLE [dbo].[RBOTRANSACTIONSAFETENDERTRANS] ADD  CONSTRAINT [I_20379TRANSACTIONLINEIDX] PRIMARY KEY CLUSTERED 
	(
	[DATAAREAID] ASC,
	[STORE] ASC,
	[TERMINAL] ASC,
	[TRANSACTIONID] ASC,
	[LINENUM] ASC,
	[STATEMENTID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN ITEMDEPARTMENTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN ITEMGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN TAXGROUP [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN SHIFT [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN DISCOFFERID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN DISCGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN STATEMENTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN SECTION [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN SHELF [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN STATEMENTCODE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN STORE [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN STAFF [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN VARIANTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN UNIT [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN STAFFID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN PERIODICDISCGROUP [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN CREATEDBY [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN PRESCRIPTIONID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN RETURNTRANSACTIONID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTABLE' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN RECEIPTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN STORE [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN TERMINAL [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN STAFF [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN SHIFT [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN INFOCODEDISCGROUP [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN STATEMENTCODE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN STATEMENTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN REFUNDRECEIPTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN RETRIEVEDFROMRECEIPTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN ZREPORTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN CREATEDONPOSTERMINAL [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN CREATEDBY [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN ORGTRANSSTORE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN ORGTRANSACTIONID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN ORGRECEIPTID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTAXTRANS' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTAXTRANS ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONTAXTRANS ALTER COLUMN TAXGROUP [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTAXTRANS ALTER COLUMN TAXCODE [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTAXTRANS ALTER COLUMN STORE [nvarchar](10) NOT NULL
	ALTER TABLE RBOTRANSACTIONTAXTRANS ALTER COLUMN TERMINAL [nvarchar](10) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN RECEIPTID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN CARDID [nvarchar](20) NULL
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN SHIFT [nvarchar](10) NULL
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN STAFF [nvarchar](10) NULL
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN STORE [nvarchar](10) NULL
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN TERMINAL [nvarchar](10) NULL
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN STATEMENTID [nvarchar](10) NULL
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN ZREPORTID [nvarchar](10) NULL
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN STATEMENTCODE [nvarchar](10) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOUNIT' AND COLUMN_NAME = 'UNITID') = 10)
begin
	ALTER TABLE RBOUNIT ALTER COLUMN UNITID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'SALESTYPE' AND COLUMN_NAME = 'PURCHASINGCODE') = 10)
begin
	ALTER TABLE SALESTYPE ALTER COLUMN PURCHASINGCODE [nvarchar](20) NULL
	ALTER TABLE SALESTYPE ALTER COLUMN TAXGROUPID [nvarchar](20) NULL
	ALTER TABLE SALESTYPE ALTER COLUMN PRICEGROUP [nvarchar](20) NULL
	ALTER TABLE SALESTYPE ALTER COLUMN LOCATIONCODE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXDATA' AND COLUMN_NAME = 'TAXCODE') = 10)
begin
	ALTER TABLE TAXDATA ALTER COLUMN TAXCODE [nvarchar](20) NOT NULL
	ALTER TABLE TAXDATA ALTER COLUMN POSTAXCODEID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXGROUPDATA' AND COLUMN_NAME = 'TAXGROUP') = 10)
begin
	ALTER TABLE TAXGROUPDATA ALTER COLUMN TAXGROUP [nvarchar](20) NOT NULL
	ALTER TABLE TAXGROUPDATA ALTER COLUMN TAXCODE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXGROUPHEADING' AND COLUMN_NAME = 'TAXGROUP') = 10)
begin
	ALTER TABLE TAXGROUPHEADING ALTER COLUMN TAXGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXITEMGROUPHEADING' AND COLUMN_NAME = 'TAXITEMGROUP') = 10)
begin
	ALTER TABLE TAXITEMGROUPHEADING ALTER COLUMN TAXITEMGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXONITEM' AND COLUMN_NAME = 'TAXITEMGROUP') = 10)
begin
	ALTER TABLE TAXONITEM ALTER COLUMN TAXITEMGROUP [nvarchar](20) NOT NULL
	ALTER TABLE TAXONITEM ALTER COLUMN TAXCODE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXTABLE' AND COLUMN_NAME = 'TAXCODE') = 10)
begin
	ALTER TABLE TAXTABLE ALTER COLUMN TAXCODE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'UNIT' AND COLUMN_NAME = 'UNITID') = 10)
begin
	ALTER TABLE UNIT ALTER COLUMN UNITID [nvarchar](20) NOT NULL
	ALTER TABLE UNIT ADD MINUNITDECIMALS int NULL  
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'UNITCONVERT' AND COLUMN_NAME = 'FROMUNIT') = 10)
begin
	ALTER TABLE UNITCONVERT ALTER COLUMN FROMUNIT [nvarchar](20) NOT NULL
	ALTER TABLE UNITCONVERT ALTER COLUMN TOUNIT [nvarchar](20) NOT NULL 
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'STAFFID') = 10)
begin
	ALTER TABLE USERS ALTER COLUMN STAFFID [nvarchar](20) NULL
end

GO







