
/*

	Incident No.	: N/A
	Responsible		: Guðbjörn Einarsson
	Sprint			: 2011 - Sprint 5
	Date created	: 10.01.2011

	Description		: Changed fields in transactions tables from nvarchar(10) to nvarchar(20)

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: RBOTRANSACTIONPAYMENTTRANS - STAFF changed
						RBOTRANSACTIONTENDERDECLA20165 - TENDERTYPE changed
						RBOTRANSACTIONTENDERDECLA20165 - SHIFT changed
						RBOTRANSACTIONTENDERDECLA20165 - STAFF changed
						RBOTRANSACTIONTENDERDECLA20165 - STORE changed
						RBOTRANSACTIONTENDERDECLA20165 - TERMINAL changed
						RBOTRANSACTIONTENDERDECLA20165 - STATEMENTID changed
						RBOTRANSACTIONTENDERDECLA20165 - ZREPORTID changed
						RBOTRANSACTIONTENDERDECLA20165 - STATEMENTCODE changed
						RBOTRANSACTIONSALESTRANS - RECEIPTID changed
						
*/

USE LSPOSNET

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONPAYMENTTRANS' AND COLUMN_NAME = 'STAFF') = 10)
begin
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN STAFF [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND COLUMN_NAME = 'TENDERTYPE') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN TENDERTYPE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND COLUMN_NAME = 'SHIFT') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN SHIFT [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND COLUMN_NAME = 'STAFF') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN STAFF [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND COLUMN_NAME = 'STORE') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN STORE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND COLUMN_NAME = 'TERMINAL') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN TERMINAL [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND COLUMN_NAME = 'STATEMENTID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN STATEMENTID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND COLUMN_NAME = 'ZREPORTID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN ZREPORTID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND COLUMN_NAME = 'STATEMENTCODE') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN STATEMENTCODE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'RECEIPTID') = 10)
begin
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN RECEIPTID [nvarchar](20) NOT NULL
end



