
/*

	Incident No.	: N/A
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Sprint 4
	Date created	: 18.01.2011

	Description		: Inserts the default data into table PosParameterSetup

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: PosParameterSetup - default data added
						
*/

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 109 AND PARAMETERCODE = 'DOWN' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('109','DOWN','Next guest','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 109 AND PARAMETERCODE = 'UP' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('109','UP','Previous guest','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = '/?' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','/?','Asks how many parts the item should be split into','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = '/?ALL' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','/?ALL','Splits an item between all guests','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = '/2' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','/2','Splits an item in half','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = '/3' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','/3','Splits an item in three','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = '/4' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','/4','Splits an item in four','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = '/ALL' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','/ALL','Splits an item between all guests','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = '-?' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','-?','Move the item to the split','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = '-1' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','-1','Move the item to the split','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = 'AMT' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','AMT','Splits an item by amount','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = 'UNSPLIT' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','UNSPLIT','Unsplits an item','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 200 AND PARAMETERCODE = 'UNSPLITALL' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('200','UNSPLITALL','Unsplits all items','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 201 AND PARAMETERCODE = 'BACK' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('201','BACK','Move item from a split back to original transaction','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 301 AND PARAMETERCODE = 'ALL' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('301','ALL','Print all splits','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 501 AND PARAMETERCODE = 'DOWN' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('501','DOWN','Next guest','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 501 AND PARAMETERCODE = 'UP' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('501','UP','Previous guest','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 700 AND PARAMETERCODE = 'CANCEL_ALL' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('700','CANCEL_ALL','Cancel all transfers for table','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 700 AND PARAMETERCODE = 'OK' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('700','OK','Transfer table, Save and Exit','LSR')

IF NOT EXISTS (SELECT * FROM [POSPARAMETERSETUP] WHERE [OPERATIONID] = 701 AND PARAMETERCODE = 'BACK' AND [DATAAREAID] = 'LSR')
INSERT POSPARAMETERSETUP(OPERATIONID,PARAMETERCODE,DESCRIPTION,DATAAREAID)       VALUES('701','BACK','Transfer line back to the original line','LSR')
GO


