
/*

	Incident No.	: N/A
	Responsible		: Hörður Kristjánsson
	Sprint			: 2011 - Sprint 5
	Date created	: 18.01.2011

	Description		: Adds fields to the POSMENUHEADER table

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: POSMENUHEADER
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENUHEADER') AND NAME='BACKCOLOR2')
BEGIN
	ALTER TABLE [dbo].[POSMENUHEADER] ADD BACKCOLOR2 int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENUHEADER') AND NAME='GRADIENTMODE')
BEGIN
	ALTER TABLE [dbo].[POSMENUHEADER] ADD GRADIENTMODE int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSMENUHEADER') AND NAME='SHAPE')
BEGIN
	ALTER TABLE [dbo].[POSMENUHEADER] ADD SHAPE int NULL
END
GO