
/*

	Incident No.	: N/A
	Responsible		: Hörður Kristjánsson
	Sprint			: 2011 - Sprint 5
	Date created	: 06.01.2011

	Description	: Add table POSLOOKUP

*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[POSLOOKUP]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[POSLOOKUP](
		[LOOKUPID] [nvarchar](20) NOT NULL,
		[DESCRIPTION] [nvarchar](50) NULL,
		[DYNAMICMENUID] [nvarchar](20) NULL,
		[DYNAMICMENU2ID] [nvarchar](20) NULL,
		[GRID1MENUID] [nvarchar](20) NULL,
		[GRID2MENUID] [nvarchar](20) NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_POSLOOKUP] PRIMARY KEY CLUSTERED 
	(
		[LOOKUPID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO