/*

	Incident No.	: N/A
	Responsible		: Tobias Helmer
	Sprint			: 2011 - Sprint 5
	Date created	: 25.01.2011

	Description		: Add enum fields to be able to resolve the address formats

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: CUSTTABLE,  VENDTABLE, RBOSTORETABLE
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLE') AND NAME='ADDRESSFORMAT')
BEGIN
	ALTER TABLE [dbo].[CUSTTABLE] ADD ADDRESSFORMAT int NULL;
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('VENDTABLE') AND NAME='ADDRESSFORMAT')
BEGIN
	ALTER TABLE [dbo].[VENDTABLE] ADD ADDRESSFORMAT int NULL;
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETABLE') AND NAME='ADDRESSFORMAT')
BEGIN
	ALTER TABLE [dbo].[RBOSTORETABLE] ADD ADDRESSFORMAT int NULL;
END
GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('COMPANYINFO') AND NAME='ADDRESSFORMAT')
BEGIN
	ALTER TABLE [dbo].[COMPANYINFO] ADD ADDRESSFORMAT int NULL;
END
GO

