
/*

	Incident No.	: N/A
	Responsible		: Pétur Þór Sigurðsson
	Sprint			: Sprint 5
	Date created	: 27.01.2011

	Description		: Text ids needed for hospitality added

	Logic scripts   : No stored procedures added or changed
	
-- 	Tables affected	: PosisLanguageText - data added
						
*/


-- LanguageID's for the main hostpitality dialog
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 200)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '200','Error connecting to the Store Server. The application is unable to display the Hospitality table layout and will be closed.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Error connecting to the Store Server. The application is unable to display the Hospitality table layout and will be closed.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 200
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 200)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '200','Villa í tengingu við búðarþjón.  Kerfið getur ekki sýnt borðavalmynd og hættir vinnslu.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Villa í tengingu við búðarþjón.  Kerfið getur ekki sýnt borðavalmynd og hættir vinnslu.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 200
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 201)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '201','Connection to the Store Server has been lost.  Could not carry out the requested operation.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Connection to the Store Server has been lost.  Could not carry out the requested operation.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 201
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 201)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '201','Tenging við búðarþjón rofin.  Kerfið getur ekki framkvæmt aðgerðina.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Tenging við búðarþjón rofin.  Kerfið getur ekki framkvæmt aðgerðina.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 201
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 202)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '202','Unexpected exception. Could not carry out the requested operation.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Unexpected exception. Could not carry out the requested operation.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 202
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 202)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '202','Villa!  Kerfið getur ekki framkvæmt aðgerðina.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Villa.  Kerfið getur ekki framkvæmt aðgerðina.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 202
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 203)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '203','Seating guests is not possible on this table at this time.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Seating guests is not possible on this table at this time.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 203
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 203)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '203','Ekki er hægt að vísa gestum til sætis á þetta borð.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ekki er hægt að vísa gestum til sætis á þetta borð.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 203
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 204)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '204','Select a table to transfer to...',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Select a table to transfer to...', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 204
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 204)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '204','Veljið borð til að flytja á...',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Veljið borð til að flytja á...', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 204
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 205)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '205','Error transfering between tables.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Error transfering between tables.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 205
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 205)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '205','Villa við að færa á milli borða.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Villa við að færa á milli borða.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 205
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 206)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '206','No transaction is available on this table.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'No transaction is available on this table.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 206
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 206)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '206','Engin afgreiðsla er skráð á þetta borð.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Engin afgreiðsla er skráð á þetta borð.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 206
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 207)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '207','The selected table already belongs to the current staff member.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'The selected table already belongs to the current staff member.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 207
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 207)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '207','Valið borð tilheyrir nú þegar innskráðum starfsmanni.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Valið borð tilheyrir nú þegar innskráðum starfsmanni.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 207
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 208)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '208','Do you want to overwrite the staff member on this transaction?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Do you want to overwrite the staff member on this tansaction?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 208
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 208)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '208','Viltu skipta um starfsmann á þessari afgreiðslu?',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Viltu skipta um starfsmann á þessari afgreiðslu?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 208
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 209)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '209','No transaction is available on this table.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'No transaction is available on this table.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 209
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 209)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '209','Engin afgreiðsla er skráð á þetta borð.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Engin afgreiðsla er skráð á þetta borð.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 209
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 210)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '210','Please select a table before running the operation.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Please select a table before running the operation.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 210
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 210)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '210','Vinsamlegast veljið borð áður en aðgerðin er framkvæmd.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Vinsamlegast veljið borð áður en aðgerðin er framkvæmd.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 210
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 211)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '211','The selected table is unavailable.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'The selected table is unavailable.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 211
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 211)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '211','Valið borð er ekki í notkun.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Valið borð er ekki í notkun.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 211
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 212)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '212','The selected table is locked to another staff member.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'The selected table is locked to another staff member.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 212
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 212)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '212','Valið borð er læst af öðrum starfsmanni.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Valið borð er læst af öðrum starfsmanni.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 212
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 213)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '213','Selected table',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Selected table', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 213
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 213)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '213','Valið borð',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Valið borð', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 213

-- LanguageID's new for DiningTable.cs
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 250)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '250','Available',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Available', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 250
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 250)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '250','Laust',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Laust', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 250
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 251)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '251','Guests seated',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Guests seated', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 251
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 251)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '251','Gestir',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gestir', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 251
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 252)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '252','Order not printed',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Order not printed', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 252
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 252)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '252','Pöntun óprentuð',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Pöntun óprentuð', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 252
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 253)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '253','Order printed',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Order printed', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 253
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 253)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '253','Pöntun prentuð',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Pöntun prentuð', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 253
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 254)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '254','Order started',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Order started', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 254
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 254)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '254','Pöntun í framleiðslu',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Pöntun í framleiðslu', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 254
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 255)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '255','Order finished',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Order finished', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 255
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 255)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '255','Pöntun tilbúin',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Pöntun tilbúin', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 255
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 256)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '256','Order confirmed',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Order confirmed', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 256
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 256)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '256','Pöntun staðfest',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Pöntun staðfest', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 256
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 257)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '257','Unavailable',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Unavailable', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 257
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 257)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '257','Ekki í notkun',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ekki í notkun', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 257
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 258)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '258','Not served',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Not served', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 258
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 258)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '258','Engin þjónusta',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Engin þjónusta', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 258
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 259)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '259','Unknown state',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Unknown state', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 259
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 259)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '259','Óþekkt staða',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Óþekkt staða', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 259

-- LanguageID's new for various hospitality operations
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4640)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4640','Menu types',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Menu types', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4640
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4640)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4640','Gerðir',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gerðir', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4640
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4641)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4641','Please conclude the current transaction before running this operation.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Please conclude the current transaction before running this operation', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4641
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4641)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4641','Vinsamlegast ljúkið núverandi afgreiðslu áður en þessi aðgerð er framkvæmd.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Vinsamlegast ljúkið núverandi afgreiðslu áður en þessi aðgerð er framkvæmd.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4641
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4660)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4660','Please conclude the current transaction before running this operation.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Please conclude the current transaction before running this operation', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4660
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4660)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4660','Vinsamlegast ljúkið núverandi afgreiðslu áður en þessi aðgerð er framkvæmd.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Vinsamlegast ljúkið núverandi afgreiðslu áður en þessi aðgerð er framkvæmd.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4660
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4661)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4661','There are no items to change.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'There are no items to change.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4661
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4661)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4661','Það eru engar línur til að breyta.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Það eru engar línur til að breyta.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4661
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4662)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4662','Menu types',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Menu types', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4662
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4662)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4662','Gerðir',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gerðir', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4662
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4680)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4680','Please conclude the current transaction before running this operation.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Please conclude the current transaction before running this operation', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4680
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4680)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4680','Vinsamlegast ljúkið núverandi afgreiðslu áður en þessi aðgerð er framkvæmd.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Vinsamlegast ljúkið núverandi afgreiðslu áður en þessi aðgerð er framkvæmd.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4680
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4681)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4681','There are no items to print.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'There are no items to print.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4681
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4681)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4681','Það eru engar línur til að prenta.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Það eru engar línur til að prenta.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4681
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4682)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4682','Menu types',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Menu types', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4682
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 4682)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '4682','Gerðir',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gerðir', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 4682
GO






