
/*

	Incident No.	: N/A
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Sprint 5
	Date created	: 26.01.2011

	Description		: Text ids needed for Popup dialog added

	Logic scripts   : No stored procedures added or changed
	
-- 	Tables affected	: PosisLanguageText - data added
						
*/


-- LanguageID's for frmPopUpDialog
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2800)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2800','Sel.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Sel.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2800
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2800)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2800','Val',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Val', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2800
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2801)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2801','Req.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Req.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2801
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2801)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2801','Skil.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Skil.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2801
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2802)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2802','No Charge',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'No Charge', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2802
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2802)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2802','Ókeypis',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ókeypis', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2802
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2803)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2803','Price:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Price:', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2803
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2803)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2803','Verð:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Verð:', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2803
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2804)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2804','Discount:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Discount:', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2804
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2804)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2804','Afsláttur:',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Afsláttur:', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2804
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2805)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2805','Multiple selection',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Multiple selection', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2805
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2805)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2805','Multiple selection',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Multiple selection', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2805
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2806)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2806','Selection required',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Selection required', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2806
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2806)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2806','Selection required',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Selection required', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2806
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2807)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2807','Select Max',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Select Max', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2807
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2807)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2807','Hámark',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Hámark', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2807
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2808)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2808','Maximum selection reached for the group',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Maximum selection reached for the group', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2808
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2808)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2808','Ekki er hægt að velja fleiri atriði í flokknum',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ekki er hægt að velja fleiri atriði í flokknum', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2808
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2809)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2809','Minimum requirement is',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Minimum requirement is', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2809
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2809)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2809','Lágmark er að velja',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Lágmark er að velja', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2809
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2810)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2810','Normal price',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Normal price', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2810
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2810)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2810','Vöruverð',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Vöruverð', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2810
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2811)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2811','Cancel',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Cancel', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2811
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2811)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2811','Hætta við',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Hætta við', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2811
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2812)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2812','OK',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'OK', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2812
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2812)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2812','OK',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'OK', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2812
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2813)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2813','Clear selection',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Clear selection', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2813
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2813)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2813','Hreinsa val',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Hreinsa val', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2813
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2814)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2814','Clear Qty',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Clear Qty', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2814
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2814)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2814','Hreinsa fj.',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Hreinsa fj.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2814
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 2815)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '2815','Unlimited selection',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Unlimited selection', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 2815
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 2815)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '2815','Ótakmarkað val',0, '7.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ótakmarkað val', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 2815
GO






