//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.Services.EFT.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.Services.EFT.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount due: #1.
        /// </summary>
        internal static string AmountDue {
            get {
                return ResourceManager.GetString("AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number length is not valid..
        /// </summary>
        internal static string CardNumberLengthNotValid {
            get {
                return ResourceManager.GetString("CardNumberLengthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card number for this card type cannot be manually entered.
        /// </summary>
        internal static string CardTypeCannotManuallyEnter {
            get {
                return ResourceManager.GetString("CardTypeCannotManuallyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type unrecognized by the EFT broker.
        /// </summary>
        internal static string CardUnidentified {
            get {
                return ResourceManager.GetString("CardUnidentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear card.
        /// </summary>
        internal static string ClearCard {
            get {
                return ResourceManager.GetString("ClearCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string ConnectingToTerminal {
            get {
                return ResourceManager.GetString("ConnectingToTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV number is not valid.
        /// </summary>
        internal static string CVVNotValid {
            get {
                return ResourceManager.GetString("CVVNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogMessage_48 {
            get {
                object obj = ResourceManager.GetObject("DialogMessage_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An EFT mapping for scheme name &apos;*&apos; is not defined. In order for the processing to run, such a mapping must exist to accomodate accepting cards that haven&apos;t been matched to a payment type..
        /// </summary>
        internal static string EFTMappingFallbackNotDefined {
            get {
                return ResourceManager.GetString("EFTMappingFallbackNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An EFT mapping rule is required.
        /// </summary>
        internal static string EFTMappingRequired {
            get {
                return ResourceManager.GetString("EFTMappingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount.
        /// </summary>
        internal static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter card number.
        /// </summary>
        internal static string EnterCardNumber {
            get {
                return ResourceManager.GetString("EnterCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expire date.
        /// </summary>
        internal static string EnterExpireDate {
            get {
                return ResourceManager.GetString("EnterExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date is not valid..
        /// </summary>
        internal static string ExpiryDateNotValid {
            get {
                return ResourceManager.GetString("ExpiryDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number length is not valid..
        /// </summary>
        internal static string InvalidCardLength {
            get {
                return ResourceManager.GetString("InvalidCardLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card number for this card type cannot be manually entered.
        /// </summary>
        internal static string ManuallyEnteredNotAllowed {
            get {
                return ResourceManager.GetString("ManuallyEnteredNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative payments cannot go below the balance amount.
        /// </summary>
        internal static string NegativePaymentsNotBelowBalance {
            get {
                return ResourceManager.GetString("NegativePaymentsNotBelowBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item to pay.
        /// </summary>
        internal static string NoItemToPay {
            get {
                return ResourceManager.GetString("NoItemToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only negative amounts are allowed.
        /// </summary>
        internal static string OnlyNegativeAmountsAllowed {
            get {
                return ResourceManager.GetString("OnlyNegativeAmountsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This payment method cannot be used to pay for the remaining items.
        /// </summary>
        internal static string PaymentMethodCannotBeUsedToPayForItems {
            get {
                return ResourceManager.GetString("PaymentMethodCannotBeUsedToPayForItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an amount.
        /// </summary>
        internal static string PleaseEnterAnAmount {
            get {
                return ResourceManager.GetString("PleaseEnterAnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the card number.
        /// </summary>
        internal static string PleaseEnterCardNumber {
            get {
                return ResourceManager.GetString("PleaseEnterCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select card type first.
        /// </summary>
        internal static string PleaseSelectCardTypeFirst {
            get {
                return ResourceManager.GetString("PleaseSelectCardTypeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is concluded. Please take out the card.
        /// </summary>
        internal static string TakeTheCard {
            get {
                return ResourceManager.GetString("TakeTheCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tender #1 cannot be found. Card payment operation cannot continue..
        /// </summary>
        internal static string TenderInformationNotFound {
            get {
                return ResourceManager.GetString("TenderInformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tender #1 has not been properly configured. Card payment operation cannot continue..
        /// </summary>
        internal static string TenderNotProperlyConfigured {
            get {
                return ResourceManager.GetString("TenderNotProperlyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for card and pin number.
        /// </summary>
        internal static string WaitingForCardAndPin {
            get {
                return ResourceManager.GetString("WaitingForCardAndPin", resourceCulture);
            }
        }
    }
}
