/*

	Incident No.	: ONE-6494 Reason codes
	Responsible		: Adrian Chiorean
	Sprint			: Billy
	Date created	: 30.03.2017

	Description		: Add multiple columns to INVENTTRANSREASON
*/

USE LSPOSNET

-----------------------  ADD COLUMNS -----------------------

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ACTION' AND TABLE_NAME = 'INVENTTRANSREASON')
BEGIN
	ALTER TABLE INVENTTRANSREASON ADD [ACTION] INT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'BEGINDATE' AND TABLE_NAME = 'INVENTTRANSREASON')
BEGIN
	ALTER TABLE INVENTTRANSREASON ADD [BEGINDATE] DATETIME NOT NULL DEFAULT DATEADD(yy, DATEDIFF(yy, 0, getdate()), 0)
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ENDDATE' AND TABLE_NAME = 'INVENTTRANSREASON')
BEGIN
	ALTER TABLE INVENTTRANSREASON ADD [ENDDATE] DATETIME NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ISSYSTEMREASONCODE' AND TABLE_NAME = 'INVENTTRANSREASON')
BEGIN
	ALTER TABLE INVENTTRANSREASON ADD [ISSYSTEMREASONCODE] BIT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'SHOWONPOS' AND TABLE_NAME = 'INVENTTRANSREASON')
BEGIN
	ALTER TABLE INVENTTRANSREASON ADD [SHOWONPOS] BIT NOT NULL DEFAULT 1
END
GO

-----------------------  UPDATE EXISTING RECORDS -----------------------

UPDATE INVENTTRANSREASON SET [ISSYSTEMREASONCODE] = 1, [SHOWONPOS] = 0, [ACTION] = 2 WHERE [REASONID] IN ('COR001','COR002','COR003')
UPDATE INVENTTRANSREASON SET [ISSYSTEMREASONCODE] = 1, [SHOWONPOS] = 0, [ACTION] = 0 WHERE [REASONID] IN ('TRANS001')
UPDATE INVENTTRANSREASON SET [ISSYSTEMREASONCODE] = 1, [SHOWONPOS] = 0, [ACTION] = 3 WHERE [REASONID] IN ('ADJ001')