/*

	Incident No.	: ONE-6253 Quotes
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Grundtal
	Date created	: 24.03.2017

	Description		: Update the quote and customer order operations, add a new formtype for Quotes
*/

USE LSPOSNET

IF EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 615 AND USEROPERATION = 0)
BEGIN
	UPDATE POSISOPERATIONS
	SET USEROPERATION = 1
	WHERE OPERATIONID = 615
END
GO

IF EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 617 AND USEROPERATION = 0)
BEGIN
	UPDATE POSISOPERATIONS
	SET USEROPERATION = 1
	WHERE OPERATIONID = 617
END
GO

IF EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 614 AND LOOKUPTYPE = 0)
BEGIN
	UPDATE POSISOPERATIONS
	SET LOOKUPTYPE = 19
	WHERE OPERATIONID = 614
END
GO


IF NOT EXISTS (SELECT * FROM POSFORMTYPE WHERE ID = '4A159122-9684-4090-A117-E0A4DCDA0088')
BEGIN
	INSERT INTO POSFORMTYPE
	VALUES ('4A159122-9684-4090-A117-E0A4DCDA0088', 'Quote information', 36, 'LSR');
END
GO
