/*
	Incident No.	: ONE-6510
	Responsible		: Hörður Kristjánsson
	Sprint			: Billy
	Date created	: 11.04.2017

	Description		: Added table RBOTRANSACTIONLOGTRANS
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RBOTRANSACTIONLOGTRANS')
BEGIN
	CREATE TABLE [dbo].[RBOTRANSACTIONLOGTRANS](
	[TRANSACTIONID] [nvarchar](20) NOT NULL,
	[LINENUM] [numeric](28, 12) NOT NULL,
	[STORE] [nvarchar](20) NOT NULL,
	[TERMINAL] [nvarchar](20) NOT NULL,
	[LOGTEXT] [nvarchar](max) NULL,
	[REPLICATIONCOUNTER] [int] IDENTITY(1,1) NOT NULL,
	[REPLICATED] [tinyint] NULL,
	[DATAAREAID] nvarchar(4) NOT NULL
 CONSTRAINT [PK_RBOTRANSACTIONLOGTRANS] PRIMARY KEY CLUSTERED 
(
	[TRANSACTIONID] ASC,
	[LINENUM] ASC,
	[DATAAREAID] ASC,
	[STORE] ASC,
	[TERMINAL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO