/*
	Incident No.	: ONE-6495 Default reason code on store
	Responsible		: Adrian Chiorean
	Sprint			: Billy
	Date created	: 03.04.2017

	Description		: Add RETURNREASONCODEID column to RBOSTORETABLE
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RETURNREASONCODEID' AND TABLE_NAME = 'RBOSTORETABLE')
BEGIN
	ALTER TABLE RBOSTORETABLE ADD [RETURNREASONCODEID] NVARCHAR(20) NULL
END
GO