/*
	Incident No.	: ONE-6461
	Responsible		: Adrian Chiorean
	Sprint			: Lack
	Date created	: 03.04.2017

	Description		: Insert new system styles
*/

USE LSPOSNET


IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsBalanceLabel' OR ID = 2000016)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000016, 'PosTotalsBalanceLabel', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 9)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsBalanceLabelNegative' OR ID = 2000017)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000017, 'PosTotalsBalanceLabelNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 10)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsBalanceValueNegative' OR ID = 2000018)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000018, 'PosTotalsBalanceValueNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 11)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptSaleTotalLabel' OR ID = 2000019)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000019, 'PosReceiptSaleTotalLabel', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 12)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptSaleTotalLabelNegative' OR ID = 2000020)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000020, 'PosReceiptSaleTotalLabelNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 13)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptSaleTotalValue' OR ID = 2000021)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000021, 'PosReceiptSaleTotalValue', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 14)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptSaleTotalValueNegative' OR ID = 2000022)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000022, 'PosReceiptSaleTotalValueNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 15)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptLineSub' OR ID = 2000023)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000023, 'PosReceiptLineSub', 'Segoe UI', 10, 1, -14264184, -1, 0, 0, 'LSR', -1, 0, 5, 1, 16)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalLabelNegative' OR ID = 2000024)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000024, 'DualDisplayTotalLabelNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 17)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalValue' OR ID = 2000025)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000025, 'DualDisplayTotalValue', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 18)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalValueNegative' OR ID = 2000026)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000026, 'DualDisplayTotalValueNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 19)
END

GO
