/*
	Incident No.	: ONE-6649
	Responsible		: Simona Avornicesei
	Sprint			: Lack
	Date created	: 18.04.2017

	Description		: Added MASTERID column to INVENTJOURNALTRANS
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'MASTERID' AND TABLE_NAME = 'INVENTJOURNALTRANS')
BEGIN
	ALTER TABLE INVENTJOURNALTRANS ADD [MASTERID] UNIQUEIDENTIFIER NULL;

	EXECUTE spDB_SetFieldDescription_1_0 'INVENTJOURNALTRANS', 'MASTERID', 'Unique GUID for each inventory journal line/transaction.';
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'PARENTMASTERID' AND TABLE_NAME = 'INVENTJOURNALTRANS')
BEGIN
	ALTER TABLE INVENTJOURNALTRANS ADD [PARENTMASTERID] UNIQUEIDENTIFIER NULL;
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTJOURNALTRANS', 'PARENTMASTERID', 'The parent parked inventory journal line/transaction from which the current quantity was moved to main inventory.';
END
GO