/*
	Incident No.	: ONE-6499
	Responsible		: Adrian Chiorean
	Sprint			: Lack
	Date created	: 13.04.2017

	Description		: Added column to RBOTRANSACTIONSALESTRANS
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'REASONCODEID' AND TABLE_NAME = 'RBOTRANSACTIONSALESTRANS')
BEGIN
	ALTER TABLE RBOTRANSACTIONSALESTRANS ADD [REASONCODEID] NVARCHAR(20) NULL
END
GO