/*
	Incident No.	: ONE-6572
	Responsible		: Adrian Chiorean
	Sprint			: Hemnes
	Date created	: 27.04.2017

	Description		: Add GUID column to IMAGES for touch button layout export/import functionality
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'GUID' AND TABLE_NAME = 'IMAGES')
BEGIN
	ALTER TABLE IMAGES ADD [GUID] UNIQUEIDENTIFIER NULL
END
GO

DECLARE @PICTUREID NVARCHAR(20)

DECLARE IMAGECURSOR CURSOR FOR
	SELECT P.PICTUREID
	FROM IMAGES P
	WHERE P.[GUID] IS NULL

OPEN IMAGECURSOR

FETCH FROM IMAGECURSOR INTO @PICTUREID

WHILE @@FETCH_STATUS = 0
BEGIN
	UPDATE IMAGES SET [GUID] = NEWID() WHERE PICTUREID = @PICTUREID
	FETCH NEXT FROM IMAGECURSOR INTO @PICTUREID
END

CLOSE IMAGECURSOR
DEALLOCATE IMAGECURSOR
GO