/*
	Incident No.	: ONE-6497, ONE-6498
	Responsible		: Adrian Chiorean
	Sprint			: Lack
	Date created	: 18.04.2017

	Description		: Update Return transaction operation, Add reason code operation
*/

USE LSPOSNET

IF EXISTS(SELECT 1 FROM POSISOPERATIONS WHERE OPERATIONID = 114 AND LOOKUPTYPE = 0) -- Return transaction
BEGIN
	UPDATE POSISOPERATIONS SET LOOKUPTYPE = 22 WHERE OPERATIONID = 114 -- 22 = LookupTypeEnum.ReasonCode
END

IF EXISTS(SELECT 1 FROM POSISOPERATIONS WHERE OPERATIONID = 109 AND LOOKUPTYPE = 0) -- Return item
BEGIN
	UPDATE POSISOPERATIONS SET LOOKUPTYPE = 22 WHERE OPERATIONID = 109 -- 22 = LookupTypeEnum.ReasonCode
END

IF NOT EXISTS(SELECT 1 FROM POSISOPERATIONS WHERE OPERATIONID = 135)
BEGIN
	INSERT INTO POSISOPERATIONS (OPERATIONID, OPERATIONNAME, CHECKUSERACCESS, USEROPERATION, DATAAREAID, LOOKUPTYPE, AUDIT)
	VALUES (135, 'Set reason code', 1, 1, 'LSR', 0, 1)
END
GO