/*

	Incident No.	: ONE-7035
	Responsible		: Hörður Kristjánsson
	Sprint			: Applraro
	Date created	: 09.06.2017

	Description		: Adding identity column to Barcode mask table
	
	
	Tables affected	: RBOBARCODEMASKTABLE
						
*/

USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOBARCODEMASKTABLE' AND COLUMN_NAME = 'SEQUENCE')
BEGIN
	ALTER TABLE RBOBARCODEMASKTABLE
	ADD SEQUENCE INT IDENTITY(1,1) NOT NULL
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOBARCODEMASKSEGMENT' AND COLUMN_NAME = 'SEQUENCE')
BEGIN
	ALTER TABLE RBOBARCODEMASKSEGMENT
	ADD SEQUENCE INT IDENTITY(1,1) NOT NULL
END