/*
	Incident No.	: ONE-6892
	Responsible		: Adrian Chiorean
	Sprint			: Pax
	Date created	: 25.05.2017

	Description		: Add RECEIPTPAYMENTLINESSIZE column to visual profile
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTPAYMENTLINESSIZE' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD RECEIPTPAYMENTLINESSIZE INT NOT NULL DEFAULT 30
END
GO