/*
	Incident No.	: ONE-6894
	Responsible		: Adrian Chiorean
	Sprint			: Färgrik
	Date created	: 22.05.2017

	Description		: Cleanup unused columns from RETAILITEM
*/

USE LSPOSNET

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'PURCHASEPRICEINCLTAX')
BEGIN
	IF EXISTS(SELECT 1 FROM DBO.SYSOBJECTS WHERE id = OBJECT_ID('DF_RETAILITEM_PURCHASEPRICEINCLTAX') AND type = 'D')
	BEGIN
		ALTER TABLE RETAILITEM DROP CONSTRAINT DF_RETAILITEM_PURCHASEPRICEINCLTAX
	END
	
	ALTER TABLE RETAILITEM DROP COLUMN PURCHASEPRICEINCLTAX
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'PURCHASEPRICEUNIT')
BEGIN
	IF EXISTS(SELECT 1 FROM DBO.SYSOBJECTS WHERE id = OBJECT_ID('DF_RETAILITEM_PURCHASEPRICEUNIT') AND type = 'D')
	BEGIN
		ALTER TABLE RETAILITEM DROP CONSTRAINT DF_RETAILITEM_PURCHASEPRICEUNIT
	END

	ALTER TABLE RETAILITEM DROP COLUMN PURCHASEPRICEUNIT
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'PURCHASEMARKUP')
BEGIN
	IF EXISTS(SELECT 1 FROM DBO.SYSOBJECTS WHERE id = OBJECT_ID('DF_RETAILITEM_PURCHASEMARKUP') AND type = 'D')
	BEGIN
		ALTER TABLE RETAILITEM DROP CONSTRAINT DF_RETAILITEM_PURCHASEMARKUP
	END

	ALTER TABLE RETAILITEM DROP COLUMN PURCHASEMARKUP
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'SALESPRICEUNIT')
BEGIN
	IF EXISTS(SELECT 1 FROM DBO.SYSOBJECTS WHERE id = OBJECT_ID('DF_RETAILITEM_SALESPRICEUNIT') AND type = 'D')
	BEGIN
		ALTER TABLE RETAILITEM DROP CONSTRAINT DF_RETAILITEM_SALESPRICEUNIT
	END

	ALTER TABLE RETAILITEM DROP COLUMN SALESPRICEUNIT
END
GO