/*
	Incident No.	: ONE-6768
	Responsible		: Adrian Chiorean
	Sprint			: Färgrik
	Date created	: 18.05.2017

	Description		: Increase RECEIPTID columns size to 61 (StoreID 20 + dash '-' 1 + TerminalID 20 + ReceiptID 20)
	Check query		: SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME LIKE '%RECEIPTID%'
*/

USE LSPOSNET

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'CUSTOMERLEDGERENTRIES' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE CUSTOMERLEDGERENTRIES ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'POSISTILLLAYOUT' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE POSISTILLLAYOUT ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONTENDERDECLA20165' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONTABLE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'REFUNDRECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONTABLE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN REFUNDRECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RETRIEVEDFROMRECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONTABLE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN RETRIEVEDFROMRECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ORGRECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONTABLE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONTABLE ALTER COLUMN ORGRECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONSAFETENDERTRANS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONSAFETENDERTRANS ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN RECEIPTID NVARCHAR(61) NOT NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RETURNRECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN RETURNRECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONPAYMENTTRANS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONPAYMENTTRANS ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONINCOMEEXPEN20158' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'POSISCUSTTRANSACTIONS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE POSISCUSTTRANSACTIONS ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONBANKEDTENDE20338' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONBANKEDTENDE20338 ALTER COLUMN RECEIPTID NVARCHAR(61) NOT NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTIDNUMBERSEQUENCE' AND TABLE_NAME = 'RBOTERMINALTABLE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN RECEIPTIDNUMBERSEQUENCE NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONLOYALTYPOINTTRANS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOTRANSACTIONFISCALTRANS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONFISCALTRANS ALTER COLUMN RECEIPTID NVARCHAR(61) NOT NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOGIFTCARDTRANSACTIONS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOGIFTCARDTRANSACTIONS ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOCREDITVOUCHERTRANSACTIONS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOCREDITVOUCHERTRANSACTIONS ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTID' AND TABLE_NAME = 'RBOLOYALTYTRANS' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE RBOLOYALTYTRANS ALTER COLUMN RECEIPTID NVARCHAR(61) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'DOCUMENTNO' AND TABLE_NAME = 'CUSTOMERLEDGERENTRIES' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE CUSTOMERLEDGERENTRIES ALTER COLUMN DOCUMENTNO NVARCHAR(61) NULL
END
GO