//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.ViewPlugins.CreditVouchers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.ViewPlugins.CreditVouchers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to credit voucher....
        /// </summary>
        internal static string AddToCreditVoucher {
            get {
                return ResourceManager.GetString("AddToCreditVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Site Service.
        /// </summary>
        internal static string CouldNotConnectToStoreServer {
            get {
                return ResourceManager.GetString("CouldNotConnectToStoreServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap credit_memos_16 {
            get {
                object obj = ResourceManager.GetObject("credit_memos_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap credit_memos_32 {
            get {
                object obj = ResourceManager.GetObject("credit_memos_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit memo.
        /// </summary>
        internal static string CreditMemo {
            get {
                return ResourceManager.GetString("CreditMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to search for and view credit memos.
        /// </summary>
        internal static string CreditMemoDescription {
            get {
                return ResourceManager.GetString("CreditMemoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit memo ID.
        /// </summary>
        internal static string CreditMemoId {
            get {
                return ResourceManager.GetString("CreditMemoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings up a menu with credit memo operations.
        /// </summary>
        internal static string CreditMemoOperationDescription {
            get {
                return ResourceManager.GetString("CreditMemoOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit memos.
        /// </summary>
        internal static string CreditMemos {
            get {
                return ResourceManager.GetString("CreditMemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and search for credit memos.
        /// </summary>
        internal static string CreditMemoTooltipDescription {
            get {
                return ResourceManager.GetString("CreditMemoTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete credit memo.
        /// </summary>
        internal static string DeleteCreditMemo {
            get {
                return ResourceManager.GetString("DeleteCreditMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected credit memo?.
        /// </summary>
        internal static string DeleteCreditMemoQuestion {
            get {
                return ResourceManager.GetString("DeleteCreditMemoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete credit memos.
        /// </summary>
        internal static string DeleteCreditMemos {
            get {
                return ResourceManager.GetString("DeleteCreditMemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected credit memos?.
        /// </summary>
        internal static string DeleteCreditMemosQuestion {
            get {
                return ResourceManager.GetString("DeleteCreditMemosQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount to add to the selected credit memo.
        /// </summary>
        internal static string EnterAmountToAddToCreditMemo {
            get {
                return ResourceManager.GetString("EnterAmountToAddToCreditMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GiftCard16 {
            get {
                object obj = ResourceManager.GetObject("GiftCard16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift cards / Credit memos.
        /// </summary>
        internal static string GiftcardsCreditMemo {
            get {
                return ResourceManager.GetString("GiftcardsCreditMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last used date.
        /// </summary>
        internal static string LastUsedDate {
            get {
                return ResourceManager.GetString("LastUsedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap List32x32 {
            get {
                object obj = ResourceManager.GetObject("List32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site service has not been configured yet.
        /// </summary>
        internal static string NoStoreServerIsSetUp {
            get {
                return ResourceManager.GetString("NoStoreServerIsSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not empty.
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        internal static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View credit memos.
        /// </summary>
        internal static string ViewCreditMemos {
            get {
                return ResourceManager.GetString("ViewCreditMemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View POS user.
        /// </summary>
        internal static string ViewPOSUser {
            get {
                return ResourceManager.GetString("ViewPOSUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View store.
        /// </summary>
        internal static string ViewStore {
            get {
                return ResourceManager.GetString("ViewStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View terminal.
        /// </summary>
        internal static string ViewTerminal {
            get {
                return ResourceManager.GetString("ViewTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View user.
        /// </summary>
        internal static string ViewUser {
            get {
                return ResourceManager.GetString("ViewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers.
        /// </summary>
        internal static string Vouchers {
            get {
                return ResourceManager.GetString("Vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
