//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.ViewPlugins.ExcelFiles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.ViewPlugins.ExcelFiles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variant item with the attribute combination already exists.
        /// </summary>
        internal static string AttributeCombinationAlreadyExists {
            get {
                return ResourceManager.GetString("AttributeCombinationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute count does not match dimensions count.
        /// </summary>
        internal static string AttributeCountMismatch {
            get {
                return ResourceManager.GetString("AttributeCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes for variant items cannot be empty.
        /// </summary>
        internal static string AttributesCannotBeEmpty {
            get {
                return ResourceManager.GetString("AttributesCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar code is longer than allowed by the selected bar code setup. Please correct the problem and then try importing again.
        /// </summary>
        internal static string BarCodeIsLongerThanAllowedByBarCodeSetup {
            get {
                return ResourceManager.GetString("BarCodeIsLongerThanAllowedByBarCodeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar code is shorter than allowed by the selected bar code setup. Please correct the problem and then try importing again.
        /// </summary>
        internal static string BarCodeIsShorterThanAllowedByBarCodeSetup {
            get {
                return ResourceManager.GetString("BarCodeIsShorterThanAllowedByBarCodeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar code setup does not exist, please create correct bar code setup and try importing again.
        /// </summary>
        internal static string BarCodeSetupDoesNotExist {
            get {
                return ResourceManager.GetString("BarCodeSetupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar code setup missing.
        /// </summary>
        internal static string BarCodeSetupMissing {
            get {
                return ResourceManager.GetString("BarCodeSetupMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find base templated file.
        /// </summary>
        internal static string CouldNotFindBaseTemplateFile {
            get {
                return ResourceManager.GetString("CouldNotFindBaseTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find item with Item ID #1.
        /// </summary>
        internal static string CouldNotFindItem {
            get {
                return ResourceManager.GetString("CouldNotFindItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find one of the following worksheets: #1.
        /// </summary>
        internal static string CouldNotFindOneOfTheFollowingWorksheets {
            get {
                return ResourceManager.GetString("CouldNotFindOneOfTheFollowingWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate adjustment ID because the connection to Site Service could not be established. The ID must be entered manually before importing the file..
        /// </summary>
        internal static string CouldNotGenerateIDFromHeadQuarters {
            get {
                return ResourceManager.GetString("CouldNotGenerateIDFromHeadQuarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import customers since mandatory column named #1 was missing.
        /// </summary>
        internal static string CouldNotImportCustomersSinceMandatory {
            get {
                return ResourceManager.GetString("CouldNotImportCustomersSinceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import retail departments since mandatory column named #1 was missing.
        /// </summary>
        internal static string CouldNotImportDepartmentsSinceMandatory {
            get {
                return ResourceManager.GetString("CouldNotImportDepartmentsSinceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import replenishment data since mandatory column named #1 was missing.
        /// </summary>
        internal static string CouldNotImportReplenishmentDataSinceMandatory {
            get {
                return ResourceManager.GetString("CouldNotImportReplenishmentDataSinceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import retail groups since mandatory column named #1 was missing.
        /// </summary>
        internal static string CouldNotImportRetailGroupsSinceMandatory {
            get {
                return ResourceManager.GetString("CouldNotImportRetailGroupsSinceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import retail items since mandatory column named #1 was missing.
        /// </summary>
        internal static string CouldNotImportRetailItemsSinceMandatory {
            get {
                return ResourceManager.GetString("CouldNotImportRetailItemsSinceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import serial number data since mandatory column named #1 was missing.
        /// </summary>
        internal static string CouldNotImportSerialNumberDataSinceMandatory {
            get {
                return ResourceManager.GetString("CouldNotImportSerialNumberDataSinceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import stock counting header data since mandatory column named #1 was missing.
        /// </summary>
        internal static string CouldNotImportStockCountingHeaderSinceMandatory {
            get {
                return ResourceManager.GetString("CouldNotImportStockCountingHeaderSinceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import stock counting lines since mandatory column named #1 was missing.
        /// </summary>
        internal static string CouldNotImportStockCountingLinesSinceMandatory {
            get {
                return ResourceManager.GetString("CouldNotImportStockCountingLinesSinceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import vendors since mandatory column named #1 was missing.
        /// </summary>
        internal static string CouldNotImportVendorsSinceMandatory {
            get {
                return ResourceManager.GetString("CouldNotImportVendorsSinceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open workbook.
        /// </summary>
        internal static string CouldNotOpenWorkbook {
            get {
                return ResourceManager.GetString("CouldNotOpenWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not write the template file at the choosen location.
        /// </summary>
        internal static string CouldNotWriteFileAtTheChoosenLocation {
            get {
                return ResourceManager.GetString("CouldNotWriteFileAtTheChoosenLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create import template.
        /// </summary>
        internal static string CreateImportTemplate {
            get {
                return ResourceManager.GetString("CreateImportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Excel import template.
        /// </summary>
        internal static string CreateNewExcelTemplate {
            get {
                return ResourceManager.GetString("CreateNewExcelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new Excel import template and saves it at location of your choice.
        /// </summary>
        internal static string CreateNewExcelTemplateDescription {
            get {
                return ResourceManager.GetString("CreateNewExcelTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Excel import template and select a location to save it.
        /// </summary>
        internal static string CreateNewExcelTemplateTooltipDescription {
            get {
                return ResourceManager.GetString("CreateNewExcelTemplateTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file.
        /// </summary>
        internal static string CSVFile {
            get {
                return ResourceManager.GetString("CSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string DashboardConfigureButton {
            get {
                return ResourceManager.GetString("DashboardConfigureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string DashboardImportButton {
            get {
                return ResourceManager.GetString("DashboardImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure a working folder to continue.
        /// </summary>
        internal static string DashboardItemConfigureWorkingFolder {
            get {
                return ResourceManager.GetString("DashboardItemConfigureWorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working folder does not exist,  Configure a working folder to continue.
        /// </summary>
        internal static string DashboardItemConfigureWorkingFolderError {
            get {
                return ResourceManager.GetString("DashboardItemConfigureWorkingFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Excel Files.
        /// </summary>
        internal static string DashboardItemInfo {
            get {
                return ResourceManager.GetString("DashboardItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define working folder before continuing..
        /// </summary>
        internal static string DefineWorkingFolderBeforeContinuing {
            get {
                return ResourceManager.GetString("DefineWorkingFolderBeforeContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously deleted vendor cannot be imported..
        /// </summary>
        internal static string DeletedVendorCannotBeImported {
            get {
                return ResourceManager.GetString("DeletedVendorCannotBeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions already defined for header item.
        /// </summary>
        internal static string DimensionsAlreadyDefined {
            get {
                return ResourceManager.GetString("DimensionsAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions and attributes can only be defined to header or variant items.
        /// </summary>
        internal static string DimensionsAndAttributesMustBeDefinedForVariants {
            get {
                return ResourceManager.GetString("DimensionsAndAttributesMustBeDefinedForVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions or attributes cannot be defined when updating items.
        /// </summary>
        internal static string DimensionsAndAttributesWhenUpdating {
            get {
                return ResourceManager.GetString("DimensionsAndAttributesWhenUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number is empty.
        /// </summary>
        internal static string EmptySerialNumber {
            get {
                return ResourceManager.GetString("EmptySerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving serial number.
        /// </summary>
        internal static string ErrorSavingSerialNumber {
            get {
                return ResourceManager.GetString("ErrorSavingSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel_template_16 {
            get {
                object obj = ResourceManager.GetObject("excel_template_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel_template_32 {
            get {
                object obj = ResourceManager.GetObject("excel_template_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel document.
        /// </summary>
        internal static string ExcelDocument {
            get {
                return ResourceManager.GetString("ExcelDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file.
        /// </summary>
        internal static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files.
        /// </summary>
        internal static string ExcelFilesPlugin {
            get {
                return ResourceManager.GetString("ExcelFilesPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel import.
        /// </summary>
        internal static string ExcelImport {
            get {
                return ResourceManager.GetString("ExcelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExcelImport16 {
            get {
                object obj = ResourceManager.GetObject("ExcelImport16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExcelNewTemplate16 {
            get {
                object obj = ResourceManager.GetObject("ExcelNewTemplate16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file.
        /// </summary>
        internal static string ExcelOrCSVFile {
            get {
                return ResourceManager.GetString("ExcelOrCSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export_16 {
            get {
                object obj = ResourceManager.GetObject("export_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap export_32 {
            get {
                object obj = ResourceManager.GetObject("export_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to display the exported file?.
        /// </summary>
        internal static string ExportedFileQuestion {
            get {
                return ResourceManager.GetString("ExportedFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to Excel simple template....
        /// </summary>
        internal static string ExportListExcelSimple {
            get {
                return ResourceManager.GetString("ExportListExcelSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to Excel template....
        /// </summary>
        internal static string ExportListToExcel {
            get {
                return ResourceManager.GetString("ExportListToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to Excel replenishment template....
        /// </summary>
        internal static string ExportListToReplenishmentExcelTemplate {
            get {
                return ResourceManager.GetString("ExportListToReplenishmentExcelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to Excel stock counting template....
        /// </summary>
        internal static string ExportListToStockCountingExcelTemplate {
            get {
                return ResourceManager.GetString("ExportListToStockCountingExcelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection to Excel simple template....
        /// </summary>
        internal static string ExportSelectionExcelSimple {
            get {
                return ResourceManager.GetString("ExportSelectionExcelSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected items to Excel template....
        /// </summary>
        internal static string ExportSelectionToExcel {
            get {
                return ResourceManager.GetString("ExportSelectionToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected items to Excel replenishment template....
        /// </summary>
        internal static string ExportSelectionToReplenishmentExcelTemplate {
            get {
                return ResourceManager.GetString("ExportSelectionToReplenishmentExcelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Excel document....
        /// </summary>
        internal static string FromExcelDocument {
            get {
                return ResourceManager.GetString("FromExcelDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General setup.
        /// </summary>
        internal static string GeneralSetup {
            get {
                return ResourceManager.GetString("GeneralSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header item for variant was not found.
        /// </summary>
        internal static string HeaderItemNotFound {
            get {
                return ResourceManager.GetString("HeaderItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap import_16 {
            get {
                object obj = ResourceManager.GetObject("import_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap import_32 {
            get {
                object obj = ResourceManager.GetObject("import_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Excel.
        /// </summary>
        internal static string ImportFromExcel {
            get {
                return ResourceManager.GetString("ImportFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from excel document.
        /// </summary>
        internal static string ImportFromExcelDocument {
            get {
                return ResourceManager.GetString("ImportFromExcelDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Excel document.
        /// </summary>
        internal static string ImportFromExcelOrCSV {
            get {
                return ResourceManager.GetString("ImportFromExcelOrCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports retail data from Excel document.
        /// </summary>
        internal static string ImportFromExcelOrCSVDescription {
            get {
                return ResourceManager.GetString("ImportFromExcelOrCSVDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import items, groups, departments, customer and/or vendors from an Excel document.
        /// </summary>
        internal static string ImportFromExcelOrCSVTooltipDescription {
            get {
                return ResourceManager.GetString("ImportFromExcelOrCSVTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously deleted items can not be imported .
        /// </summary>
        internal static string ImportPreviousItemDeleted {
            get {
                return ResourceManager.GetString("ImportPreviousItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import results.
        /// </summary>
        internal static string ImportResults {
            get {
                return ResourceManager.GetString("ImportResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in column #1.
        /// </summary>
        internal static string InvalidValueInColumn {
            get {
                return ResourceManager.GetString("InvalidValueInColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory unit not found.
        /// </summary>
        internal static string InventoryUnitNotFound {
            get {
                return ResourceManager.GetString("InventoryUnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item #1 is deleted.
        /// </summary>
        internal static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item replenishment.
        /// </summary>
        internal static string ItemReplenishment {
            get {
                return ResourceManager.GetString("ItemReplenishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory column missing:.
        /// </summary>
        internal static string MandatoryColumnmissing {
            get {
                return ResourceManager.GetString("MandatoryColumnmissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field #1 missing.
        /// </summary>
        internal static string MandatoryFieldMissing {
            get {
                return ResourceManager.GetString("MandatoryFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel document.
        /// </summary>
        internal static string NewExcelDocumentCaption {
            get {
                return ResourceManager.GetString("NewExcelDocumentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to display the excel template file.
        /// </summary>
        internal static string NewExcelDocumentQuestion {
            get {
                return ResourceManager.GetString("NewExcelDocumentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Excel template.
        /// </summary>
        internal static string NewExcelTemplate {
            get {
                return ResourceManager.GetString("NewExcelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records inserted.
        /// </summary>
        internal static string NoRecordsInserted {
            get {
                return ResourceManager.GetString("NoRecordsInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records skipped.
        /// </summary>
        internal static string NoRecordsSkipped {
            get {
                return ResourceManager.GetString("NoRecordsSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records updated.
        /// </summary>
        internal static string NoRecordsUpdated {
            get {
                return ResourceManager.GetString("NoRecordsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock does not exist for header items.
        /// </summary>
        internal static string NoStockForHeaderItems {
            get {
                return ResourceManager.GetString("NoStockForHeaderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record: #1.
        /// </summary>
        internal static string Record1 {
            get {
                return ResourceManager.GetString("Record1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped #1 record(s).
        /// </summary>
        internal static string RecordsSkippedNotificationMessage {
            get {
                return ResourceManager.GetString("RecordsSkippedNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail department.
        /// </summary>
        internal static string RetailDepartment {
            get {
                return ResourceManager.GetString("RetailDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail groups.
        /// </summary>
        internal static string RetailGroups {
            get {
                return ResourceManager.GetString("RetailGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail item does not exist.
        /// </summary>
        internal static string RetailItemDoesNotExist {
            get {
                return ResourceManager.GetString("RetailItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail items.
        /// </summary>
        internal static string RetailItems {
            get {
                return ResourceManager.GetString("RetailItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving data from file....
        /// </summary>
        internal static string RetrievingDataFromFile {
            get {
                return ResourceManager.GetString("RetrievingDataFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales unit not found.
        /// </summary>
        internal static string SalesUnitNotFound {
            get {
                return ResourceManager.GetString("SalesUnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected retail group is not in the selected retail department.
        /// </summary>
        internal static string SelectedRetailGroupDoesNotExist {
            get {
                return ResourceManager.GetString("SelectedRetailGroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator cannot be empty.
        /// </summary>
        internal static string SeparatorCannotBeEmpty {
            get {
                return ResourceManager.GetString("SeparatorCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial numbers.
        /// </summary>
        internal static string SerialNumbersListViewHeader {
            get {
                return ResourceManager.GetString("SerialNumbersListViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number template.
        /// </summary>
        internal static string SerialNumberTemplate {
            get {
                return ResourceManager.GetString("SerialNumberTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock counting header.
        /// </summary>
        internal static string StockCountingHeader {
            get {
                return ResourceManager.GetString("StockCountingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock counting line.
        /// </summary>
        internal static string StockCountingLine {
            get {
                return ResourceManager.GetString("StockCountingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import deleted items..
        /// </summary>
        internal static string StockCountingLineItemDeleted {
            get {
                return ResourceManager.GetString("StockCountingLineItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import service items..
        /// </summary>
        internal static string StockCountingLineServiceItem {
            get {
                return ResourceManager.GetString("StockCountingLineServiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock count does not exist.
        /// </summary>
        internal static string StockCountNotExist {
            get {
                return ResourceManager.GetString("StockCountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not exist.
        /// </summary>
        internal static string StoreDoesNotExist {
            get {
                return ResourceManager.GetString("StoreDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted #1 record(s).
        /// </summary>
        internal static string SuccessfullyInserted {
            get {
                return ResourceManager.GetString("SuccessfullyInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated #1 record(s).
        /// </summary>
        internal static string SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SystemImage {
            get {
                object obj = ResourceManager.GetObject("SystemImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SystemImage24 {
            get {
                object obj = ResourceManager.GetObject("SystemImage24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TableImport16 {
            get {
                object obj = ResourceManager.GetObject("TableImport16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax group does not exist, please set it up and then try importing again.
        /// </summary>
        internal static string TaxGroupDoesNotExist {
            get {
                return ResourceManager.GetString("TaxGroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax group not found.
        /// </summary>
        internal static string TaxGroupNotFound {
            get {
                return ResourceManager.GetString("TaxGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested file was not found.
        /// </summary>
        internal static string TheRequestedFileWasNotFound {
            get {
                return ResourceManager.GetString("TheRequestedFileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit conversion rule from inventory unit to bar code unit does not exist.
        /// </summary>
        internal static string UnitConversionRuleFromBarCodeToInventoryUnitDoesNotExist {
            get {
                return ResourceManager.GetString("UnitConversionRuleFromBarCodeToInventoryUnitDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit conversion rule from inventory unit to sales unit does not exist.
        /// </summary>
        internal static string UnitConversionRuleFromInventoryToSalesDoesNotExist {
            get {
                return ResourceManager.GetString("UnitConversionRuleFromInventoryToSalesDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred. Error details:.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor does not exist. Please correct the problem and try importing again.
        /// </summary>
        internal static string VendorDoesNotExits {
            get {
                return ResourceManager.GetString("VendorDoesNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        internal static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When blocking is active then blocking date must be set.
        /// </summary>
        internal static string WhenBlockedIsActiveThenBlockingDateMustBeSet {
            get {
                return ResourceManager.GetString("WhenBlockedIsActiveThenBlockingDateMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working folder.
        /// </summary>
        internal static string WorkingFolder {
            get {
                return ResourceManager.GetString("WorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working folder not defined..
        /// </summary>
        internal static string WorkingFolderNotDefined {
            get {
                return ResourceManager.GetString("WorkingFolderNotDefined", resourceCulture);
            }
        }
    }
}
