//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrowdownthin_32px {
            get {
                object obj = ResourceManager.GetObject("Arrowdownthin_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrowupthin_32px {
            get {
                object obj = ResourceManager.GetObject("Arrowupthin_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is linked to a Tax Refund.
        /// Make sure that the customer has the tax refund form..
        /// </summary>
        internal static string AskForForm {
            get {
                return ResourceManager.GetString("AskForForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Country Code Missing.
        /// </summary>
        internal static string BCErrCountryCode {
            get {
                return ResourceManager.GetString("BCErrCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Form Type Missing.
        /// </summary>
        internal static string BCErrFormType {
            get {
                return ResourceManager.GetString("BCErrFormType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Tax Free Info missing.
        /// </summary>
        internal static string BCErrTaxFreeInfo {
            get {
                return ResourceManager.GetString("BCErrTaxFreeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Tax Number Missing.
        /// </summary>
        internal static string BCErrTaxNr {
            get {
                return ResourceManager.GetString("BCErrTaxNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Tax Numer must be 5 chars.
        /// </summary>
        internal static string BCErrTaxNrLen {
            get {
                return ResourceManager.GetString("BCErrTaxNrLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Terminal Id Missing.
        /// </summary>
        internal static string BCErrTerm {
            get {
                return ResourceManager.GetString("BCErrTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking number is required.
        /// </summary>
        internal static string BookingNumberRequried {
            get {
                return ResourceManager.GetString("BookingNumberRequried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK when ready..
        /// </summary>
        internal static string ClickOKWhenReady {
            get {
                return ResourceManager.GetString("ClickOKWhenReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogMessage_48 {
            get {
                object obj = ResourceManager.GetObject("DialogMessage_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap double_arrow_down_16 {
            get {
                object obj = ResourceManager.GetObject("double_arrow_down_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap double_arrow_up_16 {
            get {
                object obj = ResourceManager.GetObject("double_arrow_up_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Doublearrowdownthin_32px {
            get {
                object obj = ResourceManager.GetObject("Doublearrowdownthin_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Doublearrowupthin_32px {
            get {
                object obj = ResourceManager.GetObject("Doublearrowupthin_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownArrow {
            get {
                object obj = ResourceManager.GetObject("DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the tax refund?.
        /// </summary>
        internal static string DoYouWantToCancelTaxRefund {
            get {
                return ResourceManager.GetString("DoYouWantToCancelTaxRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIGHT.
        /// </summary>
        internal static string EIGHT {
            get {
                return ResourceManager.GetString("EIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a comment.
        /// </summary>
        internal static string EnterAComment {
            get {
                return ResourceManager.GetString("EnterAComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIVE.
        /// </summary>
        internal static string FIVE {
            get {
                return ResourceManager.GetString("FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date must be after arrival date.
        /// </summary>
        internal static string FlightDatesError {
            get {
                return ResourceManager.GetString("FlightDatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOUR.
        /// </summary>
        internal static string FOUR {
            get {
                return ResourceManager.GetString("FOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality is required.
        /// </summary>
        internal static string NationalityIsRequired {
            get {
                return ResourceManager.GetString("NationalityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINE.
        /// </summary>
        internal static string NINE {
            get {
                return ResourceManager.GetString("NINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers already used.
        /// </summary>
        internal static string NumbersUsed {
            get {
                return ResourceManager.GetString("NumbersUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE.
        /// </summary>
        internal static string ONE {
            get {
                return ResourceManager.GetString("ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax can only be returned on transactions from today.
        /// </summary>
        internal static string OnlyTodaysTransaction {
            get {
                return ResourceManager.GetString("OnlyTodaysTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin fee.
        /// </summary>
        internal static string OPOS_AdminFee {
            get {
                return ResourceManager.GetString("OPOS_AdminFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string OPOS_Amount {
            get {
                return ResourceManager.GetString("OPOS_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Address:.
        /// </summary>
        internal static string OPOS_CustAddr {
            get {
                return ResourceManager.GetString("OPOS_CustAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string OPOS_CustCountry {
            get {
                return ResourceManager.GetString("OPOS_CustCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string OPOS_CustEmail {
            get {
                return ResourceManager.GetString("OPOS_CustEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Details &amp; Declaration.
        /// </summary>
        internal static string OPOS_CustHead {
            get {
                return ResourceManager.GetString("OPOS_CustHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details:.
        /// </summary>
        internal static string OPOS_CustInfo {
            get {
                return ResourceManager.GetString("OPOS_CustInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued by the government of:.
        /// </summary>
        internal static string OPOS_CustIssue {
            get {
                return ResourceManager.GetString("OPOS_CustIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I declare that: I do not have a permanent.
        /// </summary>
        internal static string OPOS_CustLine1 {
            get {
                return ResourceManager.GetString("OPOS_CustLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address in Iceland. I intend to export the goods.
        /// </summary>
        internal static string OPOS_CustLine2 {
            get {
                return ResourceManager.GetString("OPOS_CustLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listed on this form from Iceland within three.
        /// </summary>
        internal static string OPOS_CustLine3 {
            get {
                return ResourceManager.GetString("OPOS_CustLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months from purchase date..
        /// </summary>
        internal static string OPOS_CustLine4 {
            get {
                return ResourceManager.GetString("OPOS_CustLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand that when I present this form to.
        /// </summary>
        internal static string OPOS_CustLine5 {
            get {
                return ResourceManager.GetString("OPOS_CustLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customs, I am declaring that I am exporting all of.
        /// </summary>
        internal static string OPOS_CustLine6 {
            get {
                return ResourceManager.GetString("OPOS_CustLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the good (listed) on this form from Iceland.
        /// </summary>
        internal static string OPOS_CustLine7 {
            get {
                return ResourceManager.GetString("OPOS_CustLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before I present  this form to Customs.
        /// </summary>
        internal static string OPOS_CustLine8 {
            get {
                return ResourceManager.GetString("OPOS_CustLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information on this form is correct..
        /// </summary>
        internal static string OPOS_CustLine9 {
            get {
                return ResourceManager.GetString("OPOS_CustLine9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in Full:.
        /// </summary>
        internal static string OPOS_CustName {
            get {
                return ResourceManager.GetString("OPOS_CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport or ID Number:.
        /// </summary>
        internal static string OPOS_CustPassport {
            get {
                return ResourceManager.GetString("OPOS_CustPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code:.
        /// </summary>
        internal static string OPOS_CustPost {
            get {
                return ResourceManager.GetString("OPOS_CustPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Sign Here.
        /// </summary>
        internal static string OPOS_CustSign {
            get {
                return ResourceManager.GetString("OPOS_CustSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of sale:.
        /// </summary>
        internal static string OPOS_Date {
            get {
                return ResourceManager.GetString("OPOS_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string OPOS_Description {
            get {
                return ResourceManager.GetString("OPOS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to donate to charity (mark X).
        /// </summary>
        internal static string OPOS_DonateCharity {
            get {
                return ResourceManager.GetString("OPOS_DonateCharity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide credit card number:.
        /// </summary>
        internal static string OPOS_PleaseProvideCCNumber {
            get {
                return ResourceManager.GetString("OPOS_PleaseProvideCCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price excl. VAT.
        /// </summary>
        internal static string OPOS_PriceExclVAT {
            get {
                return ResourceManager.GetString("OPOS_PriceExclVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price incl. VAT.
        /// </summary>
        internal static string OPOS_PriceInclVAT {
            get {
                return ResourceManager.GetString("OPOS_PriceInclVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string OPOS_Qty {
            get {
                return ResourceManager.GetString("OPOS_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund amount.
        /// </summary>
        internal static string OPOS_Refund {
            get {
                return ResourceManager.GetString("OPOS_Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer Declaration.
        /// </summary>
        internal static string OPOS_RetailerDeclarationHeader {
            get {
                return ResourceManager.GetString("OPOS_RetailerDeclarationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I declare that the details of this form are correct.
        /// </summary>
        internal static string OPOS_RetailLine1 {
            get {
                return ResourceManager.GetString("OPOS_RetailLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and that I am satisfied that the customer has.
        /// </summary>
        internal static string OPOS_RetailLine2 {
            get {
                return ResourceManager.GetString("OPOS_RetailLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed and signed the form and that the.
        /// </summary>
        internal static string OPOS_RetailLine3 {
            get {
                return ResourceManager.GetString("OPOS_RetailLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer detailed on this form is entitled to use.
        /// </summary>
        internal static string OPOS_RetailLine4 {
            get {
                return ResourceManager.GetString("OPOS_RetailLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the VAT retail export scheme..
        /// </summary>
        internal static string OPOS_RetailLine5 {
            get {
                return ResourceManager.GetString("OPOS_RetailLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer’s Signature.
        /// </summary>
        internal static string OPOS_RetailSign {
            get {
                return ResourceManager.GetString("OPOS_RetailSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods according to sales receipt.
        /// </summary>
        internal static string OPOS_SalesReceipt {
            get {
                return ResourceManager.GetString("OPOS_SalesReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMS STAMP:.
        /// </summary>
        internal static string OPOS_Stamp {
            get {
                return ResourceManager.GetString("OPOS_Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string OPOS_Time {
            get {
                return ResourceManager.GetString("OPOS_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string OPOS_VAT {
            get {
                return ResourceManager.GetString("OPOS_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS IS A VAT FORM ISSUED BY.
        /// </summary>
        internal static string OPOS_VatFormIssued {
            get {
                return ResourceManager.GetString("OPOS_VatFormIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT No:.
        /// </summary>
        internal static string OPOS_VatNo {
            get {
                return ResourceManager.GetString("OPOS_VatNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PageDownArrow {
            get {
                object obj = ResourceManager.GetObject("PageDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PageUpArrow {
            get {
                object obj = ResourceManager.GetObject("PageUpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue date is required.
        /// </summary>
        internal static string PassportIssueDateRequired {
            get {
                return ResourceManager.GetString("PassportIssueDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued by is required.
        /// </summary>
        internal static string PassportIssuedByRequired {
            get {
                return ResourceManager.GetString("PassportIssuedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number is required.
        /// </summary>
        internal static string PassportRequired {
            get {
                return ResourceManager.GetString("PassportRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare the next page..
        /// </summary>
        internal static string PrepareTheNextPage {
            get {
                return ResourceManager.GetString("PrepareTheNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund has already been canceled.
        /// </summary>
        internal static string RefundHasAlreadyBeenCanceled {
            get {
                return ResourceManager.GetString("RefundHasAlreadyBeenCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No refund range was found for this amount.
        /// </summary>
        internal static string RefundRangeNotFound {
            get {
                return ResourceManager.GetString("RefundRangeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running number is required.
        /// </summary>
        internal static string RunningNumberRequired {
            get {
                return ResourceManager.GetString("RunningNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running number has already been used for this booking number.
        /// </summary>
        internal static string RunningNumberUsed {
            get {
                return ResourceManager.GetString("RunningNumberUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running number has already been used for this booking number. Do you want to delete the previous report?.
        /// </summary>
        internal static string RunningNumberUsedDialog {
            get {
                return ResourceManager.GetString("RunningNumberUsedDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select person.
        /// </summary>
        internal static string SelectPerson {
            get {
                return ResourceManager.GetString("SelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a printer.
        /// </summary>
        internal static string SelectPrinter {
            get {
                return ResourceManager.GetString("SelectPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEVEN.
        /// </summary>
        internal static string SEVEN {
            get {
                return ResourceManager.GetString("SEVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap single_arrow_down_16 {
            get {
                object obj = ResourceManager.GetObject("single_arrow_down_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap single_arrow_up_16 {
            get {
                object obj = ResourceManager.GetObject("single_arrow_up_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIX.
        /// </summary>
        internal static string SIX {
            get {
                return ResourceManager.GetString("SIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax refund.
        /// </summary>
        internal static string TaxRefund {
            get {
                return ResourceManager.GetString("TaxRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax refund found but was unable to load it..
        /// </summary>
        internal static string TaxRefundLoadError {
            get {
                return ResourceManager.GetString("TaxRefundLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THREE.
        /// </summary>
        internal static string THREE {
            get {
                return ResourceManager.GetString("THREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax refund report has already been created for the selected transaction. Do you want to cancel the previous report?.
        /// </summary>
        internal static string TransactionAlreadyRefunded {
            get {
                return ResourceManager.GetString("TransactionAlreadyRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has already been added..
        /// </summary>
        internal static string TransactionBeenAdded {
            get {
                return ResourceManager.GetString("TransactionBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction contains returns or items have been returned from the transaction.
        /// </summary>
        internal static string TransactionHasBeenReturnedOrContainsReturns {
            get {
                return ResourceManager.GetString("TransactionHasBeenReturnedOrContainsReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction refunded.
        /// </summary>
        internal static string TransactionRefunded {
            get {
                return ResourceManager.GetString("TransactionRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWO.
        /// </summary>
        internal static string TWO {
            get {
                return ResourceManager.GetString("TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whitesearch32px {
            get {
                object obj = ResourceManager.GetObject("Whitesearch32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZERO.
        /// </summary>
        internal static string ZERO {
            get {
                return ResourceManager.GetString("ZERO", resourceCulture);
            }
        }
    }
}
