
/*
Added description for KDS printers. 
*/
USE LSPOSNET
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSTRANSACTIONSERVICEPROFILE' AND COLUMN_NAME = 'CENTRALTABLESERVER' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
alter TABLE POSTRANSACTIONSERVICEPROFILE alter column CENTRALTABLESERVER nvarchar(50) NOT NULL 
	
END