
/*
	Table added for Kitchen printing via KDS
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KITCHENDISPLAYPRINTER')
BEGIN
	CREATE TABLE KITCHENDISPLAYPRINTER(
	ID nvarchar(20) NOT NULL,
	PRINTERHOSTID nvarchar(20) NOT NULL,
	PRINTERNAME nvarchar(100) NOT NULL,
	USEEXTERNALROUTING tinyint NOT NULL,
	VISUALPROFILEID uniqueidentifier NOT NULL,
	DATAAREAID nvarchar(4) NOT NULL,
	CONSTRAINT [PK_KITCHENDISPLAYPRINTER] PRIMARY KEY CLUSTERED 
	(
		ID ASC,
		DATAAREAID ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

