
/*
Added support for playing sound on Display station when a new order arrives
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILE' AND COLUMN_NAME = 'SOUNDONNEWORDER')
BEGIN
	ALTER TABLE KITCHENDISPLAYFUNCTIONALPROFILE ADD SOUNDONNEWORDER BIT NOT NULL DEFAULT 0
END