
/*
	Incident No.	: N/A
	Responsible		: Höður Sigurdór Heiðarsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 17.02.2014

	Description		: New tables needed fo mobile app discounts (coupons)
					  DEFAULTLOYALTYSCHEME/POINTS added to site service profile
*/
USE LSPOSNET
GO


IF NOT EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 1700)
BEGIN
  INSERT INTO POSISOPERATIONS ( OPERATIONID, OPERATIONNAME, PERMISSIONID, PERMISSIONID2, CHECKUSERACCESS, USEROPERATION,DATAAREAID,LOOKUPTYPE)
  VALUES (1700, 'Scan QR',	NULL,	NULL,	1,	0,'LSR',0)
END
GO


IF NOT EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 306)
BEGIN
  INSERT INTO POSISOPERATIONS ( OPERATIONID, OPERATIONNAME, PERMISSIONID, PERMISSIONID2, CHECKUSERACCESS, USEROPERATION,DATAAREAID,LOOKUPTYPE)
  VALUES (306, 'Clear coupon',	NULL,	NULL,	1,	1,'LSR',0)
END
GO


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'OMNICUSTOMER')
BEGIN
	CREATE TABLE [dbo].[OMNICUSTOMER](
	CUSTOMERID nvarchar(20) NOT NULL,
	USERNAME nvarchar(40) NOT NULL,
	PASSWORD nvarchar(40),
	DATAAREAID nvarchar(4) NOT NULL,
	CONSTRAINT [PK_OMNICUSTOMER] PRIMARY KEY CLUSTERED 
	(
		CUSTOMERID ASC,
		DATAAREAID ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'COUPONTABLE')
BEGIN
	CREATE TABLE [dbo].[COUPONTABLE](
	[COUPONID] [nvarchar](20) NOT NULL,
	[TXT] [nvarchar](60) NOT NULL,
	[PERCENTVALUE] [numeric](28, 12) NULL,
	[DISCVALIDPERIODID] [nvarchar](20) NULL,
	[MAXUSAGES] [int] NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[IMAGE] [varbinary](max) NULL,
	[GIVETONEW] [bit] NULL,
	[DETAILS] [nvarchar](256) NULL,
 CONSTRAINT [PK_COUPONTABLE] PRIMARY KEY CLUSTERED 
(
	[COUPONID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTLOYALTYPARAMETERS' AND COLUMN_NAME = 'OMNILOYALTYSCHEME')
BEGIN
	ALTER TABLE CUSTLOYALTYPARAMETERS ADD OMNILOYALTYSCHEME nvarchar(20)
	ALTER TABLE CUSTLOYALTYPARAMETERS ADD OMNILOYALTYPOINTS int
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'COUPONCUSTOMERLINK')
BEGIN
	CREATE TABLE [dbo].[COUPONCUSTOMERLINK](
	COUPONID nvarchar(20) NOT NULL,
	CUSTOMERID nvarchar(20) NOT NULL,
	USAGES int,
	DATAAREAID nvarchar(4) NOT NULL,
	CONSTRAINT [PK_COUPONCUSTOMERLINK] PRIMARY KEY CLUSTERED 
	(
		COUPONID ASC,
		CUSTOMERID ASC,
		DATAAREAID ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOLOYALTYMSRCARDTABLE' AND COLUMN_NAME = 'MOBILECARD')
BEGIN
	ALTER TABLE RBOLOYALTYMSRCARDTABLE ADD MOBILECARD int default 0
END
GO


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'COUPONITEMS')
BEGIN
	CREATE TABLE [dbo].[COUPONITEMS](
		[COUPONID] [nvarchar](20) NOT NULL,
		[ITEMRELATION] [nvarchar](20) NOT NULL,
		[ITEMQUANTITY] [int] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[TYPE] [tinyint] NOT NULL DEFAULT ((0)),
	 CONSTRAINT [PK_COUPONITEMS] PRIMARY KEY CLUSTERED 
	(
		[COUPONID] ASC,
		[ITEMRELATION] ASC,
		[TYPE] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]	
END
GO
