/*

	Incident No.	: ONE-1856
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Klósigar
	Date created	: 15.5.2015

	Description		: Add z report settings for customer deposit information
	
	
	Tables affected	: POSFUNCTIONALITYPROFILE
						
*/
USE LSPOSNET
GO
  
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTDISPLAYDEPOSITINFO')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTDISPLAYDEPOSITINFO TINYINT DEFAULT 1
END	
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTDEPOSITORDERBY')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTDEPOSITORDERBY INT DEFAULT 0
END	
GO
