//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.ViewPlugins.GiftCards.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.ViewPlugins.GiftCards.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to gift card....
        /// </summary>
        internal static string AddToGiftCard {
            get {
                return ResourceManager.GetString("AddToGiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By changing the sequence start you are defining a new starting point for the number sequence..
        /// </summary>
        internal static string ChangingNumberSequenceStartingPoint {
            get {
                return ResourceManager.GetString("ChangingNumberSequenceStartingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Site Service.
        /// </summary>
        internal static string CouldNotConnectToStoreServer {
            get {
                return ResourceManager.GetString("CouldNotConnectToStoreServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current sequence start is {0}, witch is higher than your selected sequence start of {1}..
        /// </summary>
        internal static string CurrentSequenceHigher {
            get {
                return ResourceManager.GetString("CurrentSequenceHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete gift card.
        /// </summary>
        internal static string DeleteGiftCard {
            get {
                return ResourceManager.GetString("DeleteGiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected gift card?.
        /// </summary>
        internal static string DeleteGiftCardQuestion {
            get {
                return ResourceManager.GetString("DeleteGiftCardQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete gift cards.
        /// </summary>
        internal static string DeleteGiftCards {
            get {
                return ResourceManager.GetString("DeleteGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected gift cards?.
        /// </summary>
        internal static string DeleteGiftCardsQuestion {
            get {
                return ResourceManager.GetString("DeleteGiftCardsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount to add to the selected gift card.
        /// </summary>
        internal static string EnterAmountToAddToGiftCard {
            get {
                return ResourceManager.GetString("EnterAmountToAddToGiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gift_cards_16 {
            get {
                object obj = ResourceManager.GetObject("gift_cards_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gift_cards_32 {
            get {
                object obj = ResourceManager.GetObject("gift_cards_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift card.
        /// </summary>
        internal static string GiftCard {
            get {
                return ResourceManager.GetString("GiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GiftCard16 {
            get {
                object obj = ResourceManager.GetObject("GiftCard16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GiftCard32 {
            get {
                object obj = ResourceManager.GetObject("GiftCard32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This gift card number already exists and cannot be used again.
        /// </summary>
        internal static string GiftCardAlreadyExists {
            get {
                return ResourceManager.GetString("GiftCardAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift cards / Credit memos.
        /// </summary>
        internal static string GiftcardCreditMemo {
            get {
                return ResourceManager.GetString("GiftcardCreditMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift card ID.
        /// </summary>
        internal static string GiftCardID {
            get {
                return ResourceManager.GetString("GiftCardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift cards.
        /// </summary>
        internal static string GiftCards {
            get {
                return ResourceManager.GetString("GiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to search for and view gift cards.
        /// </summary>
        internal static string GiftCardsDescription {
            get {
                return ResourceManager.GetString("GiftCardsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings up a menu with gift card operations.
        /// </summary>
        internal static string GiftCardsOperationDescription {
            get {
                return ResourceManager.GetString("GiftCardsOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new and view existing gift cards.
        /// </summary>
        internal static string GiftCardsTooltipDescription {
            get {
                return ResourceManager.GetString("GiftCardsTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last used date.
        /// </summary>
        internal static string LastUsedDate {
            get {
                return ResourceManager.GetString("LastUsedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New gift card(s).
        /// </summary>
        internal static string NewGiftCards {
            get {
                return ResourceManager.GetString("NewGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to create new gift card(s).
        /// </summary>
        internal static string NewGiftCardsDescription {
            get {
                return ResourceManager.GetString("NewGiftCardsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New gift card with number.
        /// </summary>
        internal static string NewGiftCardWithID {
            get {
                return ResourceManager.GetString("NewGiftCardWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Service has not been configured yet.
        /// </summary>
        internal static string NoStoreServerIsSetUp {
            get {
                return ResourceManager.GetString("NoStoreServerIsSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not empty.
        /// </summary>
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refillable.
        /// </summary>
        internal static string Refillable {
            get {
                return ResourceManager.GetString("Refillable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        internal static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a higher sequence start..
        /// </summary>
        internal static string SelectHigherSequenceStart {
            get {
                return ResourceManager.GetString("SelectHigherSequenceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequense starting point can not be set lower than the current starting point..
        /// </summary>
        internal static string StartingPointCanNotBeLower {
            get {
                return ResourceManager.GetString("StartingPointCanNotBeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View gift cards.
        /// </summary>
        internal static string ViewGiftCards {
            get {
                return ResourceManager.GetString("ViewGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View POS user.
        /// </summary>
        internal static string ViewPOSUser {
            get {
                return ResourceManager.GetString("ViewPOSUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View store.
        /// </summary>
        internal static string ViewStore {
            get {
                return ResourceManager.GetString("ViewStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View terminal.
        /// </summary>
        internal static string ViewTerminal {
            get {
                return ResourceManager.GetString("ViewTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View user.
        /// </summary>
        internal static string ViewUser {
            get {
                return ResourceManager.GetString("ViewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers.
        /// </summary>
        internal static string Vouchers {
            get {
                return ResourceManager.GetString("Vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
