//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add payment.
        /// </summary>
        internal static string AdditionalPayment {
            get {
                return ResourceManager.GetString("AdditionalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The additional payment cannot be higher than the balance of the customer order.
        /// </summary>
        internal static string AdditionalPaymentCannotBeHigherThanBalance {
            get {
                return ResourceManager.GetString("AdditionalPaymentCannotBeHigherThanBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes have been reverted.
        /// </summary>
        internal static string AllChangesHaveBeenReverted {
            get {
                return ResourceManager.GetString("AllChangesHaveBeenReverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to move all available quantity to be picked up?.
        /// </summary>
        internal static string AllItemsOnOrderSetToPickUp {
            get {
                return ResourceManager.GetString("AllItemsOnOrderSetToPickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items on the selected orders will be marked as fully received..
        /// </summary>
        internal static string AllItemsWillBeMarkedAsFullyReceived {
            get {
                return ResourceManager.GetString("AllItemsWillBeMarkedAsFullyReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An additional payment cannot be added when picking up items.
        /// </summary>
        internal static string AnAdditionalPaymentCannotBeAddedWhenPickingUpItems {
            get {
                return ResourceManager.GetString("AnAdditionalPaymentCannotBeAddedWhenPickingUpItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item on a customer order cannot be unvoided please add it again to the sale.
        /// </summary>
        internal static string AnItemOnCustomerOrderCannotBeUnvoidedPleaseAddItAgain {
            get {
                return ResourceManager.GetString("AnItemOnCustomerOrderCannotBeUnvoidedPleaseAddItAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the #1.
        /// </summary>
        internal static string AreYouSureCancelCustomerOrder {
            get {
                return ResourceManager.GetString("AreYouSureCancelCustomerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the quote.
        /// </summary>
        internal static string CancelQuote {
            get {
                return ResourceManager.GetString("CancelQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the delivery location will move the stock reservation from the current location to the new one..
        /// </summary>
        internal static string ChangingDeliveryLocationWillMoveStockReservation {
            get {
                return ResourceManager.GetString("ChangingDeliveryLocationWillMoveStockReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search.
        /// </summary>
        internal static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deposit of #1 is remaining. Please click any payment button to pay the deposit back.
        /// </summary>
        internal static string ClickAPaymentButtonToGetDeposit {
            get {
                return ResourceManager.GetString("ClickAPaymentButtonToGetDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to payment.
        /// </summary>
        internal static string ContinueToPayment {
            get {
                return ResourceManager.GetString("ContinueToPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sale.
        /// </summary>
        internal static string CreateSale {
            get {
                return ResourceManager.GetString("CreateSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap current_location_32px {
            get {
                object obj = ResourceManager.GetObject("current_location_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer information on order and sale are not the same..
        /// </summary>
        internal static string CustomerInformationOnSaleOrderNotTheSame {
            get {
                return ResourceManager.GetString("CustomerInformationOnSaleOrderNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer on order (#1) is not the same as the one on the sale (#2)..
        /// </summary>
        internal static string CustomerOnOrderIsNotSameAsOnTransaction {
            get {
                return ResourceManager.GetString("CustomerOnOrderIsNotSameAsOnTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer order changes cancelled..
        /// </summary>
        internal static string CustomerOrderCancelled {
            get {
                return ResourceManager.GetString("CustomerOrderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer order cannot be changed to a quote.
        /// </summary>
        internal static string CustomerOrderCannotBeChangedToAQuote {
            get {
                return ResourceManager.GetString("CustomerOrderCannotBeChangedToAQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer order with reference #1 has been created.
        /// </summary>
        internal static string CustomerOrderCreated {
            get {
                return ResourceManager.GetString("CustomerOrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer order details.
        /// </summary>
        internal static string CustomerOrderHeaderText {
            get {
                return ResourceManager.GetString("CustomerOrderHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer order.
        /// </summary>
        internal static string CustomerOrderLowCase {
            get {
                return ResourceManager.GetString("CustomerOrderLowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer order.
        /// </summary>
        internal static string CustomerOrderMixCase {
            get {
                return ResourceManager.GetString("CustomerOrderMixCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer order with reference #1 has been updated.
        /// </summary>
        internal static string CustomerOrderUpdated {
            get {
                return ResourceManager.GetString("CustomerOrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer order cannot be voided because an additional payment needs to be paid.
        /// </summary>
        internal static string CustomerOrderWithAdditionalPaymentsCannotBeVoided {
            get {
                return ResourceManager.GetString("CustomerOrderWithAdditionalPaymentsCannotBeVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a delivery location.
        /// </summary>
        internal static string DeliveryLocationMustBeSelected {
            get {
                return ResourceManager.GetString("DeliveryLocationMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery method has not been selected.
        /// </summary>
        internal static string DeliveryMethodHasNotBeenSelected {
            get {
                return ResourceManager.GetString("DeliveryMethodHasNotBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit for.
        /// </summary>
        internal static string DepositFor {
            get {
                return ResourceManager.GetString("DepositFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before this operation is run a deposit tender has to be configured for this store..
        /// </summary>
        internal static string DepositTenderNotConfiguredOnStore {
            get {
                return ResourceManager.GetString("DepositTenderNotConfiguredOnStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit to keep.
        /// </summary>
        internal static string DepositToKeep {
            get {
                return ResourceManager.GetString("DepositToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deposit for the voided item (#1) will be distributed to the other items on this order.
        /// </summary>
        internal static string DepositWillBeDistributedToOtherItems {
            get {
                return ResourceManager.GetString("DepositWillBeDistributedToOtherItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deposit for the voided item (#1) will be used to finish payment for the other items on this order.
        /// </summary>
        internal static string DepositWillBeUsedToPayUpOtherItems {
            get {
                return ResourceManager.GetString("DepositWillBeUsedToPayUpOtherItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogMessage_48 {
            get {
                object obj = ResourceManager.GetObject("DialogMessage_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change it to a normal sale?.
        /// </summary>
        internal static string DoYouWantToChangeToNormalSale {
            get {
                return ResourceManager.GetString("DoYouWantToChangeToNormalSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the sale to use the customer on the order?.
        /// </summary>
        internal static string DoYouWantToUpdateCustomerOnSale {
            get {
                return ResourceManager.GetString("DoYouWantToUpdateCustomerOnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_24px {
            get {
                object obj = ResourceManager.GetObject("Edit_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit details.
        /// </summary>
        internal static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift certificates cannot be on a customer order.
        /// </summary>
        internal static string GiftCertificatesAreNotAllowedOnCustomerOrder {
            get {
                return ResourceManager.GetString("GiftCertificatesAreNotAllowedOnCustomerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift certificates cannot be on a quotes.
        /// </summary>
        internal static string GiftCertificatesAreNotAllowedOnQuotes {
            get {
                return ResourceManager.GetString("GiftCertificatesAreNotAllowedOnQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income account or expense account items cannot be on a customer order.
        /// </summary>
        internal static string IncomeAccountNotAllowedOnCustomerOrder {
            get {
                return ResourceManager.GetString("IncomeAccountNotAllowedOnCustomerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income account or expense account items cannot be on a quote.
        /// </summary>
        internal static string IncomeAccountNotAllowedOnQuote {
            get {
                return ResourceManager.GetString("IncomeAccountNotAllowedOnQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has linked items, please void those first before voiding this item.
        /// </summary>
        internal static string ItemHasLinkedItemsCannotBeVoided {
            get {
                return ResourceManager.GetString("ItemHasLinkedItemsCannotBeVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items cannot be picked up when adding a payment.
        /// </summary>
        internal static string ItemsCannotBePickedUpWhenAddingAPayment {
            get {
                return ResourceManager.GetString("ItemsCannotBePickedUpWhenAddingAPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items on a quote cannot be picked up.
        /// </summary>
        internal static string ItemsOnAQuoteCannotBePickedUp {
            get {
                return ResourceManager.GetString("ItemsOnAQuoteCannotBePickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum deposit.
        /// </summary>
        internal static string MinimumDeposit {
            get {
                return ResourceManager.GetString("MinimumDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi selection.
        /// </summary>
        internal static string MultiSelection {
            get {
                return ResourceManager.GetString("MultiSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My location.
        /// </summary>
        internal static string MyLocation {
            get {
                return ResourceManager.GetString("MyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configurations for #1 exist..
        /// </summary>
        internal static string NoCustomerOrderSettingsHaveBeenSet {
            get {
                return ResourceManager.GetString("NoCustomerOrderSettingsHaveBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On order.
        /// </summary>
        internal static string OnOrder {
            get {
                return ResourceManager.GetString("OnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On sale.
        /// </summary>
        internal static string OnSale {
            get {
                return ResourceManager.GetString("OnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer order cannot be recalled to POS.
        /// </summary>
        internal static string OrderCannotBeRecalledToPOS {
            get {
                return ResourceManager.GetString("OrderCannotBeRecalledToPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override deposit.
        /// </summary>
        internal static string OverrideDeposit {
            get {
                return ResourceManager.GetString("OverrideDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deposit amount cannot be equal to or higher than the balance of the customer order.
        /// </summary>
        internal static string OverrideDepositCannotBeHigherThanBalance {
            get {
                return ResourceManager.GetString("OverrideDepositCannotBeHigherThanBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        internal static string Partial {
            get {
                return ResourceManager.GetString("Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial pick up of items.
        /// </summary>
        internal static string PartialPickup {
            get {
                return ResourceManager.GetString("PartialPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the quantity for this item has already been received so it cannot be voided.
        /// </summary>
        internal static string PartsOfThisItemHasBeenReceivedAndCannotBeVoided {
            get {
                return ResourceManager.GetString("PartsOfThisItemHasBeenReceivedAndCannotBeVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay additional payment.
        /// </summary>
        internal static string PayAdditionalPayment {
            get {
                return ResourceManager.GetString("PayAdditionalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay deposit.
        /// </summary>
        internal static string PayDeposit {
            get {
                return ResourceManager.GetString("PayDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking list.
        /// </summary>
        internal static string PickingList {
            get {
                return ResourceManager.GetString("PickingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up all.
        /// </summary>
        internal static string PickUpAll {
            get {
                return ResourceManager.GetString("PickUpAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up entire order.
        /// </summary>
        internal static string PickUpEntireOrder {
            get {
                return ResourceManager.GetString("PickUpEntireOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string PickUpQuantity {
            get {
                return ResourceManager.GetString("PickUpQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string PostOrder {
            get {
                return ResourceManager.GetString("PostOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        internal static string PrintInfo {
            get {
                return ResourceManager.GetString("PrintInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote actions.
        /// </summary>
        internal static string QuoteActions {
            get {
                return ResourceManager.GetString("QuoteActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote details.
        /// </summary>
        internal static string QuoteHeaderText {
            get {
                return ResourceManager.GetString("QuoteHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quote.
        /// </summary>
        internal static string QuoteLowCase {
            get {
                return ResourceManager.GetString("QuoteLowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string QuoteMixCase {
            get {
                return ResourceManager.GetString("QuoteMixCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ReadyForDelivery {
            get {
                return ResourceManager.GetString("ReadyForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver stock.
        /// </summary>
        internal static string ReasonCodePickUpFromOrder {
            get {
                return ResourceManager.GetString("ReasonCodePickUpFromOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve stock for order.
        /// </summary>
        internal static string ReasonCodeReserveStockForOrder {
            get {
                return ResourceManager.GetString("ReasonCodeReserveStockForOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock voided from order.
        /// </summary>
        internal static string ReasonCodeVoidStockFromOrder {
            get {
                return ResourceManager.GetString("ReasonCodeVoidStockFromOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall customer orders.
        /// </summary>
        internal static string RecallCustomerOrderHeaderText {
            get {
                return ResourceManager.GetString("RecallCustomerOrderHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall quotes.
        /// </summary>
        internal static string RecallQuoteHeaderText {
            get {
                return ResourceManager.GetString("RecallQuoteHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed deposit.
        /// </summary>
        internal static string RedeemedDeposit {
            get {
                return ResourceManager.GetString("RedeemedDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned items cannot be included in a customer order.
        /// </summary>
        internal static string ReturnedItemsCannotBeIncludedInACustomerOrder {
            get {
                return ResourceManager.GetString("ReturnedItemsCannotBeIncludedInACustomerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned items cannot be included in a quote.
        /// </summary>
        internal static string ReturnedItemsCannotBeIncludedInAQuote {
            get {
                return ResourceManager.GetString("ReturnedItemsCannotBeIncludedInAQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay back deposit.
        /// </summary>
        internal static string ReturnFullDeposit {
            get {
                return ResourceManager.GetString("ReturnFullDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay back partial deposit.
        /// </summary>
        internal static string ReturnPartialDeposit {
            get {
                return ResourceManager.GetString("ReturnPartialDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes and print.
        /// </summary>
        internal static string SaveChangesAndPrint {
            get {
                return ResourceManager.GetString("SaveChangesAndPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search quotes.
        /// </summary>
        internal static string SearchQuotes {
            get {
                return ResourceManager.GetString("SearchQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity entered for pickup is higher than the quantity that was ordered..
        /// </summary>
        internal static string SelectedPickupToHigh {
            get {
                return ResourceManager.GetString("SelectedPickupToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the orders selected have not been fully paid for and have not been printed.
        /// </summary>
        internal static string SomeOrdersHaveBalanceDueOrderNotPrinted {
            get {
                return ResourceManager.GetString("SomeOrdersHaveBalanceDueOrderNotPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the orders selected have not been fully paid for and their status has not been updated.
        /// </summary>
        internal static string SomeOrdersHaveBalanceDueStatusNotUpdated {
            get {
                return ResourceManager.GetString("SomeOrdersHaveBalanceDueStatusNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the orders selected don&apos;t have any items to be picked so they have not been printed.
        /// </summary>
        internal static string SomeOrdersHaveNoItemsToPick {
            get {
                return ResourceManager.GetString("SomeOrdersHaveNoItemsToPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source has not been selected.
        /// </summary>
        internal static string SourceHasNotBeenSelected {
            get {
                return ResourceManager.GetString("SourceHasNotBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected delivery location is not valid..
        /// </summary>
        internal static string StoreInfoNotFound {
            get {
                return ResourceManager.GetString("StoreInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This #1 has no items to be put on order..
        /// </summary>
        internal static string ThisCustomerOrderHasNoItemsOnOrder {
            get {
                return ResourceManager.GetString("ThisCustomerOrderHasNoItemsOnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has been fully recieved and cannot be voided.
        /// </summary>
        internal static string ThisItemHasBeenFullyReceivedAndCannotBeVoided {
            get {
                return ResourceManager.GetString("ThisItemHasBeenFullyReceivedAndCannotBeVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has been selected for a pick up so it cannot be voided.
        /// </summary>
        internal static string ThisItemHasBeenSelectedForPickupCannotBeVoided {
            get {
                return ResourceManager.GetString("ThisItemHasBeenSelectedForPickupCannotBeVoided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string ToOrder {
            get {
                return ResourceManager.GetString("ToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string ToPickUp {
            get {
                return ResourceManager.GetString("ToPickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale is already a customer order.
        /// </summary>
        internal static string TransactionAlreadyACustomerOrder {
            get {
                return ResourceManager.GetString("TransactionAlreadyACustomerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale is already a quote.
        /// </summary>
        internal static string TransactionAlreadyAQuote {
            get {
                return ResourceManager.GetString("TransactionAlreadyAQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating customer orders.
        /// </summary>
        internal static string UpdatingCustomerOrders {
            get {
                return ResourceManager.GetString("UpdatingCustomerOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_line_arrow_down_16 {
            get {
                object obj = ResourceManager.GetObject("white_line_arrow_down_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_line_arrow_up_16 {
            get {
                object obj = ResourceManager.GetObject("white_line_arrow_up_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whitesearch32px {
            get {
                object obj = ResourceManager.GetObject("Whitesearch32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are converting a quote to a customer order..
        /// </summary>
        internal static string YouAreConvertingAQuoteToACustomerOrder {
            get {
                return ResourceManager.GetString("YouAreConvertingAQuoteToACustomerOrder", resourceCulture);
            }
        }
    }
}
