//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.ViewPlugins.RMSMigration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.ViewPlugins.RMSMigration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar code setup.
        /// </summary>
        internal static string BarCodeSetup {
            get {
                return ResourceManager.GetString("BarCodeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company currency is missing..
        /// </summary>
        internal static string CompanyCurrencyIsMissing {
            get {
                return ResourceManager.GetString("CompanyCurrencyIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to database failed.
        /// </summary>
        internal static string ConnectingToDatabaseError {
            get {
                return ResourceManager.GetString("ConnectingToDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to database worked.
        /// </summary>
        internal static string ConnectingWorked {
            get {
                return ResourceManager.GetString("ConnectingWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user profile.
        /// </summary>
        internal static string DefaultUserProfileText {
            get {
                return ResourceManager.GetString("DefaultUserProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating currency with code {0}..
        /// </summary>
        internal static string ErrorMigratingCurrency {
            get {
                return ResourceManager.GetString("ErrorMigratingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating customer with code {0}..
        /// </summary>
        internal static string ErrorMigratingCustomer {
            get {
                return ResourceManager.GetString("ErrorMigratingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating retail department with code {0}..
        /// </summary>
        internal static string ErrorMigratingDepartment {
            get {
                return ResourceManager.GetString("ErrorMigratingDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating dimensions.
        /// </summary>
        internal static string ErrorMigratingDimensions {
            get {
                return ResourceManager.GetString("ErrorMigratingDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating item sale price with code {0}..
        /// </summary>
        internal static string ErrorMigratingItemSalePrice {
            get {
                return ResourceManager.GetString("ErrorMigratingItemSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating matrix item with code {0}..
        /// </summary>
        internal static string ErrorMigratingMatrixItem {
            get {
                return ResourceManager.GetString("ErrorMigratingMatrixItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating purchase order header with code {0}..
        /// </summary>
        internal static string ErrorMigratingPurchaseOrderHeader {
            get {
                return ResourceManager.GetString("ErrorMigratingPurchaseOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating purchase order line with code {0}..
        /// </summary>
        internal static string ErrorMigratingPurchaseOrderLine {
            get {
                return ResourceManager.GetString("ErrorMigratingPurchaseOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating retail group with code {0}..
        /// </summary>
        internal static string ErrorMigratingRetailGroup {
            get {
                return ResourceManager.GetString("ErrorMigratingRetailGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating standard item with code {0}..
        /// </summary>
        internal static string ErrorMigratingStandardItem {
            get {
                return ResourceManager.GetString("ErrorMigratingStandardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating tax with code {0}..
        /// </summary>
        internal static string ErrorMigratingTax {
            get {
                return ResourceManager.GetString("ErrorMigratingTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating sales item tax group with code {0}..
        /// </summary>
        internal static string ErrorMigratingTaxGroup {
            get {
                return ResourceManager.GetString("ErrorMigratingTaxGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating transaction header with code {0}..
        /// </summary>
        internal static string ErrorMigratingTransaction {
            get {
                return ResourceManager.GetString("ErrorMigratingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating user with code {0}..
        /// </summary>
        internal static string ErrorMigratingUser {
            get {
                return ResourceManager.GetString("ErrorMigratingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating variant item with code {0}..
        /// </summary>
        internal static string ErrorMigratingVariantItems {
            get {
                return ResourceManager.GetString("ErrorMigratingVariantItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating vendor with code {0}..
        /// </summary>
        internal static string ErrorMigratingVendor {
            get {
                return ResourceManager.GetString("ErrorMigratingVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating vendor item with code {0}..
        /// </summary>
        internal static string ErrorMigratingVendorItem {
            get {
                return ResourceManager.GetString("ErrorMigratingVendorItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please finish configuring #1 information before starting a migration between RMS and LS One.
        /// </summary>
        internal static string FinishConfigureInformation {
            get {
                return ResourceManager.GetString("FinishConfigureInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General setup.
        /// </summary>
        internal static string GeneralSetup {
            get {
                return ResourceManager.GetString("GeneralSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing {0} of {1}.
        /// </summary>
        internal static string ImportingMessage {
            get {
                return ResourceManager.GetString("ImportingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RMS database.
        /// </summary>
        internal static string InvalidRMSDatabase {
            get {
                return ResourceManager.GetString("InvalidRMSDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS migration has already been run on this database and cannot be run again..
        /// </summary>
        internal static string MigrationAlreadyBeenRun {
            get {
                return ResourceManager.GetString("MigrationAlreadyBeenRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N\A.
        /// </summary>
        internal static string N_AStore {
            get {
                return ResourceManager.GetString("N_AStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bar code setup exists..
        /// </summary>
        internal static string NoSetupBarCodeExists {
            get {
                return ResourceManager.GetString("NoSetupBarCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No store exists..
        /// </summary>
        internal static string NoStoreExists {
            get {
                return ResourceManager.GetString("NoStoreExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining:.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RMS_import_16 {
            get {
                object obj = ResourceManager.GetObject("RMS_import_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RMS_import_32 {
            get {
                object obj = ResourceManager.GetObject("RMS_import_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS data import.
        /// </summary>
        internal static string RMSDataImport {
            get {
                return ResourceManager.GetString("RMSDataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data from a RMS database through an import wizard.
        /// </summary>
        internal static string RMSDataImportDescription {
            get {
                return ResourceManager.GetString("RMSDataImportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS data migration.
        /// </summary>
        internal static string RMSDataMigration {
            get {
                return ResourceManager.GetString("RMSDataMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS Migration.
        /// </summary>
        internal static string RMSMigration {
            get {
                return ResourceManager.GetString("RMSMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are migration errors. Do you want to save errors to log files? Please select the folder where you want to save the log files..
        /// </summary>
        internal static string SaveLogToFileHeader {
            get {
                return ResourceManager.GetString("SaveLogToFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default store has no sale tax group..
        /// </summary>
        internal static string StoreMissingSalesTaxGroup {
            get {
                return ResourceManager.GetString("StoreMissingSalesTaxGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store named #1 has no functionality profile..
        /// </summary>
        internal static string StoreNamedHasNoFunctionalityProfile {
            get {
                return ResourceManager.GetString("StoreNamedHasNoFunctionalityProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store named #1 has no terminal..
        /// </summary>
        internal static string StoreNamedHasNoTerminal {
            get {
                return ResourceManager.GetString("StoreNamedHasNoTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store named #1 has no touch button layout..
        /// </summary>
        internal static string StoreNamedHasNoTouchButtons {
            get {
                return ResourceManager.GetString("StoreNamedHasNoTouchButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terminal.
        /// </summary>
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal named #1 has no hardware profile..
        /// </summary>
        internal static string TerminalNamedHasNoHardwareProfile {
            get {
                return ResourceManager.GetString("TerminalNamedHasNoHardwareProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal named #1 has no visual profile..
        /// </summary>
        internal static string TerminalNamedHasNoVisualProfile {
            get {
                return ResourceManager.GetString("TerminalNamedHasNoVisualProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
