
/*
Added description for KDS printers. 
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYPRINTER' AND COLUMN_NAME = 'DESCRIPTION')
BEGIN
	ALTER TABLE KITCHENDISPLAYPRINTER ADD [DESCRIPTION] NVARCHAR(100) NOT NULL DEFAULT ''
END