
/*

	Incident No.	: N/A
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.2\H&M
	Date created	: 19.11.2013

	Description		: New column to POSFUNCTIONALITYPROFILE

						
*/

USE LSPOSNET

GO


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ALLOWSALEANDRETURNINSAMETX')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ALLOWSALEANDRETURNINSAMETX tinyint
END


