
/*

	Incident No.	: 26882
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: LS One 2014 - Stratus
	Date created	: 09.12.13

	Description		: Create new tables and fields for customer group functionality
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUSTGROUPCATEGORY')
BEGIN
	CREATE TABLE [dbo].[CUSTGROUPCATEGORY](
		[ID] [nvarchar](20) NOT NULL,
		[DESCRIPTION] [nvarchar](60) NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_CUSTGROUPCATEGORY] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[CUSTGROUPCATEGORY] ADD  CONSTRAINT [DF_CUSTGROUPCATEGORY_DATAAREAID]  DEFAULT ('LSR') FOR [DATAAREAID]

END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTGROUP' AND COLUMN_NAME = 'CUSTGROUP')
BEGIN

	EXECUTE sp_rename N'dbo.CUSTGROUP.CUSTGROUP', N'Tmp_ID', 'COLUMN'	
	EXECUTE sp_rename N'dbo.CUSTGROUP.Tmp_ID', N'ID', 'COLUMN' 
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTGROUP' AND COLUMN_NAME = 'EXCLUSIVE')
BEGIN
	ALTER TABLE dbo.CUSTGROUP ADD EXCLUSIVE tinyint NULL	
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTGROUP' AND COLUMN_NAME = 'CATEGORY')
BEGIN	
	ALTER TABLE dbo.CUSTGROUP ADD CATEGORY NVARCHAR(20) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTGROUP' AND COLUMN_NAME = 'DISCOUNTLIMIT')
BEGIN	
	ALTER TABLE dbo.CUSTGROUP ADD DISCOUNTLIMIT numeric(28, 12) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUSTGROUP')	
BEGIN

	CREATE TABLE [dbo].[CUSTGROUP](
		[ID] [nvarchar](20) NOT NULL,
		[NAME] [nvarchar](60) NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[EXCLUSIVE] [tinyint] NULL,
		[CATEGORY] [NVARCHAR](20) NULL,
	 CONSTRAINT [I_057GROUPIDX] PRIMARY KEY CLUSTERED 
	(
		[DATAAREAID] ASC,
		[ID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]		

	ALTER TABLE [dbo].[CUSTGROUP] ADD  CONSTRAINT [DF__CUSTGROUP__DATAA__0EE3280B]  DEFAULT ('LSR') FOR [DATAAREAID]

END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUSTINGROUP')	
BEGIN
	CREATE TABLE [dbo].[CUSTINGROUP](
		[ACCOUNTNUM] [nvarchar](20) NOT NULL,
		[GROUPID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[DEFAULTGROUP] [tinyint] NULL,
	 CONSTRAINT [PK_CUSTINGROUP] PRIMARY KEY CLUSTERED 
	(
		[ACCOUNTNUM] ASC,
		[GROUPID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END




