/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 18.12.2013

	Description		: New field to POSISOPERATIONS
*/

USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISOPERATIONS' AND COLUMN_NAME = 'AUDIT')
BEGIN
	ALTER TABLE dbo.POSISOPERATIONS ADD AUDIT TINYINT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTORETABLE' AND COLUMN_NAME = 'OPERATIONAUDITSETTING')
BEGIN
	ALTER TABLE dbo.RBOSTORETABLE ADD OPERATIONAUDITSETTING int	
END
GO

UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=102; -- Void item
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=104; -- Price override
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=109; -- Return item
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=114; -- Return transaction
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=123; -- Change unit of measure
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=127; -- Discount voucher add
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=211; -- Void payment
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=300; -- Line discount amount
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=301; -- Line discount percent
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=302; -- Total discount amount
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=303; -- Total discount percent
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=304; -- Manually trigger periodic discount
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=500; -- Void transaction
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=503; -- Suspend transaction
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=511; -- Issue credit memo
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=512; -- Issue gift card
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=905; -- Print Z
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=1000; -- Open drawer
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=1100; -- Customer account deposit
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=1101; -- Add customer to loyalty card
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=1211; -- Safe drop
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=1212; -- Bank drop
UPDATE POSISOPERATIONS SET AUDIT=1 WHERE AUDIT IS NULL AND OPERATIONID=1400; -- Tax exempt transaction
