/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 17.12.2013

	Description		: Added new table for auditing operations
*/

USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RBOTRANSACTIONOPERATIONAUDIT')
BEGIN
	CREATE TABLE [dbo].[RBOTRANSACTIONOPERATIONAUDIT](
		[UID] uniqueidentifier NOT NULL,
		[TRANSACTIONID] [nvarchar](20) NOT NULL,
		[LINENUM] [numeric](28, 12),
		[STORE] [nvarchar](20) NOT NULL,
		[TERMINALID] [nvarchar](20) NOT NULL,
		[USERID] [nvarchar](20) NOT NULL,
		[MANAGERID] [nvarchar](20) NULL,
		[OPERATIONID] [int] NOT NULL,
		[CREATEDDATE] [datetime] NOT NULL,
		[REPLICATIONCOUNTER] [int] IDENTITY(1,1) NOT NULL,
		[REPLICATED] [tinyint] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
	 CONSTRAINT [PK_OPERATIONAUDIT] PRIMARY KEY CLUSTERED 
		(
			[UID]
		)
	);

	CREATE INDEX [IDX_RBOTRANSACTIONOPERATIONAUDIT_TERM] ON [dbo].[RBOTRANSACTIONOPERATIONAUDIT]
		([DATAAREAID], [STORE], [TERMINALID], [OPERATIONID])
	CREATE INDEX [IDX_RBOTRANSACTIONOPERATIONAUDIT_DATE] ON [dbo].[RBOTRANSACTIONOPERATIONAUDIT]
		([DATAAREAID], [CREATEDDATE])
END