/*

	Incident No.	: 
	Responsible		: Sigfus Johannesson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 20.12.2013

	Description		: Expanded field size
*/

USE LSPOSNET
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONINFOCODETRANS' AND COLUMN_NAME = 'INFORMATION' AND CHARACTER_MAXIMUM_LENGTH < 512)
BEGIN
alter table RBOTRANSACTIONINFOCODETRANS ALTER COLUMN INFORMATION NVARCHAR(512)
END