/*
	Incident No.	: N/A
	Responsible		: Erna Guðrún Sigurðardóttir
	Sprint			: LS One 2014 - Stratus
	Date created	: 09.12.13

	Description		: Added STATEMENTPOSTING to RBOTERMINALTABLE
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLE' AND COLUMN_NAME = 'STATEMENTPOSTING')
BEGIN
	ALTER TABLE RBOTERMINALTABLE ADD STATEMENTPOSTING int not null default 0
END