/*

	Incident No.	: 
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 17.12.2013

	Description		: Added a new field to table KITCHENDISPLAYVISUALPROFILE to contain LanguageCode
*/

USE LSPOSNET
GO
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'LANGUAGECODE')
BEGIN
	ALTER TABLE dbo.KITCHENDISPLAYVISUALPROFILE ADD LANGUAGECODE NVARCHAR(20) NOT NULL DEFAULT 'en'
END
