
/*

	Incident No.	: NA
	Responsible		: Sigfus Johannesson
	Sprint			: 2014
	Date created	: 07.01.2014

	Description		: Added field for tax free and post transaction DD job.
	
						
*/
USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'DDSCHEDULERLOCATION')
BEGIN
ALTER TABLE POSFUNCTIONALITYPROFILE ADD POSTTRANSACTIONDDJOB NVARCHAR(127), DDSCHEDULERLOCATION NVARCHAR(127)
END