/*

	Incident No.	: NA
	Responsible		: Sigfus Johannesson
	Sprint			: LS One 2014 - Stratus
	Date created	: 06.01.13

	Description		: Added tables for tax free
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TAXREFUND')
BEGIN
	CREATE TABLE TAXREFUND (
		ID UNIQUEIDENTIFIER CONSTRAINT PK_TAXREFUND PRIMARY KEY, 
		CREATED DATETIME NOT NULL,
		TOURISTID UNIQUEIDENTIFIER,
		BOOKING NVARCHAR(127), 
		RUNNING NVARCHAR(127),
		TOTAL NUMERIC(28,12) NOT NULL, 
		TAX NUMERIC(28,12) NOT NULL, 
		TAXREFUND NUMERIC(28,12) NOT NULL)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TOURIST')
BEGIN
	CREATE TABLE TOURIST (
		ID UNIQUEIDENTIFIER CONSTRAINT PK_TOURIST PRIMARY KEY, 
		NAME VARCHAR(100), 
		NATIONALITY NVARCHAR(100), 
		EMAIL NVARCHAR(100), 
		PASSPORTNUMBER NVARCHAR(40), 
		PASSPORTISSUEDBY NVARCHAR(100), 
		PASSPORTISSUEDON DATE, 
		[ADDRESS] NVARCHAR(100), 
		STREET NVARCHAR(100), 
		ZIPCODE NVARCHAR(15), 
		CITY NVARCHAR(60), 
		[STATE] NVARCHAR(30), 
		COUNTY NVARCHAR(30), 
		COUNTRY NVARCHAR(50),
		FLIGHTNUMBER NVARCHAR(20), 
		ARRIVALEDATE DATE, 
		DEPARTUREDATE DATE)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TAXREFUNDTRANSACTION')
BEGIN
	CREATE TABLE TAXREFUNDTRANSACTION (
		ID UNIQUEIDENTIFIER CONSTRAINT PK_TAXREFUNDTRANSACTION PRIMARY KEY, 
		TAXREFUNDDATAID UNIQUEIDENTIFIER, 
		STOREID NVARCHAR(20),
		TERMINALID NVARCHAR(20),
		TRANSACTIONID NVARCHAR(20),
		TOTAL NUMERIC(28,12), 
		TAX NUMERIC(28,12), 
		TAXREFUND NUMERIC(28,12))
END
