/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 06.01.2014

	Description		: New indices for optimization purposes
*/

USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IDX_RBOTRANSACTIONTABLE_RECEIPTID' AND object_id = OBJECT_ID('RBOTRANSACTIONTABLE'))
BEGIN
	CREATE NONCLUSTERED INDEX [IDX_RBOTRANSACTIONTABLE_RECEIPTID] ON [dbo].[RBOTRANSACTIONTABLE]
	(
		[RECEIPTID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO


