/*
	Incident No.	: N/A
	Responsible		: Sigfus Johannesson
	Sprint			: LS One 2014 - Stratus
	Date created	: 06.01.13

	Description		: Added an operation
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 1600)
BEGIN
  INSERT INTO POSISOPERATIONS ( OPERATIONID, OPERATIONNAME, PERMISSIONID, PERMISSIONID2, CHECKUSERACCESS, USEROPERATION,DATAAREAID,LOOKUPTYPE)
  VALUES (1600, 'Tax refund',	NULL,	NULL,	1,	1,'LSR',0)
END
GO