/*
	Incident No.	: N/A
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2014 - Stratus
	Date created	: 06.01.13

	Description		: Added STATEMENTSTATUS to RBOSTATEMENTLINE
	
						
*/
USE LSPOSNET
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'JSCJOBS' )
BEGIN
	IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'JSCJOBS' AND COLUMN_NAME = 'PLUGINPATH') 
	BEGIN
		ALTER TABLE JSCJOBS	ADD PLUGINPATH VARCHAR(250) NULL;
	END;
	IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'JSCJOBS' AND COLUMN_NAME = 'PLUGINARGUMENTS') 
	BEGIN
		ALTER TABLE JSCJOBS	ADD PLUGINARGUMENTS VARCHAR (MAX) NULL;
	END;
END;