/*
	Incident No.	: N/A
	Responsible		: Sigfus Johannesson
	Sprint			: LS One 2014 - Stratus
	Date created	: 03.01.2014

	Description		: Added TAXREFUNDRANGE table
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TAXREFUNDRANGE')
BEGIN
	CREATE TABLE TAXREFUNDRANGE 
	(
		ID UNIQUEIDENTIFIER CONSTRAINT PK_TAXREFUNDRANGE PRIMARY KEY, 
		VALUEFROM NUMERIC(28, 12), 
		VALUETO NUMERIC(28, 12), 
		TAXREFUND NUMERIC(28, 12),
		TAXREFUNDPERCENTAGE NUMERIC(28, 12))
END