/*
	Incident No.	: N/A
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2014 - Stratus
	Date created	: 06.01.13

	Description		: Added STATEMENTSTATUS to RBOSTATEMENTLINE
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTATEMENTLINE' AND COLUMN_NAME = 'STATEMENTSTATUS')
BEGIN
	ALTER TABLE RBOSTATEMENTLINE ADD STATEMENTSTATUS int not null default 0
END