/*
	Incident No.	: N/A
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 21.01.2014

	Description		: Split NUMBERSEQUENCETABLE into NUMBERSEQUENCETABLE and NUMBERSEQUENCEVALUE
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NUMBERSEQUENCEVALUE') 
BEGIN
	CREATE TABLE [dbo].[NUMBERSEQUENCEVALUE](
		[NUMBERSEQUENCE] [nvarchar](20) NOT NULL,
		[NEXTREC] [int] NOT NULL,
		[STOREID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
	 CONSTRAINT [PK_NUMBERSEQUENCEVALUE] PRIMARY KEY CLUSTERED 
	(
		[DATAAREAID] ASC,
		[NUMBERSEQUENCE] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF (0 = (select count(*) from NUMBERSEQUENCEVALUE))
BEGIN
	exec sp_executesql N'INSERT INTO [dbo].[NUMBERSEQUENCEVALUE] (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID) SELECT NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID FROM NUMBERSEQUENCETABLE'
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NUMBERSEQUENCETABLE' AND COLUMN_NAME = 'NEXTREC') 
BEGIN
	exec sp_executesql N'ALTER TABLE [dbo].[NUMBERSEQUENCETABLE] DROP CONSTRAINT DF__NUMBERSEQ__NEXTR__7993D0C1'
	exec sp_executesql N'ALTER TABLE NUMBERSEQUENCETABLE DROP COLUMN NEXTREC'
END
GO