/*
	Incident No.	: N/A
	Responsible		: Sigfús Jóhannesson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 20.01.2014

	Description		: Adding new Job Fields
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PENDINGDDJOBS')
BEGIN
	CREATE TABLE PENDINGDDJOBS(ID UNIQUEIDENTIFIER PRIMARY KEY, CREATEDDATE DATETIME, JOBID UNIQUEIDENTIFIER, PARAMETERS NVARCHAR(128))
END
GO