/*
	Incident No.	: N/A
	Responsible		: Sigfús Jóhannesson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 21.01.2014

	Description		: Added start of day operation
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 1610)
BEGIN
  INSERT INTO POSISOPERATIONS ( OPERATIONID, OPERATIONNAME, PERMISSIONID, PERMISSIONID2, CHECKUSERACCESS, USEROPERATION,DATAAREAID,LOOKUPTYPE)
  VALUES (1610, 'Start of day',	NULL,	NULL,	1,	1,'LSR',0)
END
GO