/*
	Incident No.	: N/A
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 13.01.2014

	Description		: Fixed column type
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'ORIGINALPRICE') 
BEGIN
  ALTER TABLE RBOTRANSACTIONSALESTRANS ADD ORIGINALPRICE numeric(28,12) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'ORIGINALPRICEWITHTAX') 
BEGIN
  ALTER TABLE RBOTRANSACTIONSALESTRANS ADD ORIGINALPRICEWITHTAX numeric(28,12) NULL
END
GO