/*
	Incident No.	: N/A
	Responsible		: Sigfús Jóhannesson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 22.01.2014

	Description		: Added columns to POSFUNCTIONALITYPROFILE
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'USESTARTOFDAY')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD USESTARTOFDAY BIT
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'FORCESTARTOFDAYONLOGON')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD FORCESTARTOFDAYONLOGON BIT
END

GO