
/*
	Incident No.	: N/A
	Responsible		: Hörður Kristjánsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 05.02.2014

	Description		: Adding fields to the Z report table to show total returns
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSZREPORT' AND COLUMN_NAME = 'ZRETURNGROSSAMOUNT')
BEGIN
	ALTER TABLE POSZREPORT ADD ZRETURNGROSSAMOUNT numeric(28, 12) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSZREPORT' AND COLUMN_NAME = 'ZRETURNNETAMOUNT')
BEGIN
	ALTER TABLE POSZREPORT ADD ZRETURNNETAMOUNT numeric(28, 12) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSZREPORT' AND COLUMN_NAME = 'TOTALRETURNGROSSAMOUNT')
BEGIN
	ALTER TABLE POSZREPORT ADD TOTALRETURNGROSSAMOUNT numeric(28, 12) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSZREPORT' AND COLUMN_NAME = 'TOTALRETURNNETAMOUNT')
BEGIN
	ALTER TABLE POSZREPORT ADD TOTALRETURNNETAMOUNT numeric(28, 12) NULL
END
GO



