/*
	Incident No.	: N/A
	Responsible		: Sigfús Jóhannesson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 23.01.2014

	Description		: Added columns to TAXREFUND
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TAXREFUND' AND COLUMN_NAME = 'COMMENT')
BEGIN
	ALTER TABLE TAXREFUND ADD COMMENT NTEXT
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TAXREFUND' AND COLUMN_NAME = 'STATUS')
BEGIN
	ALTER TABLE TAXREFUND ADD [STATUS] INT
END


GO