
/*
	Incident No.	: N/A
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 05.02.2014

	Description		: Renamed columns, fixed older values
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONOPERATIONAUDIT' AND COLUMN_NAME = 'OPERATIONID')
BEGIN
	ALTER TABLE RBOTRANSACTIONOPERATIONAUDIT ADD OPERATIONID INT NOT NULL DEFAULT(-1)
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONOPERATIONAUDIT' AND COLUMN_NAME = 'OPERATION')
BEGIN
	IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RBOTRANSACTIONOPERATIONAUDIT]') AND name = N'IDX_RBOTRANSACTIONOPERATIONAUDIT_TERM')
		DROP INDEX [IDX_RBOTRANSACTIONOPERATIONAUDIT_TERM] ON [dbo].[RBOTRANSACTIONOPERATIONAUDIT] WITH ( ONLINE = OFF );
	
	CREATE INDEX [IDX_RBOTRANSACTIONOPERATIONAUDIT_TERM] ON [dbo].[RBOTRANSACTIONOPERATIONAUDIT]
		([DATAAREAID], [STORE], [TERMINALID], [OPERATIONID]);

	exec sp_executesql N'
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''0'' WHERE OPERATION=''NoOperation'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''100'' WHERE OPERATION=''ItemSale'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''101'' WHERE OPERATION=''PriceCheck'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''102'' WHERE OPERATION=''VoidItem'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''103'' WHERE OPERATION=''ItemComment'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''104'' WHERE OPERATION=''PriceOverride'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''105'' WHERE OPERATION=''SetQty'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''106'' WHERE OPERATION=''ClearQty'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''108'' WHERE OPERATION=''ItemSearch'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''109'' WHERE OPERATION=''ReturnItem'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''110'' WHERE OPERATION=''WeighItem'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''111'' WHERE OPERATION=''FuelItemSale'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''112'' WHERE OPERATION=''LinkedItemsAdd'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''113'' WHERE OPERATION=''SetDimensions'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''114'' WHERE OPERATION=''ReturnTransaction'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''115'' WHERE OPERATION=''ShowJournal'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''116'' WHERE OPERATION=''SetCostPrice'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''117'' WHERE OPERATION=''LoyaltyRequest'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''118'' WHERE OPERATION=''ProcessInput'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''119'' WHERE OPERATION=''SalespersonBarcode'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''120'' WHERE OPERATION=''SalespersonCard'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''121'' WHERE OPERATION=''SalespersonClear'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''122'' WHERE OPERATION=''InvoiceComment'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''123'' WHERE OPERATION=''ChangeUnitOfMeasure'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''124'' WHERE OPERATION=''ItemSaleMulti'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''125'' WHERE OPERATION=''RFIDSale'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''126'' WHERE OPERATION=''SalesHistory'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''127'' WHERE OPERATION=''DiscountVoucherAdd'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''128'' WHERE OPERATION=''DiscountVoucherRemove'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''129'' WHERE OPERATION=''InfocodesOnRequest'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''130'' WHERE OPERATION=''ClearItemComments'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''131'' WHERE OPERATION=''ChangeItemComments'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''132'' WHERE OPERATION=''GetLoyaltycardInfo'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''133'' WHERE OPERATION=''LoyaltyPointDiscount'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''200'' WHERE OPERATION=''PayCash'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''201'' WHERE OPERATION=''PayCard'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''202'' WHERE OPERATION=''PayCustomerAccount'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''203'' WHERE OPERATION=''PayCurrency'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''204'' WHERE OPERATION=''PayCheque'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''205'' WHERE OPERATION=''PayTransaction'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''206'' WHERE OPERATION=''PayCashQuick'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''207'' WHERE OPERATION=''PayLoyalty'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''208'' WHERE OPERATION=''PayCorporateCard'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''210'' WHERE OPERATION=''ChangeBack'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''211'' WHERE OPERATION=''VoidPayment'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''212'' WHERE OPERATION=''FleetCardInfo'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''213'' WHERE OPERATION=''PayCreditMemo'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''214'' WHERE OPERATION=''PayGiftCertificate'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''215'' WHERE OPERATION=''AuthorizeCard'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''300'' WHERE OPERATION=''LineDiscountAmount'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''301'' WHERE OPERATION=''LineDiscountPercent'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''302'' WHERE OPERATION=''TotalDiscountAmount'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''303'' WHERE OPERATION=''TotalDiscountPercent'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''304'' WHERE OPERATION=''ManuallyTriggerPeriodicDisount'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''305'' WHERE OPERATION=''ClearPeriodicDiscount'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''500'' WHERE OPERATION=''VoidTransaction'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''501'' WHERE OPERATION=''TransactionComment'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''502'' WHERE OPERATION=''SalesPerson'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''503'' WHERE OPERATION=''SuspendTransaction'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''504'' WHERE OPERATION=''RecallTransaction'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''505'' WHERE OPERATION=''RecallUnconcludedTransaction'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''506'' WHERE OPERATION=''CardSwipe'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''507'' WHERE OPERATION=''PharmacyPrescriptionAdd'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''508'' WHERE OPERATION=''PharmacyPrescriptionCancel'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''509'' WHERE OPERATION=''PharmacyPrescriptionPaid'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''510'' WHERE OPERATION=''PharmacyPrescriptions'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''511'' WHERE OPERATION=''IssueCreditMemo'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''512'' WHERE OPERATION=''IssueGiftCertificate'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''513'' WHERE OPERATION=''DisplayTotal'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''514'' WHERE OPERATION=''CreditMemoBalance'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''515'' WHERE OPERATION=''SalesOrder'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''516'' WHERE OPERATION=''SalesInvoice'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''517'' WHERE OPERATION=''IncomeAccounts'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''518'' WHERE OPERATION=''ExpenseAccounts'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''519'' WHERE OPERATION=''ReturnIncomeAccounts'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''520'' WHERE OPERATION=''ReturnExpenseAccounts'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''521'' WHERE OPERATION=''GetGiftCardBalance'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''550'' WHERE OPERATION=''CashChangerRegisterAmount'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''551'' WHERE OPERATION=''CashChangerReset'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''552'' WHERE OPERATION=''CashChangerRegret'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''553'' WHERE OPERATION=''CashChangerExit'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''554'' WHERE OPERATION=''CashChangerChange'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''555'' WHERE OPERATION=''CashChangerLogin'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''556'' WHERE OPERATION=''CashChangerInit'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''600'' WHERE OPERATION=''Customer'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''602'' WHERE OPERATION=''CustomerSearch'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''603'' WHERE OPERATION=''CustomerClear'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''604'' WHERE OPERATION=''CustomerCard'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''609'' WHERE OPERATION=''CustomerTransactions'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''610'' WHERE OPERATION=''CustomerTransactionsReport'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''611'' WHERE OPERATION=''CustomerBalanceReport'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''612'' WHERE OPERATION=''CustomerAdd'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''613'' WHERE OPERATION=''CustomerBarcode'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''700'' WHERE OPERATION=''LogOn'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''701'' WHERE OPERATION=''LogOff'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''702'' WHERE OPERATION=''ChangeUser'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''703'' WHERE OPERATION=''LockTerminal'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''704'' WHERE OPERATION=''LogOffForce'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''705'' WHERE OPERATION=''EmployeeCard'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''706'' WHERE OPERATION=''EmployeeBarcode'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''800'' WHERE OPERATION=''NegativeAdjustment'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''801'' WHERE OPERATION=''InventoryLookup'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''900'' WHERE OPERATION=''ApplicationExit'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''902'' WHERE OPERATION=''InitializeZReport'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''904'' WHERE OPERATION=''PrintX'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''905'' WHERE OPERATION=''PrintZ'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''906'' WHERE OPERATION=''PrintTaxFree'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''907'' WHERE OPERATION=''PrintPreviousSlip'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''908'' WHERE OPERATION=''PrintPreviousInvoice'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''909'' WHERE OPERATION=''UploadPrinterLogo'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''910'' WHERE OPERATION=''RestartComputer'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''911'' WHERE OPERATION=''ShutDownComputer'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''912'' WHERE OPERATION=''DesignModeEnable'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''913'' WHERE OPERATION=''DesignModeDisable'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''914'' WHERE OPERATION=''MinimizePOSWindow'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''915'' WHERE OPERATION=''BlankOperation'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''916'' WHERE OPERATION=''RunExternalCommand'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''917'' WHERE OPERATION=''ExecutePOSPlugin'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1000'' WHERE OPERATION=''OpenDrawer'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1050'' WHERE OPERATION=''EndOfDay'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1051'' WHERE OPERATION=''EndOfShift'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1052'' WHERE OPERATION=''TenderDeclaration'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1100'' WHERE OPERATION=''CustomerAccountDeposit'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1101'' WHERE OPERATION=''AddCustomerToLoyaltyCard'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1200'' WHERE OPERATION=''DeclareStartAmount'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1201'' WHERE OPERATION=''FloatEntry'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1210'' WHERE OPERATION=''TenderRemoval'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1211'' WHERE OPERATION=''SafeDrop'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1212'' WHERE OPERATION=''BankDrop'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1213'' WHERE OPERATION=''SafeDropReversal'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1214'' WHERE OPERATION=''BankDropReversal'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1300'' WHERE OPERATION=''SplitBill'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1301'' WHERE OPERATION=''ShowHospitality'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1302'' WHERE OPERATION=''PrintHospitalityMenuType'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1303'' WHERE OPERATION=''SetHospitalityMenuType'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1304'' WHERE OPERATION=''ChangeHospitalityMenuType'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1305'' WHERE OPERATION=''BumpOrder'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1400'' WHERE OPERATION=''TaxExemptTransaction'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1401'' WHERE OPERATION=''ClearTransactionTaxExemption'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1405'' WHERE OPERATION=''InfocodeTaxGroupChange'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1500'' WHERE OPERATION=''OpenMenu'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1501'' WHERE OPERATION=''RefreshDisplayStations'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1600'' WHERE OPERATION=''TaxRefund'';
	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATION=''1610'' WHERE OPERATION=''StartOfDay'';

	UPDATE RBOTRANSACTIONOPERATIONAUDIT SET OPERATIONID=CAST(OPERATION as int) WHERE OPERATIONID=-1;
	
	ALTER TABLE RBOTRANSACTIONOPERATIONAUDIT DROP COLUMN OPERATION;'
END
GO