
/*
	Incident No.	: N/A
	Responsible		: Sigfús Jóhannesson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 06.02.2014

	Description		: Adding fields to RBOSTORETENDERTYPETABLE AND RBOTRANSACTIONOPERATIONAUDIT
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTORETENDERTYPETABLE' AND COLUMN_NAME = 'MAXIMUMAMOUNTINPOSENABLED')
BEGIN
	ALTER TABLE RBOSTORETENDERTYPETABLE ADD MAXIMUMAMOUNTINPOSENABLED TINYINT
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTORETENDERTYPETABLE' AND COLUMN_NAME = 'MAXIMUMAMOUNTINPOS')
BEGIN
	ALTER TABLE RBOSTORETENDERTYPETABLE ADD MAXIMUMAMOUNTINPOS NUMERIC(28,12)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONOPERATIONAUDIT' AND COLUMN_NAME = 'OPERATIONID')
BEGIN
	ALTER TABLE RBOTRANSACTIONOPERATIONAUDIT ADD OPERATIONID INT
END

