
/*
	Incident No.	: N/A
	Responsible		: Marý B. Steingrímsdóttir
	Sprint			: LS One 2014 - Nimbo
	Date created	: 31.01.2014

	Description		: Added columns to POSFUNCTIONALITYPROFILE
	
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTINCLUDEFLOATINCASH')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTINCLUDEFLOATINCASH TINYINT
END




