
/*
	Incident No.	: N/A
	Responsible		: Hörður Kristjánsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 07.02.2014

	Description		: Adding returns settings to POSFUNCTIONALITYPROFILE
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTCOMBINESALESRETURNS')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTCOMBINESALESRETURNS TINYINT
END
GO

