
/*
	Incident No.	: N/A
	Responsible		: Hörður Kristjánsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 12.02.2014

	Description		: Adding tender declaration z report setting to POSFUNCTIONALITYPROFILE
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTINCLUDETENDERDECLARATION')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTINCLUDETENDERDECLARATION TINYINT
END
GO

