
/*
	Incident No.	: N/A
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 20.02.2014

	Description		: Modifying KITCHENDISPLAYSTYLEPROFILE to support the new KDS functionality
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMONTIMESTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ITEMONTIMESTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMVOIDEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ITEMVOIDEDSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DEFAULTFOOTERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD DEFAULTFOOTERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DEFAULTHEADERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD DEFAULTHEADERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'COMMENTMODIFIERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD COMMENTMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERMODIFIEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD  ITEMMODIFIERMODIFIEDSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERVOIDEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD  ITEMMODIFIERVOIDEDSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMMODIFIERGLYPHSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD  ITEMMODIFIERGLYPHSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DEALHEADERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD  DEALHEADERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DEALHEADERVOIDEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE ADD DEALHEADERVOIDEDSTYLEID UNIQUEIDENTIFIER
END

-- Changing datatypes of old columns
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ORDERPANESTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column ORDERPANESTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ORDERPANESTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ORDERSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column ORDERSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ORDERSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ITEMDEFAULTSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column ITEMDEFAULTSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ITEMDEFAULTSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUMPEDSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column BUMPEDSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ITEMDONESTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'MODIFIEDITEMSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column MODIFIEDITEMSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILE ADD ITEMMODIFIEDSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'NORMALITEMMODIFIERSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column NORMALITEMMODIFIERSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILE ADD NORMALITEMMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'INCREASEITEMMODIFIERSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column INCREASEITEMMODIFIERSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILE ADD INCREASEITEMMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'DECREASEITEMMODIFIERSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column DECREASEITEMMODIFIERSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILE ADD DECREASEITEMMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND COLUMN_NAME = 'STYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYTIMESTYLE DROP Column STYLEID
	alter table KITCHENDISPLAYTIMESTYLE ADD STYLEID UNIQUEIDENTIFIER
END

-- Deleting unused columns
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'STARTEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column STARTEDSTYLEID
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ORDERPROPERTIESMODIFIEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column ORDERPROPERTIESMODIFIEDSTYLEID
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'BUTTONPANESTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILE DROP Column BUTTONPANESTYLEID
END







