
/*
	Incident No.	: N/A
	Responsible		: Hörður Kristjánsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 24.02.2014

	Description		: Fixing return values for Z reports
						
*/
USE LSPOSNET
GO

DECLARE @DATAAREAID nvarchar(4)
DECLARE @RETURNTOTALGROSSAMOUNT NUMERIC(28,12)
DECLARE @RETURNTOTALNETAMOUNT NUMERIC(28,12)
DECLARE @MAXZREPORTID nvarchar(20)

DECLARE @CURRZREPORTID nvarchar(20)
DECLARE @STORE nvarchar(20)
DECLARE @TERMINAL nvarchar(20)
DECLARE @ZRETURNNETAMOUNT NUMERIC(28,12)
DECLARE @ZRETURNGROSSAMOUNT NUMERIC(28,12)
DECLARE @SUMGROSS NUMERIC(28, 12)
DECLARE @SUMNET NUMERIC(28,12)
DECLARE @DOUPDATES INT

SET @DATAAREAID = (SELECT TOP(1) DATAAREAID FROM POSZREPORT)
SET @SUMGROSS = 0
SET @SUMNET = 0
SET @DOUPDATES = 1

-- if the last z report has total returns as 0 then do these calculations
--IF (SELECT TOP 1 ISNULL(TOTALRETURNGROSSAMOUNT, -1)
--	FROM POSZREPORT 
--	ORDER BY ZREPORTID DESC) < 0
--BEGIN	
--	SET @DOUPDATES = 0
--END

IF @DOUPDATES = 1
BEGIN	
	DECLARE ZREPORTS CURSOR FOR

	SELECT ZREPORTID, ZRETURNGROSSAMOUNT, ZRETURNNETAMOUNT, TOTALRETURNGROSSAMOUNT, TOTALRETURNNETAMOUNT, STOREID, TERMINALID
	FROM POSZREPORT
	WHERE DATAAREAID = @DATAAREAID

	OPEN ZREPORTS

	FETCH FROM ZREPORTS INTO @CURRZREPORTID, @ZRETURNGROSSAMOUNT, @ZRETURNNETAMOUNT, @RETURNTOTALGROSSAMOUNT, @RETURNTOTALNETAMOUNT, @STORE, @TERMINAL

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- If the Z report doesn't exist in the current database then don't calculate
		IF EXISTS (SELECT DISTINCT ZREPORTID FROM RBOTRANSACTIONTABLE WHERE ZREPORTID = @CURRZREPORTID AND STORE = @STORE AND TERMINAL = @TERMINAL)
		BEGIN		
			-- Total of all returns for a specific z report   
			select @ZRETURNNETAMOUNT = ISNULL(SUM(sales.NETAMOUNT), 0) * -1, @ZRETURNGROSSAMOUNT = ISNULL(SUM(sales.NETAMOUNTINCLTAX), 0) * -1
			from RBOTRANSACTIONSALESTRANS sales
			join RBOTRANSACTIONTABLE rt on rt.TRANSACTIONID = sales.TRANSACTIONID
			where sales.QTY > 0
			and rt.ZREPORTID = @CURRZREPORTID
			and rt.STORE = @STORE
			and rt.TERMINAL = @TERMINAL
			and rt.DATAAREAID = @DATAAREAID
			and rt.TYPE = 2
			and rt.ENTRYSTATUS = 0
			and sales.TRANSACTIONSTATUS = 0
			
			IF @ZRETURNGROSSAMOUNT <> 0
			BEGIN
			
				SET @SUMGROSS = @SUMGROSS + @ZRETURNGROSSAMOUNT
				SET @SUMNET = @SUMNET + @ZRETURNNETAMOUNT
			
				UPDATE POSZREPORT
				SET ZRETURNGROSSAMOUNT = @ZRETURNGROSSAMOUNT, ZRETURNNETAMOUNT = @ZRETURNNETAMOUNT,
					TOTALRETURNGROSSAMOUNT = @SUMGROSS, TOTALRETURNNETAMOUNT = @SUMNET
				WHERE STOREID = @STORE
				AND TERMINALID = @TERMINAL
				AND ZREPORTID = @CURRZREPORTID
			END
			ELSE
			BEGIN
				UPDATE POSZREPORT
				SET TOTALRETURNGROSSAMOUNT = @SUMGROSS, TOTALRETURNNETAMOUNT = @SUMNET
				WHERE STOREID = @STORE
				AND TERMINALID = @TERMINAL
				AND ZREPORTID = @CURRZREPORTID
			END
		END
		
		FETCH NEXT FROM ZREPORTS INTO @CURRZREPORTID, @ZRETURNGROSSAMOUNT, @ZRETURNNETAMOUNT, @RETURNTOTALGROSSAMOUNT, @RETURNTOTALNETAMOUNT, @STORE, @TERMINAL
		
	END

	CLOSE ZREPORTS
	DEALLOCATE ZREPORTS
END
GO
