
/*
	Incident No.	: N/A
	Responsible		: Sigfus Johannesson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 11.03.2014

	Description		: Added field to functionality profile
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'STARTOFTRANSACTIONINFOCODETYPE')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD STARTOFTRANSACTIONINFOCODETYPE int
END
