
/*
	Incident No.	: N/A
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 26.02.2014

	Description		: Changing the way screen location is stored for Kitchen display stations
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'FULLSCREEN')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD FULLSCREEN bit null
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'HORIZONTALLOCATION')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD HORIZONTALLOCATION INT null
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'VERTICALLOCATION')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD VERTICALLOCATION INT null
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'SCREENALIGNMENT')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION DROP COLUMN SCREENALIGNMENT
END