
/*
	Incident No.	: N/A
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 27.02.2014

	Description		: Adding refresh rate setting for KDS chits
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'CHITREFRESHRATE')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE ADD CHITREFRESHRATE int NOT NULL DEFAULT 1
END
