
/*
	Incident No.	: N/A
	Responsible		: Sigfus Johannesson	
	Sprint			: LS One 2014
	Date created	: 10.04.2014

	Description		: Added fields to Taxrefund and pendingddjobs
						
*/
USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TAXREFUND' AND COLUMN_NAME = 'STOREID')
BEGIN
	ALTER TABLE TAXREFUND ADD STOREID NVARCHAR(20)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TAXREFUND' AND COLUMN_NAME = 'TERMINALID')
BEGIN
	ALTER TABLE TAXREFUND ADD TERMINALID NVARCHAR(20)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PENDINGDDJOBS' AND COLUMN_NAME = 'STOREID')
BEGIN
	ALTER TABLE PENDINGDDJOBS ADD STOREID NVARCHAR(20)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PENDINGDDJOBS' AND COLUMN_NAME = 'TERMINALID')
BEGIN
	ALTER TABLE PENDINGDDJOBS ADD TERMINALID NVARCHAR(20)
END


