
/*

	Incident No.	: ONE-223
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Dottoe
	Date created	: 24.6.2014

	Description		: Add new fields to table PosisHospitalityDiningTable
	
						
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISHOSPITALITYDININGTABLES' AND COLUMN_NAME = 'CUSTOMERID')
BEGIN
	ALTER TABLE POSISHOSPITALITYDININGTABLES ADD CUSTOMERID NVARCHAR(20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HOSPITALITYTYPE' AND COLUMN_NAME = 'PROMPTFORCUSTOMER')
BEGIN
	ALTER TABLE HOSPITALITYTYPE ADD PROMPTFORCUSTOMER TINYINT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HOSPITALITYTYPE' AND COLUMN_NAME = 'DISPLAYCUSTOMERONTABLE')
BEGIN
	ALTER TABLE HOSPITALITYTYPE ADD DISPLAYCUSTOMERONTABLE INT
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISHOSPITALITYDININGTABLES' AND COLUMN_NAME = 'DESCRIPTION' AND CHARACTER_MAXIMUM_LENGTH > 30)
BEGIN
	ALTER TABLE POSISHOSPITALITYDININGTABLES ALTER COLUMN [DESCRIPTION] nvarchar(200) NULL
END
GO




