
/*

	Incident No.	: ONE-162
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Dottoe
	Date created	: 5.7.2014

	Description		: Add new fields to table CustTable
	
						
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTTABLE' AND COLUMN_NAME = 'GENDER')
BEGIN
	ALTER TABLE CUSTTABLE ADD GENDER INT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTTABLE' AND COLUMN_NAME = 'DATEOFBIRTH')
BEGIN
	ALTER TABLE CUSTTABLE ADD DATEOFBIRTH DATETIME
END
GO


