
/*
	Incident No.	: XXX
	Responsible		: Gudbjorn Einarsson
	Date created	: 09.07.2014

	Description		: Remove unused columns from inventory adjustments and stock counting tables
*/

USE LSPOSNET

EXEC spDeleteColumnAndConstaint @TABLE='INVENTJOURNALTABLE', @COLUMN='JOURNALNAMEID'
EXEC spDeleteColumnAndConstaint @TABLE='INVENTJOURNALTABLE', @COLUMN='NUMOFLINES'

-- Remove columns from INVENTJOURNALTRANS. Primary key has to be restructured because one of the dropped column is contained in it
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND CONSTRAINT_NAME ='PK_INVENTJOURNALTRANS')
BEGIN
	ALTER TABLE INVENTJOURNALTRANS 
	DROP CONSTRAINT PK_INVENTJOURNALTRANS
	
	EXEC spDeleteColumnAndConstaint @TABLE='INVENTJOURNALTRANS', @COLUMN='ORIGIN'
	
	ALTER TABLE INVENTJOURNALTRANS
	ADD CONSTRAINT PK_INVENTJOURNALTRANS_2 PRIMARY KEY CLUSTERED (JOURNALID, LINENUM, DATAAREAID);
END
GO

EXEC spDeleteColumnAndConstaint @TABLE='INVENTJOURNALTRANS', @COLUMN='VOUCHER'
EXEC spDeleteColumnAndConstaint @TABLE='INVENTJOURNALTRANS', @COLUMN='JOURNALTYPE'
EXEC spDeleteColumnAndConstaint @TABLE='INVENTJOURNALTRANS', @COLUMN='DIMENSION'
EXEC spDeleteColumnAndConstaint @TABLE='INVENTJOURNALTRANS', @COLUMN='DIMENSION2_'
EXEC spDeleteColumnAndConstaint @TABLE='INVENTJOURNALTRANS', @COLUMN='DIMENSION3_'


GO