
/*

	Incident No.	: N/A
	Responsible		: Hrólfur Gestsson 
	Description		: Update as a result of the new Fiscal service	
							
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM POSISOPERATIONS WHERE OPERATIONID = 134)
Begin
  insert into POSISOPERATIONS ( OPERATIONID, OPERATIONNAME, PERMISSIONID, PERMISSIONID2, CHECKUSERACCESS, USEROPERATION,DATAAREAID,LOOKUPTYPE)
  values (134, 'Journal log export',	NULL,	NULL,	1,	1, 'LSR', 0)
End


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONREPRINTTRANS'))
BEGIN

	CREATE TABLE dbo.RBOTRANSACTIONREPRINTTRANS
		(
		TRANSACTIONID nvarchar(20) NOT NULL,
		STORE nvarchar(20) NOT NULL,
		TERMINAL nvarchar(20) NOT NULL,
		DATAAREAID nvarchar(4) NOT NULL,
		LINENUM int NOT NULL,	
		REPLICATIONCOUNTER int NOT NULL IDENTITY (1, 1),
		PRINTDATE datetime NULL,
		STAFF nvarchar(20) NULL,
		PRINTSTORE nvarchar(20) NULL,
		PRINTTERMINAL nvarchar(20) NULL,		
		REPRINTTYPE int NULL,
		)  ON [PRIMARY]


	ALTER TABLE dbo.RBOTRANSACTIONREPRINTTRANS ADD CONSTRAINT
		PK_RBOTRANSACTIONREPRINTTRANS PRIMARY KEY CLUSTERED 
		(
		TRANSACTIONID,
		LINENUM,
		STORE,
		TERMINAL,
		DATAAREAID
		)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON
	) ON [PRIMARY]

END