
/*

	Incident No.	: N/A
	Responsible		: Marý B Steingrímsdóttir
	Sprint			: Gina
	Date created	: 13.9.2014

	Description		: X/Z report changes merged
	
						
*/

USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISSUSPENDEDTRANSACTIONS' AND COLUMN_NAME = 'LOCALLYSAVED')
BEGIN
	ALTER TABLE POSISSUSPENDEDTRANSACTIONS ADD LOCALLYSAVED TINYINT
	ALTER TABLE dbo.POSISSUSPENDEDTRANSACTIONS ADD CONSTRAINT DF_POSISSUSPENDEDTRANSACTIONS_LOCALLYSAVED DEFAULT 0 FOR LOCALLYSAVED	
END

GO

-- Update all the existing transactions to be Locally saved = false
UPDATE POSISSUSPENDEDTRANSACTIONS
SET LOCALLYSAVED = 0
WHERE LOCALLYSAVED IS NULL

GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTDISPLAYRETURNINFO')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTDISPLAYRETURNINFO tinyint
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTDISPLAYSUSPENDED')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTDISPLAYSUSPENDED TINYINT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTDISPLAYOTHERINFO')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTDISPLAYOTHERINFO TINYINT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTGRANDTOTALAMTDISPLAY')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTGRANDTOTALAMTDISPLAY INT
END
GO


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTSALESRPTAMTDISPLAY')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTSALESRPTAMTDISPLAY INT
END

GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTCOMBINESALESREPORTSALESRETURNS')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ZRPTCOMBINESALESREPORTSALESRETURNS TINYINT
END
GO



