USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYFUNCTIONALPROFILE') AND NAME='BUMPPOSSIBLE')
BEGIN
	 ALTER TABLE KITCHENDISPLAYFUNCTIONALPROFILE Add BUMPPOSSIBLE int NOT NULL default 0 
END	
GO