USE LSPOSNET

GO

if not exists(select * from INFORMATION_SCHEMA.COLUMNS where  TABLE_NAME = 'POSHARDWAREPROFILE' and COLUMN_NAME = 'DALLASKEYCONNECTED')
BEGIN
ALTER TABLE POSHARDWAREPROFILE ADD DALLASKEYCONNECTED TINYINT
END

if not exists(select * from INFORMATION_SCHEMA.COLUMNS where  TABLE_NAME = 'POSHARDWAREPROFILE' and COLUMN_NAME = 'DALLASMESSAGEPREFIX')
BEGIN
ALTER TABLE POSHARDWAREPROFILE ADD DALLASMESSAGEPREFIX NVARCHAR(50)
END

if not exists(select * from INFORMATION_SCHEMA.COLUMNS where  TABLE_NAME = 'POSHARDWAREPROFILE' and COLUMN_NAME = 'DALLASKEYREMOVEDMESSAGE')
BEGIN
ALTER TABLE POSHARDWAREPROFILE ADD DALLASKEYREMOVEDMESSAGE NVARCHAR(50)
END
if not exists(select * from INFORMATION_SCHEMA.COLUMNS where  TABLE_NAME = 'POSHARDWAREPROFILE' and COLUMN_NAME = 'DALLASCOMPORT')
BEGIN
ALTER TABLE POSHARDWAREPROFILE ADD DALLASCOMPORT NVARCHAR(6)
END

if not exists(select * from INFORMATION_SCHEMA.COLUMNS where  TABLE_NAME = 'POSHARDWAREPROFILE' and COLUMN_NAME = 'DALLASBAUDRATE')
BEGIN
ALTER TABLE POSHARDWAREPROFILE ADD DALLASBAUDRATE INT
END

if not exists(select * from INFORMATION_SCHEMA.COLUMNS where  TABLE_NAME = 'POSHARDWAREPROFILE' and COLUMN_NAME = 'DALLASPARITY')
BEGIN
ALTER TABLE POSHARDWAREPROFILE ADD DALLASPARITY INT
END

if not exists(select * from INFORMATION_SCHEMA.COLUMNS where  TABLE_NAME = 'POSHARDWAREPROFILE' and COLUMN_NAME = 'DALLASSTOPBITS')
BEGIN
ALTER TABLE POSHARDWAREPROFILE ADD DALLASSTOPBITS INT
END

if not exists(select * from INFORMATION_SCHEMA.COLUMNS where  TABLE_NAME = 'POSHARDWAREPROFILE' and COLUMN_NAME = 'DALLASDATABITS')
BEGIN
ALTER TABLE POSHARDWAREPROFILE ADD DALLASDATABITS INT
END
