/*

	Incident No.	: 23021
	Responsible		: Hörður Kristjánsson
	Sprint			: LS Retail .NET 2013.1\S1
	Date created	: 05.04.2013

	Description		: Added new transaction table
	
	Tables affected	: added RBOTRANSACTIONDININGTABLE
						
*/

USE LSPOSNET

GO

if not exists(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'RBOTRANSACTIONDININGTABLE')
BEGIN
CREATE TABLE [dbo].[RBOTRANSACTIONDININGTABLE](
	[TRANSACTIONID] [nvarchar](20) NOT NULL,
	[STORE] [nvarchar](20) NOT NULL,
	[TERMINAL] [nvarchar](20) NOT NULL,
	[SALESTYPE] [nvarchar](20) NULL,
	[DININGTABLELAYOUTID] [nvarchar](20) NULL,
	[DINEINTABLENO] [int] NULL,
	[NOOFGUESTS] [int] NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[REPLICATIONCOUNTER] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_RBOTRANSACTIONDININGTABLE] PRIMARY KEY CLUSTERED 
(
	[TRANSACTIONID] ASC,
	[STORE] ASC,
	[TERMINAL] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END