USE LSPOSNET

GO

if not exists(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'STATIONPRINTINGHOSTS')
BEGIN
	CREATE TABLE [dbo].[STATIONPRINTINGHOSTS](
		[ID] [nvarchar](20) NOT NULL,
		[DESCRIPTION] [nvarchar](60) NULL,
		[ADDRESS] [nvarchar](100) NULL,
		[PORT] [int] NULL,
		[CHARSET] [int] NULL,
		[LOCKCODE] [nvarchar](50) NULL,
		[DEBUGLEVELCON] [int] NULL,
		[DEBUGLEVELFILE] [int] NULL,
		[DEBUGFILESIZE] [int] NULL,
		[DEBUGFILECOUNT] [int] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_STATIONPRINTINGHOST] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

GO