USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILE') AND NAME='RUSHBORDERCOLOR')
BEGIN
	 ALTER TABLE KITCHENDISPLAYVISUALPROFILE Add RUSHBORDERCOLOR int NULL 
END	
GO