USE LSPOSNET

GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATEUNITS')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATEUNITS](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[UNITID] [nvarchar](20) NOT NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATEUNITS] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC,
		[UNITID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATETILLLAYOUTS')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATETILLLAYOUTS](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[LINENUM] [int] NOT NULL,
		[TILLLAYOUTID] [nvarchar](20) NULL,
		[RETAILGRID] [nvarchar](20) NULL,
		[ITEMGRIDID] [nvarchar](20) NULL,
		[IMAGE] [varbinary](max) NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATETILLLAYOUTS] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC,
		[LINENUM] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATETENDERS')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATETENDERS](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[TENDERTYPEID] [nvarchar](20) NOT NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATETENDERS] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC,
		[TENDERTYPEID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATETAX')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATETAX](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[TAXGROUPTYPE] [int] NULL,
		[TAXGROUP] [nvarchar](20) NOT NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATETAX] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC,
		[TAXGROUP] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATERETAILGROUPS')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATERETAILGROUPS](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[RETAILGROUPID] [nvarchar](20) NOT NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATERETAILGROUPS] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC,
		[RETAILGROUPID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATEPERMISSION')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATEPERMISSION](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[PERMISSIONGROUPID] [nvarchar](20) NOT NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATEPERMISSION] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC,
		[PERMISSIONGROUPID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATEPERIPHERALS')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATEPERIPHERALS](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[DRAWER] [tinyint] NULL,
		[LINEDISPLAY] [tinyint] NULL,
		[DUALDISPLAY] [tinyint] NULL,
		[CARDREADER] [tinyint] NULL,
		[PRINTER] [tinyint] NULL,
		[BARCODE] [tinyint] NULL,
		[SCALE] [tinyint] NULL,
		[KEY] [tinyint] NULL,
		[EFT] [tinyint] NULL,
		[RFID] [tinyint] NULL,
		[CASHCHANGER] [tinyint] NULL,
		[FISCALPRINTER] [tinyint] NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATEPERIPHERALS] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATEFORMLAYOUTS')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATEFORMLAYOUTS](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[LINENUM] [int] NOT NULL,
		[FORMLAYOUTID] [nvarchar](20) NULL,
		[IMAGE] [image] NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATEFORMLAYOUTS] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC,
		[LINENUM] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATECURRENCY')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATECURRENCY](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[CURRENCY] [nvarchar](3) NOT NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATECURRENCY] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC,
		[CURRENCY] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = N'WIZARDTEMPLATE')
BEGIN
	CREATE TABLE [dbo].[WIZARDTEMPLATE](
		[ID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
		[DESCRIPTION] [nvarchar](60) NOT NULL,
		[STATUS] [int] NULL,
		[LASTEXPORTDATE] [datetime] NULL,
		[IMAGE] [varbinary](max) NULL,
		[STOREID] [nvarchar](20) NULL,
		[TERMINALID] [nvarchar](20) NULL,
		[NAME] [int] NULL,
		[ADDRESS] [int] NULL,
		[PRICECALCULATION] [int] NULL,
		[CHOOSENAME] [tinyint] NULL,
		[CHOOSEADDRESS] [tinyint] NULL,
		[VISUALPROFILEID] [nvarchar](20) NULL,
		[FUNCTIONALITYPROFILEID] [nvarchar](20) NULL,
		[STORESERVERPROFILEID] [nvarchar](20) NULL,
		[DEFAULTCURRENCY] [nvarchar](3) NULL,
		[CHOOSEPAYMENTS] [tinyint] NULL,
		[HARDWAREPROFILEID] [nvarchar](20) NULL,
		[CHOOSEPERIPHERALS] [tinyint] NULL,
		[CHOOSETILLLAYOUTS] [tinyint] NULL,
		[CHOOSERECEIPTS] [tinyint] NULL,
		[CHOOSERETAILGROUPS] [tinyint] NULL,
		[CHOOSEPERMISSIONGROUP] [tinyint] NULL,
	 CONSTRAINT [PK_WIZARDTEMPLATE] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC,
		[DESCRIPTION] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
