USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOINTEGRATIONMAPPINGS'))
BEGIN
	CREATE TABLE [RBOINTEGRATIONMAPPINGS](
		[TABLENAME] [nvarchar](60) NOT NULL,
		[EXTERNALID] [nvarchar](20) NOT NULL,
		[INTERNALID] [nvarchar](20) NOT NULL,
		[CREATED] [datetime] NOT NULL,
		[UPDATED] [datetime],
		[DATAAREAID] [nvarchar](4) NOT NULL,
		CONSTRAINT [PK_RBOINTEGRATIONMAPPINGS] PRIMARY KEY CLUSTERED 
		(
			[TABLENAME] ASC,
			[EXTERNALID] ASC,
			[DATAAREAID] ASC
		)
		WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOINTEGRATIONLOG'))
BEGIN
	CREATE TABLE [RBOINTEGRATIONLOG] (
	    [ID] [BIGINT] IDENTITY(1,1) NOT NULL,
		[STAMP] [datetime] NOT NULL,
		[ERRORID] [int],
		[LOGTYPE] [nvarchar](20) NOT NULL,
		[METHOD] [nvarchar](40) NOT NULL,
		[MESSAGE] [nvarchar](4000),
		[DATAAREAID] [nvarchar](4) NOT NULL,
		CONSTRAINT [PK_RBOINTEGRATIONLOG] PRIMARY KEY
		(
			[ID] ASC
		)
		WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
