USE LSPOSNET
GO
  
IF NOT EXISTS (SELECT 'x' FROM POSISOPERATIONS WHERE OPERATIONID='1501')
Begin
	insert into POSISOPERATIONS ( OPERATIONID, OPERATIONNAME, PERMISSIONID, PERMISSIONID2, CHECKUSERACCESS, USEROPERATION,DATAAREAID,LOOKUPTYPE)
	values (1501, 'Refresh kitchen displays',	NULL,	NULL,	1,	1,'LSR',0)
End


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='KITCHENDISPLAYLOG' AND COLUMN_NAME='ORDERID' AND CHARACTER_MAXIMUM_LENGTH = 20)
Begin
	Alter table KITCHENDISPLAYLOG Alter column ORDERID nvarchar(50) 
End