USE LSPOSNET
GO
  
 IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONTABLE'  AND COLUMN_NAME = 'INVENTORYUPDATED')
 BEGIN
	ALTER TABLE RBOTRANSACTIONTABLE ADD INVENTORYUPDATED bit NOT NULL DEFAULT 0
 END

GO