USE LSPOSNET
GO
  
 IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'INVENTORYTEMPLATEITEMFILTERSECTIONS')
 BEGIN
	 CREATE TABLE [dbo].[INVENTORYTEMPLATEITEMFILTERSECTIONS](
		[ID] [nvarchar](20) NOT NULL,
		[INVENTORYTEMPLATEIDID] [nvarchar](20) NOT NULL,
		[SORTRANK] int NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_INVENTORYTEMPLATEITEMFILTERSECTIONS] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[INVENTORYTEMPLATEIDID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
 END

 IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'INVENTORYTEMPLATEITEMFILTERSELECTIONS')
 BEGIN
	 CREATE TABLE [dbo].[INVENTORYTEMPLATEITEMFILTERSELECTIONS](
		[ID] [nvarchar](20) NOT NULL,
		[SECTIONID] [nvarchar](20) NOT NULL,
		[INVENTORYTEMPLATEIDID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_INVENTORYTEMPLATEITEMFILTERSELECTIONS] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[SECTIONID] ASC,
		[INVENTORYTEMPLATEIDID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
 END

GO