/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 20.5.2013

	Description		: New tables for label templates and label queues
						
*/
USE LSPOSNET
GO
  
IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'RBOLABELTEMPLATES')
BEGIN
	CREATE TABLE [dbo].RBOLABELTEMPLATES(
		[LABELID] [NVARCHAR](20) NOT NULL,
		[NAME] [NVARCHAR](100) NOT NULL,
		[DESCRIPTION] [NVARCHAR](400) NULL,
		[CONTEXT] [int] NOT NULL,
		[TEMPLATE] [NVARCHAR](max) NOT NULL,
		[SAMPLEIMAGE] [VARBINARY](max) NULL,
		[CODEPAGE] [NVARCHAR](10) NULL,
		[DATAAREAID] [NVARCHAR](4) NOT NULL,
		CONSTRAINT [PK_RBOLABELTEMPLATES] PRIMARY KEY CLUSTERED 
	(
		[LABELID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	CREATE UNIQUE NONCLUSTERED INDEX [UIDX_CONTEXTNAME] ON [dbo].[RBOLABELTEMPLATES]
	(
		[CONTEXT] ASC,
		[NAME] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
END

GO

  
IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'RBOLABELQUEUE')
BEGIN
	CREATE TABLE [dbo].RBOLABELQUEUE(
		[LABELQUEUEID] int IDENTITY(1,1) NOT NULL,
		[PRINTER] [NVARCHAR](100) NOT NULL,
		[NUMBEROFLABELS] [int] NOT NULL,
		[LABELTEMPLATEID] [NVARCHAR](20) NULL,
		[ENTITYID] [NVARCHAR](20) NOT NULL,
		[DATAAREAID] [NVARCHAR](4) NOT NULL,
		[BATCH] [NVARCHAR](100) NULL,
		[PRINTED] [DATETIME] NULL,
		[MESSAGE] [NVARCHAR](400) NULL,
		CONSTRAINT [PK_RBOLABELQUEUE] PRIMARY KEY CLUSTERED 
	(
		[LABELQUEUEID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [IDX_NOTPRINTED] ON [dbo].RBOLABELQUEUE
	(
		[BATCH] ASC,
		[PRINTED] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
END
