USE LSPOSNET
GO
  
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONINFOCODETRANS' AND COLUMN_NAME = 'INFORMATION' AND CHARACTER_MAXIMUM_LENGTH < 120)
BEGIN
	alter table RBOTRANSACTIONINFOCODETRANS ALTER COLUMN INFORMATION NVARCHAR(120)
END


GO




