USE LSPOSNET
GO
  
 IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSTRANSACTIONSERVICEPROFILE'  AND COLUMN_NAME = 'IMMEDIATELYUPDATEINVENTORY')
 BEGIN
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ADD IMMEDIATELYUPDATEINVENTORY bit NOT NULL DEFAULT 0
 END

GO