USE LSPOSNET
GO
  
 IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'INVENTORYTEMPLATE')
 BEGIN
	 CREATE TABLE [dbo].[INVENTORYTEMPLATE](
		[ID] [nvarchar](20) NOT NULL,
		[NAME] [nvarchar](100) NOT NULL,
		[UNIT] [int] NOT NULL,
		[CHANGEVENDORINLINE] [bit] NOT NULL,
		[CHANGEUOMINLINE] [bit] NOT NULL,
		[CALCULATESUGGESTEDQUANTITY] [bit] NOT NULL,
		[SETQUANTITYTOSUGGESTEDQUANTITY] [bit] NOT NULL,
		[DISPLAYREORDERPOINT] [bit] NOT NULL,
		[DISPLAYMAXIMUMINVENTORY] [bit] NOT NULL,
		[DISPLAYBARCODE] [bit] NOT NULL,
		[ALLSTORES] [bit] NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_INVENTORYTEMPLATE] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
 END

   IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'INVENTORYTEMPLATESTORECONNECTION')
 BEGIN
	 CREATE TABLE [dbo].INVENTORYTEMPLATESTORECONNECTION(
		[ID] [uniqueidentifier] NOT NULL DEFAULT newid(),
		[INVENTORYTEMPLATEID] [nvarchar](20) NOT NULL,
		[STOREID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_INVENTORYTEMPLATESTORECONNECTION] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
 END

 IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'PURCHASEWORKSHEET')
 BEGIN
	 CREATE TABLE [dbo].[PURCHASEWORKSHEET](
		[ID] [nvarchar](20) NOT NULL,
		[INVENTORYTEMPLATEID] [nvarchar](20) NOT NULL,
		[STOREID] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_PURCHASEWORKSHEET] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
 END
 
  IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'PURCHASEWORKSHEETLINE')
 BEGIN
	 CREATE TABLE [dbo].[PURCHASEWORKSHEETLINE](
		[ID] uniqueidentifier NOT NULL,
		[PURCHASEWORKSHEETID] [nvarchar](20) NOT NULL,
		[BARCODENUMBER] [nvarchar](100) NOT NULL,
		[ITEMID] [nvarchar](20) NOT NULL,
		[QUANTITY] [numeric](24,6) NOT NULL,
		[UNITID] [nvarchar](20) NOT NULL,
		[VENDORID] [nvarchar](20) NOT NULL,
		[SUGGESTEDQUANTITY] [numeric](24,6) NOT NULL,		
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_PURCHASEWORKSHEETLINE] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
 END

GO