USE LSPOSNET
GO
  
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE'  AND COLUMN_NAME = 'ORDERTIMESTART')
 BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE DROP COLUMN ORDERTIMESTART
 END

GO




