USE LSPOSNET
GO
  
 IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'USERSETTINGS' AND COLUMN_NAME = N'LONGTEXT')
 BEGIN
 ALTER TABLE USERSETTINGS ADD LONGTEXT NVARCHAR(MAX)
 END

GO
