
/*

	Incident No.	: 22666
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 28.5.2013

	Description		: Add fields to RboTransactionLoyaltyTrans table
					  Updates new field (RELATION) on data already in table if any	
					  Adds field RELATION to the primary key
						
*/

USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'RBOTRANSACTIONLOYALTYPOINTTRANS'  AND COLUMN_NAME = 'RULEID')
 BEGIN
	ALTER TABLE [dbo].RBOTRANSACTIONLOYALTYPOINTTRANS ADD RULEID uniqueidentifier NULL
	ALTER TABLE [dbo].RBOTRANSACTIONLOYALTYPOINTTRANS ADD RELATION INT NULL	
 END

GO

UPDATE RBOTRANSACTIONLOYALTYPOINTTRANS
SET RELATION = 0
WHERE RELATION IS NULL
GO

BEGIN TRANSACTION

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__TRANS__12B48446]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS DROP CONSTRAINT DF__RBOTRANSA__TRANS__12B48446
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__LINEN__13A8A87F]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS DROP CONSTRAINT DF__RBOTRANSA__LINEN__13A8A87F
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__RECEI__149CCCB8]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__RECEI__149CCCB8
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__POINT__1590F0F1]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__POINT__1590F0F1
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__DATEO__1685152A]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__DATEO__1685152A
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__STORE__17793963]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__STORE__17793963
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__TERMI__186D5D9C]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__TERMI__186D5D9C
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__CARDN__196181D5]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__CARDN__196181D5
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__SEQUE__1A55A60E]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__SEQUE__1A55A60E
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__LOYAL__1B49CA47]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__LOYAL__1B49CA47
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__ENTRY__1C3DEE80]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__ENTRY__1C3DEE80
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__EXPIR__1D3212B9]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__EXPIR__1D3212B9
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__LOYAL__1E2636F2]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__LOYAL__1E2636F2
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__STATE__1F1A5B2B]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__STATE__1F1A5B2B
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__STATE__200E7F64]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__STATE__200E7F64
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__STAFF__2102A39D]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__STAFF__2102A39D
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__MODIF__21F6C7D6]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__MODIF__21F6C7D6
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__MODIF__22EAEC0F]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__MODIF__22EAEC0F
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__MODIF__23DF1048]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__MODIF__23DF1048
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__CREAT__24D33481]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__CREAT__24D33481
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__CREAT__25C758BA]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__CREAT__25C758BA
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__CREAT__26BB7CF3]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__CREAT__26BB7CF3
END

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__RBOTRANSA__DATAA__27AFA12C]') AND type = 'D')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS	DROP CONSTRAINT DF__RBOTRANSA__DATAA__27AFA12C
END

CREATE TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS
	(
	TRANSACTIONID nvarchar(20) NOT NULL,
	LINENUM numeric(28, 12) NOT NULL,
	RECEIPTID nvarchar(20) NULL,
	POINTS numeric(28, 12) NULL,
	DATEOFISSUE datetime NULL,
	STOREID nvarchar(20) NOT NULL,
	TERMINALID nvarchar(20) NOT NULL,
	CARDNUMBER nvarchar(30) NULL,
	SEQUENCENUMBER int NULL,
	LOYALTYCUSTID nvarchar(20) NULL,
	ENTRYTYPE int NULL,
	EXPIRATIONDATE datetime NULL,
	LOYALTYSCHEMEID nvarchar(20) NULL,
	STATEMENTID nvarchar(20) NULL,
	STATEMENTCODE nvarchar(20) NULL,
	STAFFID nvarchar(20) NULL,
	MODIFIEDDATE datetime NULL,
	MODIFIEDTIME int NULL,
	MODIFIEDBY uniqueidentifier NULL,
	CREATEDDATE datetime NULL,
	CREATEDTIME int NULL,
	CREATEDBY uniqueidentifier NULL,
	DATAAREAID nvarchar(4) NOT NULL,
	REPLICATED tinyint NULL,
	REPLICATIONCOUNTER int NOT NULL IDENTITY (1, 1),
	ACCUMULATEDPOINTS numeric(28, 12) NULL,
	RULEID uniqueidentifier NULL,
	RELATION int NOT NULL
	)  ON [PRIMARY]

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS SET (LOCK_ESCALATION = TABLE)

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__TRANS__12B48446 DEFAULT ('') FOR TRANSACTIONID

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__LINEN__13A8A87F DEFAULT ((0)) FOR LINENUM

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__RECEI__149CCCB8 DEFAULT ('') FOR RECEIPTID

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__POINT__1590F0F1 DEFAULT ((0)) FOR POINTS

ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__DATEO__1685152A DEFAULT (getdate()) FOR DATEOFISSUE

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__STORE__17793963 DEFAULT ('') FOR STOREID

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__TERMI__186D5D9C DEFAULT ('') FOR TERMINALID

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__CARDN__196181D5 DEFAULT ('') FOR CARDNUMBER

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__SEQUE__1A55A60E DEFAULT ((0)) FOR SEQUENCENUMBER

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__LOYAL__1B49CA47 DEFAULT ('') FOR LOYALTYCUSTID

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__ENTRY__1C3DEE80 DEFAULT ((0)) FOR ENTRYTYPE

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__EXPIR__1D3212B9 DEFAULT ('1900-01-01 00:00:00.000') FOR EXPIRATIONDATE

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__LOYAL__1E2636F2 DEFAULT ('') FOR LOYALTYSCHEMEID

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__STATE__1F1A5B2B DEFAULT ('') FOR STATEMENTID

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__STATE__200E7F64 DEFAULT ('') FOR STATEMENTCODE

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__STAFF__2102A39D DEFAULT ('') FOR STAFFID

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__MODIF__21F6C7D6 DEFAULT GetDate() FOR MODIFIEDDATE

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__MODIF__22EAEC0F DEFAULT ((0)) FOR MODIFIEDTIME

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__MODIF__23DF1048 DEFAULT ('00000000-0000-0000-0000-000000000000') FOR MODIFIEDBY

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__CREAT__24D33481 DEFAULT GetDate() FOR CREATEDDATE

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__CREAT__25C758BA DEFAULT ((0)) FOR CREATEDTIME

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__CREAT__26BB7CF3 DEFAULT ('00000000-0000-0000-0000-000000000000') FOR CREATEDBY

ALTER TABLE dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	DF__RBOTRANSA__DATAA__27AFA12C DEFAULT ('LSR') FOR DATAAREAID

SET IDENTITY_INSERT dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS ON

IF EXISTS(SELECT * FROM dbo.RBOTRANSACTIONLOYALTYPOINTTRANS)
		EXEC('INSERT INTO dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS (TRANSACTIONID, LINENUM, RECEIPTID, POINTS, DATEOFISSUE, STOREID, TERMINALID, CARDNUMBER, SEQUENCENUMBER, LOYALTYCUSTID, ENTRYTYPE, EXPIRATIONDATE, LOYALTYSCHEMEID, STATEMENTID, STATEMENTCODE, STAFFID, MODIFIEDDATE, MODIFIEDTIME, MODIFIEDBY, CREATEDDATE, CREATEDTIME, CREATEDBY, DATAAREAID, REPLICATED, REPLICATIONCOUNTER, ACCUMULATEDPOINTS, RULEID, RELATION)
		SELECT TRANSACTIONID, LINENUM, RECEIPTID, POINTS, DATEOFISSUE, STOREID, TERMINALID, CARDNUMBER, SEQUENCENUMBER, LOYALTYCUSTID, ENTRYTYPE, EXPIRATIONDATE, LOYALTYSCHEMEID, STATEMENTID, STATEMENTCODE, STAFFID, MODIFIEDDATE, MODIFIEDTIME, MODIFIEDBY, CREATEDDATE, CREATEDTIME, CREATEDBY, DATAAREAID, REPLICATED, REPLICATIONCOUNTER, ACCUMULATEDPOINTS, RULEID, RELATION FROM dbo.RBOTRANSACTIONLOYALTYPOINTTRANS WITH (HOLDLOCK TABLOCKX)')

SET IDENTITY_INSERT dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS OFF

DROP TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS

EXECUTE sp_rename N'dbo.Tmp_RBOTRANSACTIONLOYALTYPOINTTRANS', N'RBOTRANSACTIONLOYALTYPOINTTRANS', 'OBJECT' 

ALTER TABLE dbo.RBOTRANSACTIONLOYALTYPOINTTRANS ADD CONSTRAINT
	I_20296TRANSACTIONLINEIDX PRIMARY KEY CLUSTERED 
	(
	TRANSACTIONID,
	LINENUM,
	STOREID,
	TERMINALID,
	DATAAREAID,
	RELATION
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


COMMIT
GO
