USE LSPOSNET

GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'VENDTABLE' AND COLUMN_NAME = 'DELIVERYDAYSTYPE')
BEGIN
ALTER TABLE VENDTABLE ADD DELIVERYDAYSTYPE int NULL
END

GO
