USE LSPOSNET

GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILE' AND COLUMN_NAME = 'ORDERPROPERTIESMODIFIEDSTYLEID')
BEGIN
ALTER TABLE KITCHENDISPLAYSTYLEPROFILE ADD ORDERPROPERTIESMODIFIEDSTYLEID nvarchar(20) NULL
END

GO
