/*

	Incident No.	: 23692
	Responsible		: Höður Sigurdór Heiðarsson
	Sprint			: LS One 2013.1\S1
	Date created	: 28.05.2013

	Description		: 'KEY' column renamed to 'KEYLOCK'
	
	Tables affected	: WIZARDTEMPLATEPERIPHERALS
						
*/

USE LSPOSNET
GO
  
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'WIZARDTEMPLATEPERIPHERALS'  AND COLUMN_NAME = 'KEY')
 BEGIN
	ALTER TABLE [dbo].[WIZARDTEMPLATEPERIPHERALS] DROP COLUMN [KEY]
	ALTER TABLE [dbo].[WIZARDTEMPLATEPERIPHERALS] ADD [KEYLOCK] TINYINT NULL
 END
GO