
/*

	Incident No.	: 23995
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 03.06.2013

	Description		: Add item replenishment tables
						
*/

USE LSPOSNET
GO

if not exists(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ITEMREPLENISHMENTSETTING')
BEGIN
	CREATE TABLE [dbo].[ITEMREPLENISHMENTSETTING](
		[ID] [uniqueidentifier] NOT NULL,
		[ITEMID] [nvarchar](20) NOT NULL,
		[STOREID] [nvarchar](20) NOT NULL,
		[REPLENISHMENTMETHOD] [int] NOT NULL,
		[REORDERPOINT] [decimal](24,6) NOT NULL,
		[MAXIMUMINVENTORY] [decimal](24,6) NOT NULL,
		[PURCHASEORDERMULTIPLE] [int] NOT NULL,
		[PURCHASEORDERMULTIPLEROUNDING] [int] NOT NULL,
		[BLOCKEDFORREPLENISHMENT] [int] NOT NULL,
		[BLOCKINGDATE] [DateTime] NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL,
	 CONSTRAINT [PK_ITEMREPLENISHMENTSETTING] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

GO
