/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 04.6.2013

	Description		: Added image index to item image table and support more than one image per item
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOINVENTITEMIMAGE' AND COLUMN_NAME = 'IMAGEINDEX')
BEGIN
	ALTER TABLE [dbo].[RBOINVENTITEMIMAGE] ADD IMAGEINDEX tinyint; 
END
GO

UPDATE [dbo].[RBOINVENTITEMIMAGE] SET IMAGEINDEX=1 where IMAGEINDEX IS NULL
GO

ALTER TABLE [dbo].[RBOINVENTITEMIMAGE] ALTER COLUMN IMAGEINDEX tinyint NOT NULL; 
GO

IF EXISTS (select * from sys.objects where name ='PK_RBOINVENTITEMIMAGE'and parent_object_id=OBJECT_ID('RBOINVENTITEMIMAGE'))
BEGIN
	ALTER TABLE [dbo].[RBOINVENTITEMIMAGE] DROP CONSTRAINT [PK_RBOINVENTITEMIMAGE]
END
GO

IF NOT EXISTS (select * from sys.objects where name ='PK_RBOINVENTITEMIMAGE'and parent_object_id=OBJECT_ID('RBOINVENTITEMIMAGE'))
BEGIN
	ALTER TABLE [dbo].[RBOINVENTITEMIMAGE] ADD  CONSTRAINT [PK_RBOINVENTITEMIMAGE] PRIMARY KEY CLUSTERED 
	(
		[ITEMID] ASC,
		[IMAGEINDEX] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO