
/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 09.06.2013

	Description		: New tables for email settings, email queue and email queue attachments
						
*/

USE LSPOSNET
GO

IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'EMAILSETTINGS')
BEGIN
	CREATE TABLE [dbo].EMAILSETTINGS(
		[EMAILSETTINGID] int IDENTITY(1,1) NOT NULL,
		[STOREID] [NVARCHAR](20) NULL,
		[SMTPSERVER] [NVARCHAR](100) NOT NULL,
		[SMTPPORT] int NOT NULL,
		[SMTPEMAILADDRESS] [NVARCHAR](100) NOT NULL,
		[SMTPPASSWORD] [NVARCHAR](100) NOT NULL,
		[SMTPDISPLAYNAME] [NVARCHAR](100) NOT NULL,
		[USESSL] int NOT NULL,
		[TEXTONLY] int NOT NULL,
		[SIGNATURE] [NVARCHAR](500) NULL,
		[DATAAREAID] [NVARCHAR](4) NOT NULL,
		CONSTRAINT [PK_EMAILSETTINGS] PRIMARY KEY CLUSTERED 
	(
		[EMAILSETTINGID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
  
IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'EMAILQUEUE')
BEGIN
	CREATE TABLE [dbo].EMAILQUEUE(
		[EMAILID] int IDENTITY(1,1) NOT NULL,
		[STOREID] [NVARCHAR](20) NULL,
		[SENT] [DATETIME] NULL,
		[PRIORITY] [int] NOT NULL,
		[ATTEMPTS] [int] NOT NULL,
		[LASTERROR] [NVARCHAR](100) NULL,
		[TO] [NVARCHAR](500) NOT NULL,
		[CC] [NVARCHAR](500) NULL,
		[BCC] [NVARCHAR](500) NULL,
		[SUBJECT] [NVARCHAR](200) NULL,
		[BODY] [NVARCHAR](max) NOT NULL,
		[BODYISHTML] [int] NOT NULL,
		[CREATED] [DATETIME] NOT NULL,
		[MODIFIED] [DATETIME] NOT NULL,
		[DATAAREAID] [NVARCHAR](4) NOT NULL,
		CONSTRAINT [PK_EMAILQUEUE] PRIMARY KEY CLUSTERED 
	(
		[EMAILID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF NOT EXISTS(SELECT 'x' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'EMAILQUEUEATTACHMENT')
BEGIN
	CREATE TABLE [dbo].EMAILQUEUEATTACHMENT(
		[EMAILATTACHMENTID] int IDENTITY(1,1) NOT NULL,
		[EMAILID] int NOT NULL,
		[NAME] [NVARCHAR](200) NOT NULL,
		[ATTACHMENT] [VARBINARY](max) NOT NULL,
		[DATAAREAID] [NVARCHAR](4) NOT NULL,
		CONSTRAINT [PK_EMAILQUEUEATTACHMENT] PRIMARY KEY CLUSTERED 
	(
		[EMAILATTACHMENTID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].EMAILQUEUEATTACHMENT  WITH CHECK ADD  CONSTRAINT [FK_EMAILQUEUEATTACHMENT] FOREIGN KEY([EMAILID])
	REFERENCES [dbo].[EMAILQUEUE] ([EMAILID])

	CREATE NONCLUSTERED INDEX [IDX_EMAILID] ON [dbo].[EMAILQUEUEATTACHMENT]
	(
		[EMAILID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO

