/*

	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 10.06.2013

	Description		: Added tables to support mapping between EFT device scheme names and tender types (payment types)
*/
USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'EFTMERCHANTACCOUNT')
BEGIN
	ALTER TABLE [dbo].POSHARDWAREPROFILE ADD EFTMERCHANTACCOUNT NVARCHAR(100); 
	ALTER TABLE [dbo].POSHARDWAREPROFILE ADD EFTMERCHANTKEY NVARCHAR(200); 
	ALTER TABLE [dbo].POSHARDWAREPROFILE ADD EFTCUSTOMFIELD1 NVARCHAR(100); 
	ALTER TABLE [dbo].POSHARDWAREPROFILE ADD EFTCUSTOMFIELD2 NVARCHAR(100); 
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'EFTSERVERNAME' AND CHARACTER_MAXIMUM_LENGTH < 120)
BEGIN
	alter table [dbo].POSHARDWAREPROFILE ALTER COLUMN EFTSERVERNAME NVARCHAR(120)
	alter table [dbo].POSHARDWAREPROFILE ALTER COLUMN EFTDESCRIPTION NVARCHAR(100)
	alter table [dbo].POSHARDWAREPROFILE ALTER COLUMN EFTCOMPANYID NVARCHAR(100)
	alter table [dbo].POSHARDWAREPROFILE ALTER COLUMN EFTUSERID NVARCHAR(100)
	alter table [dbo].POSHARDWAREPROFILE ALTER COLUMN EFTPASSWORD NVARCHAR(50)
END
