/*
	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 05.06.2013

	Description		: Move data from customer table to customer address table
					  Drop columns from customer table
*/

USE LSPOSNET
GO

IF (0 = (SELECT count(*) FROM [dbo].[CUSTOMERADDRESS] WHERE [DATAAREAID] = 'LSR'))
BEGIN
	exec sp_executesql N'INSERT into dbo.[CUSTOMERADDRESS](ACCOUNTNUM,DATAAREAID,ADDRESSTYPE,STREET,ADDRESS,ZIPCODE,CITY,STATE,COUNTY,COUNTRY,ADDRESSFORMAT,TAXGROUP,PHONE,CELLULARPHONE,EMAIL)
		SELECT ACCOUNTNUM,DATAAREAID,0,STREET,ADDRESS,ZIPCODE,CITY,STATE,COUNTY,COUNTRY,ADDRESSFORMAT,null,PHONE,CELLULARPHONE,EMAIL
			FROM dbo.[CUSTTABLE] WHERE [DATAAREAID] = ''LSR'''
END

/* Removed so that DD replication will still work on the customer table
IF EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'CUSTTABLE' AND COLUMN_NAME = 'STREET')
BEGIN
	ALTER TABLE CUSTTABLE DROP COLUMN [STREET]
	ALTER TABLE CUSTTABLE DROP COLUMN [ADDRESS]	
	ALTER TABLE CUSTTABLE DROP COLUMN [ZIPCODE]
	ALTER TABLE CUSTTABLE DROP COLUMN [CITY]
	ALTER TABLE CUSTTABLE DROP COLUMN [STATE]
	ALTER TABLE CUSTTABLE DROP COLUMN [COUNTY]
	ALTER TABLE CUSTTABLE DROP COLUMN [COUNTRY]
	ALTER TABLE CUSTTABLE DROP COLUMN [ADDRESSFORMAT]
END
*/

IF EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'CUSTTABLE' AND COLUMN_NAME = 'STREET')
BEGIN
	exec sp_executesql N'UPDATE CUSTTABLE SET [STREET]='''''
	exec sp_executesql N'UPDATE CUSTTABLE SET [ADDRESS]='''''	
	exec sp_executesql N'UPDATE CUSTTABLE SET [ZIPCODE]='''''
	exec sp_executesql N'UPDATE CUSTTABLE SET [CITY]='''''
	exec sp_executesql N'UPDATE CUSTTABLE SET [STATE]='''''
	exec sp_executesql N'UPDATE CUSTTABLE SET [COUNTY]='''''
	exec sp_executesql N'UPDATE CUSTTABLE SET [COUNTRY]='''''
END