/*

	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 10.06.2013

	Description		: Added tables to support mapping between EFT device scheme names and tender types (payment types)
*/
USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYS.COLUMNS WHERE object_id=OBJECT_ID('RBOEFTMAPPING'))
BEGIN
	CREATE TABLE [RBOEFTMAPPING](
	[MAPPINGID] [nvarchar](20) NOT NULL,
	[TENDERTYPEID] [nvarchar](20) NULL,
	[SCHEMENAME] [nvarchar](100) NOT NULL,
	[ENABLED] [bit] NULL,
	[CREATED] [datetime] NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL
	 CONSTRAINT [PK_RBOEFTMAPPING] PRIMARY KEY CLUSTERED 
	(
		[MAPPINGID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [UIDX_SCHEMENAME] ON [dbo].[RBOEFTMAPPING]
	(
		[SCHEMENAME] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO