/*

	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 16.06.2013

	Description		: Add MANUALLYEDITED and DELETED flags to purchase worksheet lines table
*/
USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEWORKSHEETLINE' AND COLUMN_NAME = 'DELETED')
BEGIN
	ALTER TABLE PURCHASEWORKSHEETLINE ADD DELETED bit not null default 0
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEWORKSHEETLINE' AND COLUMN_NAME = 'MANUALLYEDITED')
BEGIN
	ALTER TABLE PURCHASEWORKSHEETLINE ADD MANUALLYEDITED bit not null default 0
END
GO
