/*

	Responsible		: Sigfus Johannesson
	Date created	: 20.06.2013

	Description		: Increaded field size of PERMISSIONGROUPID in WIZARDTEMPLATEPERMISSION
*/


USE LSPOSNET

GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE Table_name = 'WIZARDTEMPLATEPERMISSION' AND COLUMN_NAME = 'PERMISSIONGROUPID' AND CHARACTER_MAXIMUM_LENGTH < 50)
BEGIN
	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE Table_name = 'WIZARDTEMPLATEPERMISSION' AND COLUMN_NAME = 'PERMISSIONGROUPID')
	BEGIN
		ALTER TABLE WIZARDTEMPLATEPERMISSION DROP CONSTRAINT PK_WIZARDTEMPLATEPERMISSION
	END
	ALTER TABLE WIZARDTEMPLATEPERMISSION ALTER COLUMN PERMISSIONGROUPID NVARCHAR(50) NOT NULL
	ALTER TABLE WIZARDTEMPLATEPERMISSION 
	ADD CONSTRAINT PK_WIZARDTEMPLATEPERMISSION PRIMARY KEY CLUSTERED (ID, DATAAREAID, PERMISSIONGROUPID)
END
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WIZARDTEMPLATEPERMISSION' AND COLUMN_NAME = 'NAME')
BEGIN
	ALTER TABLE WIZARDTEMPLATEPERMISSION ADD NAME NVARCHAR(100)
END
GO
