/*

	Responsible		: Erna Gudrun Sigurdardottir
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 18.06.2013

	Description		: Add ADDLINESWITHZEROSUGGESTEDQTY flag to INVENTORYTEMPLATE
*/
USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATE' AND COLUMN_NAME = 'ADDLINESWITHZEROSUGGESTEDQTY')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD ADDLINESWITHZEROSUGGESTEDQTY bit not null default 0
END
GO



