
/*

	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 25.6.2013 / Modified 12.7.2013 (new field added, script name changed)

	Description		: Adds a new field to Functionality profile table
	
*/


USE LSPOSNET

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ALLOWIMAGEVIEWINITEMLOOKUP')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD ALLOWIMAGEVIEWINITEMLOOKUP TINYINT NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'REMEMBERLISTIMAGESELECTION')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD REMEMBERLISTIMAGESELECTION TINYINT NULL
END
GO




