
/*

	Incident No.	: XXX
	Responsible		: Höður Sigurdór Heiðarsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 10.07.2013

	Description		: Add ChoosePriceCalculation and ChooseNameAddress, drop ChooseName and ChooseAddress form WIZARDTEMPLATE
	
						
*/

USE LSPOSNET
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WIZARDTEMPLATE' AND COLUMN_NAME = 'CHOOSENAME')
BEGIN
	ALTER TABLE WIZARDTEMPLATE ADD CHOOSENAMEADDRESS tinyint NOT NULL DEFAULT 1
	ALTER TABLE WIZARDTEMPLATE ADD CHOOSEPRICECALCULATION tinyint NOT NULL DEFAULT 1
	ALTER TABLE WIZARDTEMPLATE DROP COLUMN CHOOSENAME
	ALTER TABLE WIZARDTEMPLATE DROP COLUMN CHOOSEADDRESS
END
GO