
/*

	Incident No.	: 24891
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\Sprint One
	Date created	: 17.7.2013

	Description		: Copy purchase unit from inventory unit, when there is no purchase unit
*/

USE LSPOSNET

-- make sure we have a purchase module for each item that has an inventory module
INSERT into dbo.[INVENTTABLEMODULE]
	(ITEMID,MODULETYPE,UNITID,PRICE,PRICEUNIT,PRICEINCLTAX,MARKUP,QUANTITY,LOWESTQTY,HIGHESTQTY,BLOCKED,DELIVERYTIME,INVENTLOCATIONID,MANDATORYINVENTLOCATION,
	 STANDARDQTY,PRICEDATE,PRICEQTY,ALLOCATEMARKUP,CALENDARDAYS,INTERCOMPANYBLOCKED,DATAAREAID,TAXITEMGROUPID,LINEDISC,MULTILINEDISC,ENDDISC,MARKUPGROUPID,
	 OVERDELIVERYPCT,UNDERDELIVERYPCT,SUPPITEMGROUPID,PRICEINCLVAT)
	 SELECT
		 ITEMID,1 AS MODULETYPE,UNITID,PRICE,PRICEUNIT,PRICEINCLTAX,MARKUP,QUANTITY,LOWESTQTY,HIGHESTQTY,BLOCKED,DELIVERYTIME,INVENTLOCATIONID,MANDATORYINVENTLOCATION,
		 STANDARDQTY,PRICEDATE,PRICEQTY,ALLOCATEMARKUP,CALENDARDAYS,INTERCOMPANYBLOCKED,DATAAREAID,TAXITEMGROUPID,LINEDISC,MULTILINEDISC,ENDDISC,MARKUPGROUPID,
		 OVERDELIVERYPCT,UNDERDELIVERYPCT,SUPPITEMGROUPID,PRICEINCLVAT
	 FROM dbo.[INVENTTABLEMODULE] A
	 WHERE A.DATAAREAID = 'LSR' and A.ModuleType=0 and NOT EXISTS (select * from dbo.INVENTTABLEMODULE B where A.ITEMID=B.ITEMID and B.MODULETYPE=1)
GO

-- copy units for existing purchase modules, from inventory modules, where there is no purchase module unit
UPDATE dbo.[INVENTTABLEMODULE]
	SET UNITID = (SELECT B.UNITID FROM dbo.[INVENTTABLEMODULE] B WHERE B.DATAAREAID=INVENTTABLEMODULE.DATAAREAID AND B.ITEMID=INVENTTABLEMODULE.ITEMID AND B.MODULETYPE=0)
	WHERE MODULETYPE=1 AND (UNITID IS NULL OR LEN(LTRIM(RTRIM(UNITID)))=0)
GO