//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.ViewPlugins.Replenishment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.ViewPlugins.Replenishment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All stores.
        /// </summary>
        internal static string AllStores {
            get {
                return ResourceManager.GetString("AllStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected area is in use and cannot be deleted..
        /// </summary>
        internal static string AreaLineInUse {
            get {
                return ResourceManager.GetString("AreaLineInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This assembly item will be replaced with its components when the template is used..
        /// </summary>
        internal static string AssemblyItemWillBeReplacedWithComponents {
            get {
                return ResourceManager.GetString("AssemblyItemWillBeReplacedWithComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked for purchase.
        /// </summary>
        internal static string BlockedForPurchase {
            get {
                return ResourceManager.GetString("BlockedForPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked for purchase and replenishment.
        /// </summary>
        internal static string BlockedForPurchaseAndReplenishment {
            get {
                return ResourceManager.GetString("BlockedForPurchaseAndReplenishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked for replenishment.
        /// </summary>
        internal static string BlockedForReplenishment {
            get {
                return ResourceManager.GetString("BlockedForReplenishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_open {
            get {
                object obj = ResourceManager.GetObject("book_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following assembly components were not added because they have no default vendor:.
        /// </summary>
        internal static string ComponentsNotAddedHaveNoDefaultVendor {
            get {
                return ResourceManager.GetString("ComponentsNotAddedHaveNoDefaultVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertible.
        /// </summary>
        internal static string Convertible {
            get {
                return ResourceManager.GetString("Convertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Site Service.
        /// </summary>
        internal static string CouldNotConnectToStoreServer {
            get {
                return ResourceManager.GetString("CouldNotConnectToStoreServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default vendors.
        /// </summary>
        internal static string DefaultVendors {
            get {
                return ResourceManager.GetString("DefaultVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected area?.
        /// </summary>
        internal static string DeleteAreaQuestion {
            get {
                return ResourceManager.GetString("DeleteAreaQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete area.
        /// </summary>
        internal static string DeleteAreaQuestionCaption {
            get {
                return ResourceManager.GetString("DeleteAreaQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete inventory template.
        /// </summary>
        internal static string DeleteInventoryTemplate {
            get {
                return ResourceManager.GetString("DeleteInventoryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete the selected inventory template?.
        /// </summary>
        internal static string DeleteInventoryTemplateQuestion {
            get {
                return ResourceManager.GetString("DeleteInventoryTemplateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete inventory templates.
        /// </summary>
        internal static string DeleteInventoryTemplates {
            get {
                return ResourceManager.GetString("DeleteInventoryTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete the selected inventory templates ?.
        /// </summary>
        internal static string DeleteInventoryTemplatesQuestion {
            get {
                return ResourceManager.GetString("DeleteInventoryTemplatesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete line.
        /// </summary>
        internal static string DeletePurchaseWorksheetLine {
            get {
                return ResourceManager.GetString("DeletePurchaseWorksheetLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete the selected line?.
        /// </summary>
        internal static string DeletePurchaseWorksheetLineQuestion {
            get {
                return ResourceManager.GetString("DeletePurchaseWorksheetLineQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete purchase worksheet lines.
        /// </summary>
        internal static string DeletePurchaseWorksheetLines {
            get {
                return ResourceManager.GetString("DeletePurchaseWorksheetLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete the selected lines ?.
        /// </summary>
        internal static string DeletePurchaseWorksheetLinesQuestion {
            get {
                return ResourceManager.GetString("DeletePurchaseWorksheetLinesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete replenishment setting.
        /// </summary>
        internal static string DeleteReplenishmentSetting {
            get {
                return ResourceManager.GetString("DeleteReplenishmentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete the selected replenishment setting ?.
        /// </summary>
        internal static string DeleteReplenishmentSettingQuestion {
            get {
                return ResourceManager.GetString("DeleteReplenishmentSettingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete replenishment settings.
        /// </summary>
        internal static string DeleteReplenishmentSettings {
            get {
                return ResourceManager.GetString("DeleteReplenishmentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete the selected replenishment settings ?.
        /// </summary>
        internal static string DeleteReplenishmentSettingsQuestion {
            get {
                return ResourceManager.GetString("DeleteReplenishmentSettingsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Desktop {
            get {
                object obj = ResourceManager.GetObject("Desktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit all.
        /// </summary>
        internal static string EditAll {
            get {
                return ResourceManager.GetString("EditAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This might take a few minutes.
        /// </summary>
        internal static string FewMinutesMessage {
            get {
                return ResourceManager.GetString("FewMinutesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General setup.
        /// </summary>
        internal static string GeneralSetup {
            get {
                return ResourceManager.GetString("GeneralSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory on hand.
        /// </summary>
        internal static string InventoryOnHand {
            get {
                return ResourceManager.GetString("InventoryOnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory template.
        /// </summary>
        internal static string InventoryTemplate {
            get {
                return ResourceManager.GetString("InventoryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory templates.
        /// </summary>
        internal static string InventoryTemplates {
            get {
                return ResourceManager.GetString("InventoryTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to manage inventory templates.
        /// </summary>
        internal static string InventoryTemplatesDescription {
            get {
                return ResourceManager.GetString("InventoryTemplatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage inventory templates for purchase orders, store transfers and stock counting.
        /// </summary>
        internal static string InventoryTemplatesTooltipDescription {
            get {
                return ResourceManager.GetString("InventoryTemplatesTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory unit missing for item.
        /// </summary>
        internal static string InventoryUnitMissing {
            get {
                return ResourceManager.GetString("InventoryUnitMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item filter.
        /// </summary>
        internal static string ItemFilter {
            get {
                return ResourceManager.GetString("ItemFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like for like.
        /// </summary>
        internal static string LikeForLike {
            get {
                return ResourceManager.GetString("LikeForLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple stores.
        /// </summary>
        internal static string MultipleStores {
            get {
                return ResourceManager.GetString("MultipleStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No purchase unit found. This item will not be added.
        /// </summary>
        internal static string NoPurchaseUnitFound {
            get {
                return ResourceManager.GetString("NoPurchaseUnitFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No replenishment settings have been configured for the item. This item will not be added.
        /// </summary>
        internal static string NoSettingFound {
            get {
                return ResourceManager.GetString("NoSettingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Service has not been configured yet.
        /// </summary>
        internal static string NoStoreServerIsSetUp {
            get {
                return ResourceManager.GetString("NoStoreServerIsSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stores selected. The template will not be saved..
        /// </summary>
        internal static string NoStoresSelected {
            get {
                return ResourceManager.GetString("NoStoresSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not blocked.
        /// </summary>
        internal static string NotBlocked {
            get {
                return ResourceManager.GetString("NotBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vendor found. This item will not be added.
        /// </summary>
        internal static string NoVendorFound {
            get {
                return ResourceManager.GetString("NoVendorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post purchase worksheet.
        /// </summary>
        internal static string PostPurchaseWorksheet {
            get {
                return ResourceManager.GetString("PostPurchaseWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error posting the purchase worksheet..
        /// </summary>
        internal static string PostPurchaseWorksheetError {
            get {
                return ResourceManager.GetString("PostPurchaseWorksheetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purchase worksheet contains no items to post..
        /// </summary>
        internal static string PostPurchaseWorksheetNoItems {
            get {
                return ResourceManager.GetString("PostPurchaseWorksheetNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are items on the worksheet that cannot be posted to a purchase order. Do you want to continue?.
        /// </summary>
        internal static string PostPurchaseWorksheetNonInventoryItemsQuestion {
            get {
                return ResourceManager.GetString("PostPurchaseWorksheetNonInventoryItemsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are items on the worksheet that cannot be posted because they have no vendor selected..
        /// </summary>
        internal static string PostPurchaseWorksheetNonVendorItems {
            get {
                return ResourceManager.GetString("PostPurchaseWorksheetNonVendorItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like the post the purchase worksheet ?.
        /// </summary>
        internal static string PostPurchaseWorksheetQuestion {
            get {
                return ResourceManager.GetString("PostPurchaseWorksheetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inventory template could not be found for the purchase worksheet..
        /// </summary>
        internal static string PostPurchaseWorksheetTemplateNotFound {
            get {
                return ResourceManager.GetString("PostPurchaseWorksheetTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order created.
        /// </summary>
        internal static string PurchaseOrderCreated {
            get {
                return ResourceManager.GetString("PurchaseOrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to view the purchase order ?.
        /// </summary>
        internal static string PurchaseOrderCreatedQuestion {
            get {
                return ResourceManager.GetString("PurchaseOrderCreatedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase orders created.
        /// </summary>
        internal static string PurchaseOrdersCreated {
            get {
                return ResourceManager.GetString("PurchaseOrdersCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 purchase orders created. Would you like to view them ?.
        /// </summary>
        internal static string PurchaseOrdersCreatedQuestion {
            get {
                return ResourceManager.GetString("PurchaseOrdersCreatedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheets.
        /// </summary>
        internal static string PurchaseWorksheet {
            get {
                return ResourceManager.GetString("PurchaseWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase worksheets.
        /// </summary>
        internal static string PurchaseWorksheets {
            get {
                return ResourceManager.GetString("PurchaseWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to manage purchase worksheets.
        /// </summary>
        internal static string PurchaseWorksheetsDescription {
            get {
                return ResourceManager.GetString("PurchaseWorksheetsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase worksheet.
        /// </summary>
        internal static string PurchaseWorksheetSettings {
            get {
                return ResourceManager.GetString("PurchaseWorksheetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage purchase worksheets to create purchase orders based on replenishment settings.
        /// </summary>
        internal static string PurchaseWorksheetsTooltipDescription {
            get {
                return ResourceManager.GetString("PurchaseWorksheetsTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested quantity updated.
        /// </summary>
        internal static string QuantityUpdated {
            get {
                return ResourceManager.GetString("QuantityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested quantity has changed for some items. Would you like to update the ordering quantity to be equal to the new suggested quantities? This will not affect manually added items nor items modified by user..
        /// </summary>
        internal static string QuantityUpdatedQuestion {
            get {
                return ResourceManager.GetString("QuantityUpdatedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove action.
        /// </summary>
        internal static string RemoveAction {
            get {
                return ResourceManager.GetString("RemoveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replenishment.
        /// </summary>
        internal static string Replenishment {
            get {
                return ResourceManager.GetString("Replenishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset worksheet.
        /// </summary>
        internal static string ResetWorksheet {
            get {
                return ResourceManager.GetString("ResetWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to reset the worksheet? You will lose all manual changes to the worksheet..
        /// </summary>
        internal static string ResetWorksheetQuestion {
            get {
                return ResourceManager.GetString("ResetWorksheetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail department.
        /// </summary>
        internal static string RetailDepartment {
            get {
                return ResourceManager.GetString("RetailDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail group.
        /// </summary>
        internal static string RetailGroup {
            get {
                return ResourceManager.GetString("RetailGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail item.
        /// </summary>
        internal static string RetailItem {
            get {
                return ResourceManager.GetString("RetailItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RevertSmallImage {
            get {
                object obj = ResourceManager.GetObject("RevertSmallImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select store to delete overwrite settings for..
        /// </summary>
        internal static string SelectStoreToDeleteOverwriteSettings {
            get {
                return ResourceManager.GetString("SelectStoreToDeleteOverwriteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special group.
        /// </summary>
        internal static string SpecialGroup {
            get {
                return ResourceManager.GetString("SpecialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock counting.
        /// </summary>
        internal static string StockCounting {
            get {
                return ResourceManager.GetString("StockCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock level.
        /// </summary>
        internal static string StockLevel {
            get {
                return ResourceManager.GetString("StockLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store setup.
        /// </summary>
        internal static string StoreSetup {
            get {
                return ResourceManager.GetString("StoreSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template cannot be deleted as there are worksheets attached to it.
        /// </summary>
        internal static string TemplateCannotBeDeletedWhenOpenWorksheetsAreAttached {
            get {
                return ResourceManager.GetString("TemplateCannotBeDeletedWhenOpenWorksheetsAreAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templates_16 {
            get {
                object obj = ResourceManager.GetObject("templates_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templates_32 {
            get {
                object obj = ResourceManager.GetObject("templates_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer orders.
        /// </summary>
        internal static string TransferOrders {
            get {
                return ResourceManager.GetString("TransferOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unit conversion rule exists to convert from the selected unit to the inventory unit for the selected item. Would you like to create the rule?.
        /// </summary>
        internal static string UnitConversionQuestion {
            get {
                return ResourceManager.GetString("UnitConversionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit conversion rule is missing.
        /// </summary>
        internal static string UnitConversionRuleMissing {
            get {
                return ResourceManager.GetString("UnitConversionRuleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unit conversion rule exists to convert from the selected unit to the inventory unit for the selected item..
        /// </summary>
        internal static string UnitConversionRuleMissingAlert {
            get {
                return ResourceManager.GetString("UnitConversionRuleMissingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        internal static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap worksheets_16 {
            get {
                object obj = ResourceManager.GetObject("worksheets_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap worksheets_32 {
            get {
                object obj = ResourceManager.GetObject("worksheets_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
