      IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[RBOTRANSACTIONEFTINFOTRANS]') AND TYPE IN (N'U'))
      BEGIN
      CREATE TABLE [dbo].[RBOTRANSACTIONEFTINFOTRANS](
      [TRANSACTIONID] [nvarchar](10) NOT NULL,
      [LINENUM] [numeric](28, 12) NOT NULL,
      [STORE] [nvarchar](10) NOT NULL,
      [TERMINAL] [nvarchar](10) NOT NULL,
      [TIMEOUT] int NULL,
      [MERCHANTNUMBER] nvarchar(60) NULL,
      [TERMINALNUMBER] nvarchar(60) NULL,
      [TRACK2] nvarchar(60) NULL,
      [CARDNUMBER] nvarchar(60) NULL,
      [CARDNUMBERHIDDEN] tinyint NULL,
      [EXPDATE] varchar(10) NULL,
      [CARDENTRYTYPE] tinyint NULL,
      [CARDNAME] nvarchar(60) NULL,
      [AMOUNT] numeric(28, 12) NULL,
      [AMOUNTINCENTS] int NULL,
      [STAFFID] nvarchar(60) NULL,
      [TRANSACTIONNUMBER] int NULL,
      [AUTHORIZED] tinyint NULL,
      [AUTHCODE] nvarchar(60) NULL,
      [CARDTYPE] int NULL,
      [TENDERTYPE] int NULL,
      [ACQUIRERNAME] nvarchar(60) NULL,
      [TRANSACTIONDATETIME] datetime NULL,
      [ISSUERNUMBER] int NULL,
      [BATCHNUMBER] bigint NULL,
      [RESPONSECODE] nvarchar(60) NULL,
      [AUTHSOURCECODE] nvarchar(60) NULL,
      [ENTRYSOURCECODE] nvarchar(60) NULL,
      [PROCESSLOCALLY] tinyint NULL,
      [AUTHSTRING] nvarchar(60) NULL,
      [VISAAUTHCODE] nvarchar(60) NULL,
      [EUROPAYAUTHCODE] nvarchar(60) NULL,
      [BATCHCODE] nvarchar(60) NULL,
      [SEQUENCECODE] nvarchar(60) NULL,
      [NOTAUTHORIZEDTEXT] nvarchar(60) NULL,
      [AUTHORIZEDTEXT] nvarchar(60) NULL,
      [TRANSACTIONTYPE] int NULL,
      [MESSAGE] nvarchar(60) NULL,
      [ISSUERNAME] nvarchar(60) NULL,
      [ERRORCODE] nvarchar(60) NULL,
      [REFERRALTELNUMBER] nvarchar(60) NULL,
      [TRACKSEPERATOR] nvarchar(60) NULL,
      [PREVIOUSSEQUENCECODE] nvarchar(60) NULL,
      [EXTERNALCARDRECEIPTS] text NULL,
      [DATAAREAID] [nvarchar](3) NOT NULL,
      [RECID] [int] NULL,
      CONSTRAINT [TRANSACTIONEFTINFOIDX] PRIMARY KEY CLUSTERED
      (
      [TRANSACTIONID] ASC,
      [LINENUM] ASC,
      [STORE] ASC,
      [TERMINAL] ASC,
      [DATAAREAID] ASC
      )WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
      ) ON [PRIMARY]
      END
      GO
