
/*

	Incident No.	: 9658/9657/9665
	Responsible		: Marý B. Steingrímsdóttir
	Sprint			: LS Retail.Net 2011.1\DotNetStream\Sprint 2
	Date created	: 14.04.2011

	Description		: Adds new fields to table RboStoreTenderTypeTable

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: RboStoreTenderTypeTable - new fields
						
*/

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETENDERTYPETABLE') AND NAME='ALLOWVOIDING')
ALTER TABLE dbo.RBOSTORETENDERTYPETABLE ADD ALLOWVOIDING TINYINT NULL DEFAULT 1
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETENDERTYPETABLE') AND NAME='ALLOWSPLITPAYMENT')
ALTER TABLE dbo.RBOSTORETENDERTYPETABLE ADD ALLOWSPLITPAYMENT TINYINT NULL DEFAULT 1
GO

IF NOT EXISTS (SELECT TOP 1 ALLOWRETURNNEGATIVE FROM RBOSTORETENDERTYPETABLE WHERE ALLOWRETURNNEGATIVE = 1)
BEGIN
	UPDATE RBOSTORETENDERTYPETABLE
	SET ALLOWRETURNNEGATIVE = 1
END
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 1384)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '1384','Payment type #1 cannot be used when returning items',0, '8.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Payment type #1 cannot be used when returning items', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 1384
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-ZA' and TEXTID = 1384)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-ZA', '1384','Payment type #1 cannot be used when returning items',0, '8.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Payment type #1 cannot be used when returning items', DateUpdated = GetDate() where LANGUAGEID = 'en-ZA' AND TEXTID = 1384
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 1384)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '1384','Ekki er hægt að nota greiðslumáta #1 þegar verið er að skila vörum',0, '8.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ekki er hægt að nota greiðslumáta #1 þegar verið er að skila vörum', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 1384

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 1398)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '1398','Payment type #1 cannot be used in a split payment',0, '8.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Payment type #1 cannot be used in a split payment', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 1398
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 3618)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '1398','Greiðslumátan #1 er ekki hægt að nota með öðrum greiðslumiðlum',0, '8.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Greiðslumátan #1 er ekki hægt að nota með öðrum greiðslumiðlum', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 1398


-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3618)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3618','Could not void the loyalty card payment',0, '8.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Could not void the card payment', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3618
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 3618)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '3618','Ekki var hægt að ógilda heimildina á vildarkortinu',0, '8.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ekki var hægt að ógilda heimildina á vildarkortinu', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 3618
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3619)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3619','Payment type #1 cannot be voided',0, '8.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Payment type #1 cannot be voided', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3619
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 3619)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '3619','Ekki er leyfilegt að ógilda greiðslumátann #1',0, '8.0.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ekki er leyfilegt að ógilda greiðslumátann #1', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 3619
GO

