
/*

	Incident No.	: N/A
	Responsible		: Marý B. Steingrímsdóttir
	Sprint			: N/A
	Date created	: 10.04.2011

	Description		: New fields added to RboTransactionSalestrans

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: RboTransactionSalesTrans - new fields
						
*/

USE LSPOSNET
GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONSALESTRANS') AND NAME='TAXITEMGROUP')
ALTER TABLE dbo.RBOTRANSACTIONSALESTRANS ADD TAXITEMGROUP nvarchar(20) NULL
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONSALESTRANS') AND NAME='STORETAXGROUP')
ALTER TABLE dbo.RBOTRANSACTIONSALESTRANS ADD STORETAXGROUP nvarchar(20) NULL
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONSALESTRANS') AND NAME='ORIGINALTAXGROUP')
ALTER TABLE dbo.RBOTRANSACTIONSALESTRANS ADD ORIGINALTAXGROUP nvarchar(20) NULL
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONSALESTRANS') AND NAME='ORIGINALTAXITEMGROUP')
ALTER TABLE dbo.RBOTRANSACTIONSALESTRANS ADD ORIGINALTAXITEMGROUP nvarchar(20) NULL
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONSALESTRANS') AND NAME='CURRENCY')
ALTER TABLE dbo.RBOTRANSACTIONSALESTRANS ADD CURRENCY nvarchar(3) NULL
GO


