
/*

	Incident No.	: 9741
	Responsible		: Marý B. Steingrímsdóttir
	Sprint			: LS Retail.NET 2011.1\Sprint 2
	Date created	: 26.04.2011

	Description		: Add central suspension within a store to the LS POS functionality

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: POSISSUSPENDEDTRANSACTIONS - new fields added
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSISSUSPENDEDTRANSACTIONS') AND NAME='RECALLEDBY')
ALTER TABLE dbo.POSISSUSPENDEDTRANSACTIONS ADD RECALLEDBY NVARCHAR(20) NULL

IF ((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns WHERE TABLE_NAME = 'POSISSUSPENDEDTRANSACTIONS' AND COLUMN_NAME = 'TERMINALID') = 10)
BEGIN

	IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[POSISSUSPENDEDTRANSACTIONS]') AND name = N'PK_POSISSUSPENDEDTRANSACTIONS')
	ALTER TABLE [dbo].[POSISSUSPENDEDTRANSACTIONS] DROP CONSTRAINT [PK_POSISSUSPENDEDTRANSACTIONS]

	ALTER TABLE POSISSUSPENDEDTRANSACTIONS ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL

	ALTER TABLE [dbo].[POSISSUSPENDEDTRANSACTIONS] ADD  CONSTRAINT [PK_POSISSUSPENDEDTRANSACTIONS] PRIMARY KEY CLUSTERED 
	(
		[SUSPENDEDTRANSACTIONID] ASC,
		[STOREID] ASC,
		[TERMINALID] ASC,
		[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
END
GO




