
/*

	Incident No.	: 9861
	Responsible		: Marý B. Steingrímsdóttir
	Sprint			: LS Retail .NET 2011.1\Sprint 2
	Date created	: 28.04.2011

	Description		: Update field LanguageId to be 20 characters instead of 5

	Logic scripts   : POSIS_GETTRANSLATION stored procedure changed too
	
-- 	Tables affected	: POSISLANGUAGETEXT - fields changed
						
*/

/*
--USE LSPOSNET
--GO

-- IF ((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns WHERE TABLE_NAME = 'POSISLANGUAGETEXT' AND COLUMN_NAME = 'LANGUAGEID') = 5)
--BEGIN

-- 	IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSISLANGUAGETEXT_MODULEID]') AND type = 'D')
-- 	ALTER TABLE dbo.POSISLANGUAGETEXT DROP CONSTRAINT DF_POSISLANGUAGETEXT_MODULEID
-- 	IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSISLANGUAGETEXT_ACTIVE]') AND type = 'D')
-- 	ALTER TABLE dbo.POSISLANGUAGETEXT DROP CONSTRAINT DF_POSISLANGUAGETEXT_ACTIVE
-- 	IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSISLANGUAGETEXT_FIRSTINVERSION]') AND type = 'D')
-- 	ALTER TABLE dbo.POSISLANGUAGETEXT DROP CONSTRAINT DF_POSISLANGUAGETEXT_FIRSTINVERSION
-- 	IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSISLANGUAGETEXT_DATECREATED]') AND type = 'D')
-- 	ALTER TABLE dbo.POSISLANGUAGETEXT DROP CONSTRAINT DF_POSISLANGUAGETEXT_DATECREATED
-- 	IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSISLANGUAGETEXT_DATEUPDATED]') AND type = 'D')
-- 	ALTER TABLE dbo.POSISLANGUAGETEXT DROP CONSTRAINT DF_POSISLANGUAGETEXT_DATEUPDATED

-- 	CREATE TABLE dbo.Tmp_POSISLANGUAGETEXT
--		(
--		LANGUAGEID nvarchar(20) NOT NULL,
--		TEXTID int NOT NULL,
--		TEXT ntext NULL,
--		ERRORTEXT bit NULL,
--		MODULEID int NULL,
--		ACTIVE tinyint NULL,
--		FIRSTINVERSION nvarchar(20) NULL,
--		DATECREATED datetime NULL,
--		DATEUPDATED datetime NULL
--		)  ON [PRIMARY]
--		 TEXTIMAGE_ON [PRIMARY]

-- 	ALTER TABLE dbo.Tmp_POSISLANGUAGETEXT SET (LOCK_ESCALATION = TABLE)
-- 	ALTER TABLE dbo.Tmp_POSISLANGUAGETEXT ADD CONSTRAINT DF_POSISLANGUAGETEXT_MODULEID DEFAULT ((1)) FOR MODULEID
-- 	ALTER TABLE dbo.Tmp_POSISLANGUAGETEXT ADD CONSTRAINT DF_POSISLANGUAGETEXT_ACTIVE DEFAULT ((1)) FOR ACTIVE
-- 	ALTER TABLE dbo.Tmp_POSISLANGUAGETEXT ADD CONSTRAINT DF_POSISLANGUAGETEXT_FIRSTINVERSION DEFAULT ('8.0.0.0000') FOR FIRSTINVERSION
-- 	ALTER TABLE dbo.Tmp_POSISLANGUAGETEXT ADD CONSTRAINT DF_POSISLANGUAGETEXT_DATECREATED DEFAULT (getdate()) FOR DATECREATED
-- 	ALTER TABLE dbo.Tmp_POSISLANGUAGETEXT ADD CONSTRAINT DF_POSISLANGUAGETEXT_DATEUPDATED DEFAULT (getdate()) FOR DATEUPDATED

-- 	IF EXISTS(SELECT * FROM dbo.POSISLANGUAGETEXT)
-- 		 EXEC('INSERT INTO dbo.Tmp_POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, MODULEID, ACTIVE, FIRSTINVERSION, DATECREATED, DATEUPDATED)
-- 			SELECT LANGUAGEID, TEXTID, TEXT, ERRORTEXT, MODULEID, ACTIVE, FIRSTINVERSION, DATECREATED, DATEUPDATED FROM dbo.POSISLANGUAGETEXT WITH (HOLDLOCK TABLOCKX)')

-- 	DROP TABLE dbo.POSISLANGUAGETEXT

-- 	EXECUTE sp_rename N'dbo.Tmp_POSISLANGUAGETEXT', N'POSISLANGUAGETEXT', 'OBJECT' 

-- 	ALTER TABLE dbo.POSISLANGUAGETEXT ADD CONSTRAINT
-- 		PK_POSISLANGUAGETEXT PRIMARY KEY CLUSTERED 
		(
--		LANGUAGEID,
--		TEXTID
--		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--END
--GO

--DECLARE @TABLENAME NVARCHAR(50)
---- SET @TABLENAME = 'POSISLANGUAGETEXT'
--
---- Add table description
--exec spDB_SetTableDescription_1_0 @TABLENAME,'Contains all translation information for the LS POS'
--
---- Add field description
--exec spDB_SetFieldDescription_1_0 @TABLENAME,'LANGUAGEID','The language id the text applies to.'
--exec spDB_SetFieldDescription_1_0 @TABLENAME,'TEXTID','The text id - each text has a unique id within each language id'
--exec spDB_SetFieldDescription_1_0 @TABLENAME,'TEXT', 'The text to be displayed when the text id is translated'
--exec spDB_SetFieldDescription_1_0 @TABLENAME,'ERRORTEXT', 'Is the text an error text - is usually set to false'
--exec spDB_SetFieldDescription_1_0 @TABLENAME,'MODULEID', 'Which module uses this text id - default value is 1 and is used for the LS POS texts'
--exec spDB_SetFieldDescription_1_0 @TABLENAME,'ACTIVE', 'FIELD NOT USED'
--exec spDB_SetFieldDescription_1_0 @TABLENAME,'FIRSTINVERSION', 'When was this text id first added to the LS POS - the version refers to a LS POS version'
--exec spDB_SetFieldDescription_1_0 @TABLENAME,'DATECREATED', 'When was the text created - default value is GETDATE()'
--exec spDB_SetFieldDescription_1_0 @TABLENAME,'DATEUPDATED', 'If the text has been updated this value is set - default value is GETDATE()'

--GO
*/