
/*

	Incident No.	: XXX
	Responsible		: Guðbjörn Einarsson
	Sprint			: LS Retail.NET 2011.1\Sprint 3
	Date created	: 02.05.2011

	Description		: Add functionality to purchase orders and vendors

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: PURCHASEORDERMISCCHARGES - Added column lineNumber
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('VENDTABLE') AND NAME='TAXGROUP')
ALTER TABLE dbo.VENDTABLE ADD TAXGROUP NVARCHAR(20) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERLINE') AND NAME='DISCOUNTAMOUNT')
ALTER TABLE dbo.PURCHASEORDERLINE ADD DISCOUNTAMOUNT decimal(24,6) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERLINE') AND NAME='DISCOUNTPERCENTAGE')
ALTER TABLE dbo.PURCHASEORDERLINE ADD DISCOUNTPERCENTAGE decimal(24,6) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERLINE') AND NAME='TAXAMOUNT')
ALTER TABLE dbo.PURCHASEORDERLINE ADD TAXAMOUNT decimal(24,6) NULL


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERMISCCHARGES'))
BEGIN
	Create table PURCHASEORDERMISCCHARGES
	(
		PURCHASEORDERID NVARCHAR(20) NOT NULL,
		LINENUMBER nvarchar(20) NOT NULL,
		TYPE INT,
		REASON NVARCHAR(60),
		AMOUNT DECIMAL(24,6),
		TAXAMOUNT DECIMAL(24,6),
		DATAAREAID NVARCHAR(4),
		PRIMARY KEY (PURCHASEORDERID,LINENUMBER)
	)
END