
/*

	Incident No.	: [TFS incident no]
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: [Sprint number/ID]
	Date created	: 05.05.2011

	Description		: Updates and adds textids

	Logic scripts   : No stored procedures added or changed
	
-- 	Tables affected	: PosisLanguageText - data added and updated
						
*/

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55','TotalExclTax',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'TotalExclTax', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55','Samtals',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Samtals', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 104)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '104','Price',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Price', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 104
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 104)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '104','Verð',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Verð', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 104
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 105)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '105','PriceExclTax',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'PriceExclTax', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 105
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 105)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '105','Verð án vsk',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Verð án vsk', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 105
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 106)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '106','Fyrirtækjakort',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Fyrirtækjakort', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 106
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 107)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '107','Item Group',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Item Group', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 107
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 107)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '107','Vöruflokkur',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Vöruflokkur', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 107
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 108)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '108','Batch Id',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Batch Id', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 108
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 108)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '108','Batch Id',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Batch Id', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 108
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 109)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '109','Batch Exp Date',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Batch Exp Date', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 109
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 109)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '109','Batch Exp Date',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Batch Exp Date', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 109
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 110)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '110','Serialnúmer',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Serialnúmer', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 110
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 111)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '111','Found',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Found', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 111
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 111)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '111','Fundið',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Fundið', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 111
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 112)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '112','Blocked',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Blocked', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 112
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 112)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '112','Blokkað',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Blokkað', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 112
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 113)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '113','Activated',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Activated', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 113
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 113)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '113','Activated',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Activated', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 113
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 114)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '114','RFID',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'RFID', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 114
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 114)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '114','RFID',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'RFID', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 114
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 115)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '115','Selected',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Selected', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 115
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 115)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '115','Valið',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Valið', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 115
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 116)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '116','ItemType',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'ItemType', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 116
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 116)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '116','Vörugerð',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Vörugerð', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 116
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 117)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '117','DV voided',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'DV voided', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 117
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 117)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '117','DV voided',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'DV voided', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 117
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 118)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '118','Menu type',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Menu type', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 118
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 118)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '118','Gerðir',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gerðir', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 118
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 119)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '119','Printed',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Printed', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 119
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 119)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '119','Prentað',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Prentað', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 119
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 122)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '122','ExtraInfo1',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'ExtraInfo1', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 122
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 122)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '122','AukaUppl1',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'AukaUppl1', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 122
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 123)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '123','ExtraInfo2',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'ExtraInfo2', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 123
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 123)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '123','AukaUppl2',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'AukaUppl2', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 123
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 124)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '124','ExtraInfo3',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'ExtraInfo3', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 124
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 124)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '124','AukaUppl3',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'AukaUppl3', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 124
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 125)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '125','ExtraInfo4',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'ExtraInfo4', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 125
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 125)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '125','AukaUppl4',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'AukaUppl4', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 125
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 126)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '126','ExtraInfo5',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'ExtraInfo5', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 126
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 126)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '126','AukaUppl5',0, '8.0.1.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'AukaUppl5', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 126
GO
