/*

	Incident No.	: 10346
	Responsible		: Hörður Kristjánsson
	Sprint			: LS Retail .NET 2011.1\Sprint 3
	Date created	: 26.05.2011

	Description		: Add fields to RboTransactionTaxTrans table

	Logic scripts   : 
	
	Tables affected	: RBOTRANSACTIONTAXTRANS  - added fields TAXCODERECEIPTDISPLAY, TAXGROUPRECEIPTDISPLAY
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONTAXTRANS' AND COLUMN_NAME = 'TAXCODERECEIPTDISPLAY')
ALTER TABLE RBOTRANSACTIONTAXTRANS ADD TAXCODERECEIPTDISPLAY [nvarchar](20) NULL

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONTAXTRANS' AND COLUMN_NAME = 'TAXGROUPRECEIPTDISPLAY')
ALTER TABLE RBOTRANSACTIONTAXTRANS ADD TAXGROUPRECEIPTDISPLAY [nvarchar](30) NULL