
/*

	Incident No.	: 10561
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: N/A
	Date created	: 03.06.2011

	Description		: Add a fields to RboStoreTable and RboTransactionEFTInfoTrans

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: RboStoretable - new field
					  RboTransactionEFTInfoTrans - new field
						
*/


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETABLE') AND NAME='CALCDISCFROM')
BEGIN
	ALTER TABLE [dbo].[RBOSTORETABLE] ADD CALCDISCFROM int NULL DEFAULT 0
END
GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETABLE') AND NAME='DISPLAYDISCOUNTINCLTAX')
BEGIN
	ALTER TABLE [dbo].[RBOSTORETABLE] ADD DISPLAYDISCOUNTINCLTAX tinyint NULL DEFAULT 1
END
GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONEFTINFOTRANS') AND NAME='REPLICATIONCOUNTER')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONEFTINFOTRANS ADD REPLICATIONCOUNTER int NOT NULL IDENTITY (1, 1)
END
GO

