/*

	Incident No.	: 10355
	Responsible		: Hörður Kristjánsson
	Sprint			: LS Retail .NET 2011.1\Sprint 3
	Date created	: 26.05.2011

-- 	Description		: Adding text toe POSISLANGUAGETEXT table for Extra info fields on the totals component in the POS

	Logic scripts   : 
	
-- 	Tables affected	: PosisLanguageText - adding data
						
*/

USE LSPOSNET

GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 1789)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '1789','Extra info 1',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Extra info 1', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 1789
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 1789)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '1789','Auka uppl. 1',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Auka uppl. 1', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 1789

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 1790)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '1790','Extra info 2',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Extra info 2', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 1790
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 1790)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '1790','Auka uppl. 2',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Auka uppl. 2', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 1790

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 1791)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '1791','Extra info 3',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Extra info 3', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 1791
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 1791)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '1791','Auka uppl. 3',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Auka uppl. 3', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 1791

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 1792)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '1792','Extra info 4',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Extra info 4', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 1792
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 1792)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '1792','Auka uppl. 4',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Auka uppl. 4', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 1792

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 1793)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '1793','Extra info 5',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Extra info 5', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 1793
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 1793)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '1793','Auka uppl. 5',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Auka uppl. 5', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 1793
