
/*

	Incident No.	: 10561
	Responsible		: Hörður Kristjánsson
	Sprint			: N/A
	Date created	: 06.07.2011

	Description		: Add fields to transaction tables for tax exemption and added operation id's o posisoperations

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: RboTransactionTable		- new field
					  RboTransactionSalesTrans	- new field
					  RboTransactionTaxTrans	- new fields
					  PosisLanguageText			- Added new translation texts
					  
						
*/


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONTABLE') AND NAME='TAXEXEMPT')
BEGIN
	ALTER TABLE [dbo].[RBOTRANSACTIONTABLE] ADD TAXEXEMPT tinyint NULL DEFAULT 0
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONSALESTRANS') AND NAME='TAXEXEMPT')
BEGIN
	ALTER TABLE [dbo].[RBOTRANSACTIONSALESTRANS] ADD TAXEXEMPT tinyint NULL DEFAULT 0
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONTAXTRANS') AND NAME='TAXEXEMPT')
BEGIN
	ALTER TABLE [dbo].[RBOTRANSACTIONTAXTRANS] ADD TAXEXEMPT tinyint NULL DEFAULT 0
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONTAXTRANS') AND NAME='TAXEXEMPTIONCODE')
BEGIN
	ALTER TABLE [dbo].[RBOTRANSACTIONTAXTRANS] ADD TAXEXEMPTIONCODE nvarchar(20) NULL
END
GO

IF NOT EXISTS (SELECT * FROM [POSISOPERATIONS] WHERE [OPERATIONID] = 1400 and [DATAAREAID] = 'LSR')
INSERT POSISOPERATIONS(OPERATIONID,OPERATIONNAME,CHECKUSERACCESS,USEROPERATION,DATAAREAID) VALUES('1400','Tax Exempt Transaction','1','1','LSR')

IF NOT EXISTS (SELECT * FROM [POSISOPERATIONS] WHERE [OPERATIONID] = 1401 and [DATAAREAID] = 'LSR')
INSERT POSISOPERATIONS(OPERATIONID,OPERATIONNAME,CHECKUSERACCESS,USEROPERATION,DATAAREAID) VALUES('1401','Clear Transaction Tax Exemption','1','1','LSR')
GO


IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6200)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6200','This operation is invalid for this type of transaction',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'This operation is invalid for this type of transaction', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6200
IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6200)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6200','Þessi aðgerð er óleyfileg í viðkomandi afgreiðslutegund.',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'Þessi aðgerð er óleyfileg í viðkomandi afgreiðslutegund.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6200

IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6201)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6201','Enter tax exemption code',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'Enter tax exemption code', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6201
IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6201)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6201','Sláðu inn skattaundanþágunúmer',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'Sláðu inn skattaundanþágunúmer', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6201

IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6202)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6202','Invalid tax exemption code entered, enter a valid code',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'Invalid tax exemption code entered, enter a valid code', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6202
IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6202)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6202','Ógilt skattaundanþágunúmer slegið inn, vinsamlegast sláið inn gilt númer',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'Ógilt skattaundanþágunúmer slegið inn, vinsamlegast sláið inn gilt númer', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6202

IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6210)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6210','This operation is invalid for this type of transaction',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'This operation is invalid for this type of transaction', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6210
IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6210)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6210','Þessi aðgerð er óleyfileg í viðkomandi afgreiðslutegund.',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'Þessi aðgerð er óleyfileg í viðkomandi afgreiðslutegund.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6210

IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6211)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6211','Are you sure you want to clear the transaction tax exemption ?',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to clear the transaction tax exemption ?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6211
IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6211)
INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6211','Ertu viss um að þú viljir hreinsa skattaundanþáguna af sölunni ?',0, '8.1.0.0000')
UPDATE POSISLANGUAGETEXT SET TEXT = 'Ertu viss um að þú viljir hreinsa skattaundanþáguna af sölunni ?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6211