
/*

	Incident No.	: 15805
	Responsible		: Óskar Bjarnason
	Sprint			: LS Retail .NET 2012\Embla
	Date created	: 12.03.2012

	Description		: Alterning fields in table

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: POSPERIODICDISCOUNTLINE - Id field added and 
						
*/

--USE LSPOSNET

GO

--Drop Primary key

IF EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'POSPERIODICDISCOUNTLINE' AND CONSTRAINT_NAME = 'PK_POSPERIODICDISCOUNTLINE')
Begin
	Alter Table POSPERIODICDISCOUNTLINE
	DROP CONSTRAINT PK_POSPERIODICDISCOUNTLINE

End
GO


--Add GUID column
IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POSPERIODICDISCOUNTLINE' AND COLUMN_NAME='POSPERIODICDISCOUNTLINEGUID')
Begin
	ALTER TABLE POSPERIODICDISCOUNTLINE 
	Add POSPERIODICDISCOUNTLINEGUID uniqueidentifier NOT NULL default NEWID()	
End
GO



--Set primary key

IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'POSPERIODICDISCOUNTLINE' AND CONSTRAINT_NAME = 'PK_POSPERIODICDISCOUNTLINE')
BEGIN

ALTER TABLE dbo.POSPERIODICDISCOUNTLINE ADD CONSTRAINT
		PK_POSPERIODICDISCOUNTLINE PRIMARY KEY CLUSTERED 
		(
		POSPERIODICDISCOUNTLINEGUID,
		DATAAREAID
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

END











