
/*

	Incident No.	: 15921
	Responsible		: Hrólfur
	Sprint			: LS Retail .NET 2012\Höður
	Date created	: 22.03.2012

	Description		: Adding field to table

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: POSMENULINE - Added field ImagePosition
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME='HOSPITALITYSALESTYPE')
	alter table RBOTRANSACTIONSALESTRANS add HOSPITALITYSALESTYPE nvarchar(20) NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POSFUNCTIONALITYPROFILE' AND COLUMN_NAME='SKIPHOSPITALITYTABLEVIEW')
	alter table POSFUNCTIONALITYPROFILE add SKIPHOSPITALITYTABLEVIEW tinyint NULL
GO