
/*

	Incident No.	: 16158
	Responsible		: Marý B Steingrímsdóttir
	Sprint			: LS Retail .NET 2012/Hel
	Date created	: 31.03.2012

	Description		: Add new fields to a tables

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: RboParameters - add two new fields
				      RboInventItemRetailGroups - new field
					  RboInventTable - new field
						
*/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='RBOPARAMETERS' AND COLUMN_NAME='MANUALLYENTERITEMID')
BEGIN
	ALTER TABLE RBOPARAMETERS ADD MANUALLYENTERITEMID tinyint NULL	
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='RBOPARAMETERS' AND COLUMN_NAME='MANUALLYENTERCUSTID')
BEGIN
	ALTER TABLE RBOPARAMETERS ADD MANUALLYENTERCUSTID tinyint NULL	
END
GO

UPDATE RBOPARAMETERS
SET MANUALLYENTERCUSTID = 0
WHERE MANUALLYENTERCUSTID IS NULL


UPDATE RBOPARAMETERS
SET MANUALLYENTERITEMID = 0
WHERE MANUALLYENTERITEMID IS NULL
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='RBOINVENTITEMRETAILGROUP' AND COLUMN_NAME='DEFAULTPROFIT')
alter table RBOINVENTITEMRETAILGROUP add DEFAULTPROFIT numeric(28, 12) NULL 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='RBOINVENTTABLE' AND COLUMN_NAME='DEFAULTPROFIT')
alter table RBOINVENTTABLE add DEFAULTPROFIT numeric(28, 12) NULL
GO


