/*

	Incident No.	: 16188
	Responsible		: Óskar Bjarnason
	Sprint			: LS Retail .NET 2012\Embla
	Date created	: 11.04.2012

	Description		: Altering row in table

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: POSISOPERATIONS - Changed operationID 611
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='HOSPITALITYTYPE' AND COLUMN_NAME='DEFAULTTYPE')
	alter table HOSPITALITYTYPE add DEFAULTTYPE tinyint NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='RBOTERMINALTABLE' AND COLUMN_NAME='HOSPTRANSSTORESERVERPROFILE')
	alter table RBOTERMINALTABLE add HOSPTRANSSTORESERVERPROFILE nvarchar(20) NULL					
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='RBOSTORETABLE' AND COLUMN_NAME='TRANSACTIONSERVICEPROFILE')
	alter table RBOSTORETABLE add TRANSACTIONSERVICEPROFILE nvarchar(20) NULL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='HOSPITALITYSETUP' AND COLUMN_NAME='TABLEUPDATETIMERINTERVAL')
	alter table HOSPITALITYSETUP add TABLEUPDATETIMERINTERVAL int NULL
GO
