/*

	Incident No.	: 16182
	Responsible		: Óskar Bjarnason
	Sprint			: LS Retail .NET 2012\Embla
	Date created	: 22.04.2012

	Description		: Altering row in table

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: POSISOPERATIONS - Fixing spelling in 508 and 510
						
*/

USE LSPOSNET

GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POSISOPERATIONS' AND COLUMN_NAME='USEROPERATION')

delete from POSISOPERATIONS 
where OPERATIONID = '508'

insert into POSISOPERATIONS ( OPERATIONID, OPERATIONNAME, PERMISSIONID, PERMISSIONID2, CHECKUSERACCESS, USEROPERATION,DATAAREAID,LOOKUPTYPE)
values (508, 'Pharmacy Prescription Cancel',	NULL,	NULL,	1,	1,'LSR',0)


GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POSISOPERATIONS' AND COLUMN_NAME='USEROPERATION')

delete from POSISOPERATIONS 
where OPERATIONID = '510'

insert into POSISOPERATIONS ( OPERATIONID, OPERATIONNAME, PERMISSIONID, PERMISSIONID2, CHECKUSERACCESS, USEROPERATION,DATAAREAID,LOOKUPTYPE)
values (510, 'Pharmacy Prescriptions',	NULL,	NULL,	1,	1,'LSR',0)

