/*
	Incident No.	: ONE-10209 Prepare receipt examples for certification
	Responsible		: Andrei Sonka
	Sprint			: Saiph
	Date created	: 10.06.2019

	Description		: Added ETax device properties to POSHARDWAREPROFILE 
*/

USE LSPOSNET


IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'ETAX')
BEGIN
	ALTER TABLE POSHARDWAREPROFILE ADD ETAX INT NULL
END
ELSE
BEGIN 
	PRINT '[POSHARDWAREPROFILE.ETAX] was already inserted'
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'ETAXPORTNAME')
BEGIN
	ALTER TABLE POSHARDWAREPROFILE ADD ETAXPORTNAME NVARCHAR(30) NULL
END
ELSE
BEGIN 
	PRINT '[POSHARDWAREPROFILE.ETAXPORTNAME] was already inserted'
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WIZARDTEMPLATEPERIPHERALS' AND COLUMN_NAME = 'ETAX')
BEGIN
	ALTER TABLE WIZARDTEMPLATEPERIPHERALS ADD ETAX NVARCHAR(30) NULL
END
ELSE
BEGIN 
	PRINT '[WIZARDTEMPLATEPERIPHERALS.ETAX] was already inserted'
END
GO