/*
	Incident No.	: ONE-7025
	Responsible		: Adrian Chiorean
	Sprint			: Aldebaran
	Date created	: 28.03.2019

	Description		: Add column CREATEDDATE, LASTUSEDDATE to RBOCREDITVOUCHERTABLE and RBOGIFTCARDTABLE
	Remarks			: RBOGIFTCARDTABLE already has CREATEDDATE
*/

USE LSPOSNET

CREATE TABLE #TEMP00894 (
GIFTCARDLASTUSEDADDED BIT NOT NULL,
VOUCHERLASTUSEDADDED BIT NOT NULL,
VOUCHERCREATEDADDED BIT NOT NULL)

INSERT INTO #TEMP00894 VALUES (0, 0, 0)

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOGIFTCARDTABLE' AND COLUMN_NAME = 'LASTUSEDDATE')
BEGIN
	ALTER TABLE RBOGIFTCARDTABLE ADD LASTUSEDDATE DATETIME NULL
	UPDATE #TEMP00894 SET GIFTCARDLASTUSEDADDED = 1
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOCREDITVOUCHERTABLE' AND COLUMN_NAME = 'CREATEDDATE')
BEGIN
	ALTER TABLE RBOCREDITVOUCHERTABLE ADD CREATEDDATE DATETIME NULL
	UPDATE #TEMP00894 SET VOUCHERCREATEDADDED = 1
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOCREDITVOUCHERTABLE' AND COLUMN_NAME = 'LASTUSEDDATE')
BEGIN
	ALTER TABLE RBOCREDITVOUCHERTABLE ADD LASTUSEDDATE DATETIME NULL
	UPDATE #TEMP00894 SET VOUCHERLASTUSEDADDED = 1
END
GO

IF EXISTS (SELECT 1 FROM #TEMP00894 WHERE GIFTCARDLASTUSEDADDED = 1)
BEGIN
	-- Update last used date date
	UPDATE gc 
	SET gc.LASTUSEDDATE = IIF(gct.GIFTCARDID IS NULL, gc.LASTUSEDDATE, CAST(gct.TRANSACTIONDATE AS DATETIME) + CAST(gct.TRANSACTIONTIME AS DATETIME))
	FROM RBOGIFTCARDTABLE gc
	JOIN RBOGIFTCARDTRANSACTIONS gct ON gct.GIFTCARDID = (SELECT TOP 1 gct.GIFTCARDID WHERE gc.GIFTCARDID = gct.GIFTCARDID AND OPERATION = 3 ORDER BY TRANSACTIONDATE DESC, TRANSACTIONTIME DESC)
	WHERE gc.LASTUSEDDATE IS NULL
END
GO

IF EXISTS (SELECT 1 FROM #TEMP00894 WHERE VOUCHERLASTUSEDADDED = 1)
BEGIN
	-- Update created date
	UPDATE cv 
	SET cv.CREATEDDATE = IIF(cvt.VOUCHERID IS NULL, cv.CREATEDDATE, CAST(cvt.TRANSACTIONDATE AS DATETIME) + CAST(cvt.TRANSACTIONTIME AS DATETIME))
	FROM RBOCREDITVOUCHERTABLE cv
	JOIN RBOCREDITVOUCHERTRANSACTIONS cvt ON cvt.VOUCHERID = (SELECT TOP 1 cvt.VOUCHERID WHERE cv.VOUCHERID = cvt.VOUCHERID AND OPERATION = 0 ORDER BY TRANSACTIONDATE ASC, TRANSACTIONTIME ASC)
	WHERE cv.CREATEDDATE IS NULL
END
GO

IF EXISTS (SELECT 1 FROM #TEMP00894 WHERE VOUCHERCREATEDADDED = 1)
BEGIN
	-- Update last used date date
	UPDATE cv 
	SET cv.LASTUSEDDATE = IIF(cvt.VOUCHERID IS NULL, cv.LASTUSEDDATE, CAST(cvt.TRANSACTIONDATE AS DATETIME) + CAST(cvt.TRANSACTIONTIME AS DATETIME))
	FROM RBOCREDITVOUCHERTABLE cv
	JOIN RBOCREDITVOUCHERTRANSACTIONS cvt ON cvt.VOUCHERID = (SELECT TOP 1 cvt.VOUCHERID WHERE cv.VOUCHERID = cvt.VOUCHERID AND OPERATION = 3 ORDER BY TRANSACTIONDATE DESC, TRANSACTIONTIME DESC)
	WHERE cv.CREATEDDATE IS NULL
END
GO

IF OBJECT_ID('tempdb..#TEMP00894') IS NOT NULL DROP TABLE #TEMP00894
GO