/*
	Incident No.	: ONE-10281 Investigate documents backup and recovery
					  ONE-10376 Add Processing status to Purchase orders and Transfer orders
	Responsible		: Adrian Chiorean
	Sprint			: Sun
	Date created	: 08.07.2019

	Description		: Add columns XMLDATA column to OMNIJOURNAL. Mark OMNIJOURNALLINE as obsolete
					  Add Processing status to Purchase orders and Transfer orders
					  Add DEFAULTVENDOR to inventory templates
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'OMNIJOURNAL' AND COLUMN_NAME = 'XMLDATA')
BEGIN
	ALTER TABLE OMNIJOURNAL ADD XMLDATA XML NULL
	EXECUTE spDB_SetFieldDescription_1_0 'OMNIJOURNAL', 'XMLDATA', 'Lines to be added to an inventory document in XML format.';
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'OMNIJOURNALLINE')
BEGIN
	TRUNCATE TABLE OMNIJOURNALLINE
	EXECUTE spDB_SetTableDescription_1_0 'OMNIJOURNALLINE', '[Obsolete, ONE-10281] This table is no longer used. Data is saved in OMNIJOURNAL as XML.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERS' AND COLUMN_NAME = 'PROCESSINGSTATUS')
BEGIN
	ALTER TABLE PURCHASEORDERS ADD PROCESSINGSTATUS INT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'PURCHASEORDERS', 'PROCESSINGSTATUS', 'Indicates the current processing status of the purchase order.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDER' AND COLUMN_NAME = 'PROCESSINGSTATUS')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDER ADD PROCESSINGSTATUS INT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTRANSFERORDER', 'PROCESSINGSTATUS', 'Indicates the current processing status of the transfer order.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATE' AND COLUMN_NAME = 'DEFAULTVENDOR')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD DEFAULTVENDOR NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTEMPLATE', 'DEFAULTVENDOR', 'Default vendor used on templates on type purchase order.';
END
GO

-- Add number sequence for OMNIJOURNAL
IF NOT EXISTS(SELECT 1 FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = 'LSR' and NUMBERSEQUENCE = 'OMNIJOURNAL')
BEGIN
	INSERT INTO dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	VALUES ('OMNIJOURNAL','Omni journal',1,999999999,'OMNI#########',1,0,0,'HO','LSR')
	INSERT INTO dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	VALUES ('OMNIJOURNAL',1,'HO','LSR')
END
GO