/*
	Incident No.	: ONE-10136 Inventory template changes, ONE-10358 Add OMNI general settings to functionality profile
	Responsible		: Adrian Chiorean
	Sprint			: Sun
	Date created	: 01.07.2019

	Description		: Add column ALLOWIMAGEIMPORT to INVENTORYTEMPLATE. Add columns OMNIENTERINGTYPE, OMNIQUANTITYMETHOD, OMNIDEFAULTQUANTITY to POSFUNCTIONALITYPROFILE
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATE' AND COLUMN_NAME = 'ALLOWIMAGEIMPORT')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD ALLOWIMAGEIMPORT BIT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTEMPLATE', 'ALLOWIMAGEIMPORT', 'If true, images can be allowed to inventory document lines (Stock counting, purchase orders, store transfers). Only used in OMNI.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'OMNIENTERINGTYPE')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD OMNIENTERINGTYPE INT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'POSFUNCTIONALITYPROFILE', 'OMNIENTERINGTYPE', 'Specifies how lines are added to inventory documents (Stock counting, purchase orders, store transfers). Only used in OMNI.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'OMNIQUANTITYMETHOD')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD OMNIQUANTITYMETHOD INT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'POSFUNCTIONALITYPROFILE', 'OMNIQUANTITYMETHOD', 'Specifies how quantity is set on inventory document lines (Stock counting, purchase orders, store transfers). Only used in OMNI.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'OMNIDEFAULTQUANTITY')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD OMNIDEFAULTQUANTITY DECIMAL NOT NULL DEFAULT 1
	EXECUTE spDB_SetFieldDescription_1_0 'POSFUNCTIONALITYPROFILE', 'OMNIDEFAULTQUANTITY', 'Specifies the default quantity to be used when adding inventory document lines (Stock counting, purchase orders, store transfers). Only used in OMNI.';
END
GO