/*
	Incident No.	: ONE-9887
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: Vega
	Date created	: 26.06.2019

	Description		: Add columns LINENUMBER and GRLINENUMBER to OMNIJOURNALLINE
*/
USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'OMNIJOURNALLINE' AND COLUMN_NAME = 'LINENUMBER')
BEGIN
	ALTER TABLE OMNIJOURNALLINE ADD LINENUMBER NVARCHAR(100) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'OMNIJOURNALLINE', 'LINENUMBER', 'The line number of the purchase order line or stock counting line';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'OMNIJOURNALLINE' AND COLUMN_NAME = 'GRLINENUMBER')
BEGIN
		ALTER TABLE OMNIJOURNALLINE ADD GRLINENUMBER NVARCHAR(100) NULL
		EXECUTE spDB_SetFieldDescription_1_0 'OMNIJOURNALLINE', 'GRLINENUMBER', 'The line number of the goods receiving line';
END
GO