/*
	Incident No.	: ONE-9856 Add item picture to stock counting journal lines
	Responsible		: Hörður Kristjánsson
	Sprint			: Sun
	Date created	: 13.08.2019

	Description		: Add PICTUREID column to INVENTJOURNALTRANS
*/

USE LSPOSNET

-- INVENTJOURNALTRANS --
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANS' AND COLUMN_NAME = 'PICTUREID')
BEGIN
	ALTER TABLE INVENTJOURNALTRANS ADD PICTUREID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTJOURNALTRANS', 'PICTUREID', 'The ID of the picture that is associated with the journal line.';
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANS' AND COLUMN_NAME = 'OMNITRANSACTIONID')
BEGIN
	ALTER TABLE INVENTJOURNALTRANS ADD OMNITRANSACTIONID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTJOURNALTRANS', 'OMNITRANSACTIONID', 'The ID of the transaction in the inventory app that this line was created on.';
END

-- When receiving lines from stock counting templates the line ID is an integer, however looking at the implementation of the journal lines this could also be a GUID
-- To stay safe we are using 38 characters which should cover any GUID string except hexademical format
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANS' AND COLUMN_NAME = 'OMNILINEID')
BEGIN
	ALTER TABLE INVENTJOURNALTRANS ADD OMNILINEID NVARCHAR(38) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTJOURNALTRANS', 'OMNILINEID', 'The ID of the journal line when it was create in the inventory app.';
END

-- INVENTORYTRANSFERORDERLINE --
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLINE' AND COLUMN_NAME = 'PICTUREID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLINE ADD PICTUREID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTRANSFERORDERLINE', 'PICTUREID', 'The ID of the picture that is associated with line.';
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLINE' AND COLUMN_NAME = 'OMNITRANSACTIONID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLINE ADD OMNITRANSACTIONID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTRANSFERORDERLINE', 'OMNITRANSACTIONID', 'The ID of the transaction in the inventory app that this line was created on.';
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLINE' AND COLUMN_NAME = 'OMNILINEID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLINE ADD OMNILINEID NVARCHAR(38) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTRANSFERORDERLINE', 'OMNILINEID', 'The ID of the line when it was create in the inventory app.';
END

-- PURCHASEORDERLINE --
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERLINE' AND COLUMN_NAME = 'PICTUREID')
BEGIN
	ALTER TABLE PURCHASEORDERLINE ADD PICTUREID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'PURCHASEORDERLINE', 'PICTUREID', 'The ID of the picture that is associated with line.';
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERLINE' AND COLUMN_NAME = 'OMNITRANSACTIONID')
BEGIN
	ALTER TABLE PURCHASEORDERLINE ADD OMNITRANSACTIONID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'PURCHASEORDERLINE', 'OMNITRANSACTIONID', 'The ID of the transaction in the inventory app that this line was created on.';
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERLINE' AND COLUMN_NAME = 'OMNILINEID')
BEGIN
	ALTER TABLE PURCHASEORDERLINE ADD OMNILINEID NVARCHAR(38) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'PURCHASEORDERLINE', 'OMNILINEID', 'The ID of the line when it was create in the inventory app.';
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'OMNIJOURNAL' AND COLUMN_NAME = 'TRANSACTIONID')
BEGIN
	ALTER TABLE OMNIJOURNAL ADD TRANSACTIONID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'OMNIJOURNAL', 'TRANSACTIONID', 'The ID of the transaction in the inventory app that journal was created from.';
END
GO