/*
	Incident No.	: ONE-10362 Create store transfers and purchase orders from templates
	Responsible		: Adrian Chiorean
	Sprint			: Sun
	Date created	: 03.07.2019

	Description		: Add columns CREATEDFROMOMNI, TEMPLATEID to tables INVENTORYTRANSFERREQUEST, INVENTORYTRANSFERORDER, PURCHASEORDERS
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERREQUEST' AND COLUMN_NAME = 'CREATEDFROMOMNI')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUEST ADD CREATEDFROMOMNI BIT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTRANSFERREQUEST', 'CREATEDFROMOMNI', 'True if the transfer request was created from the mobile inventory app.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERREQUEST' AND COLUMN_NAME = 'TEMPLATEID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUEST ADD TEMPLATEID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTRANSFERREQUEST', 'TEMPLATEID', 'ID of the inventory template from which the transfer request was created.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDER' AND COLUMN_NAME = 'CREATEDFROMOMNI')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDER ADD CREATEDFROMOMNI BIT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTRANSFERORDER', 'CREATEDFROMOMNI', 'True if the transfer order was created from the mobile inventory app.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDER' AND COLUMN_NAME = 'TEMPLATEID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDER ADD TEMPLATEID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTRANSFERORDER', 'TEMPLATEID', 'ID of the inventory template from which the transfer order was created.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERS' AND COLUMN_NAME = 'CREATEDFROMOMNI')
BEGIN
	ALTER TABLE PURCHASEORDERS ADD CREATEDFROMOMNI BIT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'PURCHASEORDERS', 'CREATEDFROMOMNI', 'True if the purchase order was created from the mobile inventory app.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERS' AND COLUMN_NAME = 'TEMPLATEID')
BEGIN
	ALTER TABLE PURCHASEORDERS ADD TEMPLATEID NVARCHAR(20) NULL
	EXECUTE spDB_SetFieldDescription_1_0 'PURCHASEORDERS', 'TEMPLATEID', 'ID of the inventory template from which the purchase order was created.';
END
GO