/*
	Incident No.	: ONE-9084
	Responsible		: Tan Bee Tze
	Sprint			: 
	Date created	: 12.10.2018
	Description		: Add columns into RBOTRANSACTIONFISCALTRANS table
	Notes			: Moved from customization to standard in 1.11.2019 by Adrian Chiorean
					  Aggreed that those colums are common enough and they may be used in new fiscalizations
*/

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONFISCALTRANS' AND COLUMN_NAME = 'TRANSDATE')
BEGIN
	ALTER TABLE RBOTRANSACTIONFISCALTRANS ADD TRANSDATE DATETIME NOT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'RBOTRANSACTIONFISCALTRANS', 'TRANSDATE', 'Date of the transaction.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONFISCALTRANS' AND COLUMN_NAME = 'GROSSAMOUNT')
BEGIN
	ALTER TABLE RBOTRANSACTIONFISCALTRANS ADD GROSSAMOUNT numeric(28, 12) NOT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'RBOTRANSACTIONFISCALTRANS', 'GROSSAMOUNT', 'Total gross amount of the transaction.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONFISCALTRANS' AND COLUMN_NAME = 'NETAMOUNT')
BEGIN
	ALTER TABLE RBOTRANSACTIONFISCALTRANS ADD NETAMOUNT numeric(28, 12) NOT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'RBOTRANSACTIONFISCALTRANS', 'NETAMOUNT', 'Total net amount of the transaction.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONFISCALTRANS' AND COLUMN_NAME = 'PRIVATEKEYVER')
BEGIN
	ALTER TABLE RBOTRANSACTIONFISCALTRANS ADD PRIVATEKEYVER NVARCHAR(60) NOT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'RBOTRANSACTIONFISCALTRANS', 'PRIVATEKEYVER', 'Private certificate version used to hash the transaction, if applicable.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONFISCALTRANS' AND COLUMN_NAME = 'SIGNATURE')
BEGIN
	ALTER TABLE RBOTRANSACTIONFISCALTRANS ADD [SIGNATURE] NVARCHAR(500) NOT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'RBOTRANSACTIONFISCALTRANS', 'SIGNATURE', 'Hashed signature of the transaction.';
END
GO