/*
	Incident No.	: ONE-11223 Table fields of type Real are not replicated
	Responsible		: Adrian Chiorean
	Sprint			: Nashira
	Date created	: 20.11.2019

	Description		: Change column types from real to decimal in WINDOWSPRINTERCONFIGURATION
*/

USE LSPOSNET

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WINDOWSPRINTERCONFIGURATION' AND COLUMN_NAME = 'FONTSIZE' AND DATA_TYPE = 'real')
BEGIN
	ALTER TABLE WINDOWSPRINTERCONFIGURATION ALTER COLUMN FONTSIZE DECIMAL(24, 2)
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WINDOWSPRINTERCONFIGURATION' AND COLUMN_NAME = 'WIDEHIGHFONTSIZE' AND DATA_TYPE = 'real')
BEGIN
	ALTER TABLE WINDOWSPRINTERCONFIGURATION ALTER COLUMN WIDEHIGHFONTSIZE DECIMAL(24, 2)
END
GO