/*

	Incident No.	: ONE-3587
	Responsible		: Indriði Ingi Stefánsson
	Sprint			: Amsterdam

	Description		: Setting two text fields in CustTable to allow longer strings than before

*/


USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLE' AND COLUMN_NAME = 'MASTERID')
Begin
	ALTER TABLE dbo.INVENTJOURNALTABLE ADD MASTERID uniqueidentifier NULL
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTTRANS' AND COLUMN_NAME = 'VARIANTID')
Begin
	ALTER TABLE dbo.INVENTTRANS DROP COLUMN VARIANTID
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANS' AND COLUMN_NAME = 'VARIANTID')
Begin
	ALTER TABLE dbo.INVENTJOURNALTRANS DROP COLUMN VARIANTID
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLINE' AND COLUMN_NAME = 'VARIANTID')
Begin
	ALTER TABLE dbo.INVENTORYTRANSFERORDERLINE DROP COLUMN VARIANTID
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERREQUESTLINE' AND COLUMN_NAME = 'VARIANTID')
Begin
	ALTER TABLE dbo.INVENTORYTRANSFERREQUESTLINE DROP COLUMN VARIANTID
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERLINE' AND COLUMN_NAME = 'VARIANTID')
Begin
	ALTER TABLE dbo.PURCHASEORDERLINE DROP COLUMN VARIANTID
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'VENDORITEMS' AND COLUMN_NAME = 'VARIANTID')
Begin
	ALTER TABLE dbo.VENDORITEMS DROP COLUMN VARIANTID
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS where CONSTRAINT_NAME = 'PK_INVENTSUM')
BEGIN
	ALTER TABLE dbo.INVENTSUM ADD CONSTRAINT PK_INVENTSUM
	PRIMARY KEY CLUSTERED ([ITEMID],[STOREID])
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTSUM' AND  COLUMN_NAME  = 'VARIANTID')
BEGIN
	ALTER TABLE dbo.INVENTSUM 
	DROP COLUMN VARIANTID
END
GO

