
/*

	Incident No.	: ONE-3195
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Washington DC

	Description		: Create all customer order tables and add a new field to RboTransactionTAble

*/


USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONTABLE' AND COLUMN_NAME = 'CUSTOMERORDERID')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONTABLE ADD	CUSTOMERORDERID uniqueidentifier NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONPAYMENTTRANS' AND COLUMN_NAME = 'TENDERLINETYPE')
BEGIN
	ALTER TABLE dbo.RBOTRANSACTIONPAYMENTTRANS ADD TENDERLINETYPE INT NULL
END
GO

IF NOT EXISTS(SELECT * FROM PERMISSIONGROUP WHERE [GUID] = '9D0F831D-7B2B-4A0E-B9E6-349B50A235BE')
BEGIN
	Insert into PERMISSIONGROUP (GUID,Name,DATAAREAID) values ('9D0F831D-7B2B-4A0E-B9E6-349B50A235BE','Customer orders','LSR');
END

-- CUSTOMERORDERSETTINGS
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSETTINGS')
BEGIN
	CREATE TABLE [dbo].[CUSTOMERORDERSETTINGS](
		[ORDERTYPE] [uniqueidentifier] NOT NULL,
		[ACCEPTSDEPOSITS] [tinyint] NOT NULL,
		[MINIMUMDEPOSITS] [numeric](28, 12) NOT NULL,
		[SOURCE] [tinyint] NOT NULL,
		[DELIVERY] [tinyint] NOT NULL,		
		[EXPIRATIONTIMEVALUE] [int] NOT NULL,
		[EXPIRATIONTIMEUNIT] [int] NOT NULL,
		[NUMBERSERIES] [nvarchar](20) NOT NULL,
	 CONSTRAINT [PK_CUSTOMERORDERSETTINGS] PRIMARY KEY CLUSTERED 
	(
	[ORDERTYPE] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSETTINGS' AND COLUMN_NAME = 'ACCEPTSDEPOSITS' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERSETTINGS] ADD  CONSTRAINT [DF_CUSTOMERORDERSETTINGS_ACCEPTSDEPOSITS]  DEFAULT ((0)) FOR [ACCEPTSDEPOSITS]	
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSETTINGS' AND COLUMN_NAME = 'MINIMUMDEPOSITS' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERSETTINGS] ADD  CONSTRAINT [DF_CUSTOMERORDERSETTINGS_MINIMUMDEPOSITS]  DEFAULT ((0)) FOR [MINIMUMDEPOSITS]	
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSETTINGS' AND COLUMN_NAME = 'SOURCE' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERSETTINGS] ADD  CONSTRAINT [DF_CUSTOMERORDERSETTINGS_SOURCE]  DEFAULT ((0)) FOR [SOURCE]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSETTINGS' AND COLUMN_NAME = 'DELIVERY' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERSETTINGS] ADD  CONSTRAINT [DF_CUSTOMERORDERSETTINGS_DELIVERY]  DEFAULT ((0)) FOR [DELIVERY]	
END
GO		

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSETTINGS' AND COLUMN_NAME = 'EXPIRATIONTIMEVALUE' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERSETTINGS] ADD  CONSTRAINT [DF_CUSTOMERORDERSETTINGS_EXPIRATIONTIMEVALUE]  DEFAULT ((0)) FOR [EXPIRATIONTIMEVALUE]	
END
GO				

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSETTINGS' AND COLUMN_NAME = 'EXPIRATIONTIMEUNIT' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERSETTINGS] ADD  CONSTRAINT [DF_CUSTOMERORDERSETTINGS_EXPIRATIONTIMEUNIT]  DEFAULT ((0)) FOR [EXPIRATIONTIMEUNIT]	
END
GO						

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSETTINGS' AND COLUMN_NAME = 'NUMBERSERIES' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERSETTINGS] ADD  CONSTRAINT [DF_CUSTOMERORDERSETTINGS_NUMBERSERIES]  DEFAULT ('') FOR [NUMBERSERIES]
END
GO	

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSADDITIONALCONFIG')
BEGIN	
	CREATE TABLE [dbo].[CUSTOMERORDERSADDITIONALCONFIG](
		[ID] [uniqueidentifier] NOT NULL,
		[TYPE] [int] NOT NULL,
		[DESCRIPTION] [nvarchar](50) NOT NULL,
	 CONSTRAINT [PK_CUSTOMERORDERSADDITIONALCONFIG] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSADDITIONALCONFIG' AND COLUMN_NAME = 'TYPE' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERSADDITIONALCONFIG] ADD  CONSTRAINT [DF_CUSTOMERORDERSADDITIONALCONFIG_TYPE]  DEFAULT ((0)) FOR [TYPE]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERSADDITIONALCONFIG' AND COLUMN_NAME = 'DESCRIPTION' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERSADDITIONALCONFIG] ADD  CONSTRAINT [DF_CUSTOMERORDERSADDITIONALCONFIG_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERS')
BEGIN

CREATE TABLE [dbo].[CUSTOMERORDERS](
	[ID] [uniqueidentifier] NOT NULL,
	[REFERENCE] [nvarchar](50) NOT NULL,
	[SOURCE] [uniqueidentifier] NULL,
	[DELIVERY] [uniqueidentifier] NULL,
	[EXPIRES] [datetime] NOT NULL,
	[DELIVERYLOCATIONID] [nvarchar](20) NULL,
	[ORDERTYPE] [uniqueidentifier] NULL,
	[ORDERXML] [xml] NULL,
	[CREATEDSTOREID] [nvarchar](20) NULL,
	[CREATEDBY] [nvarchar](20) NULL,
	[CREATEDTERMINALID] [nvarchar](20) NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[COMMENT] [nvarchar](250) NULL,
	[STATUS] [int] NULL,
	[CUSTOMERID] [nvarchar](20) NULL,
 CONSTRAINT [PK_CUSTOMERORDERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERS' AND COLUMN_NAME = 'REFERENCE' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERS] ADD  CONSTRAINT [DF_CUSTOMERORDERS_REFERENCE]  DEFAULT ('') FOR [REFERENCE]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERS' AND COLUMN_NAME = 'CUSTOMERID' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERS] ADD  CONSTRAINT [DF_CUSTOMERORDERS_CUSTOMERID]  DEFAULT ('') FOR [CUSTOMERID]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERS' AND COLUMN_NAME = 'EXPIRES' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERS] ADD  CONSTRAINT [DF_CUSTOMERORDERS_EXPIRES]  DEFAULT (getdate()) FOR [EXPIRES]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERS' AND COLUMN_NAME = 'CREATEDDATE' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[CUSTOMERORDERS] ADD  CONSTRAINT [DF_CUSTOMERORDERS_CREATEDDATE]  DEFAULT (getdate()) FOR [CREATEDDATE]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERORDERS' AND COLUMN_NAME = 'STATUS' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE dbo.CUSTOMERORDERS ADD CONSTRAINT DF_CUSTOMERORDERS_STATUS DEFAULT 0 FOR STATUS
END
GO


