
/*

	Incident No.	: ONE-3489
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Jerusalem

	Description		: Setting the text fields in CustomerAddress to allow longer strings than before

*/


USE LSPOSNET
GO



IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERADDRESS' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[FK__CUSTOMERADDRESS__61E66462]') AND type = 'F')
	BEGIN
		ALTER TABLE dbo.CUSTOMERADDRESS DROP CONSTRAINT FK__CUSTOMERADDRESS__61E66462
	END
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERADDRESS' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[Update_CUSTOMERADDRESS]'))
	BEGIN
	   DROP TRIGGER [dbo].[Update_CUSTOMERADDRESS]
	END
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERADDRESS' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	ALTER TABLE dbo.CUSTOMERADDRESSTYPE SET (LOCK_ESCALATION = TABLE)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERADDRESS' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN

	CREATE TABLE dbo.Tmp_CUSTOMERADDRESS
		(
		ACCOUNTNUM nvarchar(20) NOT NULL,
		DATAAREAID nvarchar(4) NOT NULL,
		ADDRESSTYPE int NOT NULL,
		STREET nvarchar(250) NULL,
		ADDRESS nvarchar(250) NULL,
		ZIPCODE nvarchar(20) NULL,
		CITY nvarchar(250) NULL,
		STATE nvarchar(250) NULL,
		COUNTY nvarchar(250) NULL,
		COUNTRY nvarchar(250) NULL,
		ADDRESSFORMAT int NULL,
		TAXGROUP nvarchar(20) NULL,
		PHONE nvarchar(80) NULL,
		CELLULARPHONE nvarchar(80) NULL,
		EMAIL nvarchar(80) NULL,
		CONTACTNAME nvarchar(50) NULL
		)  ON [PRIMARY]
	
	ALTER TABLE dbo.Tmp_CUSTOMERADDRESS SET (LOCK_ESCALATION = TABLE)

END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERADDRESS' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN

	IF EXISTS(SELECT * FROM dbo.CUSTOMERADDRESS)
		 EXEC('INSERT INTO dbo.Tmp_CUSTOMERADDRESS (ACCOUNTNUM, DATAAREAID, ADDRESSTYPE, STREET, ADDRESS, ZIPCODE, CITY, STATE, COUNTY, COUNTRY, ADDRESSFORMAT, TAXGROUP, PHONE, CELLULARPHONE, EMAIL, CONTACTNAME)
			SELECT ACCOUNTNUM, DATAAREAID, ADDRESSTYPE, STREET, ADDRESS, ZIPCODE, CITY, STATE, COUNTY, COUNTRY, ADDRESSFORMAT, TAXGROUP, PHONE, CELLULARPHONE, EMAIL, CONTACTNAME FROM dbo.CUSTOMERADDRESS WITH (HOLDLOCK TABLOCKX)')


	DROP TABLE dbo.CUSTOMERADDRESS


	EXECUTE sp_rename N'dbo.Tmp_CUSTOMERADDRESS', N'CUSTOMERADDRESS', 'OBJECT' 


	ALTER TABLE dbo.CUSTOMERADDRESS ADD CONSTRAINT
		PK_CUSTOMERADDRESS PRIMARY KEY CLUSTERED 
		(
		ACCOUNTNUM,
		DATAAREAID,
		ADDRESSTYPE
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	END

GO
