
/*

	Incident No.	: N/A
	Responsible		: Halldór Dungal
	Sprint			: [Sprint number/ID]
	Date created	: 26.11.2010

	Description		: Added log tables for RBOINFOCODETABLE,RBOINFORMATIONSUBCODETABLE and RBOINFOCODETABLESPECIFIC
					  to the audit database

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: RBOINFOCODETABLELog - added
					  RBOINFORMATIONSUBCODETABLELog - added
					  RBOINFOCODETABLESPECIFICLog - added
						
*/

USE LSPOSNET_Audit

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[RBOINFOCODETABLElog]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[RBOINFOCODETABLElog](
	AuditID int NOT NULL IDENTITY (1, 1),
	AuditUserGUID uniqueidentifier NOT NULL,
	AuditUserLogin nvarchar(32) NOT NULL,
	AuditDate datetime NOT NULL,
	[INFOCODEID] [nvarchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](60) NULL,
	[PROMPT] [nvarchar](30) NULL,
	[ONCEPERTRANSACTION] [tinyint] NULL,
	[VALUEISAMOUNTORQUANTITY] [tinyint] NULL,
	[PRINTPROMPTONRECEIPT] [tinyint] NULL,
	[PRINTINPUTONRECEIPT] [tinyint] NULL,
	[PRINTINPUTNAMEONRECEIPT] [tinyint] NULL,
	[INPUTTYPE] [int] NULL,
	[MINIMUMVALUE] [numeric](28, 12) NULL,
	[MAXIMUMVALUE] [numeric](28, 12) NULL,
	[MINIMUMLENGTH] [int] NULL,
	[MAXIMUMLENGTH] [int] NULL,
	[INPUTREQUIRED] [tinyint] NULL,
	[STD1INVALUE] [tinyint] NULL,
	[LINKEDINFOCODEID] [nvarchar](10) NULL,
	[RANDOMFACTOR] [numeric](28, 12) NULL,
	[RANDOMCOUNTER] [numeric](28, 12) NULL,
	[DATATYPEID] [nvarchar](20) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDTIME] [int] NULL,
	[MODIFIEDBY] [nvarchar](5) NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[ADDITIONALCHECK] [int] NULL,
	[USAGECATEGORY] [int] NULL,
	[DISPLAYOPTION] [int] NULL,
	[LINKITEMLINESTOTRIGGERLINE] [tinyint] NULL,
	[MULTIPLESELECTION] [tinyint] NULL,
	[TRIGGERING] [tinyint] NULL,
	[MINSELECTION] [int] NULL,
	[MAXSELECTION] [int] NULL,
	[CREATEINFOCODETRANSENTRIES] [tinyint] NULL,
	[EXPLANATORYHEADERTEXT] [nvarchar](30) NULL,
	[OKPRESSEDACTION] [int] NULL,
	[Deleted] [bit] NULL)
	
	ALTER TABLE dbo.[RBOINFOCODETABLElog] add constraint PK_RBOINFOCODETABLElog
	PRIMARY KEY CLUSTERED (AuditID) on [PRIMARY]

	CREATE NONCLUSTERED INDEX IX_RBOINFOCODETABLElog_AuditUserGUID ON dbo.RBOINFOCODETABLElog (AuditUserGUID) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[RBOINFORMATIONSUBCODETABLELog]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[RBOINFORMATIONSUBCODETABLELog](
	AuditID int NOT NULL IDENTITY (1, 1),
	AuditUserGUID uniqueidentifier NOT NULL,
	AuditUserLogin nvarchar(32) NOT NULL,
	AuditDate datetime NOT NULL,
	[INFOCODEID] [nvarchar](10) NOT NULL,
	[SUBCODEID] [nvarchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](60) NULL,
	[TRIGGERFUNCTION] [int] NULL,
	[TRIGGERCODE] [nvarchar](20) NULL,
	[NEWSALESLINE] [tinyint] NULL,
	[PRICETYPE] [int] NULL,
	[AMOUNTPERCENT] [numeric](28, 12) NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[USAGECATEGORY] [int] NULL,
	[VARIANTCODE] [nvarchar](10) NULL,
	[VARIANTNEEDED] [tinyint] NULL,
	[QTYLINKEDTOTRIGGERLINE] [tinyint] NULL,
	[PRICEHANDLING] [int] NULL,
	[LINKEDINFOCODE] [nvarchar](10) NULL,
	[UNITOFMEASURE] [nvarchar](10) NULL,
	[QTYPERUNITOFMEASURE] [numeric](28, 12) NULL,
	[INFOCODEPROMPT] [nvarchar](30) NULL,
	[MAXSELECTION] [int] NULL,
	[SERIALLOTNEEDED] [tinyint] NULL,
	[Deleted] [bit] NULL)

	ALTER TABLE dbo.[RBOINFORMATIONSUBCODETABLELog] add constraint PK_RBOINFORMATIONSUBCODETABLELog
	PRIMARY KEY CLUSTERED (AuditID) on [PRIMARY]

	CREATE NONCLUSTERED INDEX IX_RBOINFORMATIONSUBCODETABLELog_AuditUserGUID ON dbo.RBOINFORMATIONSUBCODETABLELog (AuditUserGUID) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[RBOINFOCODETABLESPECIFICLog]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[RBOINFOCODETABLESPECIFICLog](
	AuditID int NOT NULL IDENTITY (1, 1),
	AuditUserGUID uniqueidentifier NOT NULL,
	AuditUserLogin nvarchar(32) NOT NULL,
	AuditDate datetime NOT NULL,
	[REFRELATION] [nvarchar](20) NOT NULL,
	[SEQUENCE] [int] NULL,
	[INFOCODEID] [nvarchar](10) NOT NULL,
	[INPUTREQUIRED] [tinyint] NULL,
	[WHENREQUIRED] [int] NULL,
	[REFRELATION2] [nvarchar](20) NOT NULL,
	[REFRELATION3] [nvarchar](20) NOT NULL,
	[REFTABLEID] [int] NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[TRIGGERING] [tinyint] NULL,
	[UNITOFMEASURE] [nvarchar](10) NULL,
	[SALESTYPEFILTER] [nvarchar](250) NULL,
	[USAGECATEGORY] [int] NULL,
	[Deleted] [bit] NULL)
	
ALTER TABLE dbo.[RBOINFOCODETABLESPECIFICLog] add constraint PK_RBOINFOCODETABLESPECIFICLog
	PRIMARY KEY CLUSTERED (AuditID) on [PRIMARY]

	CREATE NONCLUSTERED INDEX IX_RBOINFOCODETABLESPECIFICLog_AuditUserGUID ON dbo.RBOINFOCODETABLESPECIFICLog (AuditUserGUID) ON [PRIMARY]
END
GO
