
/*

	Incident No.	: N/A
	Responsible		: GuÃ°bjÃ¶rn Einarsson
	Sprint			: 2011 - Sprint 5
	Date created	: 04.01.2011

	Description		: Add a field to PURCHASEORDERSLog, remove some fields and edit another fields type

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	:	PURCHASEORDERSLog	-	STOREID field added	
						PURCHASEORDERSLog	-	DELIVERYNAME field removed
						PURCHASEORDERSLog	-	DELIVERYADDRESS field removed
						PURCHASEORDERSLog	-	DELIVERYSTREET field removed
						PURCHASEORDERSLog	-	DELIVERYZIPCODE field removed
						PURCHASEORDERSLog	-	DELIVERYCITY field removed
						PURCHASEORDERSLog	-	DELIVERYCOUNTY field removed
						PURCHASEORDERSLog	-	DELIVERYSTATE field removed
						PURCHASEORDERSLog	-	DELIVERYCOUNTRY field removed	
						PURCHASEORDERSLog	-	ORDERER field from nvarchar(20) to UniqueIdentifier	 
*/

USE LSPOSNET_Audit

GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERSLog') AND NAME='STOREID')
Begin
	ALTER TABLE PURCHASEORDERSLog ADD STOREID [nvarchar](20) NULL
End

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERSLog') AND NAME='DELIVERYADDRESS')
Begin
	ALTER TABLE PURCHASEORDERSLog DROP COLUMN DELIVERYADDRESS
End

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERSLog') AND NAME='DELIVERYSTREET')
Begin
	ALTER TABLE PURCHASEORDERSLog DROP COLUMN DELIVERYSTREET
End

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERSLog') AND NAME='DELIVERYZIPCODE')
Begin
	ALTER TABLE PURCHASEORDERSLog DROP COLUMN DELIVERYZIPCODE
End

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERSLog') AND NAME='DELIVERYCITY')
Begin
	ALTER TABLE PURCHASEORDERSLog DROP COLUMN DELIVERYCITY
End

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERSLog') AND NAME='DELIVERYCOUNTY')
Begin
	ALTER TABLE PURCHASEORDERSLog DROP COLUMN DELIVERYCOUNTY
End

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERSLog') AND NAME='DELIVERYSTATE')
Begin
	ALTER TABLE PURCHASEORDERSLog DROP COLUMN DELIVERYSTATE
End

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERSLog') AND NAME='DELIVERYCOUNTRY')
Begin
	ALTER TABLE PURCHASEORDERSLog DROP COLUMN DELIVERYCOUNTRY
End

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERSLog') AND NAME='DELIVERYNAME')
Begin
	ALTER TABLE PURCHASEORDERSLog DROP COLUMN DELIVERYNAME
End

IF 'nvarchar' IN (SELECT data_type FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PURCHASEORDERSLog' AND COLUMN_NAME = 'ORDERER')
BEGIN
	Alter Table PURCHASEORDERSLog Drop Column ORDERER

	Alter Table PURCHASEORDERSLog Add ORDERER UniqueIdentifier NULL
	
END