
/*

	Incident No.	: 
	Responsible		: BjÃ¶rn EirÃ­ksson
	Sprint			: LS Retail .NET v 2010 - Sprint 4
	Date created	:21.12.2010
	
	Description		: Change tables to use 20 letter keys for the new sequence manager.

	Logic scripts   : No stored procedures added or changed
	
	Tables affected:	- Most
						
*/


USE LSPOSNET_Audit

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'BARCODESETUPLog' AND COLUMN_NAME = 'BARCODESETUPID') = 10)
begin
	ALTER TABLE BARCODESETUPLog ALTER COLUMN BARCODESETUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'COMPANYINFOLog' AND COLUMN_NAME = 'COUNTRYREGIONID') = 10)
begin
	ALTER TABLE COMPANYINFOLog ALTER COLUMN COUNTRYREGIONID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'CUSTGROUPLog' AND COLUMN_NAME = 'CUSTGROUP') = 10)
begin
	ALTER TABLE CUSTGROUPLog ALTER COLUMN CUSTGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'CUSTTABLELog' AND COLUMN_NAME = 'CUSTGROUP') = 10)
begin
	ALTER TABLE CUSTTABLELog ALTER COLUMN CUSTGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN PAYMTERMID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN CASHDISC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN DIMENSION [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN DIMENSION2_ [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN DIMENSION3_ [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN VENDACCOUNT [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN INVENTLOCATION [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN DLVTERM [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN DLVMODE [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN CLEARINGPERIOD [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN CREDITRATING [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN STATISTICSGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN PAYMMODE [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN BANKACCOUNT [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN CONTACTPERSONID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN SALESPOOLID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN CUSTITEMGROUPID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN NUMBERSEQUENCEGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN PAYMDAYID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN LINEOFBUSINESSID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN DESTINATIONCODEID [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN PAYMSPEC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN TAXGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN LINEDISC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN SALESGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN PRICEGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN MULTILINEDISC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN ENDDISC [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN MARKUPGROUP [nvarchar](20) NULL
	ALTER TABLE CUSTTABLELog ALTER COLUMN COMMISSIONGROUP [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'DECIMALSETTINGSLog' AND COLUMN_NAME = 'ID') = 10)
begin
	ALTER TABLE DECIMALSETTINGSLog ALTER COLUMN ID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'HOSPITALITYSETUPLog' AND COLUMN_NAME = 'SETUP') = 10)
begin
	ALTER TABLE HOSPITALITYSETUPLog ALTER COLUMN SETUP [nvarchar](20) NOT NULL
	
	ALTER TABLE HOSPITALITYSETUPLog ALTER COLUMN TABLEFREECOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUPLog ALTER COLUMN TABLENOTAVAILCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUPLog ALTER COLUMN TABLELOCKEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUPLog ALTER COLUMN ORDERPRINTEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUPLog ALTER COLUMN ORDERSTARTEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUPLog ALTER COLUMN ORDERFINISHEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUPLog ALTER COLUMN ORDERCONFIRMEDCOLORF [nvarchar](20) NULL
	ALTER TABLE HOSPITALITYSETUPLog ALTER COLUMN POSTERMINALPRINTPREORDERS [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTDIMLog' AND COLUMN_NAME = 'WMSLOCATIONID') = 10)
begin
	ALTER TABLE INVENTDIMLog ALTER COLUMN WMSLOCATIONID [nvarchar](20) NULL
	ALTER TABLE INVENTDIMLog ALTER COLUMN INVENTLOCATIONID [nvarchar](20) NULL
	ALTER TABLE INVENTDIMLog ALTER COLUMN INVENTSTYLEID [nvarchar](20) NULL
	ALTER TABLE INVENTDIMLog ALTER COLUMN INVENTCOLORID [nvarchar](20) NULL
	ALTER TABLE INVENTDIMLog ALTER COLUMN INVENTSIZEID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTDIMCOMBINATIONLog' AND COLUMN_NAME = 'RBOVARIANTID') = 10)
begin
	ALTER TABLE INVENTDIMCOMBINATIONLog ALTER COLUMN RBOVARIANTID [nvarchar](20) NULL
	ALTER TABLE INVENTDIMCOMBINATIONLog ALTER COLUMN INVENTSIZEID [nvarchar](20) NOT NULL
	ALTER TABLE INVENTDIMCOMBINATIONLog ALTER COLUMN INVENTCOLORID [nvarchar](20) NOT NULL
	ALTER TABLE INVENTDIMCOMBINATIONLog ALTER COLUMN INVENTSTYLEID [nvarchar](20) NOT NULL
	ALTER TABLE INVENTDIMCOMBINATIONLog ALTER COLUMN CONFIGID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTDIMGROUPLog' AND COLUMN_NAME = 'DIMGROUPID') = 10)
begin
	ALTER TABLE INVENTDIMGROUPLog ALTER COLUMN DIMGROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTDIMSETUPLog' AND COLUMN_NAME = 'DIMGROUPID') = 10)
begin
	ALTER TABLE INVENTDIMSETUPLog ALTER COLUMN DIMGROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTITEMBARCODELog' AND COLUMN_NAME = 'BARCODESETUPID') = 10)
begin
	ALTER TABLE INVENTITEMBARCODELog ALTER COLUMN BARCODESETUPID [nvarchar](20) NULL
	ALTER TABLE INVENTITEMBARCODELog ALTER COLUMN RBOVARIANTID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTITEMGROUPLog' AND COLUMN_NAME = 'ITEMGROUPID') = 10)
begin
	ALTER TABLE INVENTITEMGROUPLog ALTER COLUMN ITEMGROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTTABLELog' AND COLUMN_NAME = 'ITEMGROUPID') = 10)
begin
	ALTER TABLE INVENTTABLELog ALTER COLUMN ITEMGROUPID [nvarchar](20) NOT NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN REQGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN PRIMARYVENDORID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN DIMENSION [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN DIMENSION2_ [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN DIMENSION3_ [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN BATCHNUMGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN PRODPOOLID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN PROPERTYID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN PRODGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN PROJCATEGORYID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN SERIALNUMGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN DIMGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN MODELGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN ITEMBUYERGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLELog ALTER COLUMN PBAINVENTITEMGROUPID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'INVENTTABLEMODULELog' AND COLUMN_NAME = 'UNITID') = 10)
begin
	ALTER TABLE INVENTTABLEMODULELog ALTER COLUMN UNITID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULELog ALTER COLUMN INVENTLOCATIONID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULELog ALTER COLUMN TAXITEMGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULELog ALTER COLUMN LINEDISC [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULELog ALTER COLUMN MULTILINEDISC [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULELog ALTER COLUMN MARKUPGROUPID [nvarchar](20) NULL
	ALTER TABLE INVENTTABLEMODULELog ALTER COLUMN SUPPITEMGROUPID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'NUMBERSEQUENCETABLELog' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE NUMBERSEQUENCETABLELog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSCOLORLog' AND COLUMN_NAME = 'COLORCODE') = 10)
begin
	ALTER TABLE POSCOLORLog ALTER COLUMN COLORCODE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSDISCVALIDATIONPERIODLog' AND COLUMN_NAME = 'ID') = 10)
begin
	ALTER TABLE POSDISCVALIDATIONPERIODLog ALTER COLUMN ID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'PROFILEID') = 10)
begin
	ALTER TABLE POSFUNCTIONALITYPROFILELog ALTER COLUMN PROFILEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSHARDWAREPROFILELog' AND COLUMN_NAME = 'PROFILEID') = 10)
begin
	ALTER TABLE POSHARDWAREPROFILELog ALTER COLUMN PROFILEID [nvarchar](20) NOT NULL
end

GO

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISBUTTONGRID' AND COLUMN_NAME = 'BUTTONGRIDID') = 10)
begin
	ALTER TABLE POSISBUTTONGRID ALTER COLUMN BUTTONGRIDID [nvarchar](20) NOT NULL
	ALTER TABLE POSISBUTTONGRID ALTER COLUMN KEYBOARDUSED [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISHOSPITALITYDININGTABLESLog' AND COLUMN_NAME = 'STAFFID') = 10)
begin
	ALTER TABLE POSISHOSPITALITYDININGTABLESLog ALTER COLUMN STAFFID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISHOSPITALITYTRANSTABLELog' AND COLUMN_NAME = 'TRANSACTIONID') = 10)
begin
	ALTER TABLE POSISHOSPITALITYTRANSTABLELog ALTER COLUMN TRANSACTIONID [nvarchar](20) NOT NULL
	ALTER TABLE POSISHOSPITALITYTRANSTABLELog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE POSISHOSPITALITYTRANSTABLELog ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL
	ALTER TABLE POSISHOSPITALITYTRANSTABLELog ALTER COLUMN TABLEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISINFO' AND COLUMN_NAME = 'ID') = 10)
begin
	ALTER TABLE POSISINFO ALTER COLUMN ID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISLICENSELog' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE POSISLICENSELog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE POSISLICENSELog ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISTILLLAYOUTLog' AND COLUMN_NAME = 'LAYOUTID') = 10)
begin
	ALTER TABLE POSISTILLLAYOUTLog ALTER COLUMN LAYOUTID [nvarchar](20) NOT NULL
	ALTER TABLE POSISTILLLAYOUTLog ALTER COLUMN BUTTONGRID1 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUTLog ALTER COLUMN BUTTONGRID2 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUTLog ALTER COLUMN BUTTONGRID3 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUTLog ALTER COLUMN BUTTONGRID4 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUTLog ALTER COLUMN BUTTONGRID5 [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUTLog ALTER COLUMN RECEIPTID [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUTLog ALTER COLUMN TOTALID [nvarchar](20) NULL
	ALTER TABLE POSISTILLLAYOUTLog ALTER COLUMN CUSTOMERLAYOUTID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISUPDATESMASTERLog' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE POSISUPDATESMASTERLog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE POSISUPDATESMASTERLog ALTER COLUMN POSID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSISUPGRADESLog' AND COLUMN_NAME = 'UPGRADEID') = 10)
begin
	ALTER TABLE POSISUPGRADESLog ALTER COLUMN UPGRADEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSMMLINEGROUPSLog' AND COLUMN_NAME = 'LINEGROUP') = 10)
begin
	ALTER TABLE POSMMLINEGROUPSLog ALTER COLUMN LINEGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSPERIODICDISCOUNTLog' AND COLUMN_NAME = 'DISCVALIDPERIODID') = 10)
begin
	ALTER TABLE POSPERIODICDISCOUNTLog ALTER COLUMN DISCVALIDPERIODID [nvarchar](20) NULL
	ALTER TABLE POSPERIODICDISCOUNTLog ALTER COLUMN PRICEGROUP [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSTRANSACTIONSERVICEPROFILELog' AND COLUMN_NAME = 'PROFILEID') = 10)
begin
	ALTER TABLE POSTRANSACTIONSERVICEPROFILELog ALTER COLUMN PROFILEID [nvarchar](20) NOT NULL
	ALTER TABLE POSTRANSACTIONSERVICEPROFILELog ALTER COLUMN COMPANY [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSVISUALPROFILELog' AND COLUMN_NAME = 'PROFILEID') = 10)
begin
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN PROFILEID [nvarchar](20) NOT NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN STARTMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN SALESMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN PAYMENTMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN TENDEROPERATIONMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN NEGATIVEADJUSTMENTMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN PHYSICALINVENTORYMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN NORMALCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN VOIDEDCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN MULTIBUYCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN MIXANDMATCHCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN TOTALDISCOUNTCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN INCOMEEXPENSECOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN COUPONLINECOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN LINESELECTCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN FREETEXTCOLOR [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN TABLEMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN TOPLINEMENU [nvarchar](20) NULL
	ALTER TABLE POSVISUALPROFILELog ALTER COLUMN JOURNALMENU [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'PRICEDISCGROUPLog' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE PRICEDISCGROUPLog ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'PRICEDISCTABLELog' AND COLUMN_NAME = 'UNITID') = 10)
begin
	ALTER TABLE PRICEDISCTABLELog ALTER COLUMN UNITID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'PRICEGROUPLog' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE PRICEGROUPLog ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOBARCODEMASKSEGMENTLog' AND COLUMN_NAME = 'MASKID') = 10)
begin
	ALTER TABLE RBOBARCODEMASKSEGMENTLog ALTER COLUMN MASKID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOBARCODEMASKTABLELog' AND COLUMN_NAME = 'MASKID') = 10)
begin
	ALTER TABLE RBOBARCODEMASKTABLELog ALTER COLUMN MASKID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOCOLORGROUPTABLELog' AND COLUMN_NAME = 'COLORGROUP') = 10)
begin
	ALTER TABLE RBOCOLORGROUPTABLELog ALTER COLUMN COLORGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOCOLORGROUPTRANSLog' AND COLUMN_NAME = 'COLORGROUP') = 10)
begin
	ALTER TABLE RBOCOLORGROUPTRANSLog ALTER COLUMN COLORGROUP [nvarchar](20) NOT NULL
	ALTER TABLE RBOCOLORGROUPTRANSLog ALTER COLUMN COLOR [nvarchar](20) NOT NULL
	ALTER TABLE RBOCOLORGROUPTRANSLog ALTER COLUMN NOINBARCODE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOCOLORSLog' AND COLUMN_NAME = 'COLOR') = 10)
begin
	ALTER TABLE RBOCOLORSLog ALTER COLUMN COLOR [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOCUSTTABLELog' AND COLUMN_NAME = 'ACCOUNTNUM') = 10)
begin
	ALTER TABLE RBOCUSTTABLELog ALTER COLUMN ACCOUNTNUM [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBODISCOUNTOFFERLINELog' AND COLUMN_NAME = 'OFFERID') = 10)
begin
	ALTER TABLE RBODISCOUNTOFFERLINELog ALTER COLUMN OFFERID [nvarchar](20) NOT NULL
	ALTER TABLE RBODISCOUNTOFFERLINELog ALTER COLUMN UNIT [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBODISCOUNTOFFERTABLELog' AND COLUMN_NAME = 'OFFERID') = 10)
begin
	ALTER TABLE RBODISCOUNTOFFERTABLELog ALTER COLUMN OFFERID [nvarchar](20) NOT NULL
	ALTER TABLE RBODISCOUNTOFFERTABLELog ALTER COLUMN DISCOUNTVALIDATIONPERIODID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINFOCODETABLElog' AND COLUMN_NAME = 'INFOCODEID') = 10)
begin
	ALTER TABLE RBOINFOCODETABLElog ALTER COLUMN INFOCODEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINFOCODETABLElog ALTER COLUMN LINKEDINFOCODEID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINFOCODETABLESPECIFICLog' AND COLUMN_NAME = 'INFOCODEID') = 10)
begin
	ALTER TABLE RBOINFOCODETABLESPECIFICLog ALTER COLUMN INFOCODEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINFOCODETABLESPECIFICLog ALTER COLUMN UNITOFMEASURE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINFORMATIONSUBCODETABLELog' AND COLUMN_NAME = 'INFOCODEID') = 10)
begin
	ALTER TABLE RBOINFORMATIONSUBCODETABLELog ALTER COLUMN INFOCODEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINFORMATIONSUBCODETABLELog ALTER COLUMN SUBCODEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINFORMATIONSUBCODETABLELog ALTER COLUMN VARIANTCODE [nvarchar](20) NULL
	ALTER TABLE RBOINFORMATIONSUBCODETABLELog ALTER COLUMN LINKEDINFOCODE [nvarchar](20) NULL
	ALTER TABLE RBOINFORMATIONSUBCODETABLELog ALTER COLUMN UNITOFMEASURE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINVENTITEMDEPARTMENTLog' AND COLUMN_NAME = 'DEPARTMENTID') = 10)
begin
	ALTER TABLE RBOINVENTITEMDEPARTMENTLog ALTER COLUMN DEPARTMENTID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINVENTITEMDEPARTMENTLog ALTER COLUMN DISPENSEPRINTERGROUPID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINVENTITEMRETAILGROUPLog' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN DEPARTMENTID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN SIZEGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN COLORGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN DISPENSEPRINTERGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN BARCODESETUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN STYLEGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN FSHREPLENISHMENTRULEID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN ITEMGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN INVENTLOCATIONIDFORPURCHA16016 [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN INVENTLOCATIONIDFORINVENTORY [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN INVENTLOCATIONIDFORSALESORDER [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN INVENTMODELGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN INVENTDIMGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN SALESTAXITEMGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN PURCHASETAXITEMGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN BASECOMPARISONUNITCODE [nvarchar](20) NULL
	ALTER TABLE RBOINVENTITEMRETAILGROUPLog ALTER COLUMN LSRCOMMISSIONGROUPID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOINVENTTABLELog' AND COLUMN_NAME = 'ITEMGROUP') = 10)
begin
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN ITEMGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN ITEMDEPARTMENT [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN ITEMFAMILY [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN DISPENSEPRINTERGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN BASECOMPARISONUNITCODE [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN BARCODESETUPID [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN COLORGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN SIZEGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN STYLEGROUP [nvarchar](20) NULL
	ALTER TABLE RBOINVENTTABLELog ALTER COLUMN GRADEID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOLOCATIONPRICEGROUPLog' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOLOCATIONPRICEGROUPLog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOLOCATIONPRICEGROUPLog ALTER COLUMN PRICEGROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOPARAMETERS' AND COLUMN_NAME = 'LOCALSTOREID') = 10)
begin
	ALTER TABLE RBOPARAMETERSLog ALTER COLUMN LOCALSTOREID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSIZEGROUPTABLELog' AND COLUMN_NAME = 'SIZEGROUP') = 10)
begin
	ALTER TABLE RBOSIZEGROUPTABLELog ALTER COLUMN SIZEGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSIZEGROUPTRANSLog' AND COLUMN_NAME = 'SIZEGROUP') = 10)
begin
	ALTER TABLE RBOSIZEGROUPTRANSLog ALTER COLUMN SIZEGROUP [nvarchar](20) NOT NULL
	ALTER TABLE RBOSIZEGROUPTRANSLog ALTER COLUMN SIZE_ [nvarchar](20) NOT NULL
	ALTER TABLE RBOSIZEGROUPTRANSLog ALTER COLUMN NOINBARCODE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSIZESLog' AND COLUMN_NAME = 'SIZE_') = 10)
begin
	ALTER TABLE RBOSIZESLog ALTER COLUMN SIZE_ [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSPECIALGROUPLog' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE RBOSPECIALGROUPLog ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSPECIALGROUPITEMSLog' AND COLUMN_NAME = 'GROUPID') = 10)
begin
	ALTER TABLE RBOSPECIALGROUPITEMSLog ALTER COLUMN GROUPID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSPECIALGROUPITEMSLog ALTER COLUMN ITEMID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTAFFTABLELog' AND COLUMN_NAME = 'STAFFID') = 10)
begin
	ALTER TABLE RBOSTAFFTABLELog ALTER COLUMN STAFFID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTAFFTABLELog ALTER COLUMN STOREID [nvarchar](20) NULL
	ALTER TABLE RBOSTAFFTABLELog ALTER COLUMN PERMISSIONGROUPID [nvarchar](20) NULL
	ALTER TABLE RBOSTAFFTABLELog ALTER COLUMN ZREPORTID [nvarchar](20) NULL
	ALTER TABLE RBOSTAFFTABLELog ALTER COLUMN LAYOUTID [nvarchar](20) NULL
	ALTER TABLE RBOSTAFFTABLELog ALTER COLUMN OPERATORCULTURE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTATEMENTLINELog' AND COLUMN_NAME = 'STAFFID') = 10)
begin
	ALTER TABLE RBOSTATEMENTLINELog ALTER COLUMN STAFFID [nvarchar](20) NULL
	ALTER TABLE RBOSTATEMENTLINELog ALTER COLUMN TERMINALID [nvarchar](20) NULL
	ALTER TABLE RBOSTATEMENTLINELog ALTER COLUMN CURRENCYCODE [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTATEMENTLINELog ALTER COLUMN TENDERID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTATEMENTTABLELog' AND COLUMN_NAME = 'STATEMENTID') = 10)
begin
	ALTER TABLE RBOSTATEMENTTABLELog ALTER COLUMN STATEMENTID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTATEMENTTABLELog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTORECASHDECLARATIONTABLELog' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOSTORECASHDECLARATIONTABLELog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTORETABLELog' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN MANAGERID [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN DIMENSION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN DIMENSION2_ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN DIMENSION3_ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN INVENTLOCATION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN ROUNDINGACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN STATEMENTNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN FUNCTIONALITYPROFILE [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN TERMINALNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN STAFFNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN ITEMNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN DISCOUNTOFFERNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN MIXANDMATCHNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN MULTIBUYDISCOUNTNUMSEQ [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN REMOVEADDTENDER [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN INCOMEEXEPENSEACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN TAXGROUP [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN ROUNDINGTAXACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN CULTURENAME [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN LAYOUTID [nvarchar](20) NULL
	ALTER TABLE RBOSTORETABLELog ALTER COLUMN DEFAULTCUSTACCOUNT [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTORETENDERTYPECARDTABLELog' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOSTORETENDERTYPECARDTABLELog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLELog ALTER COLUMN TENDERTYPEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLELog ALTER COLUMN CARDTYPEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLELog ALTER COLUMN ACCOUNTRELATION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLELog ALTER COLUMN DIFFERENCEACCOUNT [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLELog ALTER COLUMN DIFFERENCEACCOUNTFORBIGDI20017 [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPECARDTABLELog ALTER COLUMN CARDFEEACCOUNT [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTORETENDERTYPETABLELog' AND COLUMN_NAME = 'STOREID') = 10)
begin
	ALTER TABLE RBOSTORETENDERTYPETABLELog ALTER COLUMN STOREID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPETABLELog ALTER COLUMN TENDERTYPEID [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTORETENDERTYPETABLELog ALTER COLUMN LINENUMINTRANSACTION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPETABLELog ALTER COLUMN CHANGETENDERID [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPETABLELog ALTER COLUMN ABOVEMINIMUMTENDERID [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPETABLELog ALTER COLUMN ACCOUNTRELATION [nvarchar](20) NULL
	ALTER TABLE RBOSTORETENDERTYPETABLELog ALTER COLUMN DIFFERENCEACCOUNT [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTYLEGROUPTABLELog' AND COLUMN_NAME = 'STYLEGROUP') = 10)
begin
	ALTER TABLE RBOSTYLEGROUPTABLELog ALTER COLUMN STYLEGROUP [nvarchar](20) NOT NULL
end


GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTYLEGROUPTRANSLog' AND COLUMN_NAME = 'STYLEGROUP') = 10)
begin
	ALTER TABLE RBOSTYLEGROUPTRANSLog ALTER COLUMN STYLEGROUP [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTYLEGROUPTRANSLog ALTER COLUMN STYLE [nvarchar](20) NOT NULL
	ALTER TABLE RBOSTYLEGROUPTRANSLog ALTER COLUMN NOINBARCODE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOSTYLESLog' AND COLUMN_NAME = 'STYLE') = 10)
begin
	ALTER TABLE RBOSTYLESLog ALTER COLUMN STYLE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTENDERTYPECARDNUMBERSLog' AND COLUMN_NAME = 'CARDTYPEID') = 10)
begin
	ALTER TABLE RBOTENDERTYPECARDNUMBERSLog ALTER COLUMN CARDTYPEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTENDERTYPECARDTABLELog' AND COLUMN_NAME = 'CARDTYPEID') = 10)
begin
	ALTER TABLE RBOTENDERTYPECARDTABLELog ALTER COLUMN CARDTYPEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTENDERTYPETABLELog' AND COLUMN_NAME = 'TENDERTYPEID') = 10)
begin
	ALTER TABLE RBOTENDERTYPETABLELog ALTER COLUMN TENDERTYPEID [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTERMINALTABLELog' AND COLUMN_NAME = 'TERMINALID') = 10)
begin
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN TERMINALID [nvarchar](20) NOT NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN STOREID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN EFTSTOREID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN EFTTERMINALID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN HARDWAREPROFILE [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN VISUALPROFILE [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN LASTZREPORTID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN LAYOUTID [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN FUNCTIONALITYPROFILE [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN RECEIPTIDNUMBERSEQUENCE [nvarchar](20) NULL
	ALTER TABLE RBOTERMINALTABLELog ALTER COLUMN TRANSACTIONSERVICEPROFILE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'SALESTYPELog' AND COLUMN_NAME = 'PURCHASINGCODE') = 10)
begin
	ALTER TABLE SALESTYPELog ALTER COLUMN PURCHASINGCODE [nvarchar](20) NULL
	ALTER TABLE SALESTYPELog ALTER COLUMN TAXGROUPID [nvarchar](20) NULL
	ALTER TABLE SALESTYPELog ALTER COLUMN PRICEGROUP [nvarchar](20) NULL
	ALTER TABLE SALESTYPELog ALTER COLUMN LOCATIONCODE [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXDATALog' AND COLUMN_NAME = 'TAXCODE') = 10)
begin
	ALTER TABLE TAXDATALog ALTER COLUMN TAXCODE [nvarchar](20) NOT NULL
	ALTER TABLE TAXDATALog ALTER COLUMN POSTAXCODEID [nvarchar](20) NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXGROUPDATALog' AND COLUMN_NAME = 'TAXGROUP') = 10)
begin
	ALTER TABLE TAXGROUPDATALog ALTER COLUMN TAXGROUP [nvarchar](20) NOT NULL
	ALTER TABLE TAXGROUPDATALog ALTER COLUMN TAXCODE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXGROUPHEADINGLog' AND COLUMN_NAME = 'TAXGROUP') = 10)
begin
	ALTER TABLE TAXGROUPHEADINGLog ALTER COLUMN TAXGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXITEMGROUPHEADINGLog' AND COLUMN_NAME = 'TAXITEMGROUP') = 10)
begin
	ALTER TABLE TAXITEMGROUPHEADINGLog ALTER COLUMN TAXITEMGROUP [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXONITEMLog' AND COLUMN_NAME = 'TAXITEMGROUP') = 10)
begin
	ALTER TABLE TAXONITEMLog ALTER COLUMN TAXITEMGROUP [nvarchar](20) NOT NULL
	ALTER TABLE TAXONITEMLog ALTER COLUMN TAXCODE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'TAXTABLELog' AND COLUMN_NAME = 'TAXCODE') = 10)
begin
	ALTER TABLE TAXTABLELog ALTER COLUMN TAXCODE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'UNITLog' AND COLUMN_NAME = 'UNITID') = 10)
begin
	ALTER TABLE UNITLog ALTER COLUMN UNITID [nvarchar](20) NOT NULL
	ALTER TABLE UNITLog ADD MINUNITDECIMALS int NULL  
end


GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'UNITCONVERTLog' AND COLUMN_NAME = 'FROMUNIT') = 10)
begin
	ALTER TABLE UNITCONVERTLog ALTER COLUMN FROMUNIT [nvarchar](20) NOT NULL
	ALTER TABLE UNITCONVERTLog ALTER COLUMN TOUNIT [nvarchar](20) NOT NULL 
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'USERSLog' AND COLUMN_NAME = 'STAFFID') = 10)
begin
	ALTER TABLE USERSLog ALTER COLUMN STAFFID [nvarchar](20) NULL
end

GO