
/*
	This script collects audit updates for the 2011.1.1 branch.

	Incident No.	: NA
	Responsible		: Guðbjörn Einarsson
	Sprint			: SP3
	Date created	: 13.07.2011

	Description		: Added name field to CUSTTABLELog
					  Changed EFTPASSWORD in POSHARDWAREPROFILELog tables from nvarchar(10) to nvarchar(20)
					  Added field to RBOSTORETABLELog

	Logic scripts   : Audit Logic
	
	Tables affected	: CUSTTABLELog
					  POSHARDWAREPROFILELog - EFTPASSWORD changed
					  RBOSTORETABLELog - field added
						
*/

USE LSPOSNET_Audit

GO
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLELog') AND NAME='FIRSTNAME')
ALTER TABLE dbo.CUSTTABLELog ADD FIRSTNAME NVARCHAR(31) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLELog') AND NAME='MIDDLENAME')
ALTER TABLE dbo.CUSTTABLELog ADD MIDDLENAME NVARCHAR(15) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLELog') AND NAME='LASTNAME')
ALTER TABLE dbo.CUSTTABLELog ADD LASTNAME NVARCHAR(20) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLELog') AND NAME='NAMEPREFIX')
ALTER TABLE dbo.CUSTTABLELog ADD NAMEPREFIX NVARCHAR(8) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLELog') AND NAME='NAMESUFFIX')
ALTER TABLE dbo.CUSTTABLELog ADD NAMESUFFIX NVARCHAR(8) NULL

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSHARDWAREPROFILELog' AND COLUMN_NAME = 'EFTPASSWORD') = 10)
begin
	ALTER TABLE POSHARDWAREPROFILELog ALTER COLUMN EFTPASSWORD [nvarchar](20) NULL
end

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETABLELog') AND NAME='USETAXGROUPFROM')
ALTER TABLE dbo.RBOSTORETABLELog ADD USETAXGROUPFROM int NULL
GO
