
/*

	Incident No.	: 12062
	Responsible		: Óskar Bjarnason
	Sprint			: LS Retail .NET 2012/Thor
	Date created	: 17.10.2011
	
	Description		: Add fields to POSTRANSACTIONSERVICEPROFILELog

	Logic scripts   : No stored procedures added or changed
	
	Tables affected:	- POSTRANSACTIONSERVICEPROFILELog - fields added
						
*/


USE LSPOSNET_Audit

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSTRANSACTIONSERVICEPROFILELog') AND NAME='USECENTRALSUSPENSION')
ALTER TABLE dbo.POSTRANSACTIONSERVICEPROFILELog ADD USECENTRALSUSPENSION TINYINT NULL

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='NUMPADENTRYSTARTSINDECIMALS')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD NUMPADENTRYSTARTSINDECIMALS TINYINT NULL

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='NUMPADAMOUNTOFDECIMALS')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD NUMPADAMOUNTOFDECIMALS INT NULL

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='SAFEDROPUSESNUMPAD')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD SAFEDROPUSESNUMPAD TINYINT NULL

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='SAFEDROPREVUSESNUMPAD')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD SAFEDROPREVUSESNUMPAD TINYINT NULL

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='BANKDROPUSESNUMPAD')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD BANKDROPUSESNUMPAD TINYINT NULL

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='BANKDROPREVUSESNUMPAD')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD BANKDROPREVUSESNUMPAD TINYINT NULL

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='TENDERDECLUSESNUMPAD')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD TENDERDECLUSESNUMPAD TINYINT NULL

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='POLLINGINTERVAL')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD POLLINGINTERVAL INT NULL

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='ALWAYSASKFORPASSWORD')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD ALWAYSASKFORPASSWORD TINYINT NULL

GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='MAXIMUMPRICE')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD MAXIMUMPRICE decimal(28,12) NULL

GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILELog') AND NAME='MAXIMUMQTY')
ALTER TABLE dbo.POSFUNCTIONALITYPROFILELog ADD MAXIMUMQTY decimal(28,12) NULL

GO




