
/*

	Incident No.	: 12506
	Responsible		: Hörður Kristjánsson
	Sprint			: Thor
	Date created	: 26.10.2011
	
	Description		: Rename field and add a new one to suspended transactions log

	Logic scripts   : No stored procedures added or changed
	
	Tables affected : POSISSUSPENDEDTRANSACTIONSLog - rename NETAMOUNT to BALANCE
													- add BALANCEWITHTAX
						
*/


USE LSPOSNET_Audit

GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISSUSPENDEDTRANSACTIONSLog' AND COLUMN_NAME = 'NETAMOUNT')
BEGIN
   EXEC sp_rename 'DBO.POSISSUSPENDEDTRANSACTIONSLog.NETAMOUNT', 'BALANCE', 'COLUMN'
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISSUSPENDEDTRANSACTIONSLog' AND COLUMN_NAME = 'BALANCEWITHTAX')
BEGIN
	ALTER TABLE dbo.POSISSUSPENDEDTRANSACTIONSLog ADD BALANCEWITHTAX NUMERIC(28,12) NULL
END
GO
