/*

	Incident No.	: 19420
	Responsible		: Höður Sigurdór Heiðarsson
	Sprint			: LS Retail .NET 2013\Earth
	Date created	: 25.10.2012

	Description		: Added keyboard code and layout name columns for POS keyboard to POS user
	
	
	Tables affected	: RBOSTAFFTABLE
						
*/
USE LSPOSNET_Audit

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTAFFTABLELog') AND NAME='KEYBOARDCODE')
BEGIN
	ALTER TABLE dbo.RBOSTAFFTABLELog ADD KEYBOARDCODE nvarchar(20)
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTAFFTABLELog') AND NAME='LAYOUTNAME')
BEGIN
	ALTER TABLE dbo.RBOSTAFFTABLELog ADD LAYOUTNAME nvarchar(50)
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETABLELog') AND NAME='KEYBOARDCODE')
BEGIN
	ALTER TABLE dbo.RBOSTORETABLELog ADD KEYBOARDCODE nvarchar(20)
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETABLELog') AND NAME='LAYOUTNAME')
BEGIN
	ALTER TABLE dbo.RBOSTORETABLELog ADD LAYOUTNAME nvarchar(50)
END
GO