/*

	Incident No.	: XXX
	Responsible		: Oskar Bjarnason
	Sprint			: LS Retail .NET 2013\Earth
	Date created	: 17.09.2012

	Description		: Removing column ORDERTIMEDISPLAY and adding TimeFormat column to table KMINTERFACEPROFILELog
	
	
	Tables affected	: KMINTERFACEPROFILELog
						
*/

  
IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILELog') AND NAME='ORDERTIMEDISPLAY')
BEGIN
	ALTER TABLE KMINTERFACEPROFILELog Drop column [ORDERTIMEDISPLAY]
END	
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILELog') AND NAME='TIMEFORMAT')
BEGIN
	ALTER TABLE KMINTERFACEPROFILELog ADD [TIMEFORMAT] nvarchar(10) NULL
END	
GO