USE LSPOSNET_Audit
GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'INVENTORYTRANSFERORDERLog' AND COLUMN_NAME = 'CREATEDBY')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLog ADD CREATEDBY NVARCHAR(20) NOT NULL DEFAULT ''
END

GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'INVENTORYTRANSFERREQUESTLog' AND COLUMN_NAME = 'CREATEDBY')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUESTLog ADD CREATEDBY NVARCHAR(20) NOT NULL DEFAULT ''
END

GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'INVENTORYTRANSFERREQUESTLog' AND COLUMN_NAME = 'INVENTORYTRANSFERORDERID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUESTLog ADD INVENTORYTRANSFERORDERID NVARCHAR(20)
END
