
/*

	Incident No.	: 
	Responsible		: Óskar Bjarnason
	Sprint			: 
	Date created	: 28.13.2013
		
	Description		: Adding audtit tables 

	Logic scripts   : No stored procedures added or changed
	
	Tables affected : KITCHENDISPLAYTERMINALCONNECTIONLog
						
*/

USE LSPOSNET_Audit
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[KITCHENDISPLAYTERMINALCONNECTIONLog]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[KITCHENDISPLAYTERMINALCONNECTIONLog](
    AuditID int NOT NULL IDENTITY (1, 1),
    AuditUserGUID uniqueidentifier NOT NULL,
    AuditUserLogin nvarchar(32) NOT NULL,
    AuditDate datetime NOT NULL,
    [ID] [uniqueidentifier] NOT NULL,
    [STATIONID] [nvarchar] (20) NOT NULL,
    [TYPE] [int] NOT NULL,
    [CONNECTIONVALUE] [nvarchar] (20) NOT NULL,
    [DATAAREAID] [nvarchar] (4) NOT NULL,
    Deleted bit NULL)

    alter table dbo.KITCHENDISPLAYTERMINALCONNECTIONLog add constraint PK_KITCHENDISPLAYTERMINALCONNECTIONLog
    primary key clustered (AuditID) on [PRIMARY]

    create nonclustered index IX_KITCHENDISPLAYTERMINALCONNECTIONLog_AuditUserGUID ON dbo.KITCHENDISPLAYTERMINALCONNECTIONLog (AuditUserGUID) ON [PRIMARY]
END
GO


IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[KITCHENDISPLAYHOSPITALITYTYPECONNECTIONLog]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[KITCHENDISPLAYHOSPITALITYTYPECONNECTIONLog](
    AuditID int NOT NULL IDENTITY (1, 1),
    AuditUserGUID uniqueidentifier NOT NULL,
    AuditUserLogin nvarchar(32) NOT NULL,
    AuditDate datetime NOT NULL,
    [ID] [uniqueidentifier] NOT NULL,
    [STATIONID] [nvarchar] (20) NOT NULL,
    [TYPE] [int] NOT NULL,
    [CONNECTIONVALUE] [nvarchar] (20) NOT NULL,
    [DATAAREAID] [nvarchar] (4) NOT NULL,
    Deleted bit NULL)

    alter table dbo.KITCHENDISPLAYHOSPITALITYTYPECONNECTIONLog add constraint PK_KITCHENDISPLAYHOSPITALITYTYPECONNECTIONLog
    primary key clustered (AuditID) on [PRIMARY]

    create nonclustered index IX_KITCHENDISPLAYHOSPITALITYTYPECONNECTIONLog_AuditUserGUID ON dbo.KITCHENDISPLAYHOSPITALITYTYPECONNECTIONLog (AuditUserGUID) ON [PRIMARY]
END
GO

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[KITCHENDISPLAYFUNCTIONALPROFILELog]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[KITCHENDISPLAYFUNCTIONALPROFILELog](
    AuditID int NOT NULL IDENTITY (1, 1),
    AuditUserGUID uniqueidentifier NOT NULL,
    AuditUserLogin nvarchar(32) NOT NULL,
    AuditDate datetime NOT NULL,
    [ID] [uniqueidentifier] NOT NULL,
    [NAME] [nvarchar] (100) NOT NULL,
    [BUMPOPERATION] [int] NOT NULL,
    [ONVOID] [int] NOT NULL,
    [SHOWBUMPED] [int] NOT NULL,
    [BUTTONSMENUID] [nvarchar] (20) NOT NULL,
    [DATAAREAID] [nvarchar] (4) NOT NULL,
    Deleted bit NULL)

    alter table dbo.KITCHENDISPLAYFUNCTIONALPROFILELog add constraint PK_KITCHENDISPLAYFUNCTIONALPROFILELog
    primary key clustered (AuditID) on [PRIMARY]

    create nonclustered index IX_KITCHENDISPLAYFUNCTIONALPROFILELog_AuditUserGUID ON dbo.KITCHENDISPLAYFUNCTIONALPROFILELog (AuditUserGUID) ON [PRIMARY]
END
GO

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[KITCHENDISPLAYSTYLEPROFILELog]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[KITCHENDISPLAYSTYLEPROFILELog](
    AuditID int NOT NULL IDENTITY (1, 1),
    AuditUserGUID uniqueidentifier NOT NULL,
    AuditUserLogin nvarchar(32) NOT NULL,
    AuditDate datetime NOT NULL,
    [ID] [uniqueidentifier] NOT NULL,
    [NAME] [nvarchar] (100) NOT NULL,
    [ORDERSTYLEID] [nvarchar] (20) NULL,
    [ORDERPANESTYLEID] [nvarchar] (20) NULL,
    [BUTTONPANESTYLEID] [nvarchar] (20) NULL,
    [ITEMDEFAULTSTYLEID] [nvarchar] (20) NULL,
    [BUMPEDSTYLEID] [nvarchar] (20) NULL,
    [STARTEDSTYLEID] [nvarchar] (20) NULL,
    [MODIFIEDITEMSTYLEID] [nvarchar] (20) NULL,
    [NORMALITEMMODIFIERSTYLEID] [nvarchar] (20) NULL,
    [INCREASEITEMMODIFIERSTYLEID] [nvarchar] (20) NULL,
    [DECREASEITEMMODIFIERSTYLEID] [nvarchar] (20) NULL,
    [DATAAREAID] [nvarchar] (4) NOT NULL,
    Deleted bit NULL)

    alter table dbo.KITCHENDISPLAYSTYLEPROFILELog add constraint PK_KITCHENDISPLAYSTYLEPROFILELog
    primary key clustered (AuditID) on [PRIMARY]

    create nonclustered index IX_KITCHENDISPLAYSTYLEPROFILELog_AuditUserGUID ON dbo.KITCHENDISPLAYSTYLEPROFILELog (AuditUserGUID) ON [PRIMARY]
END
GO

IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADERLog'  AND COLUMN_NAME = 'BACKCOLOR2')
Begin

 
     
     ALTER TABLE dbo.POSMENUHEADERLog add BACKCOLOR2 int NULL
     
end 


IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADERLog' AND COLUMN_NAME = 'GRADIENTMODE')
Begin

ALTER TABLE dbo.POSMENUHEADERLog add GRADIENTMODE int NULL
    
end


IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADERLog' AND COLUMN_NAME = 'SHAPE')
Begin

 ALTER TABLE dbo.POSMENUHEADERLog add SHAPE int NULL
     
end

IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADERLog' AND COLUMN_NAME = 'MENUTYPE')
Begin

ALTER TABLE dbo.POSMENUHEADERLog add MENUTYPE int NULL
     
    
end


IF not EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADERLog'  AND COLUMN_NAME = 'STYLEID')
Begin

ALTER TABLE dbo.POSMENUHEADERLog add STYLEID nvarchar (20) NULL
    
end