/*
	Description		: Changing length of PRINTERDESCRIPTION in POSHARDWAREPROFILE 
*/

USE LSPOSNET_Audit
GO
if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSHARDWAREPROFILELog' AND COLUMN_NAME = 'PRINTERDESCRIPTION') = 30)
begin
	ALTER TABLE POSHARDWAREPROFILELog ALTER COLUMN PRINTERDESCRIPTION [nvarchar](200) NULL
end