/*
	Description		: Changing length of PRINTERDEVICENAME in POSHARDWAREPROFILE 
*/

USE LSPOSNET_Audit
GO
if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSHARDWAREPROFILELog' AND COLUMN_NAME = 'PRINTERDEVICENAME') = 30)
begin
	ALTER TABLE POSHARDWAREPROFILELog ALTER COLUMN PRINTERDEVICENAME [nvarchar](200) NULL
end