
/*

	Incident No.	: 
	Responsible		: Sigfús Jóhannesson
	Sprint			: 
	Date created	: 30.1.2013
		
	Description		: Changing incorrect filed types.

						
*/

USE LSPOSNET_Audit
GO

if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISSUSPENDEDTRANSACTIONSLog' and COLUMN_NAME = N'TRANSACTIONID' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISSUSPENDEDTRANSACTIONSLog alter column TRANSACTIONID NVARCHAR(40)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'RBOSTATEMENTTABLELog' and COLUMN_NAME = N'STOREID' and DATA_TYPE = N'VARCHAR')
begin
	alter table RBOSTATEMENTTABLELog alter column STOREID NVARCHAR(60)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'RBOSTATEMENTTABLELog' and COLUMN_NAME = N'DATAAREAID' and DATA_TYPE = N'VARCHAR')
begin
	alter table RBOSTATEMENTTABLELog alter column DATAAREAID NVARCHAR(4)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'RBOSTATEMENTLINELog' and COLUMN_NAME = N'DATAAREAID' and DATA_TYPE = N'VARCHAR')
begin
	alter table RBOSTATEMENTLINELog alter column DATAAREAID NVARCHAR(4)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISUPDATESMASTERLog' and COLUMN_NAME = N'DATAAREAID' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISUPDATESMASTERLog alter column DATAAREAID NVARCHAR(4)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISUPDATESMASTERLog' and COLUMN_NAME = N'TEXT' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISUPDATESMASTERLog alter column TEXT NVARCHAR(250)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISUPDATESMASTERLog' and COLUMN_NAME = N'FOLDERPATH' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISUPDATESMASTERLog alter column FOLDERPATH NVARCHAR(20)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISUPDATESMASTERLog' and COLUMN_NAME = N'POSAPPLICATIONPATH' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISUPDATESMASTERLog alter column POSAPPLICATIONPATH NVARCHAR(100)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISUPDATESMASTERLog' and COLUMN_NAME = N'USERNAME' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISUPDATESMASTERLog alter column USERNAME NVARCHAR(50)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISUPDATESMASTERLog' and COLUMN_NAME = N'NAME' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISUPDATESMASTERLog alter column NAME NVARCHAR(50)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISUPDATESMASTERLog' and COLUMN_NAME = N'FILEVERSION' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISUPDATESMASTERLog alter column FILEVERSION NVARCHAR(30)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISUPDATESMASTERLog' and COLUMN_NAME = N'COMPANY' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISUPDATESMASTERLog alter column COMPANY NVARCHAR(40)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSISUPDATESMASTERLog' and COLUMN_NAME = N'DESCRIPTION' and DATA_TYPE = N'VARCHAR')
begin
	alter table POSISUPDATESMASTERLog alter column DESCRIPTION NVARCHAR(255)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'RBOCOLORGROUPTRANSLog' and COLUMN_NAME = N'DATAAREAID' and DATA_TYPE = N'VARCHAR')
begin
	alter table RBOCOLORGROUPTRANSLog alter column DATAAREAID NVARCHAR(4)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'RBOSTYLEGROUPTRANSLog' and COLUMN_NAME = N'DATAAREAID' and DATA_TYPE = N'VARCHAR')
begin
	alter table RBOSTYLEGROUPTRANSLog alter column DATAAREAID NVARCHAR(4)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'RBOSIZEGROUPTRANSLog' and COLUMN_NAME = N'DATAAREAID' and DATA_TYPE = N'VARCHAR')
begin
	alter table RBOSIZEGROUPTRANSLog alter column DATAAREAID NVARCHAR(4)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'SIGNEDACTIONS' and COLUMN_NAME = N'Reason' and DATA_TYPE = N'NTEXT')
begin
	alter table SIGNEDACTIONS alter column Reason NVARCHAR(MAX)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'INVENTTABLELog' and COLUMN_NAME = N'NOTES' and DATA_TYPE = N'NTEXT')
begin
	alter table INVENTTABLELog alter column NOTES NVARCHAR(MAX)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'RBOCOLORGROUPTRANSLog' and COLUMN_NAME = N'DESCRIPTION' and DATA_TYPE = N'NTEXT')
begin
	alter table RBOCOLORGROUPTRANSLog alter column DESCRIPTION NVARCHAR(MAX)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'RBOSTYLEGROUPTRANSLog' and COLUMN_NAME = N'DESCRIPTION' and DATA_TYPE = N'NTEXT')
begin
	alter table RBOSTYLEGROUPTRANSLog alter column DESCRIPTION NVARCHAR(MAX)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'RBOSIZEGROUPTRANSLog' and COLUMN_NAME = N'DESCRIPTION' and DATA_TYPE = N'NTEXT')
begin
	alter table RBOSIZEGROUPTRANSLog alter column DESCRIPTION NVARCHAR(MAX)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSHARDWAREPROFILELog' and COLUMN_NAME = N'LOGOBITMAP' and DATA_TYPE = N'IMAGE')
begin
	alter table POSHARDWAREPROFILELog alter column LOGOBITMAP VARBINARY(MAX)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'HOSPITALITYTYPELog' and COLUMN_NAME = N'GRAPHICALLAYOUT' and DATA_TYPE = N'IMAGE')
begin
	alter table HOSPITALITYTYPELog alter column GRAPHICALLAYOUT VARBINARY(MAX)
end
 
if exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = N'POSMENULINELog' and COLUMN_NAME = N'PICTURE' and DATA_TYPE = N'IMAGE')
begin
	alter table POSMENULINELog alter column PICTURE VARBINARY(MAX)
end
