USE LSPOSNET_Audit
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYSTYLEPROFILELog') AND NAME='ORDERPROPERTIESMODIFIEDSTYLEID')
BEGIN
	 ALTER TABLE KITCHENDISPLAYSTYLEPROFILELog Add ORDERPROPERTIESMODIFIEDSTYLEID varchar(20) NOT NULL default '' 
END	
GO


