/*
	Incident No.	: 
	Responsible		: Erna Gudrun Sigurdardottir
	Sprint			: LS One 2013.1\KDS
	Date created	: 08.08.13

	Description		: Removed settings from Visual and Functional Profile
*/

USE LSPOSNET_Audit
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILELog' AND COLUMN_NAME = 'SHOWBUMPED')
BEGIN
	ALTER TABLE KITCHENDISPLAYFUNCTIONALPROFILELog DROP COLUMN SHOWBUMPED
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILELog' AND COLUMN_NAME = 'BUMPOPERATION')
BEGIN
	ALTER TABLE KITCHENDISPLAYFUNCTIONALPROFILELog DROP COLUMN BUMPOPERATION
END
GO