USE LSPOSNET_Audit
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='KITCHENDISPLAYTRANSACTIONPROFILELog' AND COLUMN_NAME='KITCHENMANAGERPORT' AND DATA_TYPE = 'nvarchar')
Begin
	Alter table KITCHENDISPLAYTRANSACTIONPROFILELog Alter column KITCHENMANAGERPORT int
End
