USE LSPOSNET_Audit
GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILELog') AND NAME='RUSHBORDERCOLOR')
BEGIN
	 ALTER TABLE KITCHENDISPLAYVISUALPROFILELog Add RUSHBORDERCOLOR int NULL 
END	
GO
