/*
	Incident No.	: 
	Responsible		: Höður Sigurdór Heiðarsson
	Sprint			: 
	Date created	: 29.10.2013

	Description		: Change column sizes

	Rerun of script 00078-00 because it has build action set as content and not embedded resource
*/

USE LSPOSNET_Audit
GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'VENDTABLELog' AND COLUMN_NAME = 'STATE') = 10)
begin
	ALTER TABLE VENDTABLELog ALTER COLUMN STATE [nvarchar](30) NULL
end

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSIZESLog' AND COLUMN_NAME = 'NAME')
BEGIN
	ALTER TABLE RBOSIZESLog ALTER COLUMN NAME NVARCHAR(30)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOCOLORSLog' AND COLUMN_NAME = 'NAME')
BEGIN
	ALTER TABLE RBOCOLORSLog ALTER COLUMN NAME NVARCHAR(30)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOCOLORGROUPTRANSLog' AND COLUMN_NAME = 'NAME')
BEGIN
	ALTER TABLE RBOCOLORGROUPTRANSLog ALTER COLUMN NAME NVARCHAR(30)
END
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSIZEGROUPTRANSLog' AND COLUMN_NAME = 'NAME')
BEGIN
	ALTER TABLE RBOSIZEGROUPTRANSLog ALTER COLUMN NAME NVARCHAR(30)
END
GO

