
/*

	Incident No.	: 
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 20.02.2014						
*/

USE LSPOSNET_Audit
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'ITEMONTIMESTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD ITEMONTIMESTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'ITEMVOIDEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD ITEMVOIDEDSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'DEFAULTFOOTERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD DEFAULTFOOTERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'DEFAULTHEADERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD DEFAULTHEADERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'COMMENTMODIFIERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD COMMENTMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'ITEMMODIFIERMODIFIEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD  ITEMMODIFIERMODIFIEDSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'ITEMMODIFIERVOIDEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD  ITEMMODIFIERVOIDEDSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'ITEMMODIFIERGLYPHSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD  ITEMMODIFIERGLYPHSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'DEALHEADERSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD  DEALHEADERSTYLEID UNIQUEIDENTIFIER
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'DEALHEADERVOIDEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD DEALHEADERVOIDEDSTYLEID UNIQUEIDENTIFIER
END

-- Changing datatypes of old columns
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'ORDERPANESTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column ORDERPANESTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD ORDERPANESTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'ORDERSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column ORDERSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD ORDERSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'ITEMDEFAULTSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column ITEMDEFAULTSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD ITEMDEFAULTSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'BUMPEDSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column BUMPEDSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD ITEMDONESTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'MODIFIEDITEMSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column MODIFIEDITEMSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD ITEMMODIFIEDSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'NORMALITEMMODIFIERSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column NORMALITEMMODIFIERSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD NORMALITEMMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'INCREASEITEMMODIFIERSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column INCREASEITEMMODIFIERSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD INCREASEITEMMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'DECREASEITEMMODIFIERSTYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column DECREASEITEMMODIFIERSTYLEID
	alter table KITCHENDISPLAYSTYLEPROFILELog ADD DECREASEITEMMODIFIERSTYLEID UNIQUEIDENTIFIER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND COLUMN_NAME = 'STYLEID' AND DATA_TYPE='nvarchar')
BEGIN
	alter table KITCHENDISPLAYTIMESTYLE DROP Column STYLEID
	alter table KITCHENDISPLAYTIMESTYLE ADD STYLEID UNIQUEIDENTIFIER
END

-- Deleting unused columns
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'STARTEDSTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column STARTEDSTYLEID
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'ORDERPROPERTIESMODIFIEDSTYLEID')
BEGIN

-- This column has a default constraint that we need to drop first
	DECLARE @ConstraintName nvarchar(200)
	SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
	WHERE PARENT_OBJECT_ID = OBJECT_ID('KITCHENDISPLAYSTYLEPROFILELog')
	AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
							WHERE NAME = N'ORDERPROPERTIESMODIFIEDSTYLEID'
							AND object_id = OBJECT_ID(N'KITCHENDISPLAYSTYLEPROFILELog'))
	IF @ConstraintName IS NOT NULL
	EXEC('ALTER TABLE KITCHENDISPLAYSTYLEPROFILELog DROP CONSTRAINT ' + @ConstraintName)
	
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column ORDERPROPERTIESMODIFIEDSTYLEID
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTYLEPROFILELog' AND COLUMN_NAME = 'BUTTONPANESTYLEID')
BEGIN
	alter table KITCHENDISPLAYSTYLEPROFILELog DROP Column BUTTONPANESTYLEID
END






