/*
Remove unused KDS fields						
*/
USE LSPOSNET_Audit

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'FLOWPATH')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column FLOWPATH
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'TOPLEFT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column TOPLEFT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'TOPCENTER')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column TOPCENTER
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'TOPRIGHT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column TOPRIGHT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'BOTTOMLEFT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column BOTTOMLEFT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'BOTTOMCENTER')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column BOTTOMCENTER
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'BOTTOMRIGHT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column BOTTOMRIGHT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'TIMEFORMAT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column TIMEFORMAT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'BORDERCOLOR')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column BORDERCOLOR
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILELog' AND COLUMN_NAME = 'RUSHBORDERCOLOR')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILELog Drop Column RUSHBORDERCOLOR
End

