
/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2014 - Nimbo
	Date created	: 20.12.2013						
*/

USE LSPOSNET_Audit
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTGROUPLog' AND COLUMN_NAME = 'DISCOUNTLIMIT')
BEGIN
  Alter Table CUSTGROUPLog drop column DISCOUNTLIMIT
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTGROUPLog' AND COLUMN_NAME = 'PURCHASEAMOUNT')
BEGIN
	Alter Table CUSTGROUPLog ADD [PURCHASEAMOUNT] [numeric] (28,12) NULL;
	Alter Table CUSTGROUPLog ADD [USEPURCHASELIMIT] [tinyint] NULL;
	Alter Table CUSTGROUPLog ADD [PURCHASEPERIOD] [tinyint] NULL;
END
GO

