
USE LSPOSNET_Audit
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALGROUPCONNECTIONLog' AND COLUMN_NAME = 'STOREID')
BEGIN
	ALTER TABLE RBOTERMINALGROUPCONNECTIONLog ADD STOREID nvarchar(20)
END
GO