
USE LSPOSNET_Audit
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOINVENTTABLELog' AND COLUMN_NAME = 'MUSTSELECTUOM')
BEGIN
	ALTER TABLE RBOINVENTTABLELog ADD MUSTSELECTUOM TINYINT
END
GO