
/*
	Description		: Remove unused stock counting and inventory adjustment columns	
*/

USE LSPOSNET_Audit
GO
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLELog' AND COLUMN_NAME = 'JOURNALNAMEID')
BEGIN
	ALTER TABLE INVENTJOURNALTABLELog DROP COLUMN JOURNALNAMEID
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLELog' AND COLUMN_NAME = 'NUMOFLINES')
BEGIN
	ALTER TABLE INVENTJOURNALTABLELog DROP COLUMN NUMOFLINES
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANSLog' AND COLUMN_NAME = 'ORIGIN')
BEGIN
	ALTER TABLE INVENTJOURNALTRANSLog DROP COLUMN ORIGIN
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANSLog' AND COLUMN_NAME = 'VOUCHER')
BEGIN
	ALTER TABLE INVENTJOURNALTRANSLog DROP COLUMN VOUCHER
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANSLog' AND COLUMN_NAME = 'JOURNALTYPE')
BEGIN
	ALTER TABLE INVENTJOURNALTRANSLog DROP COLUMN JOURNALTYPE
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANSLog' AND COLUMN_NAME = 'DIMENSION')
BEGIN
	ALTER TABLE INVENTJOURNALTRANSLog DROP COLUMN DIMENSION
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANSLog' AND COLUMN_NAME = 'DIMENSION2_')
BEGIN
	ALTER TABLE INVENTJOURNALTRANSLog DROP COLUMN DIMENSION2_
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANSLog' AND COLUMN_NAME = 'DIMENSION3_')
BEGIN
	ALTER TABLE INVENTJOURNALTRANSLog DROP COLUMN DIMENSION3_
END

GO


