
/*
	Description		: Remove unused stock counting and inventory adjustment columns	
*/

USE LSPOSNET_Audit
GO
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLELog' AND COLUMN_NAME = 'EMPLID')
BEGIN
	ALTER TABLE INVENTJOURNALTABLELog DROP COLUMN EMPLID
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLELog' AND COLUMN_NAME = 'POSTEDUSERID')
BEGIN
	ALTER TABLE INVENTJOURNALTABLELog DROP COLUMN POSTEDUSERID
END

GO


