USE LSPOSNET_Audit
GO
  
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSTRANSACTIONSERVICEPROFILELog' AND COLUMN_NAME = 'CENTRALTABLESERVER' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
alter TABLE POSTRANSACTIONSERVICEPROFILELog alter column CENTRALTABLESERVER nvarchar(50) NOT NULL 
	
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CUSTTABLELOG' AND COLUMN_NAME = 'ORGID' AND CHARACTER_MAXIMUM_LENGTH < 20  )
BEGIN
	ALTER TABLE CUSTTABLELog  
	ALTER COLUMN ORGID NVARCHAR(20)
END	
GO