
/*
	Description		: Remove unused stock counting and inventory adjustment columns	
*/

USE LSPOSNET_Audit
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSHARDWAREPROFILELog' AND COLUMN_NAME = 'FISCALPRINTERDEVICENAME')
BEGIN
	BEGIN TRANSACTION
	EXECUTE sp_rename N'dbo.POSHARDWAREPROFILELog.FISCALPRINTERDEVICENAME', N'Tmp_FISCALPRINTERCONNECTION_2', 'COLUMN' 
	EXECUTE sp_rename N'dbo.POSHARDWAREPROFILELog.Tmp_FISCALPRINTERCONNECTION_2', N'FISCALPRINTERCONNECTION', 'COLUMN' 
	ALTER TABLE dbo.POSHARDWAREPROFILELog SET (LOCK_ESCALATION = TABLE)
	COMMIT
END


GO


