USE LSPOSNET_Audit
GO

  
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLELog' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.VENDTABLELog  
	ALTER COLUMN PHONE NVARCHAR(80)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLELog' AND COLUMN_NAME = 'NAME' AND CHARACTER_MAXIMUM_LENGTH < 200  )
BEGIN
	ALTER TABLE dbo.VENDTABLELog  
	ALTER COLUMN NAME NVARCHAR(200)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLELog' AND COLUMN_NAME = 'ZIPCODE' AND CHARACTER_MAXIMUM_LENGTH < 20  )
BEGIN
	ALTER TABLE dbo.VENDTABLELog  
	ALTER COLUMN ZIPCODE NVARCHAR(20)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLELog' AND COLUMN_NAME = 'CITY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.VENDTABLELog  
	ALTER COLUMN CITY NVARCHAR(250)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLELog' AND COLUMN_NAME = 'COUNTY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.VENDTABLELog  
	ALTER COLUMN COUNTY NVARCHAR(250)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLELog' AND COLUMN_NAME = 'STATE' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.VENDTABLELog  
	ALTER COLUMN [STATE] NVARCHAR(250)
END	
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLELog' AND COLUMN_NAME = 'COUNTRY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.VENDTABLELog  
	ALTER COLUMN COUNTRY NVARCHAR(250)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'FIRSTNAME' AND CHARACTER_MAXIMUM_LENGTH < 60  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN FIRSTNAME NVARCHAR(60)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'MIDDLENAME' AND CHARACTER_MAXIMUM_LENGTH < 60  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN MIDDLENAME NVARCHAR(60)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'LASTNAME' AND CHARACTER_MAXIMUM_LENGTH < 60  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN LASTNAME NVARCHAR(60)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN PHONE NVARCHAR(80)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'PHONE2' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN PHONE2 NVARCHAR(80)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'FAX' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN FAX NVARCHAR(80)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'ZIPCODE' AND CHARACTER_MAXIMUM_LENGTH < 20  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN ZIPCODE NVARCHAR(20)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'CITY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN CITY NVARCHAR(250)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'COUNTY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN COUNTY NVARCHAR(250)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'STATE' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN [STATE] NVARCHAR(250)
END	
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLELog' AND COLUMN_NAME = 'COUNTRY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog  
	ALTER COLUMN COUNTRY NVARCHAR(250)
END	
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONTACTTABLELog' AND COLUMN_NAME = 'NAME')
BEGIN
	ALTER TABLE dbo.CONTACTTABLELog ADD NAME NVARCHAR(200)
END
GO