/*

	Incident No.	: ONE-3489
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Santiago

	Description		: Setting the text fields in CustTable to allow longer strings than before
	
						
*/


USE LSPOSNET_Audit
GO

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTTABLELog' AND COLUMN_NAME = 'NAME' AND CHARACTER_MAXIMUM_LENGTH = 60)
BEGIN
	CREATE TABLE dbo.Tmp_CUSTTABLELog
		(
		AuditID int NOT NULL IDENTITY (1, 1),
		AuditUserGUID uniqueidentifier NOT NULL,
		AuditUserLogin nvarchar(32) NOT NULL,
		AuditDate datetime NOT NULL,
		ACCOUNTNUM nvarchar(20) NOT NULL,
		NAME nvarchar(200) NULL,
		INVOICEACCOUNT nvarchar(20) NULL,
		CURRENCY nvarchar(3) NULL,
		BLOCKED int NULL,
		CREDITMAX numeric(28, 12) NULL,
		LANGUAGEID nvarchar(5) NULL,
		DATAAREAID nvarchar(4) NOT NULL,
		TAXGROUP nvarchar(20) NULL,
		LINEDISC nvarchar(20) NULL,
		PRICEGROUP nvarchar(20) NULL,
		MULTILINEDISC nvarchar(20) NULL,
		ENDDISC nvarchar(20) NULL,
		ORGID nvarchar(20) NULL,
		NONCHARGABLEACCOUNT int NULL,
		Deleted bit NOT NULL,
		FIRSTNAME nvarchar(60) NULL,
		MIDDLENAME nvarchar(60) NULL,
		LASTNAME nvarchar(60) NULL,
		NAMEPREFIX nvarchar(8) NULL,
		NAMESUFFIX nvarchar(8) NULL
		)  ON [PRIMARY]


	ALTER TABLE dbo.Tmp_CUSTTABLELog SET (LOCK_ESCALATION = TABLE)

	SET IDENTITY_INSERT dbo.Tmp_CUSTTABLELog ON

	IF EXISTS(SELECT * FROM dbo.CUSTTABLELog)
		 EXEC('INSERT INTO dbo.Tmp_CUSTTABLELog (AuditID, AuditUserGUID, AuditUserLogin, AuditDate, ACCOUNTNUM, NAME, INVOICEACCOUNT, CURRENCY, BLOCKED, CREDITMAX, LANGUAGEID, DATAAREAID, TAXGROUP, LINEDISC, PRICEGROUP, MULTILINEDISC, ENDDISC, ORGID, NONCHARGABLEACCOUNT, Deleted, FIRSTNAME, MIDDLENAME, LASTNAME, NAMEPREFIX, NAMESUFFIX)
			SELECT AuditID, AuditUserGUID, AuditUserLogin, AuditDate, ACCOUNTNUM, NAME, INVOICEACCOUNT, CURRENCY, BLOCKED, CREDITMAX, LANGUAGEID, DATAAREAID, TAXGROUP, LINEDISC, PRICEGROUP, MULTILINEDISC, ENDDISC, ORGID, NONCHARGABLEACCOUNT, Deleted, FIRSTNAME, MIDDLENAME, LASTNAME, NAMEPREFIX, NAMESUFFIX FROM dbo.CUSTTABLELog WITH (HOLDLOCK TABLOCKX)')

	SET IDENTITY_INSERT dbo.Tmp_CUSTTABLELog OFF

	DROP TABLE dbo.CUSTTABLELog

	EXECUTE sp_rename N'dbo.Tmp_CUSTTABLELog', N'CUSTTABLELog', 'OBJECT' 

	ALTER TABLE dbo.CUSTTABLELog ADD CONSTRAINT
		PK_CUSTTABLELog PRIMARY KEY CLUSTERED 
		(
		AuditID
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


	CREATE NONCLUSTERED INDEX IXCUSTTABLELog_AuditUserGUID ON dbo.CUSTTABLELog
		(
		AuditUserGUID
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	END
GO

