
/*

	Incident No.	: ONE-3037
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: Pepper

	Description		: Changes how and when customers can be deleted. CUSTTABEL and RBOCUSTTABLE combined into one and all fields not in the data providers removed
	
						
*/

USE LSPOSNET_Audit
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTTABLELog' AND COLUMN_NAME ='DELETED')
BEGIN
	ALTER TABLE dbo.CUSTTABLElog
	ADD DELETED BIT
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTTABLELog' AND COLUMN_NAME ='RECEIPTOPTION')
BEGIN
	ALTER TABLE dbo.CUSTTABLElog 
	ADD RECEIPTOPTION INT
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTTABLELog' AND COLUMN_NAME ='RECEIPTEMAIL')
BEGIN
	ALTER TABLE dbo.CUSTTABLElog 
	ADD RECEIPTEMAIL NVARCHAR(80)
END
GO
