/*

	Incident No.	: ONE-3489
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Jerusalem

	Description		: Setting the text fields in CustomerAddress to allow longer strings than before
	
						
*/


USE LSPOSNET_Audit
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERADDRESSLog' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH = 20)
BEGIN
	CREATE TABLE dbo.Tmp_CUSTOMERADDRESSLog
		(
		AuditID int NOT NULL IDENTITY (1, 1),
		AuditUserGUID uniqueidentifier NOT NULL,
		AuditUserLogin nvarchar(32) NOT NULL,
		AuditDate datetime NOT NULL,
		ACCOUNTNUM nvarchar(20) NOT NULL,
		ADDRESS nvarchar(250) NULL,
		COUNTRY nvarchar(250) NULL,
		ZIPCODE nvarchar(20) NULL,
		STATE nvarchar(250) NULL,
		COUNTY nvarchar(250) NULL,
		CITY nvarchar(250) NULL,
		STREET nvarchar(250) NULL,
		DATAAREAID nvarchar(4) NOT NULL,
		TAXGROUP nvarchar(20) NULL,
		ADDRESSTYPE int NOT NULL,
		ADDRESSFORMAT int NULL,
		PHONE nvarchar(80) NULL,
		CELLULARPHONE nvarchar(80) NULL,
		EMAIL nvarchar(80) NULL,
		Deleted bit NOT NULL
		)  ON [PRIMARY]

	ALTER TABLE dbo.Tmp_CUSTOMERADDRESSLog SET (LOCK_ESCALATION = TABLE)

	SET IDENTITY_INSERT dbo.Tmp_CUSTOMERADDRESSLog ON

	IF EXISTS(SELECT * FROM dbo.CUSTOMERADDRESSLog)
		 EXEC('INSERT INTO dbo.Tmp_CUSTOMERADDRESSLog (AuditID, AuditUserGUID, AuditUserLogin, AuditDate, ACCOUNTNUM, ADDRESS, COUNTRY, ZIPCODE, STATE, COUNTY, CITY, STREET, DATAAREAID, TAXGROUP, ADDRESSTYPE, ADDRESSFORMAT, PHONE, CELLULARPHONE, EMAIL, Deleted)
			SELECT AuditID, AuditUserGUID, AuditUserLogin, AuditDate, ACCOUNTNUM, ADDRESS, COUNTRY, ZIPCODE, STATE, COUNTY, CITY, STREET, DATAAREAID, TAXGROUP, ADDRESSTYPE, ADDRESSFORMAT, PHONE, CELLULARPHONE, EMAIL, Deleted FROM dbo.CUSTOMERADDRESSLog WITH (HOLDLOCK TABLOCKX)')



	SET IDENTITY_INSERT dbo.Tmp_CUSTOMERADDRESSLog OFF

	DROP TABLE dbo.CUSTOMERADDRESSLog

	EXECUTE sp_rename N'dbo.Tmp_CUSTOMERADDRESSLog', N'CUSTOMERADDRESSLog', 'OBJECT' 

	ALTER TABLE dbo.CUSTOMERADDRESSLog ADD CONSTRAINT
		PK_CUSTOMERADDRESSLog PRIMARY KEY CLUSTERED 
		(
		AuditID
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	

	CREATE NONCLUSTERED INDEX IXCUSTOMERADDRESSLog_AuditUserGUID ON dbo.CUSTOMERADDRESSLog
		(
		AuditUserGUID
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	
END
GO
