/*

	Incident No.	: ONE-6530
	Responsible		: Hörður Kristjánsson
	Sprint			: Billy
	Date created	: 10.04.2017

	Description		: Adding to POSHARDWAREPROFILELog
*/

USE LSPOSNET_Audit
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'STATIONPRINTINGHOSTID' AND TABLE_NAME = 'POSHARDWAREPROFILELog')
BEGIN
	ALTER TABLE POSHARDWAREPROFILELog ADD [STATIONPRINTINGHOSTID] NVARCHAR(20) NULL
END
GO
