/*
	Incident No.	: ONE-6894
	Responsible		: Adrian Chiorean
	Sprint			: Färgrik
	Date created	: 22.05.2017

	Description		: Cleanup unused columns from RETAILITEMLog
*/

USE LSPOSNET_Audit

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'PURCHASEPRICEINCLTAX')
BEGIN
	ALTER TABLE RETAILITEMLog DROP COLUMN PURCHASEPRICEINCLTAX
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'PURCHASEPRICEUNIT')
BEGIN
	ALTER TABLE RETAILITEMLog DROP COLUMN PURCHASEPRICEUNIT
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'PURCHASEMARKUP')
BEGIN
	ALTER TABLE RETAILITEMLog DROP COLUMN PURCHASEMARKUP
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'SALESPRICEUNIT')
BEGIN
	ALTER TABLE RETAILITEMLog DROP COLUMN SALESPRICEUNIT
END
GO