/*

	Incident No.	: ONE-5643
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Oregano

	Description		: Parameter field made larger
	
						
*/

USE LSPOSNET_Audit
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'RETAILDEPARTMENTMASTERID')
	ALTER TABLE RETAILITEMLog
	DROP COLUMN RETAILDEPARTMENTMASTERID
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'RETAILDIVISIONMASTERID')
	ALTER TABLE RETAILITEMLog
	DROP COLUMN RETAILDIVISIONMASTERID
GO
