/*
	Incident No.	: ONE-6892
	Responsible		: Adrian Chiorean
	Sprint			: Pax
	Date created	: 25.05.2017

	Description		: Add RECEIPTPAYMENTLINESSIZE column to visual profile
*/

USE LSPOSNET_Audit

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RECEIPTPAYMENTLINESSIZE' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD RECEIPTPAYMENTLINESSIZE INT NULL
END
GO