/*
	Incident No.	: ONE-6548
	Responsible		: Adrian Chiorean
	Sprint			: Hemnes
	Date created	: 08.05.2017

	Description		: Increase name columns size for USERSLog, RBOSTAFFTABLELog
*/

USE LSPOSNET_Audit

--------------------------------------------------- USERSLog
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERSLog' AND COLUMN_NAME = 'FirstName')
BEGIN
	ALTER TABLE USERSLog ALTER COLUMN [FirstName] NVARCHAR(60) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERSLog' AND COLUMN_NAME = 'MiddleName')
BEGIN
	ALTER TABLE USERSLog ALTER COLUMN [MiddleName] NVARCHAR(60) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERSLog' AND COLUMN_NAME = 'LastName')
BEGIN
	ALTER TABLE USERSLog ALTER COLUMN [LastName] NVARCHAR(60) NULL
END

--------------------------------------------------- RBOSTAFFTABLELog
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTAFFTABLELog' AND COLUMN_NAME = 'FIRSTNAME')
BEGIN
	ALTER TABLE RBOSTAFFTABLELog ALTER COLUMN [FIRSTNAME] NVARCHAR(60) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTAFFTABLELog' AND COLUMN_NAME = 'LASTNAME')
BEGIN
	ALTER TABLE RBOSTAFFTABLELog ALTER COLUMN [LASTNAME] NVARCHAR(60) NULL
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTAFFTABLELog' AND COLUMN_NAME = 'NAME')
BEGIN
	ALTER TABLE RBOSTAFFTABLELog ALTER COLUMN [NAME] NVARCHAR(200) NULL
END
GO