/*

	Incident No.	: ONE-6494 Reason codes
	Responsible		: Adrian Chiorean
	Sprint			: Billy
	Date created	: 03.04.2017

	Description		: Add multiple columns to INVENTTRANSREASONLog
*/

USE LSPOSNET_Audit
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ACTION' AND TABLE_NAME = 'INVENTTRANSREASONLog')
BEGIN
	ALTER TABLE INVENTTRANSREASONLog ADD [ACTION] INT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'BEGINDATE' AND TABLE_NAME = 'INVENTTRANSREASONLog')
BEGIN
	ALTER TABLE INVENTTRANSREASONLog ADD [BEGINDATE] DATETIME NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ENDDATE' AND TABLE_NAME = 'INVENTTRANSREASONLog')
BEGIN
	ALTER TABLE INVENTTRANSREASONLog ADD [ENDDATE] DATETIME NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ISSYSTEMREASONCODE' AND TABLE_NAME = 'INVENTTRANSREASONLog')
BEGIN
	ALTER TABLE INVENTTRANSREASONLog ADD [ISSYSTEMREASONCODE] BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'SHOWONPOS' AND TABLE_NAME = 'INVENTTRANSREASONLog')
BEGIN
	ALTER TABLE INVENTTRANSREASONLog ADD [SHOWONPOS] BIT NULL
END
GO