/*
	Incident No.	: ONE-7183
	Responsible		: Adrian Chiorean
	Sprint			: Vardagen
	Date created	: 13.07.2017

	Description		: Add new columns to POSMENUHEADERLog
*/

USE LSPOSNET_Audit

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADERLog' AND COLUMN_NAME = 'DEVICETYPE')
BEGIN
	ALTER TABLE POSMENUHEADERLog ADD DEVICETYPE INT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADERLog' AND COLUMN_NAME = 'MAINMENU')
BEGIN
	ALTER TABLE POSMENUHEADERLog ADD MAINMENU BIT NULL
END
GO