/*
	Incident No.	: ONE-5556
	Responsible		: Quang Nguyen
	Sprint			: Vardagen
	Date created	: 11.07.2017

	Description		: Create a new column for infocodes to table POSFUNCTIONALITYPROFILE
*/

USE LSPOSNET_Audit
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'OPENDRAWER')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILELog ADD OPENDRAWER NVARCHAR(20) NULL
END
GO