/*
	Incident No.	: ONE-8702
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Kunivas
	Date created	: 28.06.2018

	Description		: Add a new configuration for periodic discount cache
*/

USE LSPOSNET_Audit

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALESPARAMETERSLog' AND COLUMN_NAME = 'CLEARPERIODICDISCOUNTCACHE')
BEGIN
	ALTER TABLE SALESPARAMETERSLog ADD CLEARPERIODICDISCOUNTCACHE int
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SALESPARAMETERSLog' AND COLUMN_NAME = 'CLEARPERIODICDISCOUNTCACHEMINUTES')
BEGIN
	ALTER TABLE SALESPARAMETERSLog ADD CLEARPERIODICDISCOUNTCACHEMINUTES int
END

GO