/*
	Incident No.	: ONE-8356
	Responsible		: Adrian Chiorean
	Sprint			: cheng
	Date			: 28.02.2018

	Description		: Adding a unique ID column to INVENTITEMBARCODELog table
*/

USE LSPOSNET_Audit

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTITEMBARCODELog' AND COLUMN_NAME = 'ITEMBARCODEID')
BEGIN
	ALTER TABLE INVENTITEMBARCODELog ADD ITEMBARCODEID NVARCHAR(80) NULL
END
GO