/*
	Incident No.	: ONE-9733
	Responsible		: Ovidiu Caba
	Sprint			: Betelgeuse
	Date created	: 28.02.2019

	Description		: Increase column RETAILITEMLog.ITEMNAME and RETAILITEMLog.VARIANTNAME to 120 characters
*/

USE LSPOSNET_Audit

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'ITEMNAME')
BEGIN
	IF(COL_LENGTH('RETAILITEMLog', 'ITEMNAME') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE RETAILITEMLog ALTER COLUMN ITEMNAME NVARCHAR(120) NOT NULL
	END
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'VARIANTNAME')
BEGIN
	IF(COL_LENGTH('RETAILITEMLog', 'VARIANTNAME') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE RETAILITEMLog ALTER COLUMN VARIANTNAME NVARCHAR(120) NOT NULL
	END
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTDIMCOMBINATIONLog' AND COLUMN_NAME = 'NAME')
BEGIN
	IF(COL_LENGTH('INVENTDIMCOMBINATIONLog', 'NAME') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE INVENTDIMCOMBINATIONLog ALTER COLUMN NAME NVARCHAR(120) NULL
	END
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTTABLELog' AND COLUMN_NAME = 'ITEMNAME')
BEGIN
	IF(COL_LENGTH('INVENTTABLELog', 'ITEMNAME') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE INVENTTABLELog ALTER COLUMN ITEMNAME NVARCHAR(120) NULL
	END
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'NAMEALIAS')
BEGIN
	IF(COL_LENGTH('RETAILITEMLog', 'NAMEALIAS') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE RETAILITEMLog ALTER COLUMN NAMEALIAS NVARCHAR(120) NOT NULL
	END
END
GO