/*
	Incident No.	: ONE-9187
	Responsible		: Ovidiu Caba
	Sprint			: Edosian
	Date created	: 18.10.2018

	Description		: Add Timeout and MaxMessageSize to site service profile
*/

USE LSPOSNET_Audit

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSTRANSACTIONSERVICEPROFILELog' AND COLUMN_NAME = 'TIMEOUT')
BEGIN
	ALTER TABLE POSTRANSACTIONSERVICEPROFILELog ADD
		[TIMEOUT] INT NOT NULL DEFAULT(60),
		[MAXMESSAGESIZE] INT NOT NULL DEFAULT(55000000)
END

GO