/*
	Incident No.	: ONE-10136 Inventory template changes, ONE-10358 Add OMNI general settings to functionality profile
	Responsible		: Adrian Chiorean
	Sprint			: Sun
	Date created	: 01.07.2019

	Description		: Add column ALLOWIMAGEIMPORT to INVENTORYTEMPLATELog. Add columns OMNIENTERINGTYPE, OMNIQUANTITYMETHOD, OMNIDEFAULTQUANTITY to POSFUNCTIONALITYPROFILELog
*/

USE LSPOSNET_Audit

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATELog' AND COLUMN_NAME = 'ALLOWIMAGEIMPORT')
BEGIN
	ALTER TABLE INVENTORYTEMPLATELog ADD ALLOWIMAGEIMPORT BIT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'OMNIENTERINGTYPE')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILELog ADD OMNIENTERINGTYPE INT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'OMNIQUANTITYMETHOD')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILELog ADD OMNIQUANTITYMETHOD INT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'OMNIDEFAULTQUANTITY')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILELog ADD OMNIDEFAULTQUANTITY DECIMAL NOT NULL DEFAULT 1
END
GO