/*
	Incident No.	: ONE-10266 Inventory template - OMNI General tab
	Responsible		: Adrian Chiorean
	Sprint			: Vega
	Date created	: 20.06.2019

	Description		: Added columns to INVENTORYTEMPLATE 
*/

USE LSPOSNET_Audit

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATELog' AND COLUMN_NAME = 'USEBARCODEUOM')
BEGIN
	ALTER TABLE INVENTORYTEMPLATELog ADD USEBARCODEUOM BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATELog' AND COLUMN_NAME = 'ALLOWADDNEWLINE')
BEGIN
	ALTER TABLE INVENTORYTEMPLATELog ADD ALLOWADDNEWLINE BIT NULL
END
GO