/*
	Incident No.	: ONE-8441
	Responsible		: Adrian Chiorean
	Sprint			: Kazon
	Date created	: 13.12.2018

	Description		: Add TAREWEIGHT column to table RETAILITEMLog, RETAILGROUPLog
*/

USE LSPOSNET_Audit

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'TAREWEIGHT')
BEGIN
	ALTER TABLE RETAILITEMLog ADD TAREWEIGHT NUMERIC(28, 12) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILGROUPLog' AND COLUMN_NAME = 'TAREWEIGHT')
BEGIN
	ALTER TABLE RETAILGROUPLog ADD TAREWEIGHT NUMERIC(28, 12) NULL
END
GO