/*
	Incident No.	: ONE-11374
	Responsible		: Adrian Chiorean
	Sprint			: Akita
	Date created	: 27.03.2020

	Description		: Rename columns SAFEDROPUSESNUMPAD, SAFEDROPREVUSESNUMPAD, BANKDROPUSESNUMPAD, BANKDROPREVUSESNUMPAD, TENDERDECLUSESNUMPAD to
					  SAFEDROPUSESDENOMINATION, SAFEDROPREVUSESDENOMINATION, BANKDROPUSESDENOMINATION, BANKDROPREVUSESDENOMINATION, TENDERDECLUSESDENOMINATION in POSFUNCTIONALITYPROFILELog
*/

USE LSPOSNET_Audit

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'SAFEDROPUSESNUMPAD')
BEGIN
	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILELog.SAFEDROPUSESNUMPAD', 'SAFEDROPUSESDENOMINATION', 'COLUMN';
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'SAFEDROPREVUSESNUMPAD')
BEGIN
	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILELog.SAFEDROPREVUSESNUMPAD', 'SAFEDROPREVUSESDENOMINATION', 'COLUMN';
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'BANKDROPUSESNUMPAD')
BEGIN
	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILELog.BANKDROPUSESNUMPAD', 'BANKDROPUSESDENOMINATION', 'COLUMN';
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'BANKDROPREVUSESNUMPAD')
BEGIN
	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILELog.BANKDROPREVUSESNUMPAD', 'BANKDROPREVUSESDENOMINATION', 'COLUMN';
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILELog' AND COLUMN_NAME = 'TENDERDECLUSESNUMPAD')
BEGIN
	EXECUTE sp_rename 'POSFUNCTIONALITYPROFILELog.TENDERDECLUSESNUMPAD', 'TENDERDECLUSESDENOMINATION', 'COLUMN';
END
GO