/*
	Incident No.	: ONE-11556
	Responsible		: Simona Avornicesei
	Sprint			: Tamaskan 
	Date created	: 16.04.2020

	Description		: The offline transaction option is not replicated in mobile POS
*/

USE LSPOSNET_Audit

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OMNIALLOWOFFLINETRANS' AND TABLE_NAME = 'POSFUNCTIONALITYPROFILELog')
    BEGIN
        ALTER TABLE POSFUNCTIONALITYPROFILELog ADD OMNIALLOWOFFLINETRANS BIT NULL;
    END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OMNISHOWMINVENTORY' AND TABLE_NAME = 'POSFUNCTIONALITYPROFILELog')
    BEGIN
        ALTER TABLE POSFUNCTIONALITYPROFILELog ADD OMNISHOWMINVENTORY BIT NULL;
    END
GO