/*
	Incident No.	: ONE-10362 Create store transfers and purchase orders from templates
	Responsible		: Adrian Chiorean
	Sprint			: Sun
	Date created	: 03.07.2019

	Description		: Add columns CREATEDFROMOMNI, TEMPLATEID to tables INVENTORYTRANSFERREQUESTLog, INVENTORYTRANSFERORDERLog, PURCHASEORDERSLog
					  Add all missing audit columns to those tables and INVENTJOURNALTABLELog
*/

USE LSPOSNET_Audit

-- Transfer requests
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERREQUESTLog' AND COLUMN_NAME = 'DESCRIPTION')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUESTLog ADD [DESCRIPTION] NVARCHAR(60) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERREQUESTLog' AND COLUMN_NAME = 'EXPECTEDDELIVERY')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUESTLog ADD EXPECTEDDELIVERY DATETIME NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERREQUESTLog' AND COLUMN_NAME = 'REJECTED')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUESTLog ADD REJECTED BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERREQUESTLog' AND COLUMN_NAME = 'CREATEDFROMOMNI')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUESTLog ADD CREATEDFROMOMNI BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERREQUESTLog' AND COLUMN_NAME = 'TEMPLATEID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUESTLog ADD TEMPLATEID NVARCHAR(20) NULL
END
GO

-- Transfer orders
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLog' AND COLUMN_NAME = 'DESCRIPTION')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLog ADD [DESCRIPTION] NVARCHAR(60) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLog' AND COLUMN_NAME = 'EXPECTEDDELIVERY')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLog ADD EXPECTEDDELIVERY DATETIME NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLog' AND COLUMN_NAME = 'REJECTED')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLog ADD REJECTED BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLog' AND COLUMN_NAME = 'CREATEDFROMOMNI')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLog ADD CREATEDFROMOMNI BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLog' AND COLUMN_NAME = 'TEMPLATEID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLog ADD TEMPLATEID NVARCHAR(20) NULL
END
GO


-- Purchase orders
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERSLog' AND COLUMN_NAME = 'ORDERINGDATE')
BEGIN
	ALTER TABLE PURCHASEORDERSLog ADD ORDERINGDATE DATETIME NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERSLog' AND COLUMN_NAME = 'DEFAULTDISCOUNTPERCENTAGE')
BEGIN
	ALTER TABLE PURCHASEORDERSLog ADD DEFAULTDISCOUNTPERCENTAGE DECIMAL(24, 6) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERSLog' AND COLUMN_NAME = 'DEFAULTDISCOUNTAMOUNT')
BEGIN
	ALTER TABLE PURCHASEORDERSLog ADD DEFAULTDISCOUNTAMOUNT DECIMAL(24, 6) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERSLog' AND COLUMN_NAME = 'DESCRIPTION')
BEGIN
	ALTER TABLE PURCHASEORDERSLog ADD [DESCRIPTION] NVARCHAR(60) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERSLog' AND COLUMN_NAME = 'CREATEDFROMOMNI')
BEGIN
	ALTER TABLE PURCHASEORDERSLog ADD CREATEDFROMOMNI BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERSLog' AND COLUMN_NAME = 'TEMPLATEID')
BEGIN
	ALTER TABLE PURCHASEORDERSLog ADD TEMPLATEID NVARCHAR(20) NULL
END
GO

-- Inventory journals
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLELog' AND COLUMN_NAME = 'STOREID')
BEGIN
	ALTER TABLE INVENTJOURNALTABLELog ADD STOREID NVARCHAR(20) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLELog' AND COLUMN_NAME = 'MASTERID')
BEGIN
	ALTER TABLE INVENTJOURNALTABLELog ADD MASTERID UNIQUEIDENTIFIER NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLELog' AND COLUMN_NAME = 'CREATEDFROMOMNI')
BEGIN
	ALTER TABLE INVENTJOURNALTABLELog ADD CREATEDFROMOMNI BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLELog' AND COLUMN_NAME = 'TEMPLATEID')
BEGIN
	ALTER TABLE INVENTJOURNALTABLELog ADD TEMPLATEID NVARCHAR(20) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLELog' AND COLUMN_NAME = 'PROCESSINGSTATUS')
BEGIN
	ALTER TABLE INVENTJOURNALTABLELog ADD PROCESSINGSTATUS INT NULL
END
GO