/*
	Incident No.	: ONE-11528
	Responsible		: Helgi Runar Gunnarsson
	Sprint			: Chihuahua 
	Date created	: 28.05.2020

	Description		: Update TARGETID column in PERIODICDISCOUNTLINELog.
*/

USE LSPOSNET_Audit

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'UNIT' AND TABLE_NAME = 'PERIODICDISCOUNTLINELog')
    BEGIN
        ALTER TABLE PERIODICDISCOUNTLINELog ADD UNIT NVARCHAR(30) NULL
    END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'TARGETID' AND TABLE_NAME = 'PERIODICDISCOUNTLINELog')
    BEGIN
        ALTER TABLE PERIODICDISCOUNTLINELog ALTER COLUMN TARGETID NVARCHAR(60)
    END
GO