/*
	Incident No.	: ONE-9856 Add item picture to stock counting journal lines
	Responsible		: Hörður Kristjánsson
	Sprint			: Sun
	Date created	: 13.08.2019

	Description		: Add PICTUREID column to INVENTJOURNALTRANS
*/

USE LSPOSNET_Audit

-- INVENTJOURNALTRANS --
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANSLog' AND COLUMN_NAME = 'PICTUREID')
BEGIN
	ALTER TABLE INVENTJOURNALTRANSLog ADD PICTUREID NVARCHAR(20) NULL	
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANSLog' AND COLUMN_NAME = 'OMNITRANSACTIONID')
BEGIN
	ALTER TABLE INVENTJOURNALTRANSLog ADD OMNITRANSACTIONID NVARCHAR(20) NULL	
END

-- When receiving lines from stock counting templates the line ID is an integer, however looking at the implementation of the journal lines this could also be a GUID
-- To stay safe we are using 38 characters which should cover any GUID string except hexademical format
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANSLog' AND COLUMN_NAME = 'OMNILINEID')
BEGIN
	ALTER TABLE INVENTJOURNALTRANSLog ADD OMNILINEID NVARCHAR(38) NULL	
END
GO

-- INVENTORYTRANSFERORDERLINE --
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLINELog' AND COLUMN_NAME = 'PICTUREID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLINELog ADD PICTUREID NVARCHAR(20) NULL	
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLINELog' AND COLUMN_NAME = 'OMNITRANSACTIONID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLINELog ADD OMNITRANSACTIONID NVARCHAR(20) NULL	
END

-- When receiving lines from stock counting templates the line ID is an integer, however looking at the implementation of the journal lines this could also be a GUID
-- To stay safe we are using 38 characters which should cover any GUID string except hexademical format
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTRANSFERORDERLINELog' AND COLUMN_NAME = 'OMNILINEID')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDERLINELog ADD OMNILINEID NVARCHAR(38) NULL	
END
GO

-- PURCHASEORDERLINE --
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERLINELog' AND COLUMN_NAME = 'PICTUREID')
BEGIN
	ALTER TABLE PURCHASEORDERLINELog ADD PICTUREID NVARCHAR(20) NULL	
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERLINELog' AND COLUMN_NAME = 'OMNITRANSACTIONID')
BEGIN
	ALTER TABLE PURCHASEORDERLINELog ADD OMNITRANSACTIONID NVARCHAR(20) NULL	
END

-- When receiving lines from stock counting templates the line ID is an integer, however looking at the implementation of the journal lines this could also be a GUID
-- To stay safe we are using 38 characters which should cover any GUID string except hexademical format
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PURCHASEORDERLINELog' AND COLUMN_NAME = 'OMNILINEID')
BEGIN
	ALTER TABLE PURCHASEORDERLINELog ADD OMNILINEID NVARCHAR(38) NULL	
END
GO