/*
	Incident No.	: ONE-11701
	Responsible		: Hörður Kristjánsson
	Sprint			: Akita
	Date created	: 27.03.2020

	Description		: Adding columns to POSVISUALPROFILELog so users can control the colors of buttons in the POS
*/


USE LSPOSNET_Audit

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'CONFIRMBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD CONFIRMBUTTONSTYLEID NVARCHAR(20) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'CANCELBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD CANCELBUTTONSTYLEID NVARCHAR(20) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ACTIONBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD ACTIONBUTTONSTYLEID NVARCHAR(20) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'NORMALBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD NORMALBUTTONSTYLEID NVARCHAR(20) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OTHERBUTTONSTYLEID' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD OTHERBUTTONSTYLEID NVARCHAR(20) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OVERRIDEPOSCONTROLBORDERCOLOR' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD OVERRIDEPOSCONTROLBORDERCOLOR BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'POSCONTROLBORDERCOLOR' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD POSCONTROLBORDERCOLOR INT NULL
END
GO