/*
	Incident No.	: ONE-12309
	Responsible		: Adrian Chiorean
	Sprint			: Chihuahua 
	Date created	: 15.06.2020

	Description		: Add SEARCHKEYWORDS column to RETAILITEMLog table
*/

USE LSPOSNET_Audit

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMLog' AND COLUMN_NAME = 'SEARCHKEYWORDS')
BEGIN
	ALTER TABLE RETAILITEMLog ADD [SEARCHKEYWORDS] NVARCHAR(250) NULL
END
GO