/*
	Incident No.	: ONE-12498
	Responsible		: Hörður Kristjánsson
	Sprint			: Pizza Hut
	Date created	: 18.08.2020

	Description		: Added TERMINALID and STOREID since terminals have a composite key. Increased size of CONNECTIONVALUE to reflect this change.
*/


USE LSPOSNET_Audit

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTERMINALCONNECTIONLog' AND COLUMN_NAME = 'CONNECTIONVALUE' AND CHARACTER_MAXIMUM_LENGTH < 50)
    BEGIN
        ALTER TABLE KITCHENDISPLAYTERMINALCONNECTIONLog ALTER COLUMN CONNECTIONVALUE NVARCHAR(50)
    END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTERMINALCONNECTIONLog' AND COLUMN_NAME = 'TERMINALID')
    BEGIN
        ALTER TABLE KITCHENDISPLAYTERMINALCONNECTIONLog ADD TERMINALID NVARCHAR(20) NULL
    END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYTERMINALCONNECTIONLog' AND COLUMN_NAME = 'STOREID')
    BEGIN
        ALTER TABLE KITCHENDISPLAYTERMINALCONNECTIONLog ADD STOREID NVARCHAR(20) NULL
    END
GO