/*
	Incident No.	: ONE-12992
	Responsible		: Jonas Haraldsson
	Sprint			: Renminbi
	Date created	: 08.12.2020

	Description		: Adding new fields for LS Pay in RBOTERMINALTABLELog.
*/


USE LSPOSNET_Audit

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLELog' AND COLUMN_NAME = 'LSPAYUSELOCALSERVER')
BEGIN
	ALTER TABLE RBOTERMINALTABLELog ADD LSPAYUSELOCALSERVER BIT NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLELog' AND COLUMN_NAME = 'LSPAYSERVERNAME')
BEGIN
	ALTER TABLE RBOTERMINALTABLELog ADD LSPAYSERVERNAME NVARCHAR(100) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLELog' AND COLUMN_NAME = 'LSPAYSERVERPORT')
BEGIN
	ALTER TABLE RBOTERMINALTABLELog ADD LSPAYSERVERPORT INT NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLELog' AND COLUMN_NAME = 'LSPAYPLUGINID')
BEGIN
	ALTER TABLE RBOTERMINALTABLELog ADD LSPAYPLUGINID NVARCHAR(100) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLELog' AND COLUMN_NAME = 'LSPAYPLUGINNAME')
BEGIN
	ALTER TABLE RBOTERMINALTABLELog ADD LSPAYPLUGINNAME NVARCHAR(100) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLELog' AND COLUMN_NAME = 'LSPAYSUPPORTREFREFUND')
BEGIN
	ALTER TABLE RBOTERMINALTABLELog ADD LSPAYSUPPORTREFREFUND BIT NULL
END

GO
