/*
	Incident No.	: ONE-13656
	Responsible		: Sigurður Bjarni Sigurðsson
	Sprint			: Erebus
	Date created	: 31.05.2021

	Description		: Adding columns to POSVISUALPROFILELog so users can control the colors of selected rows in the POS
*/


USE LSPOSNET_Audit

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OVERRIDEPOSSELECTEDROWCOLOR' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD OVERRIDEPOSSELECTEDROWCOLOR BIT NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'POSSELECTEDROWCOLOR' AND TABLE_NAME = 'POSVISUALPROFILELog')
BEGIN
	ALTER TABLE POSVISUALPROFILELog ADD POSSELECTEDROWCOLOR INT NULL
END
GO