//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.ViewPlugins.LabelPrinting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.ViewPlugins.LabelPrinting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many printers require that RAW commands that are sent to the printer end with newline. 
        ///
        ///The current template doesn&apos;t end with a newline. Do you wish to have one added for you?.
        /// </summary>
        internal static string AddNewLine {
            get {
                return ResourceManager.GetString("AddNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified codepage does not exist or is not known.
        /// </summary>
        internal static string CodepageNotFound {
            get {
                return ResourceManager.GetString("CodepageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codepage.
        /// </summary>
        internal static string ColCodepage {
            get {
                return ResourceManager.GetString("ColCodepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        internal static string ColContext {
            get {
                return ResourceManager.GetString("ColContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColDescription {
            get {
                return ResourceManager.GetString("ColDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ColID {
            get {
                return ResourceManager.GetString("ColID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColName {
            get {
                return ResourceManager.GetString("ColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to manage label printing templates for customers.
        /// </summary>
        internal static string CustomerLabelTemplateDescription {
            get {
                return ResourceManager.GetString("CustomerLabelTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage printing templates for customer labels such as address and shipping labels.
        /// </summary>
        internal static string CustomerLabelTemplateTooltipDescription {
            get {
                return ResourceManager.GetString("CustomerLabelTemplateTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer label templates.
        /// </summary>
        internal static string CustomerLableTemplates {
            get {
                return ResourceManager.GetString("CustomerLableTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete label templates.
        /// </summary>
        internal static string DeleteLabelTemplates {
            get {
                return ResourceManager.GetString("DeleteLabelTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the selected label templates?.
        /// </summary>
        internal static string DeleteLabelTemplatesQuestion {
            get {
                return ResourceManager.GetString("DeleteLabelTemplatesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error printing labels.
        /// </summary>
        internal static string ErrorPrintingLabels {
            get {
                return ResourceManager.GetString("ErrorPrintingLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms and labels.
        /// </summary>
        internal static string FormsAndLabels {
            get {
                return ResourceManager.GetString("FormsAndLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FormsImage {
            get {
                object obj = ResourceManager.GetObject("FormsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General setup.
        /// </summary>
        internal static string GeneralSetup {
            get {
                return ResourceManager.GetString("GeneralSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to manage label printing templates for items.
        /// </summary>
        internal static string ItemLabelTemplateDescription {
            get {
                return ResourceManager.GetString("ItemLabelTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item label templates.
        /// </summary>
        internal static string ItemLabelTemplates {
            get {
                return ResourceManager.GetString("ItemLabelTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage printing templates for item labels such as shelf or price labels.
        /// </summary>
        internal static string ItemLabelTemplateTooltipDescription {
            get {
                return ResourceManager.GetString("ItemLabelTemplateTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Label {
            get {
                object obj = ResourceManager.GetObject("Label", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Label_16 {
            get {
                object obj = ResourceManager.GetObject("Label_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Label_32 {
            get {
                object obj = ResourceManager.GetObject("Label_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Label_64 {
            get {
                object obj = ResourceManager.GetObject("Label_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap label_templates_16 {
            get {
                object obj = ResourceManager.GetObject("label_templates_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap label_templates_32 {
            get {
                object obj = ResourceManager.GetObject("label_templates_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A label for this context with the given name already exists.
        /// </summary>
        internal static string LabelExistsError {
            get {
                return ResourceManager.GetString("LabelExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label printing.
        /// </summary>
        internal static string LabelPrinting {
            get {
                return ResourceManager.GetString("LabelPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label printing service is not available.
        /// </summary>
        internal static string LabelPrintingServiceUnavailable {
            get {
                return ResourceManager.GetString("LabelPrintingServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label template.
        /// </summary>
        internal static string LabelTemplate {
            get {
                return ResourceManager.GetString("LabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label templates.
        /// </summary>
        internal static string LabelTemplates {
            get {
                return ResourceManager.GetString("LabelTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to manage label printing templates.
        /// </summary>
        internal static string LabelTemplatesDescription {
            get {
                return ResourceManager.GetString("LabelTemplatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entities to print were passed to the dialog. Nothing to print..
        /// </summary>
        internal static string NoEntitesPassedToDialog {
            get {
                return ResourceManager.GetString("NoEntitesPassedToDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items selected for printing.
        /// </summary>
        internal static string NoItemSelected {
            get {
                return ResourceManager.GetString("NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No label template has been selected. Please select a label template before continuing..
        /// </summary>
        internal static string NoLabelSelected {
            get {
                return ResourceManager.GetString("NoLabelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No printer has been selected. Please select a printer before continuing..
        /// </summary>
        internal static string NoPrinterSelected {
            get {
                return ResourceManager.GetString("NoPrinterSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possibly invalid template.
        /// </summary>
        internal static string PossiblyInvalidTemplate {
            get {
                return ResourceManager.GetString("PossiblyInvalidTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
    }
}
