/*

	Incident No.	: Styles view changes - 5296
	Responsible		: Frentiu Florin
	Sprint			: ImportData/SystemData/001 - SystemStyles.sql
	Date created	: 24.10.2016

	Description		: Create styles for dual display grid control. Create styles for pos total amount control.
*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'SystemNumPadButtonStyle' OR ID = 2000000)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000000, 'SystemNumPadButtonStyle', 'Segoe UI', 24, 0, -1, -13550528, 0, 0, 'LSR', -1, 0, 5, 1, 7)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'SystemNumPadDigitButtonStyle' OR ID = 2000001)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000001, 'SystemNumPadDigitButtonStyle', 'Segoe UI', 24, 0, -1, -13550528, 0, 0, 'LSR', -1, 0, 5, 1, 8)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotal' OR ID = 2000010)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000010, 'DualDisplayTotal', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 1)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayLine' OR ID = 2000011)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000011, 'DualDisplayLine', 'Segoe UI', 12, 0, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 2)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayLineSub' OR ID = 2000012)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000012, 'DualDisplayLineSub', 'Segoe UI', 10, 1, -14264184, -1, 0, 0, 'LSR', -1, 0, 5, 1, 3)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsLabels' OR ID = 2000013)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000013, 'PosTotalsLabels', 'Segoe UI', 12, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 4)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsValues' OR ID = 2000014)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000014, 'PosTotalsValues', 'Segoe UI', 12, 0, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 5)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsBalanceValue' OR ID = 2000015)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000015, 'PosTotalsBalanceValue', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 6)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsBalanceLabel' OR ID = 2000016)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000016, 'PosTotalsBalanceLabel', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 9)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsBalanceLabelNegative' OR ID = 2000017)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000017, 'PosTotalsBalanceLabelNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 10)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosTotalsBalanceValueNegative' OR ID = 2000018)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000018, 'PosTotalsBalanceValueNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 11)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptSaleTotalLabel' OR ID = 2000019)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000019, 'PosReceiptSaleTotalLabel', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 12)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptSaleTotalLabelNegative' OR ID = 2000020)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000020, 'PosReceiptSaleTotalLabelNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 13)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptSaleTotalValue' OR ID = 2000021)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000021, 'PosReceiptSaleTotalValue', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 14)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptSaleTotalValueNegative' OR ID = 2000022)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000022, 'PosReceiptSaleTotalValueNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 15)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptLineSub' OR ID = 2000023)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000023, 'PosReceiptLineSub', 'Segoe UI', 10, 1, -14264184, -1, 0, 0, 'LSR', -1, 0, 5, 1, 16)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalLabelNegative' OR ID = 2000024)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000024, 'DualDisplayTotalLabelNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 17)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalValue' OR ID = 2000025)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000025, 'DualDisplayTotalValue', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 18)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalValueNegative' OR ID = 2000026)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000026, 'DualDisplayTotalValueNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 19)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsBalanceLabel' OR ID = 2000027)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000027, 'DualDisplayTotalsBalanceLabel', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 20)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsBalanceLabelNegative' OR ID = 2000028)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000028, 'DualDisplayTotalsBalanceLabelNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 21)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsBalanceValueNegative' OR ID = 2000029)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000029, 'DualDisplayTotalsBalanceValueNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 22)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsLabels' OR ID = 2000030)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000030, 'DualDisplayTotalsLabels', 'Segoe UI', 12, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 23)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsValues' OR ID = 2000031)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000031, 'DualDisplayTotalsValues', 'Segoe UI', 12, 0, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 24)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsBalanceValue' OR ID = 2000032)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000032, 'DualDisplayTotalsBalanceValue', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 25)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'SystemKeyboardButtonStyle' OR ID = 2000033)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000033, 'SystemKeyboardButtonStyle', 'Segoe UI', 14, 0, -1, -13550528, 0, 0, 'LSR', -1, 0, 5, 1, 26)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'PosReceiptSaleLineStyle' OR ID = 2000034)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000034, 'PosReceiptSaleLineStyle', 'Segoe UI', 12, 0, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 27)
END

GO