/*
	Incident No.	: ONE-7927
	Responsible		: Adrian Chiorean
	Sprint			: Eket
	Date created	: 06.11.2017

	Description		: Add store transfer settings to STORE table
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'DEFAULTDELIVERYTIME' AND TABLE_NAME = 'RBOSTORETABLE')
BEGIN
	ALTER TABLE RBOSTORETABLE ADD DEFAULTDELIVERYTIME INT NOT NULL DEFAULT 2 -- 2 days
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'DELIVERYDAYSTYPE' AND TABLE_NAME = 'RBOSTORETABLE')
BEGIN
	ALTER TABLE RBOSTORETABLE ADD DELIVERYDAYSTYPE INT NOT NULL DEFAULT 1 -- business days
END
GO