/*
	Incident No.	: ONE-7519
	Responsible		: Adrian Chiorean
	Sprint			: Karkotek
	Date created	: 05.12.2017

	Description		: Add store transfer rejected column
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'REJECTED' AND TABLE_NAME = 'INVENTORYTRANSFERORDER')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDER ADD [REJECTED] BIT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'REJECTED' AND TABLE_NAME = 'INVENTORYTRANSFERREQUEST')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUEST ADD [REJECTED] BIT NOT NULL DEFAULT 0
END
GO