/*
	Incident No.	: ONE-7957
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Eket
	Date created	: 16.11.2017

	Description		: Add default store and auto populate items properties to item templates
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'DEFAULTSTORE' AND TABLE_NAME = 'INVENTORYTEMPLATE')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD [DEFAULTSTORE] NVARCHAR(20) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'AUTOPOPULATEITEMS' AND TABLE_NAME = 'INVENTORYTEMPLATE')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD AUTOPOPULATEITEMS INT NULL
END
GO
