/*
	Incident No.	: ONE-4072
	Responsible		: Adrian Chiorean
	Sprint			: Nymö
	Date created	: 17.10.2017

	Description		: Add parameter to Print item sales report operation
*/

USE LSPOSNET

IF EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = 918 AND LOOKUPTYPE = 0)
BEGIN
	UPDATE OPERATIONS SET LOOKUPTYPE = 24 WHERE ID = 918 AND LOOKUPTYPE = 0 -- SET LOOKUPTYPE
	UPDATE POSMENULINE SET PARAMETER = 0 WHERE OPERATION = 918 AND PARAMETER = '' -- SET DEFAULT PARAMETER FOR LOOKUPTYPE
END
GO