/*
	Incident No.	: ONE-7519
	Responsible		: Adrian Chiorean
	Sprint			: Eket
	Date created	: 13.11.2017

	Description		: Add store transfer description and expected delivery 
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'DESCRIPTION' AND TABLE_NAME = 'INVENTORYTRANSFERORDER')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDER ADD [DESCRIPTION] NVARCHAR(60) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'EXPECTEDDELIVERY' AND TABLE_NAME = 'INVENTORYTRANSFERORDER')
BEGIN
	ALTER TABLE INVENTORYTRANSFERORDER ADD EXPECTEDDELIVERY DATETIME NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'DESCRIPTION' AND TABLE_NAME = 'INVENTORYTRANSFERREQUEST')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUEST ADD [DESCRIPTION] NVARCHAR(60) NULL
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'EXPECTEDDELIVERY' AND TABLE_NAME = 'INVENTORYTRANSFERREQUEST')
BEGIN
	ALTER TABLE INVENTORYTRANSFERREQUEST ADD EXPECTEDDELIVERY DATETIME NULL
END
GO