
/*

	Incident No.	: ONE-7458
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: cheng

	Description		: Adding a column for a deleted flag
	
						
*/

USE LSPOSNET
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTITEMBARCODE' AND COLUMN_NAME = 'DELETED')
BEGIN
	ALTER TABLE dbo.INVENTITEMBARCODE ADD DELETED BIT NULL	
	ALTER TABLE dbo.INVENTITEMBARCODE ADD CONSTRAINT DF_INVENTITEMBARCODE_DELETED DEFAULT 0 FOR DELETED

END
GO

UPDATE INVENTITEMBARCODE
SET DELETED = 0
WHERE DELETED IS NULL


GO

