/*
	Incident No.	: ONE-8005
	Responsible		: Adrian Chiorean
	Sprint			: Karkotek
	Date created	: 12.12.2017

	Description		: Add system styles for totals on the dual display
*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsBalanceLabel' OR ID = 2000027)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000027, 'DualDisplayTotalsBalanceLabel', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 20)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsBalanceLabelNegative' OR ID = 2000028)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000028, 'DualDisplayTotalsBalanceLabelNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 21)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsBalanceValueNegative' OR ID = 2000029)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000029, 'DualDisplayTotalsBalanceValueNegative', 'Segoe UI', 16, 1, -1027247, -1, 0, 0, 'LSR', -1, 0, 5, 1, 22)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsLabels' OR ID = 2000030)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000030, 'DualDisplayTotalsLabels', 'Segoe UI', 12, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 23)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsValues' OR ID = 2000031)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000031, 'DualDisplayTotalsValues', 'Segoe UI', 12, 0, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 24)
END

IF NOT EXISTS (SELECT * FROM POSSTYLE WHERE NAME = 'DualDisplayTotalsBalanceValue' OR ID = 2000032)
BEGIN
INSERT INTO POSSTYLE (ID, NAME, FONTNAME, FONTSIZE, FONTBOLD, FORECOLOR, BACKCOLOR, FONTITALIC, FONTCHARSET, DATAAREAID, BACKCOLOR2, GRADIENTMODE, SHAPE, SYSTEMSTYLE, STYLETYPE)
     VALUES (2000032, 'DualDisplayTotalsBalanceValue', 'Segoe UI', 16, 1, -13550528, -1, 0, 0, 'LSR', -1, 0, 5, 1, 25)
END
GO
