/*
	Incident No.	: ONE-8036
	Responsible		: Simona Avornicesei
	Sprint			: Karkotek
	Date created	: 07.12.2017

	Description		: Add MANUALLYENTERTAXCODEID and MANUALLYENTERTAXGROUPID columns to RBOPARAMETERS
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'MANUALLYENTERTAXCODEID' AND TABLE_NAME = 'RBOPARAMETERS')
BEGIN
	ALTER TABLE RBOPARAMETERS ADD MANUALLYENTERTAXCODEID TINYINT
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'MANUALLYENTERTAXGROUPID' AND TABLE_NAME = 'RBOPARAMETERS')
BEGIN
	ALTER TABLE RBOPARAMETERS ADD MANUALLYENTERTAXGROUPID TINYINT
END
GO

-- database documentation
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOPARAMETERS' AND COLUMN_NAME = 'MANUALLYENTERTAXCODEID')
	EXECUTE spDB_SetFieldDescription_1_0 'RBOPARAMETERS', 'MANUALLYENTERTAXCODEID', 'Flag that allows entering tax code id manually, if the user has ''Edit sales tax setup'' permission';
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOPARAMETERS' AND COLUMN_NAME = 'MANUALLYENTERTAXGROUPID')
	EXECUTE spDB_SetFieldDescription_1_0 'RBOPARAMETERS', 'MANUALLYENTERTAXGROUPID', 'Flag that allows entering tax group id manually, if the user has ''Edit sales tax setup'' permission';
GO
