/*
	Incident No.	: ONE-8149
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Dyrgrip
	Date created	: 13.12.2017

	Description		: Add MANUALLYENTERGIFTCARDID column to RBOPARAMETERS
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'MANUALLYENTERGIFTCARDID' AND TABLE_NAME = 'RBOPARAMETERS')
BEGIN
	ALTER TABLE RBOPARAMETERS ADD MANUALLYENTERGIFTCARDID TINYINT
END
GO

-- database documentation
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOPARAMETERS' AND COLUMN_NAME = 'MANUALLYENTERGIFTCARDID')
	EXECUTE spDB_SetFieldDescription_1_0 'RBOPARAMETERS', 'MANUALLYENTERGIFTCARDID', 'Flag that allows entering gift card id manually, if the user has ''Edit gift cards'' permission';
GO

