/*
	Incident No.	: LSTS-5324
	Responsible		: Hörður Kristjánsson
	Sprint			: Hirogen
	Date created	: 12.12.2018

	Description		: Adding index to REPLICATIONCOUNTER columns on all transaction tables
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONBANKEDTENDE20338_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONBANKEDTENDE20338_REPLICATIONCOUNTER
	ON RBOTRANSACTIONBANKEDTENDE20338(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONDININGTABLE_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONDININGTABLE_REPLICATIONCOUNTER
	ON RBOTRANSACTIONDININGTABLE(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONDISCOUNTTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONDISCOUNTTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONDISCOUNTTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONEFTINFOTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONEFTINFOTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONEFTINFOTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONFISCALTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONFISCALTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONFISCALTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONFUELTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONFUELTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONFUELTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONINCOMEEXPEN20158_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONINCOMEEXPEN20158_REPLICATIONCOUNTER
	ON RBOTRANSACTIONINCOMEEXPEN20158(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONINFOCODETRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONINFOCODETRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONINFOCODETRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONLOYALTYPOINTTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONLOYALTYPOINTTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONLOYALTYPOINTTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONOPERATIONAUDIT_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONOPERATIONAUDIT_REPLICATIONCOUNTER
	ON RBOTRANSACTIONOPERATIONAUDIT(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONORDERINVOICETRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONORDERINVOICETRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONORDERINVOICETRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONPAYMENTTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONPAYMENTTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONPAYMENTTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONREPRINTTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONREPRINTTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONREPRINTTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONSAFETENDERTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONSAFETENDERTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONSAFETENDERTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONSALESTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONSALESTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONSALESTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONTABLE_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONTABLE_REPLICATIONCOUNTER
	ON RBOTRANSACTIONTABLE(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONTAXTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONTAXTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONTAXTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONTENDERDECLA20165_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONTENDERDECLA20165_REPLICATIONCOUNTER
	ON RBOTRANSACTIONTENDERDECLA20165(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONLOGTRANS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONLOGTRANS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONLOGTRANS(REPLICATIONCOUNTER)
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME = 'LS_RBOTRANSACTIONRECEIPTS_REPLICATIONCOUNTER')
BEGIN
	CREATE NONCLUSTERED INDEX LS_RBOTRANSACTIONRECEIPTS_REPLICATIONCOUNTER
	ON RBOTRANSACTIONRECEIPTS(REPLICATIONCOUNTER)
END
GO
