/*
	Incident No.	: ONE-8441
	Responsible		: Adrian Chiorean
	Sprint			: Kazon
	Date created	: 13.12.2018

	Description		: Add TAREWEIGHT column to table RETAILITEM, RETAILGROUP and RBOTRANSACTIONSALESTRANS
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'TAREWEIGHT')
BEGIN
	ALTER TABLE RETAILITEM ADD TAREWEIGHT INT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'TAREWEIGHT')
BEGIN
	ALTER TABLE RBOTRANSACTIONSALESTRANS ADD TAREWEIGHT INT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILGROUP' AND COLUMN_NAME = 'TAREWEIGHT')
BEGIN
	ALTER TABLE RETAILGROUP ADD TAREWEIGHT INT NOT NULL DEFAULT 0
END
GO