/*
	Incident No.	: ONE-8257
	Responsible		: Adrian Chiorean
	Sprint			: Maquis
	Date created	: 16.01.2019

	Description		: Increase TAXEXEMPTIONCODE column size to 100 in table RBOTRANSACTIONTAXTRANS
*/

USE LSPOSNET

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONTAXTRANS' AND COLUMN_NAME = 'TAXEXEMPTIONCODE')
BEGIN
IF(COL_LENGTH('RBOTRANSACTIONTAXTRANS', 'TAXEXEMPTIONCODE') < 200) -- We want to update the column to be NVARCHAR(100) which has an equivalent length in bytes of 200
	BEGIN 
		ALTER TABLE [RBOTRANSACTIONTAXTRANS] ALTER COLUMN [TAXEXEMPTIONCODE] NVARCHAR(100) NULL
	END
END
GO