/*
	Incident No.	: ONE-9085
	Responsible		: Tan Bee Tze
	Sprint			: 
	Date created	: 12.10.2018
	Description		: Add FISCALBASICID table for NO fiscalisation purpose and add columns into RBOTRANSACTIONFISCALTRANS table

*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'FISCALBASICID')
BEGIN
	CREATE TABLE FISCALBASICID
	(
		TYPE INT NOT NULL,
		ID NVARCHAR(40) NOT NULL,
		FISCALID NVARCHAR(40)
	)

	ALTER TABLE FISCALBASICID ADD CONSTRAINT  PK_FISCALBASICID 
PRIMARY KEY (TYPE,ID)
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'PRIVATEKEYVER' AND Object_ID = Object_ID('RBOTRANSACTIONFISCALTRANS'))
BEGIN
	ALTER TABLE RBOTRANSACTIONFISCALTRANS
	ADD TYPE INT NOT NULL,
		TRANSDATE DATETIME NOT NULL,
		GROSSAMOUNT numeric(28, 12) NOT NULL,
		NETAMOUNT  numeric(28, 12) NOT NULL,
		PRIVATEKEYVER NVARCHAR(60) NOT NULL ,
		[SIGNATURE] NVARCHAR(500) NOT NULL 
END
GO