/*
	Incident No.	: ONE-8611
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: Ferengi
	Date created	: 02.11.2018

	Description		: Add a ANOTHERMETHODIFAMOUNTHIGHER to RBOSTORETENDERTYPETABLE
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTORETENDERTYPETABLE' AND COLUMN_NAME = 'ANOTHERMETHODIFAMOUNTHIGHER')
BEGIN
	ALTER TABLE RBOSTORETENDERTYPETABLE ADD ANOTHERMETHODIFAMOUNTHIGHER BIT NOT NULL DEFAULT 0
	EXECUTE spDB_SetFieldDescription_1_0 'RBOSTORETENDERTYPETABLE', 'ANOTHERMETHODIFAMOUNTHIGHER', 'Tells if another change back payment is requred if the change back amount is higher than a certain amount';
END
GO