/*
	Incident No.	: ONE-9033
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Capella
	Date created	: 22.05.2019

	Description		: Increase the size of field RBOTRANSACTIONTABLE.ORGTRANSTERMINAL	
*/

USE LSPOSNET


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONTABLE' AND COLUMN_NAME = 'ORGTRANSTERMINAL' AND CHARACTER_MAXIMUM_LENGTH < 20)
BEGIN
	ALTER TABLE RBOTRANSACTIONTABLE
	ALTER COLUMN ORGTRANSTERMINAL NVARCHAR(20)
END
GO