/*
	Incident No.	: ONE-9733
	Responsible		: Ovidiu Caba
	Sprint			: Betelgeuse
	Date created	: 28.02.2019

	Description		: Increase column RETAILITEM.ITEMNAME and RETAILITEM.VARIANTNAME to 120 characters
*/

USE LSPOSNET

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'ITEMNAME')
BEGIN
	IF(COL_LENGTH('RETAILITEM', 'ITEMNAME') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE RETAILITEM ALTER COLUMN ITEMNAME NVARCHAR(120) NOT NULL
	END
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'VARIANTNAME')
BEGIN
	IF(COL_LENGTH('RETAILITEM', 'VARIANTNAME') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE RETAILITEM ALTER COLUMN VARIANTNAME NVARCHAR(120) NOT NULL
	END
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTDIMCOMBINATION' AND COLUMN_NAME = 'NAME')
BEGIN
	IF(COL_LENGTH('INVENTDIMCOMBINATION', 'NAME') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE INVENTDIMCOMBINATION ALTER COLUMN NAME NVARCHAR(120) NULL
	END
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTTABLE' AND COLUMN_NAME = 'ITEMNAME')
BEGIN
	IF(COL_LENGTH('INVENTTABLE', 'ITEMNAME') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE INVENTTABLE ALTER COLUMN ITEMNAME NVARCHAR(120) NULL
	END
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'DESCRIPTION')
BEGIN
	IF(COL_LENGTH('RBOTRANSACTIONSALESTRANS', 'DESCRIPTION') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE RBOTRANSACTIONSALESTRANS ALTER COLUMN [DESCRIPTION] NVARCHAR(120) NULL
	END
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'NAMEALIAS')
BEGIN
	IF(COL_LENGTH('RETAILITEM', 'NAMEALIAS') < 240) -- We want to update the column to be NVARCHAR(120) which has an equivalent length in bytes of 240
	BEGIN 
		ALTER TABLE RETAILITEM ALTER COLUMN NAMEALIAS NVARCHAR(120) NOT NULL
	END
END
GO