/*
	Incident No.	: ONE-7998
	Responsible		: Adrian Chiorean
	Sprint			: Corgi
	Date created	: 18.05.2020

	Description		: Update default vendor on retail items from internal ID to vendor ID (VENDORITEMS)
*/

USE LSPOSNET

IF EXISTS (SELECT 1 FROM sys.triggers WHERE Name = 'Update_RETAILITEM')
BEGIN
    DISABLE TRIGGER Update_RETAILITEM ON RETAILITEM
END
GO

;WITH ITEMVENDOR_CTE AS (
SELECT R.ITEMID, R.DEFAULTVENDORID, VI.INTERNALID, VI.VENDORID FROM RETAILITEM R
LEFT JOIN VENDORITEMS VI ON R.DEFAULTVENDORID = VI.INTERNALID
WHERE R.DEFAULTVENDORID IS NOT NULL AND R.DEFAULTVENDORID <> '' AND VI.INTERNALID IS NOT NULL)
UPDATE ITEMVENDOR_CTE set DEFAULTVENDORID = VENDORID
GO

IF EXISTS (SELECT 1 FROM sys.triggers WHERE Name = 'Update_RETAILITEM')
BEGIN
    ENABLE TRIGGER Update_RETAILITEM ON RETAILITEM
END
GO
