
/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\KDS
	Date created	: 31.7.2013

	Description		: Added new fields to KDS
*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'USEEXTERNALROUTING')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD USEEXTERNALROUTING TINYINT NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'DISPLAYMODE')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD DISPLAYMODE TINYINT NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'NEXTSTATIONID')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD NEXTSTATIONID NVARCHAR(20) NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILE' AND COLUMN_NAME = 'DISPLAYLEVEL')
BEGIN
	ALTER TABLE KITCHENDISPLAYFUNCTIONALPROFILE ADD DISPLAYLEVEL INT NULL
END
GO