
/*

	Incident No.	: 
	Responsible		: Erna Gudrun Sigurdardottir
	Sprint			: LS One 2013.1\KDS
	Date created	: 08.08.13

	Description		: Removed settings from Visual and Functional Profile
*/

USE LSPOSNET


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILE' AND COLUMN_NAME = 'SHOWBUMPED')
BEGIN
	ALTER TABLE KITCHENDISPLAYFUNCTIONALPROFILE DROP COLUMN SHOWBUMPED
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILE' AND COLUMN_NAME = 'BUMPOPERATION')
BEGIN
	ALTER TABLE KITCHENDISPLAYFUNCTIONALPROFILE DROP COLUMN BUMPOPERATION
END
GO