
/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: 
	Date created	: 13.08.13

	Description		: Increase size of columns
*/

USE LSPOSNET

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSIZES' AND COLUMN_NAME = 'NAME' AND CHARACTER_MAXIMUM_LENGTH < 30)
BEGIN
	ALTER TABLE RBOSIZES ALTER COLUMN NAME NVARCHAR(30)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOCOLORS' AND COLUMN_NAME = 'NAME' AND CHARACTER_MAXIMUM_LENGTH < 30)
BEGIN
	ALTER TABLE RBOCOLORS ALTER COLUMN NAME NVARCHAR(30)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOCOLORGROUPTRANS' AND COLUMN_NAME = 'NAME' AND CHARACTER_MAXIMUM_LENGTH < 30)
BEGIN
	ALTER TABLE RBOCOLORGROUPTRANS ALTER COLUMN NAME NVARCHAR(30)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSIZEGROUPTRANS' AND COLUMN_NAME = 'NAME' AND CHARACTER_MAXIMUM_LENGTH < 30)
BEGIN
	ALTER TABLE RBOSIZEGROUPTRANS ALTER COLUMN NAME NVARCHAR(30)
END
GO

