USE LSPOSNET

GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'KITCHENDISPLAYLOG' AND COLUMN_NAME = 'MESSAGE')
BEGIN
ALTER TABLE KITCHENDISPLAYLOG ADD MESSAGE ntext NULL
END

GO
