
/*

	Incident No.	: 
	Responsible		: Sigfus Johannesson
	Sprint			: 
	Date created	: 12.08.13

	Description		: Removed column from KITCHENDISPLAYFUNCTIONALPROFILE
*/

USE LSPOSNET


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILE' AND COLUMN_NAME = 'ONVOID')
BEGIN
	ALTER TABLE KITCHENDISPLAYFUNCTIONALPROFILE DROP COLUMN ONVOID
END
GO
