/*

	Incident No.	: 
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013\Sprint 2
	Date created	: 29.8.2013

	Description		: New fields to RBOTERMINALTABLE
	
	Tables affected	: RBOTERMINALTABLE
						
*/
USE LSPOSNET

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLE' AND COLUMN_NAME = 'EFTCUSTOMFIELD1')
BEGIN
	ALTER TABLE RBOTERMINALTABLE ADD EFTCUSTOMFIELD1 NVARCHAR(200)
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLE' AND COLUMN_NAME = 'EFTCUSTOMFIELD2')
BEGIN
	ALTER TABLE RBOTERMINALTABLE ADD EFTCUSTOMFIELD2 NVARCHAR(200)
END
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLE' AND COLUMN_NAME = 'IPADDRESS' AND CHARACTER_MAXIMUM_LENGTH < 100)
BEGIN
	ALTER TABLE RBOTERMINALTABLE ALTER COLUMN IPADDRESS NVARCHAR(100)
END
GO

