
/*

	Incident No.	: 
	Responsible		: Erna Guðrún Sigurðardóttir
	Sprint			: LS One 2013.1\KDS
	Date created	: 06.08.13

	Description		: Added ITEMLINENUMBER to KITCHENDISPLAYLOG
*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYLOG' AND COLUMN_NAME = 'ITEMLINENUMBER')
BEGIN
	ALTER TABLE KITCHENDISPLAYLOG ADD ITEMLINENUMBER INT NULL
END
GO