
/*

	Incident No.	: 
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2013.1\KDS
	Date created	: 07.8.2013

	Description		: Added new fields to KDS
*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'STATIONTYPE')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD STATIONTYPE TINYINT NULL
END
GO
