/*

	Incident No.	: N/A
	Responsible		: Sigfus Johannesson
	Sprint			: LS One 2013.1\Sprint 2
	Date created	: 26.9.2013

	Description		: Changing PK for posislicense
*/

USE LSPOSNET

GO
   
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE CONSTRAINT_NAME = 'PK_POSISLICENSE' AND COLUMN_NAME = 'STOREID')
BEGIN
	alter table posislicense
	drop constraint PK_POSISLICENSE
END

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISLICENSE' AND COLUMN_NAME = 'ID')
Begin
  Alter Table POSISLICENSE add ID UniqueIdentifier
End
GO

update POSISLICENSE SET ID = NEWID() where ID is NULL
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISLICENSE' AND COLUMN_NAME = 'ID')
Begin
  Alter Table POSISLICENSE ALTER COLUMN ID UniqueIdentifier NOT NULL
End
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PK_POSISLICENSE')
BEGIN  
  alter table posislicense
  add constraint PK_POSISLICENSE primary key (ID)
END
GO

if not exists(SELECT * FROM [sys].[indexes] where object_id = object_id(N'[dbo].[POSISLICENSE]') AND NAME = N'IDX_POSISLICENSE_VOLUMENO')
BEGIN
 CREATE INDEX IDX_POSISLICENSE_VOLUMENO
 ON dbo.POSISLICENSE (VOLUMENO,DATAAREAID)
END
