/*
Removing unused KDS columns
*/

USE LSPOSNET

GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'FLOWPATH')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column FLOWPATH
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'TOPLEFT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column TOPLEFT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'TOPCENTER')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column TOPCENTER
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'TOPRIGHT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column TOPRIGHT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'BOTTOMLEFT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column BOTTOMLEFT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'BOTTOMCENTER')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column BOTTOMCENTER
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'BOTTOMRIGHT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column BOTTOMRIGHT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'TIMEFORMAT')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column TIMEFORMAT
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'BORDERCOLOR')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column BORDERCOLOR
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYVISUALPROFILE' AND COLUMN_NAME = 'RUSHBORDERCOLOR')
Begin
  Alter Table KITCHENDISPLAYVISUALPROFILE Drop Column RUSHBORDERCOLOR
End

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYFUNCTIONALPROFILE' AND COLUMN_NAME = 'DISPLAYLEVEL')
Begin
  Alter Table KITCHENDISPLAYFUNCTIONALPROFILE Drop Column DISPLAYLEVEL
End




