
/*

	Incident No.	: N/A
	Responsible		: Erna Guðrún Sigurðardóttir
	Sprint			: LS One 2013.1\Sprint 2
	Date created	: 11.10.2013

	Description		: Goes through all items and finds items that have only one vendor on them and sets that vendor as the default (primary) vendor
	
						
*/

USE LSPOSNET

DECLARE @ITEMID NVARCHAR(100)
DECLARE @PRIMARYVENDORID NVARCHAR(100)
DECLARE @COUNT INT
DECLARE @SQL NVARCHAR(255)
DECLARE @VENDORITEMID NVARCHAR(100)

DECLARE ITEM CURSOR FOR

	SELECT ITEMID, PRIMARYVENDORID
	FROM INVENTTABLE

OPEN ITEM

FETCH FROM ITEM INTO @ITEMID, @PRIMARYVENDORID

WHILE @@FETCH_STATUS = 0
BEGIN 

	IF @PRIMARYVENDORID != ''
	BEGIN
		SET @COUNT = 0
			
		SELECT @COUNT = COUNT(*)
		FROM VENDORITEMS
		WHERE RETAILITEMID = @ITEMID
		AND VENDORID = @PRIMARYVENDORID
		AND DATAAREAID = 'LSR'
		GROUP BY VENDORID

		IF @COUNT = 1
		BEGIN
			SET @VENDORITEMID  = ''
					
			SELECT @VENDORITEMID = INTERNALID
			FROM VENDORITEMS
			WHERE RETAILITEMID = @ITEMID
			AND VENDORID = @PRIMARYVENDORID
			AND DATAAREAID = 'LSR'
					
			IF @VENDORITEMID != ''
			BEGIN
				UPDATE INVENTTABLE
				SET PRIMARYVENDORID = @VENDORITEMID
				WHERE ITEMID = @ITEMID
				AND DATAAREAID = 'LSR'
			END

			ELSE
			BEGIN
				UPDATE INVENTTABLE
				SET PRIMARYVENDORID = ''
				WHERE ITEMID = @ITEMID
				AND DATAAREAID = 'LSR'
			END
		END

		ELSE IF @COUNT > 1
		BEGIN
			UPDATE INVENTTABLE
			SET PRIMARYVENDORID = ''
			WHERE ITEMID = @ITEMID
			AND DATAAREAID = 'LSR'
		END
			
		ELSE
		BEGIN
			SET @VENDORITEMID  = ''
			
			SELECT @VENDORITEMID = INTERNALID
			FROM VENDORITEMS VI
			LEFT OUTER JOIN INVENTTABLE IT ON IT.PRIMARYVENDORID = VI.INTERNALID 
			WHERE IT.DATAAREAID = VI.DATAAREAID
			AND RETAILITEMID = @ITEMID
					
			IF @VENDORITEMID = ''
			BEGIN
				UPDATE INVENTTABLE
				SET PRIMARYVENDORID = ''
				WHERE ITEMID = @ITEMID
				AND DATAAREAID = 'LSR'
			END
		END
	END

	ELSE
	BEGIN
		SET @COUNT = 0
	
		SELECT @COUNT = COUNT(*)
		FROM VENDORITEMS
		WHERE RETAILITEMID = @ITEMID
		AND DATAAREAID = 'LSR'
		GROUP BY RETAILITEMID

		IF @COUNT = 1
		BEGIN
			SET @VENDORITEMID  = ''
			
			SELECT @VENDORITEMID = INTERNALID
			FROM VENDORITEMS
			WHERE RETAILITEMID = @ITEMID
			AND DATAAREAID = 'LSR'
		END
	END

FETCH NEXT FROM ITEM INTO @ITEMID, @PRIMARYVENDORID

END

CLOSE ITEM
DEALLOCATE ITEM

GO

