/*

	Incident No.	: 25670
	Responsible		: Birgir Kristmannsson
	Sprint			: LS One 2013.1\July, August, September
	Date created	: 6.10.2013

	Description		: Added new fields to RBOTERMINALTABLE and RBOSTORETABLE
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTERMINALTABLE' AND COLUMN_NAME = 'FORMINFOFIELD1')
Begin
  Alter Table RBOTERMINALTABLE add FORMINFOFIELD1 NVARCHAR(60)
  Alter Table RBOTERMINALTABLE add FORMINFOFIELD2 NVARCHAR(60)
  Alter Table RBOTERMINALTABLE add FORMINFOFIELD3 NVARCHAR(60)
  Alter Table RBOTERMINALTABLE add FORMINFOFIELD4 NVARCHAR(60)
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTORETABLE' AND COLUMN_NAME = 'FORMINFOFIELD1')
Begin
  Alter Table RBOSTORETABLE add FORMINFOFIELD1 NVARCHAR(60)
  Alter Table RBOSTORETABLE add FORMINFOFIELD2 NVARCHAR(60)
  Alter Table RBOSTORETABLE add FORMINFOFIELD3 NVARCHAR(60)
  Alter Table RBOSTORETABLE add FORMINFOFIELD4 NVARCHAR(60)
End
