/*

	Incident No.	: 25932
	Responsible		: Höður Sigurdór Heiðarsson
	Sprint			: LS One 2013.1\July, August, September
	Date created	: 3.10.2013

	Description		: Added import timestamp on POSSTYLE, POSMENUHEADER and POSISTILLLAYOUT
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSSTYLE' AND COLUMN_NAME = 'IMPORTDATETIME')
Begin
  Alter Table POSSTYLE add IMPORTDATETIME datetime
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADER' AND COLUMN_NAME = 'IMPORTDATETIME')
Begin
  Alter Table POSMENUHEADER add IMPORTDATETIME datetime
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISTILLLAYOUT' AND COLUMN_NAME = 'IMPORTDATETIME')
Begin
  Alter Table POSISTILLLAYOUT add IMPORTDATETIME datetime
End
