/*

	Incident No.	: 25637
	Responsible		: Höður Sigurdór Heiðarsson
	Sprint			: LS One 2013.1\Sprint 2
	Date created	: 30.9.2013

	Description		: Added GUID to POSSTYLE, POSMENUHEADER and POSISTILLLAYOUT
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSSTYLE' AND COLUMN_NAME = 'GUID')
Begin
  Alter Table POSSTYLE add GUID uniqueidentifier NOT NULL default NEWID()
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSMENUHEADER' AND COLUMN_NAME = 'GUID')
Begin
  Alter Table POSMENUHEADER add GUID uniqueidentifier NOT NULL default NEWID()
End

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSISTILLLAYOUT' AND COLUMN_NAME = 'GUID')
Begin
  Alter Table POSISTILLLAYOUT add GUID uniqueidentifier NOT NULL default NEWID()
End
