/*

	Incident No.	: 25793
	Responsible		: Hörður Kristjánsson
	Sprint			: LS One 2013.1\Sprint 2
	Date created	: 01.10.2013

	Description		: Added CHECKID to RBOTRANSACTIONPAYMENTTRANS
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONPAYMENTTRANS' AND COLUMN_NAME = 'CHECKID')
Begin
  Alter Table RBOTRANSACTIONPAYMENTTRANS add CHECKID nvarchar(60) NOT NULL DEFAULT ('')
End

GO