/* 
        Incident No.: N/A 
        Responsible	: Höður Sigurdór Heiðarsson
        Sprint		: LS One 2013.1\July, August, September
        Date created: 16.10.13 
        Description	: Replace RECEIPT with FORM in column names of POSISRECEIPTPROFILELINES
						and in table names of POSRECEIPTPROFILELINES, POSRECEIPTPROFILE and POSRECEIPTTYPE
*/ 
USE LSPOSNET 
GO 
IF EXISTS (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'POSRECEIPTPROFILELINES' and COLUMN_NAME = 'RECEIPTTYPEID')
BEGIN
	IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSRECEIPTPROFILELINES' AND COLUMN_NAME = 'FORMTYPEID')
	BEGIN
		EXEC sp_rename 'DBO.POSRECEIPTPROFILELINES.RECEIPTTYPEID', 'FORMTYPEID', 'COLUMN'
	END
END
GO

IF EXISTS (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'POSFORMPROFILELINES' and COLUMN_NAME = 'RECEIPTTYPEID')
BEGIN
	IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFORMPROFILELINES' AND COLUMN_NAME = 'FORMTYPEID')
	BEGIN
		EXEC sp_rename 'DBO.POSFORMPROFILELINES.RECEIPTTYPEID', 'FORMTYPEID', 'COLUMN'
	END
END
GO

IF EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'POSRECEIPTPROFILELINES')
BEGIN
	IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSRECEIPTPROFILELINES' AND COLUMN_NAME = 'POSFORMPROFILELINES')
	BEGIN
		EXEC sp_rename 'DBO.POSRECEIPTPROFILELINES', 'POSFORMPROFILELINES'
	END
END
GO

IF EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'POSRECEIPTPROFILE')
BEGIN
	IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSRECEIPTPROFILE' AND COLUMN_NAME = 'POSFORMPROFILE')
	BEGIN
		EXEC sp_rename 'DBO.POSRECEIPTPROFILE', 'POSFORMPROFILE'
	END
END
GO

IF EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'POSRECEIPTTYPE')
BEGIN
	IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSRECEIPTTYPE' AND COLUMN_NAME = 'POSFORMTYPE')
	BEGIN
		EXEC sp_rename 'DBO.POSRECEIPTTYPE', 'POSFORMTYPE'
	END
END
GO