
/*

	Incident No.	: N/A
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS One 2013.1\Sprint 2
	Date created	: 31.10.2013

	Description		: Added DISCOVERSBUMPBAR and DISCOVERKEYID to KITCHENDISPLAYSTATION
	
						
*/

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'DISCOVERSBUMPBAR')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD DISCOVERSBUMPBAR bit NOT NULL DEFAULT 0
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KITCHENDISPLAYSTATION' AND COLUMN_NAME = 'DISCOVERKEY')
BEGIN
	ALTER TABLE KITCHENDISPLAYSTATION ADD DISCOVERKEY int NULL
END




