/*

	Incident No.	: XXX
	Responsible		: Guðbjörn Einarsson
	Sprint			: LS Retail .NET 2013\Mars
	Date created	: 01.11.2012

	Description		: Remove column VOIDEDSTYLEID from KMINTERFACEPROFILE
	
	
	Tables affected	: KMINTERFACEPROFILE
						
*/
USE LSPOSNET

GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KMINTERFACEPROFILE' AND COLUMN_NAME = 'VOIDEDSTYLEID')
BEGIN
	ALTER TABLE KMINTERFACEPROFILE DROP COLUMN VOIDEDSTYLEID
END
GO