/*

	Incident No.	: 19351
	Responsible		: Sigfús Jóhannesson
	Sprint			: LS Retail .NET 2013\Earth
	Date created	: 17.10.2012

	Description		: Added store and terminal to the primarykey.
	
	
	Tables affected	: RBOTRANSACTIONINFOCODETRANS
				      RBOTRANSACTIONINCOMEEXPEN20158
					  RBOTRANSACTIONLOYALTYPOINTTRANS
					  RBOTRANSACTIONTENDERDECLA20165
						
*/
USE LSPOSNET
GO
  
--TABLE RBOTRANSACTIONINFOCODETRANS
--Making sure that store and terminal columns are NOT NULL
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'RBOTRANSACTIONINFOCODETRANS' AND COLUMN_NAME = N'STORE' AND IS_NULLABLE = 'YES')
BEGIN
ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN STORE NVARCHAR(20) NOT NULL
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'RBOTRANSACTIONINFOCODETRANS' AND COLUMN_NAME = N'TERMINAL' AND IS_NULLABLE = 'YES')
BEGIN
ALTER TABLE RBOTRANSACTIONINFOCODETRANS ALTER COLUMN TERMINAL NVARCHAR(20) NOT NULL
END
GO

IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RBOTRANSACTIONINFOCODETRANS]') AND name = N'I_20159TRANSTYPELINEINFOC20001')
BEGIN
  IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = N'RBOTRANSACTIONINFOCODETRANS' AND (COLUMN_NAME = N'STORE' OR COLUMN_NAME = N'TERMINAL'))
  BEGIN
  ALTER TABLE RBOTRANSACTIONINFOCODETRANS DROP CONSTRAINT I_20159TRANSTYPELINEINFOC20001
 ALTER TABLE RBOTRANSACTIONINFOCODETRANS ADD CONSTRAINT I_20159TRANSTYPELINEINFOC20001 PRIMARY KEY CLUSTERED 
(
	DATAAREAID ASC,
	TRANSACTIONID ASC,
	[TYPE] ASC,
	LINENUM ASC,
	INFOCODEID ASC,
	STORE ASC,
	TERMINAL ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
  END
END

GO

--TABLE RBOTRANSACTIONINCOMEEXPEN20158
--Making sure that store and terminal columns are NOT NULL
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'RBOTRANSACTIONINCOMEEXPEN20158' AND COLUMN_NAME = N'STORE' AND IS_NULLABLE = 'YES')
BEGIN
ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN STORE NVARCHAR(20) NOT NULL
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'RBOTRANSACTIONINCOMEEXPEN20158' AND COLUMN_NAME = N'TERMINAL' AND IS_NULLABLE = 'YES')
BEGIN
ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN TERMINAL NVARCHAR(20) NOT NULL
END

GO

IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RBOTRANSACTIONINCOMEEXPEN20158]') AND name = N'I_20158TRANSACTIONLINEIDX')
BEGIN
  IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = N'RBOTRANSACTIONINCOMEEXPEN20158' AND (COLUMN_NAME = N'STORE' OR COLUMN_NAME = N'TERMINAL'))
  BEGIN
  ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 DROP CONSTRAINT I_20158TRANSACTIONLINEIDX
 ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ADD  CONSTRAINT I_20158TRANSACTIONLINEIDX PRIMARY KEY CLUSTERED 
(
	DATAAREAID ASC,
	TRANSACTIONID ASC,
	LINENUM ASC,
	STORE ASC,
	TERMINAL ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
  END
END

GO

--TABLE RBOTRANSACTIONLOYALTYPOINTTRANS
--Making sure that store and terminal columns are NOT NULL
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'RBOTRANSACTIONLOYALTYPOINTTRANS' AND COLUMN_NAME = N'STOREID' AND IS_NULLABLE = 'YES')
BEGIN
ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN STOREID NVARCHAR(20) NOT NULL
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'RBOTRANSACTIONLOYALTYPOINTTRANS' AND COLUMN_NAME = N'TERMINALID' AND IS_NULLABLE = 'YES')
BEGIN
ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN TERMINALID NVARCHAR(20) NOT NULL
END

GO

IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RBOTRANSACTIONLOYALTYPOINTTRANS]') AND name = N'I_20296TRANSACTIONLINEIDX')
BEGIN
  IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = N'RBOTRANSACTIONLOYALTYPOINTTRANS' AND (COLUMN_NAME = N'STOREID' OR COLUMN_NAME = N'TERMINALID'))
  BEGIN
  ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS DROP CONSTRAINT I_20296TRANSACTIONLINEIDX
 ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ADD  CONSTRAINT I_20296TRANSACTIONLINEIDX PRIMARY KEY CLUSTERED 
(
	DATAAREAID ASC,
	TRANSACTIONID ASC,
	LINENUM ASC,
	STOREID ASC,
	TERMINALID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
  END
END

--TABLE RBOTRANSACTIONTENDERDECLA20165
--Making sure that store and terminal columns are NOT NULL
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'RBOTRANSACTIONINCOMEEXPEN20158' AND COLUMN_NAME = N'STORE' AND IS_NULLABLE = 'YES')
BEGIN
ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN STORE NVARCHAR(20) NOT NULL
END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'RBOTRANSACTIONINCOMEEXPEN20158' AND COLUMN_NAME = N'TERMINAL' AND IS_NULLABLE = 'YES')
BEGIN
ALTER TABLE RBOTRANSACTIONINCOMEEXPEN20158 ALTER COLUMN TERMINAL NVARCHAR(20) NOT NULL
END

GO

IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RBOTRANSACTIONTENDERDECLA20165]') AND name = N'I_20165TRANSACTIONLINEIDX')
BEGIN
  IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = N'RBOTRANSACTIONTENDERDECLA20165' AND (COLUMN_NAME = N'STORE' OR COLUMN_NAME = N'TERMINAL'))
  BEGIN
  ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 DROP CONSTRAINT I_20165TRANSACTIONLINEIDX
 ALTER TABLE RBOTRANSACTIONTENDERDECLA20165 ADD  CONSTRAINT I_20165TRANSACTIONLINEIDX PRIMARY KEY CLUSTERED 
(
	DATAAREAID ASC,
	TRANSACTIONID ASC,
	LINENUM ASC,
	STORE ASC,
	TERMINAL ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
  END
END

GO
