/*

	Incident No.	: XXX
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS Retail .NET 2013\Mars
	Date created	: 26.11.2012

	Description		: Add tables for kithen display routing

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: KITCHENDISPLAYTERMINALCONNECTION, KITCHENDISPLAYITEMCONNECTION, KITCHENDISPLAYHOSPITALITYTYPECONNECTION
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYTERMINALCONNECTION'))
	BEGIN
		CREATE TABLE [dbo].[KITCHENDISPLAYTERMINALCONNECTION](
		[ID] [uniqueidentifier] NOT NULL,
		[STATIONID] [nvarchar](20) NOT NULL,
		[TYPE] int NOT NULL,
		[CONNECTIONVALUE] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
		)

		Alter table KITCHENDISPLAYTERMINALCONNECTION Add CONSTRAINT  PK_KITCHENDISPLAYTERMINALCONNECTION Primary Key (ID,DATAAREAID)
	END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYITEMCONNECTION'))
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYITEMCONNECTION(
		[ID] [uniqueidentifier] NOT NULL,
		[STATIONID] [nvarchar](20) NOT NULL,
		[TYPE] int NOT NULL,
		[CONNECTIONVALUE] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
		)

		Alter table KITCHENDISPLAYITEMCONNECTION Add CONSTRAINT  PK_KITCHENDISPLAYITEMCONNECTION Primary Key (ID,DATAAREAID)
	END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYHOSPITALITYTYPECONNECTION'))
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYHOSPITALITYTYPECONNECTION(
		[ID] [uniqueidentifier] NOT NULL,
		[STATIONID] [nvarchar](20) NOT NULL,
		[TYPE] int NOT NULL,
		[CONNECTIONVALUE] [nvarchar](20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
		)

		Alter table KITCHENDISPLAYHOSPITALITYTYPECONNECTION Add CONSTRAINT  PK_KITCHENDISPLAYHOSPITALITYTYPECONNECTION Primary Key (ID,DATAAREAID)
	END
GO
