/*

	Incident No.	: 19909
	Responsible		: Erna Guðrún Sigurðardóttir
	Sprint			: LS Retail .NET 2013\Mars
	Date created	: 19.11.2012

	Description		: Add NORMALITEMMODIFIERSTYLEID, INCREASEITEMMODIFIERSTYLEID and DECREASEITEMMODIFIERSTYLEID to KMINTERFACEPROFILE

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: KMINTERFACEPROFILE
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='NORMALITEMMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KMINTERFACEPROFILE ADD NORMALITEMMODIFIERSTYLEID nvarchar(20) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='INCREASEITEMMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KMINTERFACEPROFILE ADD INCREASEITEMMODIFIERSTYLEID nvarchar(20) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='DECREASEITEMMODIFIERSTYLEID')
BEGIN
	ALTER TABLE KMINTERFACEPROFILE ADD DECREASEITEMMODIFIERSTYLEID nvarchar(20) NULL
END
GO