/*

	Incident No.	: XXX
	Responsible		: Guðbjörn Einarsson
	Sprint			: LS Retail .NET 2013\Mars
	Date created	: 06.11.2012

	Description		: Remove columns SCREENALIGNMENT, SCREENNUMBER from KMINTERFACEPROFILE and add them to table RESTAURANTSTATION
	
	
	Tables affected	: KMINTERFACEPROFILE and RESTAURANTSTATION
						
*/
USE LSPOSNET

GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KMINTERFACEPROFILE' AND COLUMN_NAME = 'SCREENALIGNMENT')
BEGIN
	ALTER TABLE KMINTERFACEPROFILE DROP COLUMN SCREENALIGNMENT
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KMINTERFACEPROFILE' AND COLUMN_NAME = 'SCREENNUMBER')
BEGIN
	ALTER TABLE KMINTERFACEPROFILE DROP COLUMN SCREENNUMBER
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RESTAURANTSTATION' AND COLUMN_NAME = 'SCREENNUMBER')
BEGIN
	ALTER TABLE RESTAURANTSTATION ADD SCREENNUMBER INT NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RESTAURANTSTATION' AND COLUMN_NAME = 'SCREENALIGNMENT')
BEGIN
	ALTER TABLE RESTAURANTSTATION ADD SCREENALIGNMENT INT NULL
END
GO