/*

	Incident No.	: XXX
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS Retail .NET 2013\Mars
	Date created	: 26.11.2012

	Description		: Add new tables for kitchen display profiles

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: KITCHENDISPLAYFUNCTIONALPROFILE, KITCHENDISPLAYSTYLEPROFILE, KITCHENDISPLAYVISUALPROFILE
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYFUNCTIONALPROFILE'))
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYFUNCTIONALPROFILE (
		[ID] [uniqueidentifier] NOT NULL,
		[NAME]  [nvarchar](100) NOT NULL,
		[BUMPOPERATION] int NOT NULL,
		[ONVOID] int NOT NULL,
		[SHOWBUMPED] int NOT NULL,
		[BUTTONSMENUID] nvarchar(20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
		)

		Alter table KITCHENDISPLAYFUNCTIONALPROFILE Add CONSTRAINT  PK_KITCHENDISPLAYFUNCTIONALPROFILE Primary Key (ID,DATAAREAID)
	END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYSTYLEPROFILE'))
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYSTYLEPROFILE (
		[ID] [uniqueidentifier] NOT NULL,
		[NAME]  [nvarchar](100) NOT NULL,
		[ORDERSTYLEID] [nvarchar](20) NULL,
		[ORDERPANESTYLEID] [nvarchar](20)  NULL,
		[BUTTONPANESTYLEID] [nvarchar](20)  NULL,
		[ITEMDEFAULTSTYLEID] [nvarchar](20)  NULL,
		[BUMPEDSTYLEID] [nvarchar](20)  NULL,
		[STARTEDSTYLEID] [nvarchar](20)  NULL,
		[MODIFIEDITEMSTYLEID] [nvarchar](20)  NULL,
		[NORMALITEMMODIFIERSTYLEID] [nvarchar](20)  NULL,
		[INCREASEITEMMODIFIERSTYLEID] [nvarchar](20)  NULL,
		[DECREASEITEMMODIFIERSTYLEID] [nvarchar](20)  NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
		)

		Alter table KITCHENDISPLAYSTYLEPROFILE Add CONSTRAINT  PK_KITCHENDISPLAYSTYLEPROFILE Primary Key (ID,DATAAREAID)
	END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILE'))
	BEGIN
		CREATE TABLE [dbo].KITCHENDISPLAYVISUALPROFILE (
		ID [uniqueidentifier] NOT NULL,
		NAME nvarchar(100) NOT NULL,
		ORDERPANEWIDTH  numeric(24,6) NOT NULL,
		ORDERPANEHEIGHT  numeric(24,6) NOT NULL,
		ORDERPANEX  numeric(24,6) NOT NULL,
		ORDERPANEY   numeric(24,6) NOT NULL,
		ORDERPANEVISIBLE tinyInt NOT NULL,
		BUTTONPANEWIDTH   numeric(24,6) NOT NULL,
		BUTTONPANEHEIGHT   numeric(24,6) NOT NULL,
		BUTTONPANEX numeric(24,6) NOT NULL,
		BUTTONPANEY numeric(24,6) NOT NULL,
		BUTTONPANEVISIBLE tinyInt NOT NULL,
		FLOWPATH int NOT NULL,
		TOPLEFT int NOT NULL,
		TOPCENTER int NOT NULL,
		TOPRIGHT  int NOT NULL,
		BOTTOMLEFT  int NOT NULL,
		BOTTOMRIGHT  int NOT NULL,
		BOTTOMCENTER int NOT NULL,
		NUMBEROFCOLUMNS  int NOT NULL,
		NUMBEROFROWS int NOT NULL,
		TOPLEFTCUSTOMSTRING nvarchar(50) NULL,
		TOPCENTERCUSTOMSTRING  nvarchar(50) NULL,
		TOPRIGHTCUSTOMSTRING  nvarchar(50) NULL,
		BOTTOMLEFTCUSTOMSTRING  nvarchar(50) NULL,
		BOTTOMCENTERCUSTOMSTRING  nvarchar(50) NULL,
		BOTTOMRIGHTCUSTOMSTRING  nvarchar(50) NULL,
		TIMEFORMAT  nvarchar(10) NULL,
		ITEMMODIFIERINCREASEPREFIX nvarchar(30) NULL,
		ITEMMODIFIERDECREASEPREFIX  nvarchar(30) NULL,
		ITEMMODIFIERNORMALPREFIX  nvarchar(30) NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
		)

		Alter table KITCHENDISPLAYVISUALPROFILE Add CONSTRAINT  PK_KITCHENDISPLAYVISUALPROFILE Primary Key (ID,DATAAREAID)
	END
GO