/*

	Incident No.	: XXX
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS Retail .NET 2013\Jupiter
	Date created	: 11.12.2012

	Description		: Remove columns 
						TOPLEFTCUSTOMSTRING,
						TOPCENTERCUSTOMSTRING,
						TOPRIGHTCUSTOMSTRING,
						BOTTOMLEFTCUSTOMSTRING,
						BOTTOMCENTERCUSTOMSTRING,
						BOTTOMRIGHTCUSTOMSTRING
					  from table KITCHENDISPLAYVISUALPROFILE
	
	
	Tables affected	: KITCHENDISPLAYVISUALPROFILE					
*/


USE LSPOSNET
GO
  
IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILE') AND NAME='TOPLEFTCUSTOMSTRING')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE Drop Column TOPLEFTCUSTOMSTRING 
END	

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILE') AND NAME='TOPCENTERCUSTOMSTRING')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE Drop Column  TOPCENTERCUSTOMSTRING
END	

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILE') AND NAME='TOPRIGHTCUSTOMSTRING')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE Drop Column  TOPRIGHTCUSTOMSTRING
END	

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILE') AND NAME='BOTTOMLEFTCUSTOMSTRING')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE Drop Column  BOTTOMLEFTCUSTOMSTRING
END	

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILE') AND NAME='BOTTOMCENTERCUSTOMSTRING')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE Drop Column  BOTTOMCENTERCUSTOMSTRING
END	

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILE') AND NAME='BOTTOMRIGHTCUSTOMSTRING')
BEGIN
	ALTER TABLE KITCHENDISPLAYVISUALPROFILE Drop Column  BOTTOMRIGHTCUSTOMSTRING
END	
