/*

	Incident No.	: XXX
	Responsible		: Óskar Bjarnason
	Sprint			: LS Retail .NET 2013\Earth
	Date created	: 01.10.2012

	Description		: Adding the tables; RBOTERMINALGROUPCONNECTION and RBOTERMINALGROUP
	
	
	Tables affected	: RBOTERMINALGROUPCONNECTION and RBOTERMINALGROUP
						
*/
USE LSPOSNET
GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTERMINALGROUPCONNECTION'))
BEGIN
	Drop table RBOTERMINALGROUPCONNECTION
END
GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTERMINALGROUP'))
BEGIN
	Drop table RBOTERMINALGROUP
END
GO
  
  
IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'RBOTERMINALGROUPCONNECTION')
BEGIN

	CREATE TABLE dbo.RBOTERMINALGROUPCONNECTION(
	TERMINALGROUPID nvarchar(40) NOT NULL,
	TERMINALID nvarchar(20) NOT NULL,
	DATAAREAID nvarchar(4) NOT NULL
	)ON [PRIMARY]

	alter table dbo.RBOTERMINALGROUPCONNECTION ADD CONSTRAINT
	PK_RBOTERMINALGROUPTERMINALS PRIMARY KEY CLUSTERED 
	(
		TERMINALGROUPID ASC,
		TERMINALID ASC,
		DATAAREAID ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
END





IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'RBOTERMINALGROUP')
BEGIN
CREATE TABLE dbo.RBOTERMINALGROUP
	(
	ID nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(250) NOT NULL,
	DATAAREAID nvarchar(4) NOT NULL
	)ON [PRIMARY]

 alter table dbo.RBOTERMINALGROUP add CONSTRAINT PK_RBOTERMINALGROUP PRIMARY KEY CLUSTERED 
	(
		ID ASC,
		DATAAREAID ASC
	)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

end
GO

