/*
	Description		: Adding Store Id to INVENTJOURNALTABLE
*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('INVENTJOURNALTABLE') AND NAME='STOREID')
BEGIN
	 ALTER TABLE INVENTJOURNALTABLE Add STOREID NVARCHAR(20) NULL 
END	
GO
