/*

	Incident No.	: XXX
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS Retail .NET 2013\Jupiter
	Date created	: 12.12.2012

	Description		: Renaming tables 
						KMBUTTONOPERATIONS,
						KMLOG,
						KMTIMESTYLE,
						KMTRANSACTIONPROFILE
	
	
	Tables affected	: KMBUTTONOPERATIONS, KMLOG, KMTIMESTYLE, KMTRANSACTIONPROFILE			
*/


USE LSPOSNET
GO
  
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYBUTTONOPERATIONS'))
BEGIN
	EXEC SP_RENAME 'KMBUTTONOPERATIONS', 'KITCHENDISPLAYBUTTONOPERATIONS'
	EXEC sp_rename 'KITCHENDISPLAYBUTTONOPERATIONS.PK_KMBUTTONOPERATIONS', 'PK_KITCHENDISPLAYBUTTONOPERATIONS';
END	
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYLOG'))
BEGIN
	EXEC SP_RENAME 'KMLOG', 'KITCHENDISPLAYLOG'
	EXEC sp_rename 'KITCHENDISPLAYLOG.PK_KMLOG', 'PK_KITCHENDISPLAYLOG';
END	
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYTIMESTYLE'))
BEGIN
	EXEC SP_RENAME 'KMTIMESTYLE', 'KITCHENDISPLAYTIMESTYLE'
	EXEC sp_rename 'KITCHENDISPLAYTIMESTYLE.PK_KMTIMESTYLE', 'PK_KITCHENDISPLAYTIMESTYLE';
END	
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYTRANSACTIONPROFILE'))
BEGIN
	EXEC SP_RENAME 'KMTRANSACTIONPROFILE', 'KITCHENDISPLAYTRANSACTIONPROFILE'
	EXEC sp_rename 'KITCHENDISPLAYTRANSACTIONPROFILE.PK_KMTRANSACTIONPROFILE', 'PK_KITCHENDISPLAYTRANSACTIONPROFILE';
END	
