/*

	Incident No.	: XXX
	Responsible		: Gudbjorn Einarsson
	Sprint			: LS Retail .NET 2013\Jupiter
	Date created	: 13.12.2012

	Description		: Changing the primary key of KITCHENDISPLAYTIMESTYLE
	
	
	Tables affected	: KITCHENDISPLAYTIMESTYLE		
*/


USE LSPOSNET
GO

-- Drop old primary key
IF EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND CONSTRAINT_NAME = 'PK_KITCHENDISPLAYTIMESTYLE')
Begin
	Alter Table KITCHENDISPLAYTIMESTYLE
	DROP CONSTRAINT PK_KITCHENDISPLAYTIMESTYLE
End
GO

-- Delete old primary key column
IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYTIMESTYLE') AND NAME='ID')
BEGIN
	 Alter table KITCHENDISPLAYTIMESTYLE
	 Drop Column ID
END	

GO

-- Make the KDSTYLEPROFILEID column not nullable
IF EXISTS (select 'X' FROM SYSCOLUMNS WHERE ID=object_id('KITCHENDISPLAYTIMESTYLE') AND NAME = 'KDSTYLEPROFILEID' AND ISNULLABLE = '1')
Begin
	UPDATE KITCHENDISPLAYTIMESTYLE SET KDSTYLEPROFILEID=NEWID() WHERE KDSTYLEPROFILEID IS NULL
	Alter Table KITCHENDISPLAYTIMESTYLE
	Alter Column KDSTYLEPROFILEID UniqueIdentifier NOT NULL
End
GO

-- Create the new primary key
IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'KITCHENDISPLAYTIMESTYLE' AND CONSTRAINT_NAME = 'PK_KITCHENDISPLAYTIMESTYLE')
Begin
	ALTER TABLE KITCHENDISPLAYTIMESTYLE
	ADD CONSTRAINT PK_KITCHENDISPLAYTIMESTYLE PRIMARY KEY (KDSTYLEPROFILEID, SECONDSPASSED, DATAAREAID)
End
GO