/*
	Description		: Adding REPLICATIONCOUNTER to KITCHENDISPLAYLOG
*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYLOG') AND NAME='REPLICATIONCOUNTER')
BEGIN
	 ALTER TABLE KITCHENDISPLAYLOG Add REPLICATIONCOUNTER INT NOT NULL IDENTITY 
END	
GO
