/*
	Description		: Changing length of PRINTERDEVICENAME in POSHARDWAREPROFILE 
*/

USE LSPOSNET

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'PRINTERDEVICENAME') = 30)
begin
	ALTER TABLE POSHARDWAREPROFILE ALTER COLUMN PRINTERDEVICENAME [nvarchar](200) NULL
end