/*
	Description		: Adding DISPLAYBALANCEWITHTAX to RBOSTORETABLE
*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETABLE') AND NAME='DISPLAYBALANCEWITHTAX')
BEGIN
	 ALTER TABLE RBOSTORETABLE Add DISPLAYBALANCEWITHTAX TINYINT NULL
END	
GO
