USE LSPOSNET

 if not exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'POSISFORMLAYOUT' and COLUMN_NAME = 'DEFAULTFORMWIDTH')
begin
	alter table POSISFORMLAYOUT add DEFAULTFORMWIDTH INT
end