/*
	Description		: Adding Token login support 
*/

USE LSPOSNET

IF NOT EXISTS (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'USERLOGINTOKENS')
BEGIN

	CREATE TABLE dbo.USERLOGINTOKENS(
	[GUID] uniqueidentifier NOT NULL,
	USERGUID uniqueidentifier NOT NULL,
	[DESCRIPTION] nvarchar(40) NOT NULL,
	[HASH] nvarchar(40) NOT NULL,
	DATAAREAID nvarchar(4) NOT NULL
	)ON [PRIMARY]

	alter table dbo.USERLOGINTOKENS ADD CONSTRAINT
	PK_USERLOGINTOKENS PRIMARY KEY CLUSTERED 
	(
		[GUID] ASC,
		USERGUID ASC,
		DATAAREAID ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

	CREATE UNIQUE NONCLUSTERED INDEX IX_USERLOGINTOKENS_HASH ON dbo.USERLOGINTOKENS (HASH) 
	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

END
