/*
	Description		: Changing length of PRINTERDESCRIPTION in POSHARDWAREPROFILE 
*/

USE LSPOSNET

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'PRINTERDESCRIPTION') = 30)
begin
	ALTER TABLE POSHARDWAREPROFILE ALTER COLUMN PRINTERDESCRIPTION [nvarchar](200) NULL
end