/*
	Description		: Adding USETAXROUNTING to RBOSTORETABLE
*/

USE LSPOSNET

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETABLE') AND NAME='USETAXROUNDING')
BEGIN
	 ALTER TABLE RBOSTORETABLE Add USETAXROUNDING TINYINT NULL
END	
GO
