USE LSPOSNET

 if not exists (select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'KITCHENDISPLAYLOG' and COLUMN_NAME = 'STOREID')
begin
	alter table KITCHENDISPLAYLOG add STOREID NVARCHAR(20)
end