USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('INVENTORYTRANSFERORDER') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE INVENTORYTRANSFERORDER(
		ID nvarchar(20) NOT NULL,
		INVENTORYTRANSFERREQUESTID nvarchar(20) NULL,
		SENDINGSTOREID nvarchar(20) NOT NULL,
		RECEIVINGSTOREID nvarchar(20) NOT NULL,
		CREATIONDATE dateTime NOT NULL,
		RECEIVINGDATE dateTime NULL,
		SENTDATE dateTime NULL,
		[RECEIVED] bit NOT NULL,
		[SENT] bit NOT NULL,
		FETCHEDBYRECEIVINGSTORE bit NOT NULL,
		DATAAREAID nvarchar(4) NOT NULL
		)

	Alter table INVENTORYTRANSFERORDER Add CONSTRAINT  PK_INVENTORYTRANSFERORDER Primary Key (ID, DATAAREAID)
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('INVENTORYTRANSFERORDERLINE') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE INVENTORYTRANSFERORDERLINE(
		ID uniqueIdentifier NOT NULL,
		INVENTORYTRANSFERORDERID nvarchar(20) NOT NULL,
		ITEMID nvarchar(20) NOT NULL,
		VARIANTID nvarchar(20) NULL,
		UNITID  nvarchar(20) NOT NULL,
		QUANTITYSENT numeric(24,6) NULL,
		QUANTITYRECEIVED numeric(24,6) null,
		SENT bit NOT NULL,
		DATAAREAID nvarchar(4) NOT NULL
		)

	Alter table INVENTORYTRANSFERORDERLINE Add CONSTRAINT  PK_INVENTORYTRANSFERORDERLINE Primary Key (ID, DATAAREAID)
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('INVENTORYTRANSFERREQUEST') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE INVENTORYTRANSFERREQUEST(
		ID nvarchar(20) NOT NULL,
		SENDINGSTOREID nvarchar(20) NOT NULL,
		RECEIVINGSTOREID nvarchar(20) NOT NULL,
		CREATIONDATE dateTime NOT NULL,
		SENTDATE dateTime NULL,
		SENT bit not null,
		FETCHEDBYRECEIVINGSTORE bit not null,
		INVENTORYTRANSFERCREATED bit not null,
		DATAAREAID nvarchar(4) NOT NULL
		)

	Alter table INVENTORYTRANSFERREQUEST Add CONSTRAINT  PK_INVENTORYTRANSFERREQUEST Primary Key (ID, DATAAREAID)
END
GO
	
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('INVENTORYTRANSFERREQUESTLINE') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE INVENTORYTRANSFERREQUESTLINE(
		ID uniqueIdentifier NOT NULL,
		INVENTORYTRANSFERREQUESTID nvarchar(20) NOT NULL,
		ITEMID nvarchar(20) NOT NULL,
		VARIANTID nvarchar(20) NULL,
		UNITID  nvarchar(20) NOT NULL,
		QUANTITYREQUESTED numeric(24,6) NOT NULL,
		SENT bit NOT NULL,
		DATAAREAID nvarchar(4) NOT NULL
		)

	Alter table INVENTORYTRANSFERREQUESTLINE Add CONSTRAINT  PK_INVENTORYTRANSFERREQUESTLINE Primary Key (ID, DATAAREAID)
END
GO