/*

	Incident No.	: 18752
	Responsible		: Erna Guðrún Sigurðardóttir
	Sprint			: LS Retail .NET 2013\Neptune
	Date created	: 11.02.2013

	Description		: Added column ORDERTIMESTART
	
	
	Tables affected	: KITCHENDISPLAYVISUALPROFILE
						
*/
USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KITCHENDISPLAYVISUALPROFILE') AND NAME='ORDERTIMESTART')
BEGIN
	 ALTER TABLE KITCHENDISPLAYVISUALPROFILE Add ORDERTIMESTART int NULL 
END	
GO