USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTTABLE' AND COLUMN_NAME = 'LOYALTYCUSTOMER')
BEGIN
	ALTER TABLE CUSTTABLE ADD LOYALTYCUSTOMER tinyint NULL
END
GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTLOYALTYPARAMETERS'))
BEGIN
	CREATE TABLE [CUSTLOYALTYPARAMETERS](
	[KEY_] [int] NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[DATASOURCE] [int] NULL,
	[FILTERSTORE] [nvarchar](20) NULL,
	[FILTERTERMINAL] [nvarchar](20) NULL,
	[FILTERLOYALTYSCHEME] [nvarchar](20) NULL,
	 CONSTRAINT [PK_CUSTLOYALTYPARAMETERS] PRIMARY KEY CLUSTERED 
	(
	[KEY_] ASC,
	[DATAAREAID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOLOYALTYMSRCARDTRANS'))
BEGIN
	DROP TABLE [dbo].[RBOLOYALTYMSRCARDTRANS]
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOLOYALTYTRANS'))
BEGIN

CREATE TABLE [dbo].[RBOLOYALTYTRANS](
	[TRANSACTIONID] [nvarchar](20) NULL,
	[LINENUM] [numeric](28, 12) NOT NULL,
	[RECEIPTID] [nvarchar](20) NULL,
	[POINTS] [numeric](28, 12) NULL,
	[DATEOFISSUE] [datetime] NULL,
	[STOREID] [nvarchar](20) NULL,
	[TERMINALID] [nvarchar](20) NULL,
	[CARDNUMBER] [nvarchar](30) NOT NULL,
	[SEQUENCENUMBER] [int] NULL,
	[LOYALTYCUSTID] [nvarchar](20) NULL,
	[ENTRYTYPE] [int] NULL,
	[EXPIRATIONDATE] [datetime] NULL,
	[LOYALTYSCHEMEID] [nvarchar](20) NULL,
	[STATEMENTID] [nvarchar](20) NULL,
	[STATEMENTCODE] [nvarchar](10) NULL,
	[STAFFID] [nvarchar](20) NULL,
	[LOYALTYPOINTTRANSLINENUM] [numeric](28, 12) NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDTIME] [int] NULL,
	[MODIFIEDBY] [uniqueidentifier] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDTIME] [int] NULL,
	[CREATEDBY] [uniqueidentifier] NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[TYPE] [int] NULL,
	[REMAININGPOINTS] [numeric](28, 12) NULL,
	[STATUS] [tinyint] NULL,
 CONSTRAINT [I_20293CARDNUMBERIDX] PRIMARY KEY NONCLUSTERED 
(
	[DATAAREAID] ASC,
	[CARDNUMBER] ASC,
	[LINENUM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__TRANS__46693276]  DEFAULT ('') FOR [TRANSACTIONID]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__LINEN__475D56AF]  DEFAULT ((0)) FOR [LINENUM]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__RECEI__48517AE8]  DEFAULT ('') FOR [RECEIPTID]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__POINT__49459F21]  DEFAULT ((0)) FOR [POINTS]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__DATEO__4A39C35A]  DEFAULT ('1900-01-01 00:00:00.000') FOR [DATEOFISSUE]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__STORE__4B2DE793]  DEFAULT ('') FOR [STOREID]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__TERMI__4C220BCC]  DEFAULT ('') FOR [TERMINALID]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__CARDN__4D163005]  DEFAULT ('') FOR [CARDNUMBER]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__SEQUE__4E0A543E]  DEFAULT ((0)) FOR [SEQUENCENUMBER]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__LOYAL__4EFE7877]  DEFAULT ('') FOR [LOYALTYCUSTID]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__ENTRY__4FF29CB0]  DEFAULT ((0)) FOR [ENTRYTYPE]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__EXPIR__50E6C0E9]  DEFAULT ('1900-01-01 00:00:00.000') FOR [EXPIRATIONDATE]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__LOYAL__51DAE522]  DEFAULT ('') FOR [LOYALTYSCHEMEID]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__STATE__52CF095B]  DEFAULT ('') FOR [STATEMENTID]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__STATE__53C32D94]  DEFAULT ('') FOR [STATEMENTCODE]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__STAFF__54B751CD]  DEFAULT ('') FOR [STAFFID]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__LOYAL__55AB7606]  DEFAULT ((0)) FOR [LOYALTYPOINTTRANSLINENUM]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__MODIF__569F9A3F]  DEFAULT ('1900-01-01 00:00:00.000') FOR [MODIFIEDDATE]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__MODIF__5793BE78]  DEFAULT ((0)) FOR [MODIFIEDTIME]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__MODIF__5887E2B1]  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [MODIFIEDBY]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__CREAT__597C06EA]  DEFAULT ('1900-01-01 00:00:00.000') FOR [CREATEDDATE]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__CREAT__5A702B23]  DEFAULT ((0)) FOR [CREATEDTIME]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__CREAT__5B644F5C]  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [CREATEDBY]
ALTER TABLE [dbo].[RBOLOYALTYTRANS] ADD  CONSTRAINT [DF__RBOLOYALT__DATAA__5C587395]  DEFAULT ('LSR') FOR [DATAAREAID]
END
GO


IF NOT EXISTS (SELECT * FROM sys.indexes where [object_id] = object_id('RBOLOYALTYTRANS') and name = 'LoyaltyCustID')
BEGIN
	CREATE NONCLUSTERED INDEX [LoyaltyCustID] ON [dbo].[RBOLOYALTYTRANS] ([LOYALTYCUSTID] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOLOYALTYSCHEMESTABLE' AND COLUMN_NAME = 'USELIMIT')
BEGIN
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ADD USELIMIT int NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOLOYALTYSCHEMESTABLE' AND COLUMN_NAME = 'MODIFIEDBY' AND DATA_TYPE = 'uniqueidentifier')
BEGIN
	UPDATE RBOLOYALTYSCHEMESTABLE SET MODIFIEDBY = null; 	
	IF EXISTS (SELECT OBJECT_ID('DF__RBOLOYALT__MODIF__0A1F3E45'))
	ALTER TABLE RBOLOYALTYSCHEMESTABLE DROP CONSTRAINT DF__RBOLOYALT__MODIF__0A1F3E45; 
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ALTER COLUMN MODIFIEDBY uniqueidentifier;
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ADD  CONSTRAINT DF__RBOLOYALT__MODIF__0A1F3E45  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [MODIFIEDBY]
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOLOYALTYSCHEMESTABLE' AND COLUMN_NAME = 'CREATEDBY' AND DATA_TYPE = 'uniqueidentifier')
BEGIN

	UPDATE RBOLOYALTYSCHEMESTABLE SET CREATEDBY = null;	 
	IF EXISTS (SELECT OBJECT_ID('DF__RBOLOYALT__CREAT__0CFBAAF0'))
	ALTER TABLE RBOLOYALTYSCHEMESTABLE DROP CONSTRAINT DF__RBOLOYALT__CREAT__0CFBAAF0; 
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ALTER COLUMN CREATEDBY uniqueidentifier; 
	ALTER TABLE RBOLOYALTYSCHEMESTABLE ADD  CONSTRAINT DF__RBOLOYALT__CREAT__0CFBAAF0  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [CREATEDBY]
	
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOLOYALTYMSRCARDTABLE' AND COLUMN_NAME = 'MODIFIEDBY' AND DATA_TYPE = 'uniqueidentifier')
BEGIN
	UPDATE RBOLOYALTYMSRCARDTABLE SET MODIFIEDBY = null; 	
	IF EXISTS (SELECT OBJECT_ID('DF__RBOLOYALT__MODIF__3DD3EC75'))
	ALTER TABLE RBOLOYALTYMSRCARDTABLE DROP CONSTRAINT DF__RBOLOYALT__MODIF__3DD3EC75; 
	ALTER TABLE RBOLOYALTYMSRCARDTABLE ALTER COLUMN MODIFIEDBY uniqueidentifier;
	ALTER TABLE RBOLOYALTYMSRCARDTABLE ADD  CONSTRAINT DF__RBOLOYALT__MODIF__3DD3EC75  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [MODIFIEDBY]
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOLOYALTYMSRCARDTABLE' AND COLUMN_NAME = 'CREATEDBY' AND DATA_TYPE = 'uniqueidentifier')
BEGIN

	UPDATE RBOLOYALTYMSRCARDTABLE SET CREATEDBY = null;	 
	IF EXISTS (SELECT OBJECT_ID('DF__RBOLOYALT__CREAT__40B05920'))
	ALTER TABLE RBOLOYALTYMSRCARDTABLE DROP CONSTRAINT DF__RBOLOYALT__CREAT__40B05920; 
	ALTER TABLE RBOLOYALTYMSRCARDTABLE ALTER COLUMN CREATEDBY uniqueidentifier; 
	ALTER TABLE RBOLOYALTYMSRCARDTABLE ADD  CONSTRAINT DF__RBOLOYALT__CREAT__40B05920  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [CREATEDBY]
	
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOLOYALTYMSRCARDTABLE' AND COLUMN_NAME = 'STARTINGPOINTS')
BEGIN
	ALTER TABLE RBOLOYALTYMSRCARDTABLE ADD STARTINGPOINTS [numeric](28, 12) NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONLOYALTYPOINTTRANS' AND COLUMN_NAME = 'MODIFIEDBY' AND DATA_TYPE = 'uniqueidentifier')
BEGIN
	UPDATE RBOTRANSACTIONLOYALTYPOINTTRANS SET MODIFIEDBY = null; 	
	IF EXISTS (SELECT OBJECT_ID('DF__RBOTRANSA__MODIF__23DF1048'))
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS DROP CONSTRAINT DF__RBOTRANSA__MODIF__23DF1048; 
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN MODIFIEDBY uniqueidentifier;
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ADD  CONSTRAINT DF__RBOTRANSA__MODIF__23DF1048  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [MODIFIEDBY]
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONLOYALTYPOINTTRANS' AND COLUMN_NAME = 'CREATEDBY' AND DATA_TYPE = 'uniqueidentifier')
BEGIN

	UPDATE RBOTRANSACTIONLOYALTYPOINTTRANS SET CREATEDBY = null;	 
	IF EXISTS (SELECT OBJECT_ID('DF__RBOTRANSA__CREAT__26BB7CF3'))
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS DROP CONSTRAINT DF__RBOTRANSA__CREAT__26BB7CF3; 
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ALTER COLUMN CREATEDBY uniqueidentifier; 
	ALTER TABLE RBOTRANSACTIONLOYALTYPOINTTRANS ADD  CONSTRAINT DF__RBOTRANSA__CREAT__26BB7CF3  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [CREATEDBY]
	
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOLOYALTYPOINTSTABLE' AND COLUMN_NAME = 'LOYALTYRULEID')
BEGIN

DROP TABLE [dbo].[RBOLOYALTYPOINTSTABLE]

CREATE TABLE [dbo].[RBOLOYALTYPOINTSTABLE](
	[LOYALTYSCHEMEID] [nvarchar](20) NOT NULL,
	[LOYALTYRULEID] [uniqueidentifier] NOT NULL,
	[TYPE] [int] NOT NULL,
	[SCHEMERELATION] [nvarchar](20) NOT NULL,
	[QTYAMOUNTLIMIT] [numeric](28, 12) NOT NULL,
	[POINTS] [numeric](28, 12) NULL,
	[CUSTOMERGROUP_EDIT] [nvarchar](20) NULL,
	[CONTACTSEGMENT_EDIT] [nvarchar](20) NULL,
	[BASECALCULATIONON] [int] NOT NULL,
	[STARTINGDATE] [datetime] NOT NULL,
	[ENDINGDATE] [datetime] NOT NULL,
	[MODIFIEDDATE] [datetime] NULL,
	[MODIFIEDTIME] [int] NULL,
	[MODIFIEDBY] [uniqueidentifier] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDTIME] [int] NULL,
	[CREATEDBY] [uniqueidentifier] NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
 CONSTRAINT [I_20294LOYALTYPOINTSIDXS] PRIMARY KEY NONCLUSTERED 
(
	[DATAAREAID] ASC,
	[LOYALTYSCHEMEID] ASC,
	[LOYALTYRULEID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__LOYAL__611D28B2]  DEFAULT ('') FOR [LOYALTYSCHEMEID]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALTY__TYPE__62114CEB]  DEFAULT ((0)) FOR [TYPE]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__SCHEM__63057124]  DEFAULT ('') FOR [SCHEMERELATION]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__QTYAM__63F9955D]  DEFAULT ((0)) FOR [QTYAMOUNTLIMIT]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__POINT__64EDB996]  DEFAULT ((0)) FOR [POINTS]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__CUSTO__65E1DDCF]  DEFAULT ('') FOR [CUSTOMERGROUP_EDIT]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__CONTA__66D60208]  DEFAULT ('') FOR [CONTACTSEGMENT_EDIT]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__BASEC__67CA2641]  DEFAULT ((0)) FOR [BASECALCULATIONON]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__START__68BE4A7A]  DEFAULT ('1900-01-01 00:00:00.000') FOR [STARTINGDATE]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__ENDIN__69B26EB3]  DEFAULT ('1900-01-01 00:00:00.000') FOR [ENDINGDATE]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__MODIF__6AA692EC]  DEFAULT ('1900-01-01 00:00:00.000') FOR [MODIFIEDDATE]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__MODIF__6B9AB725]  DEFAULT ((0)) FOR [MODIFIEDTIME]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__MODIF__6C8EDB5E]  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [MODIFIEDBY]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__CREAT__6D82FF97]  DEFAULT ('1900-01-01 00:00:00.000') FOR [CREATEDDATE]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__CREAT__6E7723D0]  DEFAULT ((0)) FOR [CREATEDTIME]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__CREAT__6F6B4809]  DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [CREATEDBY]

ALTER TABLE [dbo].[RBOLOYALTYPOINTSTABLE] ADD  CONSTRAINT [DF__RBOLOYALT__DATAA__705F6C42]  DEFAULT ('LSR') FOR [DATAAREAID]

END
GO

IF NOT EXISTS(SELECT * FROM PERMISSIONGROUP WHERE [GUID] = '2c562010-f660-11e0-be50-0800200c9a66')
	Insert into PERMISSIONGROUP (GUID,Name,DATAAREAID) 
	values ('2c562010-f660-11e0-be50-0800200c9a66','Loyalty permissions','LSR');


IF NOT EXISTS(SELECT * FROM [dbo].[CUSTLOYALTYPARAMETERS] WHERE [KEY_]=0 AND [DATAAREAID]='LSR')
	INSERT [dbo].[CUSTLOYALTYPARAMETERS] ([KEY_], [DATAAREAID], [DATASOURCE], [FILTERSTORE], [FILTERTERMINAL], [FILTERLOYALTYSCHEME]) VALUES (0, N'LSR', 0, NULL, NULL, NULL)
GO