USE LSPOSNET

GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'INVENTORYTRANSFERORDER' AND COLUMN_NAME = 'CREATEDBY')
BEGIN
ALTER TABLE INVENTORYTRANSFERORDER ADD CREATEDBY NVARCHAR(20) NOT NULL DEFAULT ''
END

GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'INVENTORYTRANSFERREQUEST' AND COLUMN_NAME = 'CREATEDBY')
BEGIN
ALTER TABLE INVENTORYTRANSFERREQUEST ADD CREATEDBY NVARCHAR(20) NOT NULL DEFAULT ''
END

GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'INVENTORYTRANSFERREQUEST' AND COLUMN_NAME = 'INVENTORYTRANSFERORDERID')
BEGIN
ALTER TABLE INVENTORYTRANSFERREQUEST ADD INVENTORYTRANSFERORDERID NVARCHAR(20)
END

GO

