USE LSPOSNET

GO

IF NOT EXISTS(select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'RBOSTORETENDERTYPETABLE' AND COLUMN_NAME = 'BLINDRECOUNTALLOWED')
BEGIN
ALTER TABLE RBOSTORETENDERTYPETABLE ADD BLINDRECOUNTALLOWED tinyint NULL
END

GO
