/*

	Incident No.	: 21811
	Responsible		: Sigfus Johannesson
	Sprint			: LS Retail .NET 2013\Pluto
	Date created	: 21.03.2013

	Description		: Changed from propper casing to regular casing
	
	Tables affected	: POSISOPERATIONS
						
*/
USE LSPOSNET

GO

IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'No Operation' collate Latin1_General_CS_AS and OPERATIONID = '0')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'No operation'
WHERE OPERATIONID = '0'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Item Sale' collate Latin1_General_CS_AS and OPERATIONID = '100')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Item sale'
WHERE OPERATIONID = '100'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Price Check' collate Latin1_General_CS_AS and OPERATIONID = '101')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Price check'
WHERE OPERATIONID = '101'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Void Item' collate Latin1_General_CS_AS and OPERATIONID = '102')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Void item'
WHERE OPERATIONID = '102'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Item Comment' collate Latin1_General_CS_AS and OPERATIONID = '103')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Item comment'
WHERE OPERATIONID = '103'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Price Override' collate Latin1_General_CS_AS and OPERATIONID = '104')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Price override'
WHERE OPERATIONID = '104'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Set Qty' collate Latin1_General_CS_AS and OPERATIONID = '105')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Set qty'
WHERE OPERATIONID = '105'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Clear Qty' collate Latin1_General_CS_AS and OPERATIONID = '106')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Clear qty'
WHERE OPERATIONID = '106'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Item Search' collate Latin1_General_CS_AS and OPERATIONID = '108')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Item search'
WHERE OPERATIONID = '108'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Return Item' collate Latin1_General_CS_AS and OPERATIONID = '109')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Return item'
WHERE OPERATIONID = '109'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Weigh Item' collate Latin1_General_CS_AS and OPERATIONID = '110')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Weigh item'
WHERE OPERATIONID = '110'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Fuel Item Sale' collate Latin1_General_CS_AS and OPERATIONID = '111')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Fuel item sale'
WHERE OPERATIONID = '111'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Linked Items Add' collate Latin1_General_CS_AS and OPERATIONID = '112')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Linked items add'
WHERE OPERATIONID = '112'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Set Dimensions' collate Latin1_General_CS_AS and OPERATIONID = '113')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Set dimensions'
WHERE OPERATIONID = '113'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Return Transaction' collate Latin1_General_CS_AS and OPERATIONID = '114')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Return transaction'
WHERE OPERATIONID = '114'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Show Journal' collate Latin1_General_CS_AS and OPERATIONID = '115')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Show journal'
WHERE OPERATIONID = '115'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Loyalty Request' collate Latin1_General_CS_AS and OPERATIONID = '117')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Loyalty request'
WHERE OPERATIONID = '117'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Clear Salesperson' collate Latin1_General_CS_AS and OPERATIONID = '121')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Clear salesperson'
WHERE OPERATIONID = '121'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Invoice Comment' collate Latin1_General_CS_AS and OPERATIONID = '122')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Invoice comment'
WHERE OPERATIONID = '122'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Change Unit of Measure' collate Latin1_General_CS_AS and OPERATIONID = '123')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Change unit of measure'
WHERE OPERATIONID = '123'
END

IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Discount Voucher Add' collate Latin1_General_CS_AS and OPERATIONID = '127')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Discount voucher add'
WHERE OPERATIONID = '127'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Discount Voucher Remove' collate Latin1_General_CS_AS and OPERATIONID = '128')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Discount voucher remove'
WHERE OPERATIONID = '128'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Infocode On Request' collate Latin1_General_CS_AS and OPERATIONID = '129')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Infocode on request'
WHERE OPERATIONID = '129'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Clear Item Comments' collate Latin1_General_CS_AS and OPERATIONID = '130')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Clear item comments'
WHERE OPERATIONID = '130'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Change Item Comments' collate Latin1_General_CS_AS and OPERATIONID = '131')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Change item comments'
WHERE OPERATIONID = '131'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Cash' collate Latin1_General_CS_AS and OPERATIONID = '200')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay cash'
WHERE OPERATIONID = '200'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Card' collate Latin1_General_CS_AS and OPERATIONID = '201')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay card'
WHERE OPERATIONID = '201'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Customer Account' collate Latin1_General_CS_AS and OPERATIONID = '202')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay customer account'
WHERE OPERATIONID = '202'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Currency' collate Latin1_General_CS_AS and OPERATIONID = '203')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay currency'
WHERE OPERATIONID = '203'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Check' collate Latin1_General_CS_AS and OPERATIONID = '204')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay check'
WHERE OPERATIONID = '204'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Cash Quick' collate Latin1_General_CS_AS and OPERATIONID = '206')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay cash quick'
WHERE OPERATIONID = '206'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Loyalty' collate Latin1_General_CS_AS and OPERATIONID = '207')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay loyalty'
WHERE OPERATIONID = '207'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Corporate Card' collate Latin1_General_CS_AS and OPERATIONID = '208')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay corporate card'
WHERE OPERATIONID = '208'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Change Back' collate Latin1_General_CS_AS and OPERATIONID = '210')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Change back'
WHERE OPERATIONID = '210'
END

IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Void Payment' collate Latin1_General_CS_AS and OPERATIONID = '211')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Void payment'
WHERE OPERATIONID = '211'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Get Fleet Card Information' collate Latin1_General_CS_AS and OPERATIONID = '212')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Get fleet card information'
WHERE OPERATIONID = '212'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Credit Memo' collate Latin1_General_CS_AS and OPERATIONID = '213')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay credit memo'
WHERE OPERATIONID = '213'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pay Gift Card' collate Latin1_General_CS_AS and OPERATIONID = '214')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pay gift card'
WHERE OPERATIONID = '214'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Line Discount Amount' collate Latin1_General_CS_AS and OPERATIONID = '300')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Line discount amount'
WHERE OPERATIONID = '300'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Line Discount Percent' collate Latin1_General_CS_AS and OPERATIONID = '301')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Line discount percent'
WHERE OPERATIONID = '301'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Total Discount Amount' collate Latin1_General_CS_AS and OPERATIONID = '302')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Total discount amount'
WHERE OPERATIONID = '302'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Total Discount Percent' collate Latin1_General_CS_AS and OPERATIONID = '303')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Total discount percent'
WHERE OPERATIONID = '303'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Sub Menu' collate Latin1_General_CS_AS and OPERATIONID = '401')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Sub menu'
WHERE OPERATIONID = '401'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Void Transaction' collate Latin1_General_CS_AS and OPERATIONID = '500')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Void transaction'
WHERE OPERATIONID = '500'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Transaction Comment' collate Latin1_General_CS_AS and OPERATIONID = '501')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Transaction comment'
WHERE OPERATIONID = '501'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Sales Person' collate Latin1_General_CS_AS and OPERATIONID = '502')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Salesperson'
WHERE OPERATIONID = '502'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Suspend Transaction' collate Latin1_General_CS_AS and OPERATIONID = '503')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Suspend transaction'
WHERE OPERATIONID = '503'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Recall Transaction' collate Latin1_General_CS_AS and OPERATIONID = '504')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Recall transaction'
WHERE OPERATIONID = '504'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Recall Unconcluded Transaction' collate Latin1_General_CS_AS and OPERATIONID = '505')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Recall unconcluded transaction'
WHERE OPERATIONID = '505'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Card Swipe' collate Latin1_General_CS_AS and OPERATIONID = '506')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Card swipe'
WHERE OPERATIONID = '506'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pharmacy Prescription Cancel' collate Latin1_General_CS_AS and OPERATIONID = '508')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pharmacy prescription cancel'
WHERE OPERATIONID = '508'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Pharmacy Prescriptions' collate Latin1_General_CS_AS and OPERATIONID = '510')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Pharmacy prescriptions'
WHERE OPERATIONID = '510'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Issue Credit Memo' collate Latin1_General_CS_AS and OPERATIONID = '511')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Issue credit memo'
WHERE OPERATIONID = '511'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Issue Gift Card' collate Latin1_General_CS_AS and OPERATIONID = '512')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Issue gift card'
WHERE OPERATIONID = '512'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Display Total' collate Latin1_General_CS_AS and OPERATIONID = '513')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Display total'
WHERE OPERATIONID = '513'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Sales Order' collate Latin1_General_CS_AS and OPERATIONID = '515')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Sales order'
WHERE OPERATIONID = '515'
END

IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Sales Invoice' collate Latin1_General_CS_AS and OPERATIONID = '516')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Sales invoice'
WHERE OPERATIONID = '516'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Income Account' collate Latin1_General_CS_AS and OPERATIONID = '517')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Income account'
WHERE OPERATIONID = '517'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Expense Account' collate Latin1_General_CS_AS and OPERATIONID = '518')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Expense account'
WHERE OPERATIONID = '518'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Return Income Accounts' collate Latin1_General_CS_AS and OPERATIONID = '519')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Return income accounts'
WHERE OPERATIONID = '519'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Return Expense Accounts' collate Latin1_General_CS_AS and OPERATIONID = '520')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Return expense accounts'
WHERE OPERATIONID = '520'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Customer Search' collate Latin1_General_CS_AS and OPERATIONID = '602')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Customer search'
WHERE OPERATIONID = '602'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Customer Clear' collate Latin1_General_CS_AS and OPERATIONID = '603')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Customer clear'
WHERE OPERATIONID = '603'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Customer Transactions' collate Latin1_General_CS_AS and OPERATIONID = '609')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Customer transactions'
WHERE OPERATIONID = '609'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Customer Transactions Report' collate Latin1_General_CS_AS and OPERATIONID = '610')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Customer transactions report'
WHERE OPERATIONID = '610'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Customer Balance Report' collate Latin1_General_CS_AS and OPERATIONID = '611')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Customer balance report'
WHERE OPERATIONID = '611'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Customer Add' collate Latin1_General_CS_AS and OPERATIONID = '612')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Customer add'
WHERE OPERATIONID = '612'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Log Off' collate Latin1_General_CS_AS and OPERATIONID = '701')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Log off'
WHERE OPERATIONID = '701'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Change User' collate Latin1_General_CS_AS and OPERATIONID = '702')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Change user'
WHERE OPERATIONID = '702'
END

IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Lock Terminal' collate Latin1_General_CS_AS and OPERATIONID = '703')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Lock terminal'
WHERE OPERATIONID = '703'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Log Off Force' collate Latin1_General_CS_AS and OPERATIONID = '704')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Log off force'
WHERE OPERATIONID = '704'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Negative Adjustment' collate Latin1_General_CS_AS and OPERATIONID = '800')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Negative adjustment'
WHERE OPERATIONID = '800'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Inventory Lookup' collate Latin1_General_CS_AS and OPERATIONID = '801')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Inventory lookup'
WHERE OPERATIONID = '801'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Application Exit' collate Latin1_General_CS_AS and OPERATIONID = '900')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Application exit'
WHERE OPERATIONID = '900'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Initialize Z Report' collate Latin1_General_CS_AS and OPERATIONID = '902')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Initialize Z report'
WHERE OPERATIONID = '902'
END

IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Print X Per Day' collate Latin1_General_CS_AS and OPERATIONID = '903')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Print X per day'
WHERE OPERATIONID = '903'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Print Tax Free' collate Latin1_General_CS_AS and OPERATIONID = '906')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Print tax free'
WHERE OPERATIONID = '906'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Print Previous Slip' collate Latin1_General_CS_AS and OPERATIONID = '907')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Print previous slip'
WHERE OPERATIONID = '907'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Print Previous Invoice' collate Latin1_General_CS_AS and OPERATIONID = '908')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Print previous invoice'
WHERE OPERATIONID = '908'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Upload Printer Logo' collate Latin1_General_CS_AS and OPERATIONID = '909')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Upload printer logo'
WHERE OPERATIONID = '909'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Restart Computer' collate Latin1_General_CS_AS and OPERATIONID = '910')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Restart computer'
WHERE OPERATIONID = '910'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Shut Down Computer' collate Latin1_General_CS_AS and OPERATIONID = '911')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Shut down computer'
WHERE OPERATIONID = '911'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Design Mode Enable' collate Latin1_General_CS_AS and OPERATIONID = '912')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Design mode enable'
WHERE OPERATIONID = '912'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Design Mode disable' collate Latin1_General_CS_AS and OPERATIONID = '913')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Design mode disable'
WHERE OPERATIONID = '913'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Minimize POS Window' collate Latin1_General_CS_AS and OPERATIONID = '914')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Minimize POS window'
WHERE OPERATIONID = '914'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Blank Operation' collate Latin1_General_CS_AS and OPERATIONID = '915')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Blank operation'
WHERE OPERATIONID = '915'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Open Drawer' collate Latin1_General_CS_AS and OPERATIONID = '1000')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Open drawer'
WHERE OPERATIONID = '1000'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'End Of Day' collate Latin1_General_CS_AS and OPERATIONID = '1050')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'End of day'
WHERE OPERATIONID = '1050'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'End Of Shift' collate Latin1_General_CS_AS and OPERATIONID = '1051')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'End of shift'
WHERE OPERATIONID = '1051'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Tender Declaration' collate Latin1_General_CS_AS and OPERATIONID = '1052')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Tender declaration'
WHERE OPERATIONID = '1052'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Customer Account Deposit' collate Latin1_General_CS_AS and OPERATIONID = '1100')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Customer account deposit'
WHERE OPERATIONID = '1100'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Declare Start Amount' collate Latin1_General_CS_AS and OPERATIONID = '1200')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Declare start amount'
WHERE OPERATIONID = '1200'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Float Entry' collate Latin1_General_CS_AS and OPERATIONID = '1201')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Float entry'
WHERE OPERATIONID = '1201'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Tender Removal' collate Latin1_General_CS_AS and OPERATIONID = '1210')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Tender removal'
WHERE OPERATIONID = '1210'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Safe Drop' collate Latin1_General_CS_AS and OPERATIONID = '1211')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Safe drop'
WHERE OPERATIONID = '1211'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Bank Drop' collate Latin1_General_CS_AS and OPERATIONID = '1212')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Bank drop'
WHERE OPERATIONID = '1212'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Safe Drop Reversal' collate Latin1_General_CS_AS and OPERATIONID = '1213')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Safe drop reversal'
WHERE OPERATIONID = '1213'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Bank Drop Reversal' collate Latin1_General_CS_AS and OPERATIONID = '1214')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Bank drop reversal'
WHERE OPERATIONID = '1214'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Split Bill' collate Latin1_General_CS_AS and OPERATIONID = '1300')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Split bill'
WHERE OPERATIONID = '1300'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Exit Hospitality POS' collate Latin1_General_CS_AS and OPERATIONID = '1301')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Exit hospitality POS'
WHERE OPERATIONID = '1301'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Print Hospitality Menu Type' collate Latin1_General_CS_AS and OPERATIONID = '1302')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Print hospitality menu type'
WHERE OPERATIONID = '1302'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Set Hospitality Menu Type' collate Latin1_General_CS_AS and OPERATIONID = '1303')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Set hospitality menu type'
WHERE OPERATIONID = '1303'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Change Hospitality Menu Type' collate Latin1_General_CS_AS and OPERATIONID = '1304')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Change hospitality menu type'
WHERE OPERATIONID = '1304'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Tax Exempt Transaction' collate Latin1_General_CS_AS and OPERATIONID = '1400')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Tax exempt transaction'
WHERE OPERATIONID = '1400'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Clear Transaction Tax Exemption' collate Latin1_General_CS_AS and OPERATIONID = '1401')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Clear transaction tax exemption'
WHERE OPERATIONID = '1401'
END
 
IF EXISTS(SELECT * FROM POSISOPERATIONS where OPERATIONNAME = N'Infocode Tax Group Change' collate Latin1_General_CS_AS and OPERATIONID = '1405')
BEGIN
UPDATE POSISOPERATIONS SET OPERATIONNAME = N'Infocode tax group change'
WHERE OPERATIONID = '1405'
END
 

GO