
/*

	Incident No.	: 12062	
	Responsible		: Óskar Bjarnason	
	Sprint			: LS Retail .NET 2012/Thor
	Date created	: 17.10.2011

	Description		: Add UseCentralsuspension column to tables POSTRANSACTIONSERVICEPROFILE 

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: POSTRANSACTIONSERVICEPROFILE - Added UseCentralsuspension	
					  POSFUNCTIONALITYPROFILE - Added POLLINGINTERVAL
					  
					  
					  	
*/								

USE LSPOSNET

GO

IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POSTRANSACTIONSERVICEPROFILE' AND COLUMN_NAME='USECENTRALSUSPENSION')
Begin
	Alter Table POSTRANSACTIONSERVICEPROFILE
	ADD USECENTRALSUSPENSION tinyint NULL 
End
GO


IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POSFUNCTIONALITYPROFILE' AND COLUMN_NAME='POLLINGINTERVAL')
Begin
	Alter Table POSFUNCTIONALITYPROFILE
	ADD POLLINGINTERVAL int NULL 
End
GO



