//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.ViewPlugins.TradeAgreements.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.ViewPlugins.TradeAgreements.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add customer to line discount group.
        /// </summary>
        internal static string AddCustomerToLineDiscountGroup {
            get {
                return ResourceManager.GetString("AddCustomerToLineDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add customer to price group.
        /// </summary>
        internal static string AddCustomerToPriceGroup {
            get {
                return ResourceManager.GetString("AddCustomerToPriceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add customer to total discount group.
        /// </summary>
        internal static string AddCustomerToTotalDiscountGroup {
            get {
                return ResourceManager.GetString("AddCustomerToTotalDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to line discount group.
        /// </summary>
        internal static string AddToLineDiscountGroup {
            get {
                return ResourceManager.GetString("AddToLineDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to price group.
        /// </summary>
        internal static string AddToPriceGroup {
            get {
                return ResourceManager.GetString("AddToPriceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to total discount group.
        /// </summary>
        internal static string AddToTotalDiscountGroup {
            get {
                return ResourceManager.GetString("AddToTotalDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items.
        /// </summary>
        internal static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer has been deleted and can&apos;t be added to a group.
        /// </summary>
        internal static string CantAddDeletedCustomerToGroup {
            get {
                return ResourceManager.GetString("CantAddDeletedCustomerToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertible.
        /// </summary>
        internal static string Convertible {
            get {
                return ResourceManager.GetString("Convertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer discount group.
        /// </summary>
        internal static string CustomerDiscountGroup {
            get {
                return ResourceManager.GetString("CustomerDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer discount groups.
        /// </summary>
        internal static string CustomerDiscountGroups {
            get {
                return ResourceManager.GetString("CustomerDiscountGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to view or edit customer discount groups.
        /// </summary>
        internal static string CustomerDiscountGroupsDescription {
            get {
                return ResourceManager.GetString("CustomerDiscountGroupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage line, multiline and total customer discount groups and their discounts.
        /// </summary>
        internal static string CustomerDiscountGroupsTooltipDescription {
            get {
                return ResourceManager.GetString("CustomerDiscountGroupsTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer line discount group.
        /// </summary>
        internal static string CustomerLineDiscountGroup {
            get {
                return ResourceManager.GetString("CustomerLineDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer multiline discount group.
        /// </summary>
        internal static string CustomerMultiLineDiscountGroup {
            get {
                return ResourceManager.GetString("CustomerMultiLineDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not in customer group.
        /// </summary>
        internal static string CustomerNotInCustomerGroup {
            get {
                return ResourceManager.GetString("CustomerNotInCustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer price group.
        /// </summary>
        internal static string CustomerPriceGroup {
            get {
                return ResourceManager.GetString("CustomerPriceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer total discount group.
        /// </summary>
        internal static string CustomerTotalDiscountGroup {
            get {
                return ResourceManager.GetString("CustomerTotalDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default store has no tax group attached to it.
        /// </summary>
        internal static string DefaultStoreHasNoTaxGroupAttachedToIt {
            get {
                return ResourceManager.GetString("DefaultStoreHasNoTaxGroupAttachedToIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group.
        /// </summary>
        internal static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected group?.
        /// </summary>
        internal static string DeleteGroupQuestion {
            get {
                return ResourceManager.GetString("DeleteGroupQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete store from price group.
        /// </summary>
        internal static string DeleteStoreFromPriceGroup {
            get {
                return ResourceManager.GetString("DeleteStoreFromPriceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete the selected store from the price group ?.
        /// </summary>
        internal static string DeleteStoreFromPriceGroupQuestion {
            get {
                return ResourceManager.GetString("DeleteStoreFromPriceGroupQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete trade agreement sales price.
        /// </summary>
        internal static string DeleteTASalesPrice {
            get {
                return ResourceManager.GetString("DeleteTASalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete trade agreement.
        /// </summary>
        internal static string DeleteTradeAgreement {
            get {
                return ResourceManager.GetString("DeleteTradeAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected trade agreement?.
        /// </summary>
        internal static string DeleteTradeAgreementQuestion {
            get {
                return ResourceManager.GetString("DeleteTradeAgreementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap discount_groups_16 {
            get {
                object obj = ResourceManager.GetObject("discount_groups_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap discount_groups_32 {
            get {
                object obj = ResourceManager.GetObject("discount_groups_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount groups.
        /// </summary>
        internal static string DiscountGroups {
            get {
                return ResourceManager.GetString("DiscountGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        internal static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a submenu for discount related operations.
        /// </summary>
        internal static string DiscountsDescription {
            get {
                return ResourceManager.GetString("DiscountsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting to Site Service. .
        /// </summary>
        internal static string ErrorConnectingToSiteService {
            get {
                return ResourceManager.GetString("ErrorConnectingToSiteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date cannot be higher than to date.
        /// </summary>
        internal static string FromDateCannotBeHigherThanToDate {
            get {
                return ResourceManager.GetString("FromDateCannotBeHigherThanToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group limit.
        /// </summary>
        internal static string GroupLimit {
            get {
                return ResourceManager.GetString("GroupLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a submenu for discount and price related groups.
        /// </summary>
        internal static string GroupsRibbonDescription {
            get {
                return ResourceManager.GetString("GroupsRibbonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unit conversion rule from the selected unit to the items inventory unit is missing. You must create it to continue. Do you want to create one now ?.
        /// </summary>
        internal static string InventoryUnitConversionRuleMissing {
            get {
                return ResourceManager.GetString("InventoryUnitConversionRuleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item already belongs to that group or is already in the list.
        /// </summary>
        internal static string ItemAlreadyAdded {
            get {
                return ResourceManager.GetString("ItemAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item code.
        /// </summary>
        internal static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item discount group.
        /// </summary>
        internal static string ItemDiscountGroup {
            get {
                return ResourceManager.GetString("ItemDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item discount groups.
        /// </summary>
        internal static string ItemDiscountGroups {
            get {
                return ResourceManager.GetString("ItemDiscountGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to view or edit item discount groups.
        /// </summary>
        internal static string ItemDiscountGroupsDescription {
            get {
                return ResourceManager.GetString("ItemDiscountGroupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage line and multiline item discount groups and their discounts.
        /// </summary>
        internal static string ItemDiscountGroupsTooltipDescription {
            get {
                return ResourceManager.GetString("ItemDiscountGroupsTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has no tax group attached to it.
        /// </summary>
        internal static string ItemHasNoTaxGroupAttachedToIt {
            get {
                return ResourceManager.GetString("ItemHasNoTaxGroupAttachedToIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item line discount group.
        /// </summary>
        internal static string ItemLineDiscountGroup {
            get {
                return ResourceManager.GetString("ItemLineDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item multiline discount group.
        /// </summary>
        internal static string ItemMultilineDiscountGroup {
            get {
                return ResourceManager.GetString("ItemMultilineDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line discount.
        /// </summary>
        internal static string LineDiscount {
            get {
                return ResourceManager.GetString("LineDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line discount group:.
        /// </summary>
        internal static string LineDiscountGroup {
            get {
                return ResourceManager.GetString("LineDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line discount groups.
        /// </summary>
        internal static string LineDiscountGroup2 {
            get {
                return ResourceManager.GetString("LineDiscountGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiline.
        /// </summary>
        internal static string Multiline {
            get {
                return ResourceManager.GetString("Multiline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiline discount.
        /// </summary>
        internal static string MultilineDiscount {
            get {
                return ResourceManager.GetString("MultilineDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiline discounts.
        /// </summary>
        internal static string MultiLineDiscounts {
            get {
                return ResourceManager.GetString("MultiLineDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customers found.
        /// </summary>
        internal static string NoCustomersFound {
            get {
                return ResourceManager.GetString("NoCustomersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default store selected.
        /// </summary>
        internal static string NoDefaultStoreSelected {
            get {
                return ResourceManager.GetString("NoDefaultStoreSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap price_groups_16 {
            get {
                object obj = ResourceManager.GetObject("price_groups_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap price_groups_32 {
            get {
                object obj = ResourceManager.GetObject("price_groups_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the price for the selected items.
        /// </summary>
        internal static string PriceConficMultiDescription {
            get {
                return ResourceManager.GetString("PriceConficMultiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price/discount.
        /// </summary>
        internal static string PriceDiscount {
            get {
                return ResourceManager.GetString("PriceDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price/discount groups.
        /// </summary>
        internal static string PriceDiscountGroups {
            get {
                return ResourceManager.GetString("PriceDiscountGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price group:.
        /// </summary>
        internal static string PriceGroup {
            get {
                return ResourceManager.GetString("PriceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price groups.
        /// </summary>
        internal static string PriceGroups {
            get {
                return ResourceManager.GetString("PriceGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to view or edit price groups.
        /// </summary>
        internal static string PriceGroupsDescription {
            get {
                return ResourceManager.GetString("PriceGroupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage groups of stores and customers to use for sales price and discount setup.
        /// </summary>
        internal static string PriceGroupsTooltipDescription {
            get {
                return ResourceManager.GetString("PriceGroupsTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PriceTag16 {
            get {
                object obj = ResourceManager.GetObject("PriceTag16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be higher than 0.
        /// </summary>
        internal static string QuantityHigherThanZero {
            get {
                return ResourceManager.GetString("QuantityHigherThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove action.
        /// </summary>
        internal static string RemoveAction {
            get {
                return ResourceManager.GetString("RemoveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        internal static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail item.
        /// </summary>
        internal static string RetailItem {
            get {
                return ResourceManager.GetString("RetailItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales prices.
        /// </summary>
        internal static string SalesPrices {
            get {
                return ResourceManager.GetString("SalesPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as on item.
        /// </summary>
        internal static string SameAsOnItem {
            get {
                return ResourceManager.GetString("SameAsOnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup conditions for deleting a price.
        /// </summary>
        internal static string SetupConditionsForDeletingPrice {
            get {
                return ResourceManager.GetString("SetupConditionsForDeletingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected store is already in the selected price group.
        /// </summary>
        internal static string StoreAlreadyInPriceGroup {
            get {
                return ResourceManager.GetString("StoreAlreadyInPriceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total discount.
        /// </summary>
        internal static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total discount group:.
        /// </summary>
        internal static string TotalDiscountGroup {
            get {
                return ResourceManager.GetString("TotalDiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total discounts.
        /// </summary>
        internal static string TotalDiscounts {
            get {
                return ResourceManager.GetString("TotalDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected combination of account code, account selection, quantity, from date, currency, unit id and variant number already exists.
        /// </summary>
        internal static string TradeAgreementExists1 {
            get {
                return ResourceManager.GetString("TradeAgreementExists1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected combination of account code, quantity, from date, currency, unit id and variant number already exists.
        /// </summary>
        internal static string TradeAgreementExists2 {
            get {
                return ResourceManager.GetString("TradeAgreementExists2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line discounts.
        /// </summary>
        internal static string TradeAgreements {
            get {
                return ResourceManager.GetString("TradeAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit conversion rule missing.
        /// </summary>
        internal static string UnitConversionRuleMissing {
            get {
                return ResourceManager.GetString("UnitConversionRuleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant number.
        /// </summary>
        internal static string VariantNumber {
            get {
                return ResourceManager.GetString("VariantNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View customer.
        /// </summary>
        internal static string ViewCustomer {
            get {
                return ResourceManager.GetString("ViewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View customer group.
        /// </summary>
        internal static string ViewCustomerGroup {
            get {
                return ResourceManager.GetString("ViewCustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View group.
        /// </summary>
        internal static string ViewGroup {
            get {
                return ResourceManager.GetString("ViewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View item.
        /// </summary>
        internal static string ViewItem {
            get {
                return ResourceManager.GetString("ViewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View item group.
        /// </summary>
        internal static string ViewItemGroup {
            get {
                return ResourceManager.GetString("ViewItemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View store.
        /// </summary>
        internal static string ViewStore {
            get {
                return ResourceManager.GetString("ViewStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
