/*
	Incident No.	: ONE-13113
	Responsible		: Sigurdur Bjarni Sigurdsson
	Sprint			: Bahraini dinar
	Date created	: 04.02.2021

	Description		: Add REASON and USERID columns to RETAILITEMCOST
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'REASON' AND TABLE_NAME = 'RETAILITEMCOST')
    BEGIN
        ALTER TABLE RETAILITEMCOST ADD REASON NVARCHAR(60) NULL
    END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'USERID' AND TABLE_NAME = 'RETAILITEMCOST')
    BEGIN
        ALTER TABLE RETAILITEMCOST ADD USERID UNIQUEIDENTIFIER NULL
    END
GO


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'REASON' AND TABLE_NAME = 'RETAILITEMCOSTHISTORY')
    BEGIN
        ALTER TABLE RETAILITEMCOSTHISTORY ADD REASON NVARCHAR(60) NULL
    END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'USERID' AND TABLE_NAME = 'RETAILITEMCOSTHISTORY')
    BEGIN
        ALTER TABLE RETAILITEMCOSTHISTORY ADD USERID UNIQUEIDENTIFIER NULL
        EXECUTE spDB_SetFieldDescription_1_0 'INVENTORYTRANSFERORDERLINE', 'COSTPRICE', 'Last calculated cost price of the item from the sending store'
    END