/*
	Incident No.	: ONE-12992
	Responsible		: Jonas Haraldsson
	Sprint			: Renminbi
	Date created	: 4.12.2020

	Description		: LS Pay integration
*/

USE LSPOSNET

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'LSPAY' AND TABLE_NAME = 'POSHARDWAREPROFILE')
BEGIN
    ALTER TABLE POSHARDWAREPROFILE ADD LSPAY BIT NOT NULL DEFAULT 0
    EXECUTE spDB_SetFieldDescription_1_0 'POSHARDWAREPROFILE', 'LSPAY', 'Determines if LS Pay shall be used (if field EFT is also set to 1).'
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'LSPAYUSELOCALSERVER' AND TABLE_NAME = 'RBOTERMINALTABLE')
BEGIN
    ALTER TABLE RBOTERMINALTABLE ADD LSPAYUSELOCALSERVER BIT NOT NULL DEFAULT 0
    EXECUTE spDB_SetFieldDescription_1_0 'RBOTERMINALTABLE', 'LSPAYUSELOCALSERVER', 'Determines if LS Pay server is configured on the terminal (1) or taken from the hardware profile (0).'
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'LSPAYSERVERNAME' AND TABLE_NAME = 'RBOTERMINALTABLE')
BEGIN
    ALTER TABLE RBOTERMINALTABLE ADD LSPAYSERVERNAME NVARCHAR(100) NOT NULL DEFAULT ''
    EXECUTE spDB_SetFieldDescription_1_0 'RBOTERMINALTABLE', 'LSPAYSERVERNAME', 'The hostname or ip adress to the LS Pay server (if LSPAYUSELOCALSERVER = 1).'
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'LSPAYSERVERPORT' AND TABLE_NAME = 'RBOTERMINALTABLE')
BEGIN
    ALTER TABLE RBOTERMINALTABLE ADD LSPAYSERVERPORT INT NOT NULL DEFAULT 0
    EXECUTE spDB_SetFieldDescription_1_0 'RBOTERMINALTABLE', 'LSPAYSERVERPORT', 'The port number for the LS Pay server (if LSPAYUSELOCALSERVER = 1).'
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'LSPAYSERVERPORT' AND TABLE_NAME = 'RBOTERMINALTABLE')
BEGIN
    ALTER TABLE RBOTERMINALTABLE ADD LSPAYSERVERPORT INT NOT NULL DEFAULT 0
    EXECUTE spDB_SetFieldDescription_1_0 'RBOTERMINALTABLE', 'LSPAYSERVERPORT', 'The port number for the LS Pay server (if LSPAYUSELOCALSERVER = 1).'
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'LSPAYPLUGINID' AND TABLE_NAME = 'RBOTERMINALTABLE')
BEGIN
    ALTER TABLE RBOTERMINALTABLE ADD LSPAYPLUGINID NVARCHAR(100) NOT NULL DEFAULT ''
    EXECUTE spDB_SetFieldDescription_1_0 'RBOTERMINALTABLE', 'LSPAYPLUGINID', 'LS Pay plugin ID, identifies the payment terminal to use when when communicating with the LS Pay service.'
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'LSPAYPLUGINNAME' AND TABLE_NAME = 'RBOTERMINALTABLE')
BEGIN
    ALTER TABLE RBOTERMINALTABLE ADD LSPAYPLUGINNAME NVARCHAR(100) NOT NULL DEFAULT ''
    EXECUTE spDB_SetFieldDescription_1_0 'RBOTERMINALTABLE', 'LSPAYPLUGINNAME', 'User readable name of the LS Pay plugin corresponding to the LS Pay plugin ID.'
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'LSPAYSUPPORTREFREFUND' AND TABLE_NAME = 'RBOTERMINALTABLE')
BEGIN
    ALTER TABLE RBOTERMINALTABLE ADD LSPAYSUPPORTREFREFUND BIT NOT NULL DEFAULT 0
    EXECUTE spDB_SetFieldDescription_1_0 'RBOTERMINALTABLE', 'LSPAYSUPPORTREFREFUND', 'Determines if the LS Pay device supports reference refunds.'
END

GO