/*
	Incident No.	: ONE-13656
	Responsible		: Sigurður Bjarni Sigurðsson
	Sprint			: Erebus
	Date created	: 31.05.2021

	Description		: Adding columns to POSVISUALPROFILE so users can control the colors of selected rows in the POS
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OVERRIDEPOSSELECTEDROWCOLOR' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD OVERRIDEPOSSELECTEDROWCOLOR BIT NOT NULL DEFAULT(0)
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'OVERRIDEPOSSELECTEDROWCOLOR', 'If true then the value in POSSELECTEDROWCOLOR is used for the selected row in the POS.';
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'POSSELECTEDROWCOLOR' AND TABLE_NAME = 'POSVISUALPROFILE')
BEGIN
	ALTER TABLE POSVISUALPROFILE ADD POSSELECTEDROWCOLOR INT NULL
	EXECUTE spDB_SetFieldDescription_1_0 'POSVISUALPROFILE', 'POSSELECTEDROWCOLOR', 'The color to use for the selected row. This is only used if OVERRIDEPOSSELECTEDROWCOLOR is set to true.';
END
GO