/*
	Incident No.	: ONE-13434
	Responsible		: Hörður Kristjánsson
	Sprint			: Dogecoin
	Date created	: 05.03.2021

	Description		: Increasing length of NAMEONRECEIPT for RBOSTAFFTABLE to match STAFFID
*/

USE LSPOSNET

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOSTAFFTABLE' AND COLUMN_NAME = 'NAMEONRECEIPT' AND CHARACTER_MAXIMUM_LENGTH < 20)
    BEGIN
        ALTER TABLE RBOSTAFFTABLE ALTER COLUMN NAMEONRECEIPT NVARCHAR(20)
    END
GO