//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.DataLayer.DatabaseUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.DataLayer.DatabaseUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All upgrades finished successfully.
        /// </summary>
        internal static string AllUpgradesFinishedSuccessfully {
            get {
                return ResourceManager.GetString("AllUpgradesFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lsonehbo.cloudapp.net.
        /// </summary>
        internal static string CloudServer {
            get {
                return ResourceManager.GetString("CloudServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is closed.
        /// </summary>
        internal static string ConnectionIsClosed {
            get {
                return ResourceManager.GetString("ConnectionIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is not valid. Operation cannot continue.
        /// </summary>
        internal static string ConnectionNotValid {
            get {
                return ResourceManager.GetString("ConnectionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string cannot be created - SQLServer and Database name parameters have to have values.
        /// </summary>
        internal static string ConnectionStringCannotBeCreated {
            get {
                return ResourceManager.GetString("ConnectionStringCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;CREATE DATABASE&quot;  failed, make sure that a mdf file with same name doesn&apos;t already exists.
        /// </summary>
        internal static string CreateDatabaseFailedMdfFileAlreadyExists {
            get {
                return ResourceManager.GetString("CreateDatabaseFailedMdfFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating admin users.
        /// </summary>
        internal static string CreatingAdminUsers {
            get {
                return ResourceManager.GetString("CreatingAdminUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating audit database.
        /// </summary>
        internal static string CreatingAuditDatabase {
            get {
                return ResourceManager.GetString("CreatingAuditDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database.
        /// </summary>
        internal static string CreatingDatabase {
            get {
                return ResourceManager.GetString("CreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataAreaId is not valid, it must have a value and cannot be more than 4 characters.
        /// </summary>
        internal static string DataAreaIdIsNotValid {
            get {
                return ResourceManager.GetString("DataAreaIdIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database already exists, new database not created.
        /// </summary>
        internal static string DatabaseAlreadyExistsNewDatabaseNotCreated {
            get {
                return ResourceManager.GetString("DatabaseAlreadyExistsNewDatabaseNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection set.
        /// </summary>
        internal static string DatabaseConnectionSet {
            get {
                return ResourceManager.GetString("DatabaseConnectionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database #1 created.
        /// </summary>
        internal static string DatabaseCreated {
            get {
                return ResourceManager.GetString("DatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database does not exist.
        /// </summary>
        internal static string DatabaseDoesNotExist {
            get {
                return ResourceManager.GetString("DatabaseDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database needs to be upgraded - starting upgrade...
        /// </summary>
        internal static string DatabaseNeedsToBeUpgradedStartingUpgrade {
            get {
                return ResourceManager.GetString("DatabaseNeedsToBeUpgradedStartingUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database updates finished successfully.
        /// </summary>
        internal static string DatabaseUpdatesFinishedSuccessfully {
            get {
                return ResourceManager.GetString("DatabaseUpdatesFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseUtil.GetTable: #1 - SQL = #2.
        /// </summary>
        internal static string DatabaseUtilGetTableError {
            get {
                return ResourceManager.GetString("DatabaseUtilGetTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo data successfully loaded.
        /// </summary>
        internal static string DemoDataSuccessfullyLoaded {
            get {
                return ResourceManager.GetString("DemoDataSuccessfullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing registry keys.
        /// </summary>
        internal static string ErrorAccessingRegistryKeys {
            get {
                return ResourceManager.GetString("ErrorAccessingRegistryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error closing the database connection.
        /// </summary>
        internal static string ErrorClosingTheDatabaseConnection {
            get {
                return ResourceManager.GetString("ErrorClosingTheDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing query: #1.
        /// </summary>
        internal static string ErrorExecutingQuery {
            get {
                return ResourceManager.GetString("ErrorExecutingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting database information.
        /// </summary>
        internal static string ErrorGettingDatabaseInformation {
            get {
                return ResourceManager.GetString("ErrorGettingDatabaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting demo data: #1.
        /// </summary>
        internal static string ErrorInsertingDemoData {
            get {
                return ResourceManager.GetString("ErrorInsertingDemoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting the master connection.
        /// </summary>
        internal static string ErrorSettingMasterConnection {
            get {
                return ResourceManager.GetString("ErrorSettingMasterConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when updating database version #1.
        /// </summary>
        internal static string ErrorWhenUpdatingDatabaseVersion {
            get {
                return ResourceManager.GetString("ErrorWhenUpdatingDatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating demo data: #1.
        /// </summary>
        internal static string ErrorWhenUpdatingDemoData {
            get {
                return ResourceManager.GetString("ErrorWhenUpdatingDemoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing upgrade.
        /// </summary>
        internal static string ExecutingUpgrade {
            get {
                return ResourceManager.GetString("ExecutingUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the SQL server..
        /// </summary>
        internal static string FailedToConnectToSQLServer {
            get {
                return ResourceManager.GetString("FailedToConnectToSQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set the database connection.
        /// </summary>
        internal static string FailedToSetTheDatabaseConnection {
            get {
                return ResourceManager.GetString("FailedToSetTheDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language ids successfully created.
        /// </summary>
        internal static string LanguageIdsSuccessfullyCreated {
            get {
                return ResourceManager.GetString("LanguageIdsSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading demo data into tables.
        /// </summary>
        internal static string LoadingDemoDataIntoTables {
            get {
                return ResourceManager.GetString("LoadingDemoDataIntoTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT AUTHORITY\NETWORK SERVICE.
        /// </summary>
        internal static string NetworkService {
            get {
                return ResourceManager.GetString("NetworkService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource name provided.
        /// </summary>
        internal static string NoResourceNameProvided {
            get {
                return ResourceManager.GetString("NoResourceNameProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recompiling objects.
        /// </summary>
        internal static string RecompilingObjects {
            get {
                return ResourceManager.GetString("RecompilingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running admin script.
        /// </summary>
        internal static string RunningAdminScript {
            get {
                return ResourceManager.GetString("RunningAdminScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running audit logic scripts.
        /// </summary>
        internal static string RunningAuditLogicScripts {
            get {
                return ResourceManager.GetString("RunningAuditLogicScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running logic scripts.
        /// </summary>
        internal static string RunningLogicScripts {
            get {
                return ResourceManager.GetString("RunningLogicScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running script {0}.
        /// </summary>
        internal static string RunningScript {
            get {
                return ResourceManager.GetString("RunningScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running system data scripts.
        /// </summary>
        internal static string RunningSystemDataScripts {
            get {
                return ResourceManager.GetString("RunningSystemDataScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script to add cloud data started.
        /// </summary>
        internal static string ScriptToAddCloudData {
            get {
                return ResourceManager.GetString("ScriptToAddCloudData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script to add stored procedures started.
        /// </summary>
        internal static string ScriptToAddStoredProceduresStarted {
            get {
                return ResourceManager.GetString("ScriptToAddStoredProceduresStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script to create all language ids started.
        /// </summary>
        internal static string ScriptToCreateAllLanguageIdsStarted {
            get {
                return ResourceManager.GetString("ScriptToCreateAllLanguageIdsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script to create tables started.
        /// </summary>
        internal static string ScriptToCreateTablesStarted {
            get {
                return ResourceManager.GetString("ScriptToCreateTablesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Util.
        /// </summary>
        internal static string SenderDatabaseUtil {
            get {
                return ResourceManager.GetString("SenderDatabaseUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SQL 2017 Express.
        /// </summary>
        internal static string SenderInstallSQL2017 {
            get {
                return ResourceManager.GetString("SenderInstallSQL2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup files do not exist in path given.
        /// </summary>
        internal static string SetupFilesDoNotExistInPathGiven {
            get {
                return ResourceManager.GetString("SetupFilesDoNotExistInPathGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL install parameters have not been set. SQLExpress server cannot be installed.
        /// </summary>
        internal static string SQLInstallParametersHaveNotBeenSet {
            get {
                return ResourceManager.GetString("SQLInstallParametersHaveNotBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL install type not implemented.
        /// </summary>
        internal static string SQLInstallTypeNotImplemented {
            get {
                return ResourceManager.GetString("SQLInstallTypeNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL script #1 finished successfully.
        /// </summary>
        internal static string SQLScriptFinishedSuccessfully {
            get {
                return ResourceManager.GetString("SQLScriptFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server instance does not exist.
        /// </summary>
        internal static string SQLServerInstanceDoesNotExist {
            get {
                return ResourceManager.GetString("SQLServerInstanceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure #1 created successfully.
        /// </summary>
        internal static string StoredProcedureCreatedSuccessfully {
            get {
                return ResourceManager.GetString("StoredProcedureCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table #1 created successfully.
        /// </summary>
        internal static string TableCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TableCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - #1 -&gt; done.
        /// </summary>
        internal static string TableNameDone {
            get {
                return ResourceManager.GetString("TableNameDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update script #1 finished successfully.
        /// </summary>
        internal static string UpdateScriptFinishedSuccessfully {
            get {
                return ResourceManager.GetString("UpdateScriptFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating audit database.
        /// </summary>
        internal static string UpdatingAuditDatabase {
            get {
                return ResourceManager.GetString("UpdatingAuditDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating audit users.
        /// </summary>
        internal static string UpdatingAuditUsers {
            get {
                return ResourceManager.GetString("UpdatingAuditUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating cloud database.
        /// </summary>
        internal static string UpdatingCloudDatabase {
            get {
                return ResourceManager.GetString("UpdatingCloudDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating cloud HBO database.
        /// </summary>
        internal static string UpdatingCloudHBODatabase {
            get {
                return ResourceManager.GetString("UpdatingCloudHBODatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating database.
        /// </summary>
        internal static string UpdatingDatabase {
            get {
                return ResourceManager.GetString("UpdatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating demo data.
        /// </summary>
        internal static string UpdatingDemoData {
            get {
                return ResourceManager.GetString("UpdatingDemoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating users.
        /// </summary>
        internal static string UpdatingUsers {
            get {
                return ResourceManager.GetString("UpdatingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User scripts started.
        /// </summary>
        internal static string UserScriptsStarted {
            get {
                return ResourceManager.GetString("UserScriptsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify the username and password..
        /// </summary>
        internal static string VerifyUserAndPassword {
            get {
                return ResourceManager.GetString("VerifyUserAndPassword", resourceCulture);
            }
        }
    }
}
