
/*
	This is the branch script for 2011.1.1. If you need to add changes to the branch please add them here.

	Incident No.	: XXX
	Responsible		: Many
	Sprint			: LS Retail.NET 2012 Mjolnir\Baldur 1 June 23-aug 3
	Date created	: 13.07.2011

	Description		: Add functionality for the 2011.1.1 branch

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: CUSTTABLE - Add extra name fields
					  CUSTTABLE - Add index to two fields
					  POSHARDWAREPROFILE - EFTPASSWORD length changed
					  RboTransactionTable		- new field
					  RboTransactionSalesTrans	- new field
					  RboTransactionTaxTrans	- new fields, changed field lengths					  
-- 					  PosisLanguageText			- Added new translation texts
					  PosisOperations			- Added new operations
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLE') AND NAME='FIRSTNAME')
ALTER TABLE dbo.CUSTTABLE ADD FIRSTNAME NVARCHAR(31) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLE') AND NAME='MIDDLENAME')
ALTER TABLE dbo.CUSTTABLE ADD MIDDLENAME NVARCHAR(15) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLE') AND NAME='LASTNAME')
ALTER TABLE dbo.CUSTTABLE ADD LASTNAME NVARCHAR(20) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLE') AND NAME='NAMEPREFIX')
ALTER TABLE dbo.CUSTTABLE ADD NAMEPREFIX NVARCHAR(8) NULL

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLE') AND NAME='NAMESUFFIX')
ALTER TABLE dbo.CUSTTABLE ADD NAMESUFFIX NVARCHAR(8) NULL

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'POSHARDWAREPROFILE' AND COLUMN_NAME = 'EFTPASSWORD') = 10)
begin
	ALTER TABLE POSHARDWAREPROFILE ALTER COLUMN EFTPASSWORD [nvarchar](20) NULL
end


GO
-- Declare the variables to store the values returned by FETCH.
DECLARE @CustomerName varchar(31), @CustomerID nvarchar(20);

DECLARE CustomerNameCursor CURSOR FOR
SELECT NAME,ACCOUNTNUM  FROM CUSTTABLE

OPEN CustomerNameCursor;

FETCH NEXT FROM CustomerNameCursor
INTO @CustomerName, @CustomerID;

-- Check @@FETCH_STATUS to see if there are any more rows to fetch.
WHILE @@FETCH_STATUS = 0
BEGIN

   UPDATE CUSTTABLE 
   SET FIRSTNAME = @CustomerName
   WHERE ACCOUNTNUM = @CustomerID
   
   -- This is executed as long as the previous fetch succeeds.
   FETCH NEXT FROM CustomerNameCursor
   INTO @CustomerName, @CustomerID;
END

CLOSE CustomerNameCursor;
DEALLOCATE CustomerNameCursor;
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONTABLE') AND NAME='TAXEXEMPT')
BEGIN
	ALTER TABLE [dbo].[RBOTRANSACTIONTABLE] ADD TAXEXEMPT tinyint NULL DEFAULT 0
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONSALESTRANS') AND NAME='TAXEXEMPT')
BEGIN
	ALTER TABLE [dbo].[RBOTRANSACTIONSALESTRANS] ADD TAXEXEMPT tinyint NULL DEFAULT 0
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONTAXTRANS') AND NAME='TAXEXEMPT')
BEGIN
	ALTER TABLE [dbo].[RBOTRANSACTIONTAXTRANS] ADD TAXEXEMPT tinyint NULL DEFAULT 0
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOTRANSACTIONTAXTRANS') AND NAME='TAXEXEMPTIONCODE')
BEGIN
	ALTER TABLE [dbo].[RBOTRANSACTIONTAXTRANS] ADD TAXEXEMPTIONCODE nvarchar(20) NULL
END
GO

-- Tax exemption changes
IF NOT EXISTS (SELECT * FROM [POSISOPERATIONS] WHERE [OPERATIONID] = 1400 and [DATAAREAID] = 'LSR')
INSERT POSISOPERATIONS(OPERATIONID,OPERATIONNAME,CHECKUSERACCESS,USEROPERATION,DATAAREAID) VALUES('1400','Tax Exempt Transaction','1','1','LSR')

IF NOT EXISTS (SELECT * FROM [POSISOPERATIONS] WHERE [OPERATIONID] = 1401 and [DATAAREAID] = 'LSR')
INSERT POSISOPERATIONS(OPERATIONID,OPERATIONNAME,CHECKUSERACCESS,USEROPERATION,DATAAREAID) VALUES('1401','Clear Transaction Tax Exemption','1','1','LSR')
GO

IF NOT EXISTS (SELECT * FROM [POSISOPERATIONS] WHERE [OPERATIONID] = 1405 and [DATAAREAID] = 'LSR')
INSERT POSISOPERATIONS(OPERATIONID,OPERATIONNAME,CHECKUSERACCESS,USEROPERATION,DATAAREAID) VALUES('1405','Infocode Tax Group Change','1','1','LSR')
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6200)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6200','This operation is invalid for this type of transaction',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'This operation is invalid for this type of transaction', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6200
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6200)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6200','Þessi aðgerð er óleyfileg í viðkomandi afgreiðslutegund.',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Þessi aðgerð er óleyfileg í viðkomandi afgreiðslutegund.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6200

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6201)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6201','Enter tax exemption code',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Enter tax exemption code', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6201
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6201)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6201','Sláðu inn skattaundanþágunúmer',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Sláðu inn skattaundanþágunúmer', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6201

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6202)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6202','You cannot enter an empty code',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'You cannot enter an empty code', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6202
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6202)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6202','Ekki er hægt að slá inn tómt númer',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ekki er hægt að slá inn tómt númer', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6202

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6203)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6203','Are you sure you want to tax exempt the transaction ?',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to tax exempt the transaction ?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6203
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6203)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6203','Ertu viss um að þú viljir gera söluna undanþegna skatti ?',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ertu viss um að þú viljir gera söluna undanþegna skatti ?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6203

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6204)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6204','The transaction has been tax exempted',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'The transaction has been tax exempted', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6204
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6204)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6204','Salan hefur verið undanþegin skatti',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Salan hefur verið undanþegin skatti', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6204

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6210)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6210','This operation is invalid for this type of transaction',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'This operation is invalid for this type of transaction', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6210
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6210)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6210','Þessi aðgerð er óleyfileg í viðkomandi afgreiðslutegund.',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Þessi aðgerð er óleyfileg í viðkomandi afgreiðslutegund.', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6210

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6211)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6211','Are you sure you want to clear the transaction tax exemption ?',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to clear the transaction tax exemption ?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6211
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6211)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6211','Ertu viss um að þú viljir hreinsa skattaundanþáguna af sölunni ?',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ertu viss um að þú viljir hreinsa skattaundanþáguna af sölunni ?', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6211

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6212)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '6212','Tax exemption cleared',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Tax exemption cleared', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6212
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6212)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6212','Skattaundanþága hreinsuð',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Skattaundanþága hreinsuð', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6212


IF NOT EXISTS(SELECT * FROM sys.indexes where object_id = OBJECT_ID('CUSTTABLE') AND NAME = 'IX_CustTable_FirstName')
BEGIN
	CREATE NONCLUSTERED INDEX IX_CustTable_FirstName ON [dbo].[CUSTTABLE] 
	(
		FIRSTNAME ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
END
GO

IF NOT EXISTS(SELECT * FROM sys.indexes where object_id = OBJECT_ID('CUSTTABLE') AND NAME = 'IX_CustTable_LastName')
BEGIN
	CREATE NONCLUSTERED INDEX IX_CustTable_LastName ON [dbo].[CUSTTABLE] 
	(
		LASTNAME ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
END
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3687)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3687','The cost price for the item',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'The cost price for the item', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3687
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3688)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3688','is now set to',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'is now set to', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3688
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3689)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3689','Please enter the cost price',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Please enter the cost price', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3689
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTORETABLE') AND NAME='USETAXGROUPFROM')
BEGIN
	ALTER TABLE [dbo].[RBOSTORETABLE] ADD USETAXGROUPFROM int NULL DEFAULT 0
END
GO


-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 7036)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '7036','Safe Drop Reversion',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Safe Drop Reversion', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 7036
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 7037)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '7037','Bank Drop Reversion',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Bank Drop Reversion', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 7037

IF NOT EXISTS (SELECT * FROM [POSISOPERATIONS] WHERE [OPERATIONID] = 1213 and [DATAAREAID] = 'LSR')
INSERT POSISOPERATIONS(OPERATIONID,OPERATIONNAME,CHECKUSERACCESS,USEROPERATION,DATAAREAID) VALUES('1213','Safe Drop Reversal','1','1','LSR')
GO
IF NOT EXISTS (SELECT * FROM [POSISOPERATIONS] WHERE [OPERATIONID] = 1214 and [DATAAREAID] = 'LSR')
INSERT POSISOPERATIONS(OPERATIONID,OPERATIONNAME,CHECKUSERACCESS,USEROPERATION,DATAAREAID) VALUES('1214','Bank Drop Reversal','1','1','LSR')
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3925)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3925','Are you sure you want to perform a bank drop?',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to perform a bank drop?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3925
GO
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3904)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3904','Are you sure you want to reverse a bank drop?',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to reverse a bank drop?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3904
GO
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3905)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3905','Are you sure you want to reverse a safe drop?',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Are you sure you want to reverse a safe drop?', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3905
GO
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3906)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3906','Safe drop reversion',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Safe drop reversion', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3906
GO
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3907)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3907','Bank drop reversion',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Bank drop reversion', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3907
GO
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3908)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3908','Bank drop reversion',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Please conclude the current transaction before reversing a Safe Drop operation.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3908
GO
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 3909)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '3909','Bank drop reversion',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Please conclude the current transaction before reversing a Bank Drop operation.', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 3909
GO

-- Infocodes
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 61514)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US','61514', 'Default',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Default', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 61514
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 61514)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '61514','Sjálfgefið',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Sjálfgefið', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 61514

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6220)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US','6220', 'This operation is only valid for a retail transaction',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'This operation is only valid for a retail transaction', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6220
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6220)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6220','Þessi aðgerð er aðeins leyfileg fyrir hefðbundna söluafgreiðslu',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Þessi aðgerð er aðeins leyfileg fyrir hefðbundna söluafgreiðslu', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6220

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6221)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US','6221', 'Tax group has been changed',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Tax group has been changed', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6221
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6221)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6221','Skattflokki hefur verið breytt',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Skattflokki hefur verið breytt', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6221

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6300)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US','6300', 'Infocode',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Infocode', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6300
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6300)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6300','Upplýsingakóti',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Upplýsingakóti', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6300

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 6301)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US','6301', 'Please select an infocode',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Please select an infocode', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 6301
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 6301)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '6301','Vinsamlegast veldu upplýsingakóta',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Vinsamlegast veldu upplýsingakóta', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 6301

-- RBOTRANSACTIONTAXTRANS field lengths
if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTAXTRANS' AND COLUMN_NAME = 'STORE') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTAXTRANS ALTER COLUMN STORE [nvarchar](20) NOT NULL
end

GO

if((SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.columns
WHERE TABLE_NAME = 'RBOTRANSACTIONTAXTRANS' AND COLUMN_NAME = 'TERMINAL') = 10)
begin
	ALTER TABLE RBOTRANSACTIONTAXTRANS ALTER COLUMN TERMINAL [nvarchar](20) NOT NULL
end

GO



-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 4542)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '4542','Operation will not continue since the POS is in return state',0, '8.1.0.0000')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Operation will not continue since the POS is in return state', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 4542