
/*

	Incident No.	: 5703
	Responsible		: Hörður Kristjánsson
	Sprint			: DotNetPM\LS POS 2010.1\Dot Net Stream\Sprint 01\Dot Net Team
	Date created	: 06.10.2010

	Description		: This is the "Lookup values.sql" file from the Store Controller

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: n/a
						
*/

Use LSPOSNET 

GO

declare @dataAreaID nvarchar(10)

set @dataAreaID = 'LSR'

IF not EXISTS(SELECT * FROM dbo.DECIMALSETTINGS where DATAAREAID = @dataAreaID and ID = 'Quantity')
begin
	insert into dbo.DECIMALSETTINGS (ID,NAME,MINDECIMALS,MAXDECIMALS,DATAAREAID)
	values ('Quantity','Quantity',0,3,@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.DECIMALSETTINGS where DATAAREAID = @dataAreaID and ID = 'Tax')
begin
	insert into dbo.DECIMALSETTINGS (ID,NAME,MINDECIMALS,MAXDECIMALS,DATAAREAID)
	values ('Tax','Tax',2,4,@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.DECIMALSETTINGS where DATAAREAID = @dataAreaID and ID = 'Prices')
begin
	insert into dbo.DECIMALSETTINGS (ID,NAME,MINDECIMALS,MAXDECIMALS,DATAAREAID)
	values ('Prices','Prices',0,2,@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.DECIMALSETTINGS where DATAAREAID = @dataAreaID and ID = 'Disc pct')
begin
	insert into dbo.DECIMALSETTINGS (ID,NAME,MINDECIMALS,MAXDECIMALS,DATAAREAID)
	values ('Disc pct','Discount percent',0,2,@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.DECIMALSETTINGS where DATAAREAID = @dataAreaID and ID = 'Split Qty')
begin
	insert into dbo.DECIMALSETTINGS (ID,NAME,MINDECIMALS,MAXDECIMALS,DATAAREAID)
	values ('Split Qty','Split bill quantity',1,2,@dataAreaID)
end

-- Add to the number sequence tables

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'Variant_1')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('Variant_1','Variant Number',1,999999,'VN######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('Variant_1',1,'HO',@dataAreaID)
end


IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'R-STORE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('R-STORE','Retail stores',1,9999,'S####',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('R-STORE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'ITEM')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('ITEM','Items',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('ITEM',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'Z-RPT')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('Z-RPT','Z Report ID',1,99999999,'########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('Z-RPT',1,'HO',@dataAreaID)
	IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NUMBERSEQUENCETABLE' AND COLUMN_NAME = 'EMBEDTERMINALID')
	BEGIN
		UPDATE NUMBERSEQUENCETABLE 
		SET EMBEDTERMINALID = 1 
		WHERE NUMBERSEQUENCE = 'Z-RPT'
	END
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'INV_3')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('INV_3','INV Dimension Number',1,99999,'ID-#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('INV_3',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'R-DISCO')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('R-DISCO','Retail discount',1,999999,'D######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('R-DISCO',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'R-MULT-G')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('R-MULT-G','General multibuy',1000000,1999999,'#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('R-MULT-G',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'R-MIXM')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('R-MIXM','Mix and Match',1,999999,'MM######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('R-MIXM',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'Promotions')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('Promotions','Promotions',1,999999,'P######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('Promotions',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'Terminals')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('Terminals','Terminals',1,9999,'T####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('Terminals',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'Vendors')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('Vendors','Vendors',1,9999999,'#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('Vendors',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'PosMenuID')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('PosMenuID','Pos menu header',1,9999999,'#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('PosMenuID',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'PosMenuLN')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('PosMenuLN','Pos menu line',1,9999999,'#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('PosMenuLN',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'Contacts')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('Contacts','Contacts',1,9999999,'#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('Contacts',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'Reasons')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('Reasons','Reason codes',1,9999999,'R#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('Reasons',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'PriceGroup')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('PriceGroup','Price group',1,9999999,'PG#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('PriceGroup',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'LineDiscountG')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('LineDiscountG','Line discount group',1,9999999,'LDG######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('LineDiscountG',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'MultiLineDiscountG')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('MultiLineDiscountG','Multi line discount group',1,9999999,'MLDG#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('MultiLineDiscountG',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'TotalDiscountG')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('TotalDiscountG','Total discount group',1,9999999,'TDG#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('TotalDiscountG',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'VendorItems')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('VendorItems','Vendor items',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('VendorItems',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'InventJournal')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('InventJournal','Inventory journal',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('InventJournal',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'PurchaseOrders')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('PurchaseOrders','Purchase Orders',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('PurchaseOrders',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'DiningTableLayout')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('DiningTableLayout','Dining table layout',1,99999999,'DTL########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('DiningTableLayout',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'RestaurantStation')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('RestaurantStation','Restaurant station',1,99999999,'RS########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('RestaurantStation',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'StationPrintingRoute')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('StationPrintingRoute','Station printing route',1,99999999,'SPR########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('StationPrintingRoute',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'StatementInfo')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('StatementInfo','Statement IDs',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('StatementInfo',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'PurchaseOrderLine')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('PurchaseOrderLine','Purchase order line number',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('PurchaseOrderLine',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'GoodsReceivingLine')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('GoodsReceivingLine','Goods receiving document line',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('GoodsReceivingLine',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'StatementLine')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('StatementLine','Statement line',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('StatementLine',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'JournalLineNum')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('JournalLineNum','Journal line number',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('JournalLineNum',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'ButtonGrid')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('ButtonGrid','Button Grid ID',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('ButtonGrid',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'ButtonGridButtons')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('ButtonGridButtons','Button Grid Buttons ID',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('ButtonGridButtons',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'RETAILGROUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('RETAILGROUP','Retail group',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('RETAILGROUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'RETAILDIVISION')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('RETAILDIVISION','Retail division',1,99999999,'D########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('RETAILDIVISION',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'RETAILDEPARTMENT')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('RETAILDEPARTMENT','Retail department',1,99999999,'RD########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('RETAILDEPARTMENT',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'SPECIALGROUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('SPECIALGROUP','Special group',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('SPECIALGROUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'SALESTYPES')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('SALESTYPES','Sales types',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('SALESTYPES',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'CUSTOMER')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('CUSTOMER','Customer',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('CUSTOMER',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'DISCOUNTPERIOD')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('DISCOUNTPERIOD','Discount period',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('DISCOUNTPERIOD',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'VISUALPROFILE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('VISUALPROFILE','Visual profile',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('VISUALPROFILE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'FUNCTIONALITYPROFILE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('FUNCTIONALITYPROFILE','Functionality profile',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('FUNCTIONALITYPROFILE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'HARDWAREPROFILE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('HARDWAREPROFILE','Hardware profile',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('HARDWAREPROFILE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'TOUCHLAYOUT')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('TOUCHLAYOUT','Touch button layout',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('TOUCHLAYOUT',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'TRANSACTIONPRF')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('TRANSACTIONPRF','Transaction service profile',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('TRANSACTIONPRF',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'TENDERTYPE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('TENDERTYPE','Payment methods',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('TENDERTYPE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'CARDTYPE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('CARDTYPE','Card types',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('CARDTYPE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'TAXGROUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('TAXGROUP','Tax group',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('TAXGROUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'ITEMTAXGROUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('ITEMTAXGROUP','Item tax group',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('ITEMTAXGROUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'TAXCODE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('TAXCODE','Tax code',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('TAXCODE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'BARCODESETUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('BARCODESETUP','Bar code setup',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('BARCODESETUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'BARCODEMASK')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('BARCODEMASK','Bar code mask setup',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('BARCODEMASK',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'COLOR')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('COLOR','Color',1,99999,'C#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('COLOR',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'SIZE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('SIZE','Size',1,99999,'S#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('SIZE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'STYLE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('STYLE','Style',1,99999,'ST#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('STYLE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'COLORGROUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('COLORGROUP','Color group',1,99999,'CG#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('COLORGROUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'SIZEGROUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('SIZEGROUP','Size group',1,99999,'SG#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('SIZEGROUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'STYLEGROUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('STYLEGROUP','Style group',1,99999,'STG#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('STYLEGROUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'VARIATIONGROUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('VARIATIONGROUP','Variation group',1,99999,'VG#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('VARIATIONGROUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'HOSPITALITY_COLOR')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('HOSPITALITY_COLOR','Hospitality color',1,99999,'C#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('HOSPITALITY_COLOR',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'UNITS')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('UNITS','Units',1,99999,'U#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('UNITS',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'POSLOOKUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('POSLOOKUP','Pos lookup',1,99999,'PL#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('POSLOOKUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'INFOCODE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('INFOCODE','Infocode',1,99999,'INF#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('INFOCODE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'INFOCODESUBCODE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('INFOCODESUBCODE','Infocode subcode',1,99999,'SUB#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('INFOCODESUBCODE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'POSMMLINEGROUPS')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('POSMMLINEGROUPS','Mix and match line groups',1,9999999,'#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('POSMMLINEGROUPS',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'REMOTEHOSTS')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('REMOTEHOSTS','Remote hosts',1,9999999,'#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('REMOTEHOSTS',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'STATIONPRINTINGHOSTS')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('STATIONPRINTINGHOSTS','Station Printing hosts',1,99999,'SPH#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('STATIONPRINTINGHOSTS',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'PURCHASEORDERMISCC')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('PURCHASEORDERMISCC','PO misc charges line',1,9999999,'#######',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('PURCHASEORDERMISCC',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'EODTRANSACTIONID')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('EODTRANSACTIONID','EOD transaction ID',1,99999,'EOD#####',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('EODTRANSACTIONID',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'GIFTCARD')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('GIFTCARD','Gift card',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('GIFTCARD',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'CREDITVOUCHER')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('CREDITVOUCHER','Credit voucher',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('CREDITVOUCHER',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'SUSPENDTRANS')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('SUSPENDTRANS','Suspended transactions',1,99999999,'########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('SUSPENDTRANS',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'RECEIPTID')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('RECEIPTID','Receipt ID',1,999999999,'#########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('RECEIPTID',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'TRANSACTIONID')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('TRANSACTIONID','Transaction ID',1,999999999,'##########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('TRANSACTIONID',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'INCOMEEXPENSEACCOUNT')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('INCOMEEXPENSEACCOUNT','Income expense accounts',1,999999999,'#########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('INCOMEEXPENSEACCOUNT',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'POSIMAGES')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('POSIMAGES','Logo images used in LS POS',1,999999999,'#########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('POSIMAGES',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'POSSTYLEPROFILELINE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('POSSTYLEPROFILELINE','Profile consisting of styles',1,999999999,'#########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('POSSTYLEPROFILELINE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'POSCONTEXT')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('POSCONTEXT','Profile consisting of styles',1,999999999,'#########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('POSCONTEXT',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'POSISFORMLAYOUT')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('POSISFORMLAYOUT','Forms',1,999999999,'#########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('POSISFORMLAYOUT',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'RECEIPTPROFILELINES')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('RECEIPTPROFILELINES','Receipts',1,999999999,'#########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('RECEIPTPROFILELINES',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'TERMINALSGROUPS')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('TERMINALSGROUPS','Terminal groups',1,999999999,'#########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('TERMINALSGROUPS',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'INVENTTRANSFER')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('INVENTTRANSFER','Inventory transfer',1,999999999,'#########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('INVENTTRANSFER',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'INVENTTRANSFERREQ')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('INVENTTRANSFERREQ','Inventory transfer request',1,999999999,'#########',1,1,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('INVENTTRANSFERREQ',1,'HO',@dataAreaID)
end

IF NOT EXISTS(SELECT * FROM [dbo].[NUMBERSEQUENCETABLE] WHERE [NUMBERSEQUENCE]='LOYALTYCARD' AND [DATAAREAID]='LSR')
BEGIN
	INSERT [dbo].[NUMBERSEQUENCETABLE] ([NUMBERSEQUENCE], [TXT], [LOWEST], [HIGHEST], [BLOCKED], [FORMAT], [CONTINUOUS], [CYCLIC], [CLEANATACCESS], [INUSE], [NOINCREMENT], [CLEANINTERVAL], [LATESTCLEANDATE], [LATESTCLEANTIME], [ALLOWCHANGEUP], [ALLOWCHANGEDOWN], [MANUAL], [FETCHAHEADQTY], [FETCHAHEAD], [MODIFIEDTRANSACTIONID], [DATAAREAID], [EMBEDSTOREID], [STOREID], [CANBEDELETED]) 
	VALUES (N'LOYALTYCARD', N'Loyalty card', 1, 9999999, 0, N'1#######', 0, 0, 0, 1, 0, CAST(0.000000000000 AS Numeric(28, 12)), CAST(0x0000000000000000 AS DateTime), 0, 0, 0, 0, 0, 0, 0, N'LSR', 1, N'HO', 0)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values (N'LOYALTYCARD',1,'HO',@dataAreaID)
END

IF NOT EXISTS(SELECT * FROM [dbo].[NUMBERSEQUENCETABLE] WHERE [NUMBERSEQUENCE]='LOYALTYSCHEME' AND [DATAAREAID]='LSR')
BEGIN
	INSERT [dbo].[NUMBERSEQUENCETABLE] ([NUMBERSEQUENCE], [TXT], [LOWEST], [HIGHEST], [BLOCKED], [FORMAT], [CONTINUOUS], [CYCLIC], [CLEANATACCESS], [INUSE], [NOINCREMENT], [CLEANINTERVAL], [LATESTCLEANDATE], [LATESTCLEANTIME], [ALLOWCHANGEUP], [ALLOWCHANGEDOWN], [MANUAL], [FETCHAHEADQTY], [FETCHAHEAD], [MODIFIEDTRANSACTIONID], [DATAAREAID], [EMBEDSTOREID], [STOREID], [CANBEDELETED]) 
	VALUES (N'LOYALTYSCHEME', N'Loyalty scheme', 1, 99999999, 0, N'########', 0, 0, 0, 1, 0, CAST(0.000000000000 AS Numeric(28, 12)), CAST(0x0000000000000000 AS DateTime), 0, 0, 0, 0, 0, 0, 0, N'LSR', 1, N'HO', 0)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values (N'LOYALTYSCHEME',1,'HO',@dataAreaID)
END

IF NOT EXISTS(SELECT * FROM [dbo].[NUMBERSEQUENCETABLE] WHERE [NUMBERSEQUENCE]='WIZARDTEMPLATE' AND [DATAAREAID]='LSR')
BEGIN
	INSERT [dbo].[NUMBERSEQUENCETABLE] ([NUMBERSEQUENCE], [TXT], [LOWEST], [HIGHEST], [BLOCKED], [FORMAT], [CONTINUOUS], [CYCLIC], [CLEANATACCESS], [INUSE], [NOINCREMENT], [CLEANINTERVAL], [LATESTCLEANDATE], [LATESTCLEANTIME], [ALLOWCHANGEUP], [ALLOWCHANGEDOWN], [MANUAL], [FETCHAHEADQTY], [FETCHAHEAD], [MODIFIEDTRANSACTIONID], [DATAAREAID], [EMBEDSTOREID], [STOREID], [CANBEDELETED]) 
	VALUES (N'WIZARDTEMPLATE', N'Wizard Template', 1, 99999999, 0, N'########', 0, 0, 0, 1, 0, CAST(0.000000000000 AS Numeric(28, 12)), CAST(0x0000000000000000 AS DateTime), 0, 0, 0, 0, 0, 0, 0, N'LSR', 1, N'HO', 0)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values (N'WIZARDTEMPLATE',1,'HO',@dataAreaID)
END

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'INVENTORYTEMPLATE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('INVENTORYTEMPLATE','Inventory template',1,999999,'IT######',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('INVENTORYTEMPLATE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'PURCHASEWORKSHEET')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('PURCHASEWORKSHEET','Purchase worksheet',1,999999,'PW######',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('PURCHASEWORKSHEET',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'BTNSTYLES')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('BTNSTYLES','Styles',1,999999999,'#########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('BTNSTYLES',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'LABELTEMPLATES')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('LABELTEMPLATES','Label templates',1,999999,'LT######',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('LABELTEMPLATES',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'CUSTOMERORDERS')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('CUSTOMERORDERS','Customer orders',1,99999999,'########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('CUSTOMERORDERS',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'QUOTES')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('QUOTES','Quotes',1,99999999,'########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('QUOTES',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'EFTMAPPING')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('EFTMAPPING','EFT Mapping',1,99999999,'########',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('EFTMAPPING',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'CUSTGROUPCATEGORY')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('CUSTGROUPCATEGORY','Customer Categories',1,9999,'CAT####',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('CUSTGROUPCATEGORY',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'CUSTGROUP')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('CUSTGROUP','Customer Groups',1,9999,'CGR####',1,0,0,'HO',@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('CUSTGROUP',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'SALESSEQUENCE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,WRAPAROUND,DATAAREAID)
	values ('SALESSEQUENCE','Sales sequence',1,9999,'####',1,0,0,'HO',1,@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('SALESSEQUENCE',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'FLOORLAYOUT')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,WRAPAROUND,DATAAREAID)
	values ('FLOORLAYOUT','Dining table floor layout',1,99999,'#####',1,0,0,'HO',1,@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('FLOORLAYOUT',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'COUPON')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,WRAPAROUND,DATAAREAID)
	values ('COUPON','Coupons',1,99999,'#####',1,0,0,'HO',1,@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('COUPON',1,'HO',@dataAreaID)
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'PRICEID')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,WRAPAROUND,DATAAREAID)
	values ('PRICEID','Trade agreement price ID',1,99999999,'########',1,0,0,'HO',1,@dataAreaID)
	
	IF NOT EXISTS(SELECT * FROM dbo.NUMBERSEQUENCEVALUE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'PRICEID')
	BEGIN
		insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
		values ('PRICEID',1,'HO',@dataAreaID)
	END
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'STAFFID')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,WRAPAROUND,DATAAREAID)
	values ('STAFFID','Staff ID',1,99999,'#####',1,0,0,'HO',1,@dataAreaID)
	
	IF NOT EXISTS(SELECT * FROM dbo.NUMBERSEQUENCEVALUE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'STAFFID')
	BEGIN
		insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
		values ('STAFFID',1,'HO',@dataAreaID)
	END
end

IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = @dataAreaID and NUMBERSEQUENCE = 'CUSTOMERORDERS')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,WRAPAROUND,DATAAREAID)
	values ('CUSTOMERORDERS','Customer orders',1,99999,'#####',1,0,0,'HO',1,@dataAreaID)
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('CUSTOMERORDERS',1,'HO',@dataAreaID)
end

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NUMBERSEQUENCEVALUE' AND COLUMN_NAME = 'NEXTREC')
BEGIN
	IF EXISTS (SELECT * FROM NUMBERSEQUENCEVALUE WHERE NEXTREC = 1 AND NUMBERSEQUENCE = 'RECEIPTID')
	BEGIN
		IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NUMBERSEQUENCETABLE' AND COLUMN_NAME = 'EMBEDTERMINALID')
		BEGIN
			UPDATE NUMBERSEQUENCETABLE 
			SET EMBEDTERMINALID = 1 
			WHERE NUMBERSEQUENCE = 'RECEIPTID'
		END
	END
END

-- System settings
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{0d44bba0-3041-11df-9aae-0800200c9a66}', 'SerialNumber', '','Customer serial number', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{7cb84d26-b28b-4086-8dcf-646f68cef956}', 'PasswordExpires', '90','User password expiration in days', 0,1,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{cf221fb0-c4b6-4574-9739-ef227d0b06e8}', 'PasswordGracePeriod', '5','Grace period before password expiration (in days)', 0,1,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{6278ea02-cc60-4ad2-bea6-88cd0a8312ab}', 'LockoutThreshold', '3','Password lockout threshold', 0,1,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{17e851c0-3037-11df-9aae-0800200c9a66}', 'WriteAuditing', '1','One if write auditing is turned on else zero', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{5eb2a48e-ffec-4acd-82ac-4f8929ee7d15}', 'OperationAuditing', '2','0=no auditing, 1=log audit operations, 2=log audit operations for manager approval', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{2cf043aa-b7c2-4158-90ee-69ac5b7aec32}', 'NameConvention', '1','Controls how names are displayed', 1,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{f67862df-49a7-4da6-bf52-14632064a428}', 'AddressConvention', '1','Controls how addresses are displayed', 1,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{be5cd3f0-69c5-11db-bd13-0800200c9a66}', 'ActiveDirectoryEnabled', '0','One if Active Directory Users can be used, zero if not', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{e489e620-a91a-11de-8a39-0800200c9a66}', 'Domain', '','Active directory domain', 0,1,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{84D5DC5A-6DD5-4450-A5BC-9479CB62C266}', 'AddTaxToPurchaseOrder', '1','Add tax to purchase order', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{2880A888-7EB6-49B3-AC1C-1024DE0F9EE4}', 'MaxOverReceiveGoods', '0','Maximum amount that you can receive in excess to what you orderd in a PO', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{2BAB2653-C366-480E-8DC2-99107BC03D5F}', 'CostCalculation', '0','Calculation method of item purchase price', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{47602dcc-ba81-45fe-acf8-8033e9fcc7a9}', 'BlindReceivingPurchaseOrder', '0','Allow blind posting and receiving of purchase orders in Omni inventory', 0,1,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{B51D48B7-3E2A-4FA4-8B1B-4A6C17F4F9BE}', 'KitchenManagerHost', '','Host address of Kitchen Manager', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{9C1E9A4E-E442-4CE3-8679-31CD62815521}', 'KitchenManagerPort', '0','Port of Kitchen Manager', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'

exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{813F1380-ADAE-4110-88D5-7FEBAE948BD6}', 'POSFormUserLocationAndSize', '','The user selected location and size of POS window', 1,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{519F9C0D-6190-4BAA-B397-6082CD9E88C6}', 'POSFormUserStartMode', '','The start mode of the POS window', 1,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'

exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{67599422-85E1-4976-9161-689EFF3B78FB}', 'TaxFreeReportTopMargin', '3.0cm','Tax free report top margin', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'
exec spMAINT_AddSystemSetting_1_0 @dataAreaID,'{9C1E9A4E-E442-4CE3-8679-31CD62815521}', 'TaxFreeReportLeftMargin', '0.8cm','Tax free report left margin', 0,0,'c79ae480-7ee1-11db-9fe1-0800200c9a66'

GO
