/*
	Incident No.	: ONE-7032
	Responsible		: Adrian Chiorean
	Sprint			: Äpplarö
	Date created	: 10.06.2017

	Description		: Create REGION table.
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'REGION')
BEGIN
	CREATE TABLE REGION (
		[ID] NVARCHAR(20) NOT NULL PRIMARY KEY,
		[DESCRIPTION] NVARCHAR(250) NOT NULL
		)
END
GO

IF NOT EXISTS(SELECT 1 FROM dbo.NUMBERSEQUENCETABLE where DATAAREAID = 'LSR' and NUMBERSEQUENCE = 'REGION')
BEGIN
	INSERT INTO dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
		VALUES ('REGION','Regions',1,999999999,'RG#######',1,0,0,'HO','LSR')
	INSERT INTO dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
		VALUES ('REGION',1,'HO','LSR')
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'REGIONID' AND TABLE_NAME = 'RBOSTORETABLE')
BEGIN
	ALTER TABLE RBOSTORETABLE ADD REGIONID NVARCHAR(20) NULL
END
GO