/*
	Incident No.	: ONE-6984
	Responsible		: Adrian Chiorean
	Sprint			: Äpplarö
	Date created	: 19.06.2017

	Description		: Update CustomerAddress table. Create Customer table. Migrate existing customers to new table
*/

USE LSPOSNET

--Update CustomerAddress table
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERADDRESS' AND COLUMN_NAME = 'ISDEFAULT')
BEGIN
	ALTER TABLE CUSTOMERADDRESS ADD ISDEFAULT BIT NOT NULL DEFAULT (0)
END
GO

CREATE TABLE #indexTable (CreateIndex BIT NOT NULL)
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMERADDRESS' AND COLUMN_NAME = 'ID')
BEGIN	
	ALTER TABLE CUSTOMERADDRESS ADD ID uniqueidentifier NOT NULL DEFAULT (newid()) WITH VALUES		

	INSERT INTO #indexTable VALUES (1)
END
GO

IF EXISTS(SELECT 1 FROM #indexTable WHERE CreateIndex = 1)
BEGIN
	-- Recreate index
	ALTER TABLE CUSTOMERADDRESS DROP CONSTRAINT PK_CUSTOMERADDRESS
	ALTER TABLE CUSTOMERADDRESS ADD CONSTRAINT PK_CUSTOMERADDRESS PRIMARY KEY (ACCOUNTNUM, DATAAREAID, ID)

	-- Set all existing addresses as default
	UPDATE CUSTOMERADDRESS SET ISDEFAULT = 1 WHERE ADDRESSTYPE = 2
	UPDATE CUSTOMERADDRESS SET ISDEFAULT = 1, ADDRESSTYPE = 1 WHERE ADDRESSTYPE = 0

	DECLARE @ACCOUNTNUM NVARCHAR(20)
	DECLARE @ID uniqueidentifier
	DECLARE @ADDRESSTYPE INT

	DECLARE ADDRESSCURSOR CURSOR FOR
	SELECT ACCOUNTNUM, ADDRESSTYPE, ID FROM CUSTOMERADDRESS WHERE ADDRESSTYPE = 1 AND ISDEFAULT = 0

	OPEN ADDRESSCURSOR

	FETCH FROM ADDRESSCURSOR INTO @ACCOUNTNUM, @ADDRESSTYPE, @ID

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF NOT EXISTS(SELECT 1 FROM CUSTOMERADDRESS WHERE ID != @ID AND ACCOUNTNUM = @ACCOUNTNUM AND ADDRESSTYPE = @ADDRESSTYPE AND ISDEFAULT = 1)
		BEGIN
			UPDATE CUSTOMERADDRESS SET ISDEFAULT = 1 WHERE ID = @ID AND ACCOUNTNUM = @ACCOUNTNUM
		END
	END

	CLOSE ADDRESSCURSOR
	DEALLOCATE ADDRESSCURSOR
END
GO

DROP TABLE #indexTable
GO

--Add CUSTOMER table
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUSTOMER')
BEGIN
	CREATE TABLE CUSTOMER
	(
		MASTERID UNIQUEIDENTIFIER NOT NULL,
		ACCOUNTNUM NVARCHAR(61) NOT NULL,
		NAME NVARCHAR(200) NULL,
		INVOICEACCOUNT NVARCHAR(61) NULL,
		FIRSTNAME NVARCHAR(60) NULL,
		MIDDLENAME NVARCHAR(60) NULL,
		LASTNAME NVARCHAR(60) NULL,
		NAMEPREFIX NVARCHAR(8) NULL,
		NAMESUFFIX NVARCHAR(8) NULL,
		CURRENCY NVARCHAR(3) NULL,
		LANGUAGEID NVARCHAR(5) NULL,
		TAXGROUP NVARCHAR(20) NULL,
		PRICEGROUP NVARCHAR(20) NULL,
		LINEDISC NVARCHAR(20) NULL,
		MULTILINEDISC NVARCHAR(20) NULL,
		ENDDISC NVARCHAR(20) NULL,
		CREDITMAX NUMERIC(28,12) NULL,
		ORGID NVARCHAR(20) NULL,
		BLOCKED INT NULL,
		NONCHARGABLEACCOUNT TINYINT NULL,
		INCLTAX TINYINT NULL,
		PHONE NVARCHAR(80) NULL,
		CELLULARPHONE NVARCHAR(80) NULL,
		NAMEALIAS NVARCHAR(80) NULL,
		CUSTGROUP NVARCHAR(20) NULL,
		VATNUM NVARCHAR(20) NULL,
		EMAIL NVARCHAR(80) NULL,
		[URL] NVARCHAR(255) NULL,
		TAXOFFICE NVARCHAR(20) NULL,
		USEPURCHREQUEST TINYINT NULL,
		LOCALLYSAVED TINYINT NULL,
		GENDER INT NULL,
		DATEOFBIRTH DATETIME NULL,
		RECEIPTOPTION INT NULL,
		RECEIPTEMAIL NVARCHAR(80) NULL,
		DATAAREAID NVARCHAR(4) NOT NULL,
		DELETED BIT NOT NULL DEFAULT (0),
		CONSTRAINT PK_CUSTOMER PRIMARY KEY (MASTERID, DATAAREAID),
		CONSTRAINT UC_CUSTOMER UNIQUE (ACCOUNTNUM)
	)

	EXECUTE spDB_SetTableDescription_1_0 'CUSTTABLE', 'Obsolete - Use the CUSTOMER table instead.';

	-- Migrate existing data
	INSERT INTO CUSTOMER (MASTERID, ACCOUNTNUM, NAME, INVOICEACCOUNT, FIRSTNAME, MIDDLENAME, LASTNAME, NAMEPREFIX, NAMESUFFIX, CURRENCY, LANGUAGEID, TAXGROUP,
						  PRICEGROUP, LINEDISC, MULTILINEDISC, ENDDISC, CREDITMAX, ORGID, BLOCKED, NONCHARGABLEACCOUNT, INCLTAX, PHONE, CELLULARPHONE, NAMEALIAS,
						  CUSTGROUP, VATNUM, EMAIL, [URL], TAXOFFICE, USEPURCHREQUEST, LOCALLYSAVED, GENDER, DATEOFBIRTH, RECEIPTOPTION, RECEIPTEMAIL, DATAAREAID, DELETED)
	SELECT NEWID(), ACCOUNTNUM, NAME, INVOICEACCOUNT, FIRSTNAME, MIDDLENAME, LASTNAME, NAMEPREFIX, NAMESUFFIX, CURRENCY, LANGUAGEID, TAXGROUP,
		   PRICEGROUP, LINEDISC, MULTILINEDISC, ENDDISC, CREDITMAX, ORGID, BLOCKED, NONCHARGABLEACCOUNT, INCLTAX, PHONE, CELLULARPHONE, NAMEALIAS,
		   CUSTGROUP, VATNUM, EMAIL, [URL], TAXOFFICE, USEPURCHREQUEST, LOCALLYSAVED, GENDER, DATEOFBIRTH, RECEIPTOPTION, RECEIPTEMAIL, DATAAREAID, DELETED
		   FROM CUSTTABLE
END
GO