/*
	Incident No.	: ONE-7188
	Responsible		: Simona Avornicesei
	Sprint			: Vardagen
	Date created	: 17.07.2017

	Description		: Add Omni main menu field to POSFUNCTIONALITYPROFILE table
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'OMNIMAINMENU')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD OMNIMAINMENU NVARCHAR(20) NULL
END
GO