/*
	Incident No.	: ONE-7178
	Responsible		: Adrian Chiorean
	Sprint			: Vardagen
	Date created	: 17.07.2017

	Description		: Add new fields to INVENTORYTEMPLATE
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATE' AND COLUMN_NAME = 'TEMPLATEENTRYTYPE')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD TEMPLATEENTRYTYPE INT NOT NULL DEFAULT 0
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATE' AND COLUMN_NAME = 'UNITSELECTION')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD UNITSELECTION INT NOT NULL DEFAULT 0
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATE' AND COLUMN_NAME = 'ENTERINGTYPE')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD ENTERINGTYPE INT NOT NULL DEFAULT 0
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATE' AND COLUMN_NAME = 'QUANTITYMETHOD')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD QUANTITYMETHOD INT NOT NULL DEFAULT 0
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATE' AND COLUMN_NAME = 'DEFAULTQUANTITY')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD DEFAULTQUANTITY NUMERIC(28,12) NOT NULL DEFAULT 0
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTORYTEMPLATE' AND COLUMN_NAME = 'AREAID')
BEGIN
	ALTER TABLE INVENTORYTEMPLATE ADD AREAID UNIQUEIDENTIFIER NULL
END
GO