/*
	Incident No.	: ONE-7294
	Responsible		: Adrian Chiorean
	Sprint			: Vardagen
	Date created	: 20.07.2017

	Description		: Add STAFFID and AREA to INVENTJOURNALTRANS
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANS' AND COLUMN_NAME = 'STAFFID')
BEGIN
	ALTER TABLE INVENTJOURNALTRANS ADD STAFFID NVARCHAR(20) NULL
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTRANS' AND COLUMN_NAME = 'AREA')
BEGIN
	ALTER TABLE INVENTJOURNALTRANS ADD AREA UNIQUEIDENTIFIER NULL
END
GO