/*
	Incident No.	: ONE-7355
	Responsible		: Adrian Chiorean
	Sprint			: Vardagen
	Date created	: 02.08.2017

	Description		: Add OMNI operations
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2100')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2100', 'Change store', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2101')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2101', 'Update master data', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2102')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2102', 'Full master data update', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2103')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2103', 'Customer / vendor full update', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2104')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2104', 'Item lookup', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2105')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2105', 'Customer lookup', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2106')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2106', 'Vendor lookup', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2107')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2107', 'Stock counting', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2108')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2108', 'Goods receiving', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2109')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2109', 'Post goods receiving', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2110')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2110', 'Purchase worksheet', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2111')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2111', 'Add to purchase worksheet', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2112')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2112', 'Post purchase worksheet', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2113')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2113', 'Price check', 3, 0, NULL)
END

IF NOT EXISTS(SELECT 1 FROM OPERATIONS WHERE ID = '2114')
BEGIN
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	VALUES (NEWID(), '2114', 'Price update', 3, 0, NULL)
END
GO