/*
	Incident No.	: ONE-7185
	Responsible		: Adrian Chiorean
	Sprint			: Vardagen
	Date created	: 13.07.2017

	Description		: Create table OPERATIONS and migrate old POSISOPERATIONS table
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'OPERATIONS')
BEGIN
	CREATE TABLE OPERATIONS
	(
		MASTERID UNIQUEIDENTIFIER NOT NULL,
		ID NVARCHAR(20) NOT NULL PRIMARY KEY,
		[DESCRIPTION] NVARCHAR(50) NOT NULL,
		[TYPE] INT NOT NULL,
		[LOOKUPTYPE] INT NOT NULL,
		[AUDIT] TINYINT NULL
	)

	EXECUTE spDB_SetTableDescription_1_0 'POSISOPERATIONS', 'Obsolete - Use the OPERATIONS table instead.';

	--  Migrate data
	--  Operation types: All = 0, SystemOperation = 1, POSOperation = 2
	INSERT INTO OPERATIONS (MASTERID, ID, [DESCRIPTION], [TYPE], [LOOKUPTYPE], [AUDIT])
	SELECT NEWID(), OPERATIONID, ISNULL(OPERATIONNAME, ''), CASE WHEN USEROPERATION = 0 THEN 1 ELSE 2 END, ISNULL(LOOKUPTYPE, 0), [AUDIT] FROM POSISOPERATIONS

	--  Set Open menu operation type to all
	UPDATE OPERATIONS SET [TYPE] = 0 WHERE ID = '1500'
END
GO