/*
	Incident No.	: ONE-7293
	Responsible		: Adrian Chiorean
	Sprint			: Vardagen
	Date created	: 17.07.2017

	Description		: Add tables INVENTORYAREA and INVENTORYAREALINES
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'INVENTORYAREA')
BEGIN
	CREATE TABLE INVENTORYAREA
	(
		MASTERID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
		[DESCRIPTION] NVARCHAR(250) NOT NULL,
		[TYPE] INT NOT NULL
	)
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'INVENTORYAREALINES')
BEGIN
	CREATE TABLE INVENTORYAREALINES
	(
		MASTERID UNIQUEIDENTIFIER NOT NULL,
		AREAID NVARCHAR(250) NOT NULL,
		[DESCRIPTION] NVARCHAR(250) NOT NULL,
		CONSTRAINT PK_INVENTORYAREALINES PRIMARY KEY(MASTERID, AREAID)
	)
END
GO