/*
	Incident No.	: ONE-7557
	Responsible		: Adrian Chiorean
	Sprint			: Vindum
	Date created	: 05.09.2017

	Description		: Add ShowPricesByDefault to functionality profile
*/

USE LSPOSNET

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'SHOWPRICESBYDEFAULT')
BEGIN
	ALTER TABLE POSFUNCTIONALITYPROFILE ADD SHOWPRICESBYDEFAULT BIT NOT NULL DEFAULT 0
END
GO