/*

	Incident No.	: ONE-8367
	Responsible		: Adrian Chiorean
	Sprint			: cheng

	Description		: Adding a column for a over short amounts in z reports, add store procedure for getting over short information
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POSFUNCTIONALITYPROFILE' AND COLUMN_NAME = 'ZRPTDISPLAYOVERSHORTAMOUNT')
BEGIN
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD ZRPTDISPLAYOVERSHORTAMOUNT BIT NOT NULL DEFAULT 0	
END
GO

IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[LSR_ZREPORT_OVERSHORT]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
DROP PROCEDURE [dbo].[LSR_ZREPORT_OVERSHORT]
GO

/****** Object:  StoredProcedure [dbo].[LSR_ZREPORT_OVERSHORT]    Script Date: 14-Feb-18 4:39:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[LSR_ZREPORT_OVERSHORT] 
@ZREPORTID NVARCHAR(20),
@STOREID NVARCHAR(20),
@TERMINALID NVARCHAR(20),
@DATAAREAID NVARCHAR(4)
AS

SELECT SUM(X.DECLAREDAMOUNT - X.AMOUNT) * -1 AS AMOUNT,
	X.TENDER, 
	X.TENDERNAME, 
	X.POSOPERATION FROM ( 
SELECT 
	ISNULL(SUM(PTR.AMOUNTTENDERED), 0) AMOUNT,
	0 AS DECLAREDAMOUNT,
	STT.TENDERTYPEID TENDER,
	TT.NAME AS TENDERNAME,
	STT.POSOPERATION
FROM 
	RBOSTORETENDERTYPETABLE STT
JOIN RBOTENDERTYPETABLE TT
	ON STT.DATAAREAID = TT.DATAAREAID
	AND STT.TENDERTYPEID = TT.TENDERTYPEID
LEFT JOIN RBOTRANSACTIONPAYMENTTRANS PTR
	ON PTR.STORE = STT.STOREID 
	AND PTR.DATAAREAID = STT.DATAAREAID 
	AND PTR.TENDERTYPE = STT.TENDERTYPEID
LEFT JOIN RBOTRANSACTIONTABLE TA 
	ON PTR.TRANSACTIONID = TA.TRANSACTIONID 
	AND PTR.DATAAREAID = TA.DATAAREAID 
	AND PTR.STORE = TA.STORE 
	AND PTR.TERMINAL = TA.TERMINAL	
	
WHERE TT.DEFAULTFUNCTION <> 4 	
  AND STT.COUNTINGREQUIRED = 1
  AND STT.STOREID = @STOREID
  AND (PTR.ZREPORTID IS NULL 
  OR (TA.ZREPORTID = @ZREPORTID
  AND TA.STORE = @STOREID
  AND TA.TERMINAL = @TERMINALID
  AND TA.DATAAREAID = @DATAAREAID
  AND TA.ENTRYSTATUS = 0	
  AND PTR.TRANSACTIONSTATUS = 0
  AND TA.TYPE in (2,3,4,5,16,17,20,21,22)))

GROUP BY STT.TENDERTYPEID, TT.NAME, STT.POSOPERATION

UNION

SELECT 
	0 AS AMOUNT,
	ISNULL(SUM(RT.AMOUNTTENDERED), 0) DECLAREDAMOUNT,
	STT.TENDERTYPEID TENDER,
	TT.NAME AS TENDERNAME,
	STT.POSOPERATION
FROM 
	RBOSTORETENDERTYPETABLE STT
JOIN RBOTENDERTYPETABLE TT
	ON STT.DATAAREAID = TT.DATAAREAID
	AND STT.TENDERTYPEID = TT.TENDERTYPEID
LEFT JOIN RBOTRANSACTIONTENDERDECLA20165 RT
	ON RT.TENDERTYPE = STT.TENDERTYPEID
	AND RT.DATAAREAID = STT.DATAAREAID
	AND RT.STORE = STT.STOREID
LEFT JOIN RBOTRANSACTIONTABLE TA
	ON TA.TRANSACTIONID = RT.TRANSACTIONID
	AND TA.DATAAREAID = RT.DATAAREAID
	AND TA.STORE = RT.STORE
	AND TA.TERMINAL = RT.TERMINAL

WHERE STT.COUNTINGREQUIRED = 1
AND STT.STOREID = @STOREID
AND TA.ZREPORTID IS NULL
OR (TA.ZREPORTID = @ZREPORTID
	AND TA.STORE = @STOREID
	AND TA.TERMINAL = @TERMINALID
	AND TA.DATAAREAID = @DATAAREAID
	AND TA.ENTRYSTATUS = 0
	AND TA.TYPE = 7)

GROUP BY STT.TENDERTYPEID, TT.NAME, STT.POSOPERATION) X 
GROUP BY X.TENDER, X.TENDERNAME, X.POSOPERATION
ORDER BY X.TENDERNAME

/****** END ******/
GO