/*

	Incident No.	: ONE-7844
	Responsible		: Adrian Chiorean
	Sprint			: Nymö
	Date created	: 18.10.2017

	Description		: Add to stock counting journal from multiple mobile devices
*/

USE LSPOSNET
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLE' AND COLUMN_NAME = 'CREATEDFROMOMNI')
BEGIN
	ALTER TABLE INVENTJOURNALTABLE ADD CREATEDFROMOMNI BIT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'INVENTJOURNALTABLE' AND COLUMN_NAME = 'TEMPLATEID')
BEGIN
	ALTER TABLE INVENTJOURNALTABLE ADD TEMPLATEID NVARCHAR(20) NULL
END
GO