/*

	Incident No.	: 
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: Ingabritta
	Date created	: 09.10.2017

	Description		: Site Service Delays - Creating stock counting journal
*/

USE LSPOSNET
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'IDX_RBOTRANSACTIONSALESTRANS_CREATEPOSTJOURNAL' AND object_id = OBJECT_ID('RBOTRANSACTIONSALESTRANS'))
BEGIN
	CREATE NONCLUSTERED INDEX [IDX_RBOTRANSACTIONSALESTRANS_CREATEPOSTJOURNAL] ON [dbo].[RBOTRANSACTIONSALESTRANS] ([ITEMID],[TRANSACTIONSTATUS],[STATEMENTID])
	INCLUDE ([TRANSACTIONID],[STORE],[TERMINALID],[UNITQTY],[REASONCODEID])
END
GO


