/*

	Incident No.	: ONE-6749
	Responsible		: Hörður Kristjánsson
	Sprint			: Algot - (11.8-23.8)
	Date created	: 20.08.2017

	Description		: Changing primary key for barcode mask segments
	
	
	Tables affected	: RBOBARCODEMASKSEGMENT
						
*/


USE LSPOSNET
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'RBOBARCODEMASKSEGMENT' AND CONSTRAINT_NAME = 'I_20089MASKSEGMENTIDX')
BEGIN
	ALTER TABLE RBOBARCODEMASKSEGMENT DROP CONSTRAINT I_20089MASKSEGMENTIDX
	ALTER TABLE RBOBARCODEMASKSEGMENT ADD CONSTRAINT PK_RBOBARCODEMASKSEGMENT PRIMARY KEY(MASKID, SEQUENCE, DATAAREAID)
END