//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Data Director.
        /// </summary>
        internal static string DataDirectorConnectedMsg {
            get {
                return ResourceManager.GetString("DataDirectorConnectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string DataDirectorConnectingMsg {
            get {
                return ResourceManager.GetString("DataDirectorConnectingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read design.
        /// </summary>
        internal static string DataDirectorDialogReadDesign {
            get {
                return ResourceManager.GetString("DataDirectorDialogReadDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string DataDirectorDialogTestConnection {
            get {
                return ResourceManager.GetString("DataDirectorDialogTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / Error Code: {1}.
        /// </summary>
        internal static string DataDirectorErrorFormatMsg {
            get {
                return ResourceManager.GetString("DataDirectorErrorFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Data Director: {0}.
        /// </summary>
        internal static string DataDirectorErrorMsg {
            get {
                return ResourceManager.GetString("DataDirectorErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception in Data Director: {0}, {1}.
        /// </summary>
        internal static string DataDirectorExceptionMsg {
            get {
                return ResourceManager.GetString("DataDirectorExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string DataDirectorInitializingMsg {
            get {
                return ResourceManager.GetString("DataDirectorInitializingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response was received: {0}.
        /// </summary>
        internal static string DataDirectorNoAnswerError {
            get {
                return ResourceManager.GetString("DataDirectorNoAnswerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        internal static string DataDirectorOperationCancelledMsg {
            get {
                return ResourceManager.GetString("DataDirectorOperationCancelledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed sucessfully.
        /// </summary>
        internal static string DataDirectorOperationOkMsg {
            get {
                return ResourceManager.GetString("DataDirectorOperationOkMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read fields for {0} tables.
        /// </summary>
        internal static string DataDirectorReadFieldsForTablesMsg {
            get {
                return ResourceManager.GetString("DataDirectorReadFieldsForTablesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading fields.
        /// </summary>
        internal static string DataDirectorReadingFieldsMsg {
            get {
                return ResourceManager.GetString("DataDirectorReadingFieldsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving database fields.
        /// </summary>
        internal static string DataDirectorSavingFieldsMsg {
            get {
                return ResourceManager.GetString("DataDirectorSavingFieldsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving database tables.
        /// </summary>
        internal static string DataDirectorSavingTablesMsg {
            get {
                return ResourceManager.GetString("DataDirectorSavingTablesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send failed: {0}.
        /// </summary>
        internal static string DataDirectorSendFailedError {
            get {
                return ResourceManager.GetString("DataDirectorSendFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables read: {0}.
        /// </summary>
        internal static string DataDirectorTablesReadMsg {
            get {
                return ResourceManager.GetString("DataDirectorTablesReadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection....
        /// </summary>
        internal static string DataDirectorTestingMsg {
            get {
                return ResourceManager.GetString("DataDirectorTestingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run job.
        /// </summary>
        internal static string JobRun {
            get {
                return ResourceManager.GetString("JobRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run job as normal.
        /// </summary>
        internal static string JobRunAsNormal {
            get {
                return ResourceManager.GetString("JobRunAsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to run job {0}?.
        /// </summary>
        internal static string JobRunConfirmMsg {
            get {
                return ResourceManager.GetString("JobRunConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when requesting a run of job {0}: {1}.
        /// </summary>
        internal static string JobRunErrorMsg {
            get {
                return ResourceManager.GetString("JobRunErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred when trying to run a job: {0}, {1}.
        /// </summary>
        internal static string JobRunExceptionMsg {
            get {
                return ResourceManager.GetString("JobRunExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run job.
        /// </summary>
        internal static string JobRunHeader {
            get {
                return ResourceManager.GetString("JobRunHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scheduler service did not respond to the request. Make sure that the Service is running and configured or Scheduler Setup is pointing to correct host..
        /// </summary>
        internal static string JobRunNoResponseMsg {
            get {
                return ResourceManager.GetString("JobRunNoResponseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} was successfully submitted for run..
        /// </summary>
        internal static string JobRunOkMsg {
            get {
                return ResourceManager.GetString("JobRunOkMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scheduler service returned the following error: {0}.
        /// </summary>
        internal static string JobRunServiceError {
            get {
                return ResourceManager.GetString("JobRunServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job can not be run because it failed validation.
        ///
        ///{0}.
        /// </summary>
        internal static string JobRunValidationFailureMsg {
            get {
                return ResourceManager.GetString("JobRunValidationFailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} job(s) have errors, see job log or message log for details..
        /// </summary>
        internal static string RunJobErrorStatusFormat {
            get {
                return ResourceManager.GetString("RunJobErrorStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} scheduler job(s) are being submitted..
        /// </summary>
        internal static string RunJobPendingStatusFormat {
            get {
                return ResourceManager.GetString("RunJobPendingStatusFormat", resourceCulture);
            }
        }
    }
}
