//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter weight.
        /// </summary>
        internal static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended error.
        /// </summary>
        internal static string ExtendedError {
            get {
                return ResourceManager.GetString("ExtendedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal.
        /// </summary>
        internal static string Illegal {
            get {
                return ResourceManager.GetString("Illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input was detected.Please check the scale.
        /// </summary>
        internal static string NoInputDetectedCheckScale {
            get {
                return ResourceManager.GetString("NoInputDetectedCheckScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reconnect the scale.
        /// </summary>
        internal static string ReconnectScale {
            get {
                return ResourceManager.GetString("ReconnectScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is disabled, Do you want to manually enter weight?.
        /// </summary>
        internal static string ScaleDisabledEnterManually {
            get {
                return ResourceManager.GetString("ScaleDisabledEnterManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is illegally closed.
        /// </summary>
        internal static string ScaleIllegallyClosed {
            get {
                return ResourceManager.GetString("ScaleIllegallyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight exceeds scale limits..
        /// </summary>
        internal static string ScaleInvalidWeight {
            get {
                return ResourceManager.GetString("ScaleInvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is closed..
        /// </summary>
        internal static string ScaleIsClosed {
            get {
                return ResourceManager.GetString("ScaleIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is disabled..
        /// </summary>
        internal static string ScaleIsDisabled {
            get {
                return ResourceManager.GetString("ScaleIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale is disabled, please reconnect the scale..
        /// </summary>
        internal static string ScaleIsDisabledReconnect {
            get {
                return ResourceManager.GetString("ScaleIsDisabledReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale setup or configuration error..
        /// </summary>
        internal static string ScaleNoService {
            get {
                return ResourceManager.GetString("ScaleNoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale timed out..
        /// </summary>
        internal static string ScaleTimedOut {
            get {
                return ResourceManager.GetString("ScaleTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare:.
        /// </summary>
        internal static string Tare {
            get {
                return ResourceManager.GetString("Tare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
