//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to restrictions on the selected payment no items can be paid for..
        /// </summary>
        internal static string CardCannotBuyItems {
            get {
                return ResourceManager.GetString("CardCannotBuyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined.
        /// </summary>
        internal static string Combined {
            get {
                return ResourceManager.GetString("Combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items excluded from payment.
        /// </summary>
        internal static string ItemsExcludedFromPayment {
            get {
                return ResourceManager.GetString("ItemsExcludedFromPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items included in payment.
        /// </summary>
        internal static string ItemsIncludedInPayment {
            get {
                return ResourceManager.GetString("ItemsIncludedInPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount for payment type.
        /// </summary>
        internal static string MaximumAmountForPaymentType {
            get {
                return ResourceManager.GetString("MaximumAmountForPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sales items to check..
        /// </summary>
        internal static string NoSalesTtemsCheck {
            get {
                return ResourceManager.GetString("NoSalesTtemsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only valid for a retail transaction.
        /// </summary>
        internal static string OperationOnlyValidRetailTransaction {
            get {
                return ResourceManager.GetString("OperationOnlyValidRetailTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This payment must be used to finalize the transaction.
        /// </summary>
        internal static string PaymentFinalizeTransaction {
            get {
                return ResourceManager.GetString("PaymentFinalizeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to payment limitations attached to the selected payment method, the items listed here will be excluded from the payment..
        /// </summary>
        internal static string PaymentLimitationsExcludeTheseItems {
            get {
                return ResourceManager.GetString("PaymentLimitationsExcludeTheseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to payment limitations attached to the selected payment method, only the items listed here will be included in the payment..
        /// </summary>
        internal static string PaymentLimitationsIncludeTheseItems {
            get {
                return ResourceManager.GetString("PaymentLimitationsIncludeTheseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select another payment method to finish the sale..
        /// </summary>
        internal static string PleaseSelectAnotherPayment {
            get {
                return ResourceManager.GetString("PleaseSelectAnotherPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refundable amount limited to payment type.
        /// </summary>
        internal static string RefundableAmountLimitedToPaymentType {
            get {
                return ResourceManager.GetString("RefundableAmountLimitedToPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount of {0} can be paid with the tender.
        /// </summary>
        internal static string TotalAmountCanBePaidWithTheTender {
            get {
                return ResourceManager.GetString("TotalAmountCanBePaidWithTheTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
