
/*

	Incident No.	: ONE-4605
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Todmobil

	Description		: Adding a column for a deleted flag
	
						
*/

USE LSPOSNET
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'VENDTABLE' AND COLUMN_NAME = 'DELETED')
BEGIN
	ALTER TABLE dbo.VENDTABLE ADD DELETED BIT NULL	
	ALTER TABLE dbo.VENDTABLE ADD CONSTRAINT DF_VENDTABLE_DELETED DEFAULT 0 FOR DELETED

END
GO

UPDATE VENDTABLE
SET DELETED = 0
WHERE DELETED IS NULL


GO

