/*

	Incident No.	: ONE-5128
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: Fræbblarninr
	Date created	: 30.9.2016

	Description		: Set CustTable fields to correct length
	
	
	Tables affected	: CUSTTABLE
						
*/
USE LSPOSNET
GO
  
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CUSTTABLE' AND COLUMN_NAME = 'NAME' AND CHARACTER_MAXIMUM_LENGTH < 200  )
BEGIN
	ALTER TABLE dbo.CUSTTABLE  
	ALTER COLUMN NAME NVARCHAR(200)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CUSTTABLE' AND COLUMN_NAME = 'FIRSTNAME' AND CHARACTER_MAXIMUM_LENGTH < 60  )
BEGIN
	ALTER TABLE dbo.CUSTTABLE  
	ALTER COLUMN FIRSTNAME NVARCHAR(60)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CUSTTABLE' AND COLUMN_NAME = 'MIDDLENAME' AND CHARACTER_MAXIMUM_LENGTH < 60  )
BEGIN
	ALTER TABLE dbo.CUSTTABLE  
	ALTER COLUMN MIDDLENAME NVARCHAR(60)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CUSTTABLE' AND COLUMN_NAME = 'LASTNAME' AND CHARACTER_MAXIMUM_LENGTH < 60  )
BEGIN
	ALTER TABLE dbo.CUSTTABLE  
	ALTER COLUMN LASTNAME NVARCHAR(60)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CUSTTABLE' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.CUSTTABLE  
	ALTER COLUMN PHONE NVARCHAR(80)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CUSTTABLE' AND COLUMN_NAME = 'NAMEALIAS' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.CUSTTABLE  
	ALTER COLUMN NAMEALIAS NVARCHAR(80)
END	
GO