
/*

	Incident No.	: ONE-4297
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: Stuðmenn

	Description		: Unique ID for item images
	
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEMIMAGE' AND COLUMN_NAME = 'IMAGEID')
Begin
	
	ALTER TABLE dbo.RETAILITEMIMAGE DROP CONSTRAINT PK_RETAILITEMIMAGE
	ALTER TABLE dbo.RETAILITEMIMAGE ADD IMAGEID uniqueidentifier NOT NULL DEFAULT NEWID()
	ALTER TABLE [dbo].[RETAILITEMIMAGE] ADD CONSTRAINT [PK_RETAILITEMIMAGEID] PRIMARY KEY CLUSTERED 
	(
		[IMAGEID] ASC
	)
END

