/*
	Incident No.	: ONE-4737
	Responsible		: Stefan Contiu
	Sprint			: Sigur Ros

	Description		: Create tables used for storing import profiles
*/
Use LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'IMPORTPROFILE')
BEGIN
	CREATE TABLE [IMPORTPROFILE]
	(
		[MASTERID] uniqueidentifier NOT NULL,
		[ID] nvarchar(20) NOT NULL,
		[DESCRIPTION] nvarchar(60) NULL,
		[IMPORTTYPE] int NOT NULL,
		[DEFAULT] tinyint NOT NULL,
		CONSTRAINT [PK_IMPORTPROFILE] PRIMARY KEY CLUSTERED 
		(
			[MASTERID] ASC
		)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IMPORTPROFILE' AND COLUMN_NAME = 'MASTERID' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[IMPORTPROFILE] ADD  CONSTRAINT [DF_IMPORTPROFILE_MASTERID]  DEFAULT (newid()) FOR [MASTERID]	
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IMPORTPROFILE' AND COLUMN_NAME = 'ID' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[IMPORTPROFILE] ADD  CONSTRAINT [DF_IMPORTPROFILE_ID]  DEFAULT ('') FOR [ID]	
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IMPORTPROFILE' AND COLUMN_NAME = 'DESCRIPTION' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[IMPORTPROFILE] ADD  CONSTRAINT [DF_IMPORTPROFILE_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]	
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IMPORTPROFILE' AND COLUMN_NAME = 'DEFAULT' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[IMPORTPROFILE] ADD  CONSTRAINT [DF_IMPORTPROFILE_DEFAULT]  DEFAULT ((0)) FOR [DEFAULT]	
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'IMPORTPROFILELINES')
BEGIN
	CREATE TABLE [IMPORTPROFILELINES]
	(
		[MASTERID] uniqueidentifier NOT NULL,
		[IMPORTPROFILEMASTERID] uniqueidentifier NOT NULL,
		[FIELD] int NOT NULL,
		[FIELDTYPE] int NOT NULL,
		[SEQUENCE] int NOT NULL,
		CONSTRAINT [PK_IMPORTPROFILELINES] PRIMARY KEY CLUSTERED 
		(
			[MASTERID] ASC
		)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IMPORTPROFILELINES' AND COLUMN_NAME = 'MASTERID' AND COLUMN_DEFAULT IS NULL)
BEGIN
	ALTER TABLE [dbo].[IMPORTPROFILELINES] ADD  CONSTRAINT [DF_IMPORTPROFILELINES_MASTERID]  DEFAULT (newid()) FOR [MASTERID]	
END
GO

------------------------------------
-- 
   
IF not EXISTS(SELECT * FROM dbo.NUMBERSEQUENCETABLE where NUMBERSEQUENCE = 'IMPORTPROFILE')
begin
	insert into dbo.NUMBERSEQUENCETABLE (NUMBERSEQUENCE,TXT,LOWEST,HIGHEST,FORMAT,INUSE,EMBEDSTOREID,CANBEDELETED,STOREID,DATAAREAID)
	values ('IMPORTPROFILE','Import profile',1,99999999,'########',1,1,0,'HO','LSR')
	insert into dbo.NUMBERSEQUENCEVALUE (NUMBERSEQUENCE,NEXTREC,STOREID,DATAAREAID)
	values ('IMPORTPROFILE',1,'HO','LSR')
end