
/*

	Incident No.	: ONE-4383
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Todmobil

	Description		: Adding columns for created and posted groups as well as received and ordered information
	
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GOODSRECEIVING' AND COLUMN_NAME = 'CREATEDDATE')
BEGIN
	ALTER TABLE dbo.GOODSRECEIVING ADD CREATEDDATE [DATETIME] NULL
	ALTER TABLE [dbo].[GOODSRECEIVING] ADD  CONSTRAINT [DF_GOODSRECEIVING_CREATEDDATE]  DEFAULT (getdate()) FOR [CREATEDDATE]
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GOODSRECEIVING' AND COLUMN_NAME = 'POSTEDDATE')
BEGIN
	ALTER TABLE dbo.GOODSRECEIVING ADD POSTEDDATE [DATETIME] NULL
END
GO

