
/*

	Incident No.	: ONE-1303
	Responsible		: Hörður Kristjánsson
	Sprint			: Rome

	Description		: Adding a configuration to control wether an item can be returned or not
	
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RETAILITEM' AND COLUMN_NAME = 'RETURNABLE')
Begin
	ALTER TABLE dbo.RETAILITEM ADD RETURNABLE bit NOT NULL CONSTRAINT [DF_RETAILITEM_RETURNABLE] DEFAULT(1)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RBOTRANSACTIONSALESTRANS' AND COLUMN_NAME = 'RETURNABLE')
Begin
	ALTER TABLE dbo.RBOTRANSACTIONSALESTRANS ADD RETURNABLE bit NULL CONSTRAINT [DF_RBOTRANSACTIONSALESTRANS_RETURNABLE] DEFAULT(1) with values
END