
/*

	Incident No.	: ONE-4605
	Responsible		: Helgi Rúnar Gunnarsson
	Sprint			: Sykurmolarnir

	Description		: Adding a column for default purchase price
	
						
*/

USE LSPOSNET
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'VENDORITEMS' AND COLUMN_NAME = 'DEFAULTPURCHASEPRICE')
BEGIN
	ALTER TABLE [dbo].[VENDORITEMS] ADD DEFAULTPURCHASEPRICE NUMERIC (28,12) NULL
	ALTER TABLE [dbo].[VENDORITEMS] ADD CONSTRAINT [DF_VENDORITEMS_DEFAULTPURCHASEPRICE] DEFAULT 0 FOR DEFAULTPURCHASEPRICE

END
GO

UPDATE VENDORITEMS
SET DEFAULTPURCHASEPRICE = 0
WHERE DEFAULTPURCHASEPRICE IS NULL

GO

