/*

	Incident No.	: ONE-5146
	Responsible		: Indriði Ingi Stefánsson
	Sprint			: Fræbblarninr
	Date created	: 30.9.2016

	Description		: Add new column
	
	
	Tables affected	: Reports
						
*/
USE LSPOSNET
GO
  
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'RBOTRANSACTIONTABLE' AND COLUMN_NAME = 'COMMENT' AND CHARACTER_MAXIMUM_LENGTH = 60  )

BEGIN
 ALTER TABLE [dbo].[RBOTRANSACTIONTABLE]  alter column  [COMMENT] [nvarchar](4000) NULL
END	


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'RBOTRANSACTIONTABLE' AND COLUMN_NAME = 'INVOICECOMMENT' AND CHARACTER_MAXIMUM_LENGTH = 60  )

BEGIN
ALTER TABLE [dbo].[RBOTRANSACTIONTABLE]  alter column  [INVOICECOMMENT] [nvarchar](max) NULL
END	

 
GO