/*

	Incident No.	: ONE-4933
	Responsible		: Marý Björk Steingrímsdóttir
	Sprint			: Súkkat
	Date created	: 07.10.2016

	Description		: Update field lengths
	
	
	Tables affected	: VendTable, ContactTable
						
*/

  
USE LSPOSNET
GO
  
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLE' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.VENDTABLE  
	ALTER COLUMN PHONE NVARCHAR(80)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLE' AND COLUMN_NAME = 'NAME' AND CHARACTER_MAXIMUM_LENGTH < 200  )
BEGIN
	ALTER TABLE dbo.VENDTABLE  
	ALTER COLUMN NAME NVARCHAR(200)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLE' AND COLUMN_NAME = 'ZIPCODE' AND CHARACTER_MAXIMUM_LENGTH < 20  )
BEGIN
	ALTER TABLE dbo.VENDTABLE  
	ALTER COLUMN ZIPCODE NVARCHAR(20)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLE' AND COLUMN_NAME = 'CITY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.VENDTABLE  
	ALTER COLUMN CITY NVARCHAR(250)
END	

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLE' AND COLUMN_NAME = 'COUNTY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.VENDTABLE  
	ALTER COLUMN COUNTY NVARCHAR(250)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLE' AND COLUMN_NAME = 'STATE' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.VENDTABLE  
	ALTER COLUMN [STATE] NVARCHAR(250)
END	
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'VENDTABLE' AND COLUMN_NAME = 'COUNTRY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.VENDTABLE  
	ALTER COLUMN COUNTRY NVARCHAR(250)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'FIRSTNAME' AND CHARACTER_MAXIMUM_LENGTH < 60  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN FIRSTNAME NVARCHAR(60)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'MIDDLENAME' AND CHARACTER_MAXIMUM_LENGTH < 60  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN MIDDLENAME NVARCHAR(60)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'LASTNAME' AND CHARACTER_MAXIMUM_LENGTH < 60  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN LASTNAME NVARCHAR(60)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'PHONE' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN PHONE NVARCHAR(80)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'PHONE2' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN PHONE2 NVARCHAR(80)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'FAX' AND CHARACTER_MAXIMUM_LENGTH < 80  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN FAX NVARCHAR(80)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'ZIPCODE' AND CHARACTER_MAXIMUM_LENGTH < 20  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN ZIPCODE NVARCHAR(20)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'CITY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN CITY NVARCHAR(250)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'COUNTY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN COUNTY NVARCHAR(250)
END	
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'STATE' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN [STATE] NVARCHAR(250)
END	
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME LIKE 'CONTACTTABLE' AND COLUMN_NAME = 'COUNTRY' AND CHARACTER_MAXIMUM_LENGTH < 250  )
BEGIN
	ALTER TABLE dbo.CONTACTTABLE  
	ALTER COLUMN COUNTRY NVARCHAR(250)
END	
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONTACTTABLE' AND COLUMN_NAME = 'NAME')
BEGIN
	ALTER TABLE dbo.CONTACTTABLE ADD NAME NVARCHAR(200)
END
GO