
/*

	Incident No.	: 
	Responsible		: Óskar Bjarnason
	Sprint			: LS Retail .NET 2012\Embla
	Date created	: 27.06.2012

	Description		: Alterning PK in table

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: STATIONSELECTIONS - Primary key changed
						
*/

--USE LSPOSNET

GO

--Drop Constraint

IF EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'STATIONSELECTION' AND CONSTRAINT_NAME = 'PK_STATIONSELECTION')
Begin
	Alter Table STATIONSELECTION
	DROP CONSTRAINT PK_STATIONSELECTION

End
GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('STATIONSELECTION') AND NAME='ROUTEID')
BEGIN
	ALTER TABLE dbo.STATIONSELECTION drop column ROUTEID
END
GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('STATIONSELECTION') AND NAME='ROUTEID')
BEGIN
	ALTER TABLE dbo.STATIONSELECTION add ROUTEID nvarchar(20) null
END
GO

--Set primary key

IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'STATIONSELECTION' AND CONSTRAINT_NAME = 'PK_STATIONSELECTION')
BEGIN

ALTER TABLE dbo.STATIONSELECTION ADD CONSTRAINT
		PK_STATIONSELECTION PRIMARY KEY CLUSTERED 
		(
		TYPE,
		CODE,
		STATIONID,
		SALESTYPE,
		RESTAURANTID,
		DATAAREAID
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

END












