/*

	Incident No.	: 17481
	Responsible		: Sigfús Jóhannesson
	Sprint			: LS Retail .NET 2013\Mercury
	Date created	: 27.06.2012

	Description		: Changing the PICTUREID/LOGOPICTUREID column type from int to nvarchar
	
	
	Tables affected	: POSISIMAGE
					  POSISTILLLAYOUT
						
*/

USE LSPOSNET

GO

IF((SELECT [DATA_TYPE] from [INFORMATION_SCHEMA].[COLUMNS] WHERE [TABLE_NAME] = 'POSISIMAGES' AND [COLUMN_NAME] = 'PICTUREID')= 'INT')
BEGIN

ALTER TABLE [dbo].[POSISIMAGES]
DROP CONSTRAINT [PK_POSISIMAGES]

ALTER TABLE [dbo].[POSISIMAGES]
ALTER COLUMN [PICTUREID] NVARCHAR(20) NOT NULL

ALTER TABLE [dbo].[POSISIMAGES]
ADD CONSTRAINT [PK_POSISIMAGES] PRIMARY KEY CLUSTERED 
(
	[PICTUREID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

END

IF((SELECT [DATA_TYPE] from [INFORMATION_SCHEMA].[COLUMNS] WHERE [TABLE_NAME] = 'POSISTILLLAYOUT' AND [COLUMN_NAME] = 'LOGOPICTUREID')= 'INT')
BEGIN

ALTER TABLE [dbo].[POSISTILLLAYOUT]
ALTER COLUMN [LOGOPICTUREID] NVARCHAR(20)

END
