/*

	Incident No.	: 17689
	Responsible		: Höður Sigurdór Heiðarsson
	Sprint			: LS Retail .NET 2013\Merkúr
	Date created	: 17.07.2012

	Description		: Add statement types to RBOStatementTable
	
	
	Tables affected	: RBOSTATEMENTTABLE
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTATEMENTTABLE') AND NAME='FROMTYPE')
BEGIN
	ALTER TABLE dbo.RBOSTATEMENTTABLE ADD FROMTYPE int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTATEMENTTABLE') AND NAME='TOTYPE')
BEGIN
	ALTER TABLE dbo.RBOSTATEMENTTABLE ADD TOTYPE int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTATEMENTTABLE') AND NAME='FROMPERIODTYPE')
BEGIN
	ALTER TABLE dbo.RBOSTATEMENTTABLE ADD FROMPERIODTYPE int NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('RBOSTATEMENTTABLE') AND NAME='TOPERIODTYPE')
BEGIN
	ALTER TABLE dbo.RBOSTATEMENTTABLE ADD TOPERIODTYPE int NULL
END
GO