/*

	Incident No.	:
	Responsible		: Olga Rún Kristjánsdóttir
	Sprint			: LS Retail .NET 2013\Merkúr
	Date created	: 24.07.2012

	Description		: Change id field of POSISFORMLAYOUT
	
	
	Tables affected	: POSISFORMLAYOUT - altered table
					  POSRECEIPTPROFILELINES - dropped columns
						
*/


Use LSPOSNET

GO

IF((SELECT [DATA_TYPE] from [INFORMATION_SCHEMA].[COLUMNS] WHERE [TABLE_NAME] = 'POSISFORMLAYOUT' AND [COLUMN_NAME] = 'ID')= 'INT')
BEGIN

ALTER TABLE [dbo].[POSISFORMLAYOUT]
DROP CONSTRAINT [PK_POSISFORMLAYOUT]

ALTER TABLE dbo.POSISFORMLAYOUT ALTER column ID nvarchar(20) not null

ALTER TABLE POSISFORMLAYOUT Add CONSTRAINT  PK_POSISFORMLAYOUT Primary Key (ID, DATAAREAID)

END
GO


IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSRECEIPTPROFILELINES') AND NAME='ISSLIP')
BEGIN
	ALTER TABLE dbo.POSRECEIPTPROFILELINES DROP column ISSLIP
END
GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSRECEIPTPROFILELINES') AND NAME='WIDTH')
BEGIN
	ALTER TABLE dbo.POSRECEIPTPROFILELINES DROP column WIDTH
END
GO



