/*

	Incident No.	:
	Responsible		: Olga Rún Kristjánsdóttir
	Sprint			: LS Retail .NET 2013\Merkúr
	Date created	: 19.07.2012

	Description		: Implement receipts profiles
	
	
	Tables affected	: POSRECEIPTTYPE - new table
					  POSRECEIPTPROFILE - new table
					  POSRECEIPTPROFILELINES - new table
					  POSISFORMLAYOUT - altered table
						
*/


Use LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE (OBJECT_ID = OBJECT_ID('[DBO].[POSRECEIPTTYPE]') AND TYPE IN ('U')) or (OBJECT_ID = OBJECT_ID('[DBO].[POSFORMTYPE]') AND TYPE IN ('U')))
BEGIN
	CREATE TABLE [dbo].POSFORMTYPE(
		ID uniqueidentifier NOT NULL,
		DESCRIPTION nvarchar(60) NOT NULL,
		SYSTEMTYPE tinyint NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
		)

	Alter table POSFORMTYPE Add CONSTRAINT  PK_POSRECEIPTTYPE Primary Key (ID, DATAAREAID)
END
GO


IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE (OBJECT_ID = OBJECT_ID('[DBO].[POSRECEIPTPROFILE]') AND TYPE IN ('U')) or (OBJECT_ID = OBJECT_ID('[DBO].[POSFORMPROFILE]') AND TYPE IN ('U')))
BEGIN
	CREATE TABLE [dbo].POSFORMPROFILE(
		PROFILEID uniqueidentifier NOT NULL,
		DESCRIPTION nvarchar(60) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
		)

	Alter table POSFORMPROFILE Add CONSTRAINT  PK_POSRECEIPTPROFILE Primary Key (PROFILEID, DATAAREAID)
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE (OBJECT_ID = OBJECT_ID('[DBO].[POSRECEIPTPROFILELINES]') AND TYPE IN ('U')) or (OBJECT_ID = OBJECT_ID('[DBO].[POSFORMPROFILELINES]') AND TYPE IN ('U')))
BEGIN
	CREATE TABLE [dbo].POSFORMPROFILELINES(
		PROFILEID uniqueidentifier NOT NULL,
		RECEIPTTYPEID uniqueidentifier NOT NULL,
		FORMLAYOUTID nvarchar(20) NOT NULL,
		[DATAAREAID] [nvarchar](4) NOT NULL
		)

	Alter table POSFORMPROFILELINES Add CONSTRAINT  PK_POSRECEIPTPROFILELINES Primary Key (PROFILEID,RECEIPTTYPEID, DATAAREAID)
END
GO


IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSISFORMLAYOUT') AND NAME='PROMPTTEXT')
BEGIN
	ALTER TABLE dbo.POSISFORMLAYOUT ADD PROMPTTEXT nvarchar(60) NULL
END
GO





