/*

	Incident No.	: 17690
	Responsible		: Olga Rún Kristjánsdóttir
	Sprint			: LS Retail .NET 2013\Merkúr
	Date created	: 02.08.2012

	Description		: Add RETAILGROUPREPLENISHMENT table
	
	
	Table created	: RETAILGROUPREPLENISHMENT
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[RETAILGROUPREPLENISHMENT]') AND TYPE IN ('U'))
BEGIN
	CREATE TABLE [dbo].[RETAILGROUPREPLENISHMENT](
	[ID] [uniqueidentifier] NOT NULL,
	[RETAILGROUPID] [varchar](20) NULL,
	[STOREID] [varchar](20) NULL,
	[REORDERPOINT] [int] NULL,
	[REORDERQUANTITY] [int] NULL,
	[DATAAREAID] [varchar](4) NOT NULL
	)
	Alter table [RETAILGROUPREPLENISHMENT] Add CONSTRAINT  PK_RETAILGROUPREPLENISHMENT Primary Key (ID,DATAAREAID)
END
GO
