/*

	Incident No.	: 17690
	Responsible		: Erna Guðrún Sigurðardóttir
	Sprint			: LS Retail .NET 2013\Merkúr
	Date created	: 02.08.2012

	Description		: Add TAXCALCULATIONMETHOD to VENDTABLE
	
	
	Tables affected	: VENDTABLE
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('VENDTABLE') AND NAME='TAXCALCULATIONMETHOD')
BEGIN
	ALTER TABLE dbo.VENDTABLE ADD TAXCALCULATIONMETHOD int NULL
END
GO
