/*

	Incident No.	: xxx
	Responsible		: Guðbjörn Einarsson
	Sprint			: LS Retail .NET 2013\Mercury
	Date created	: 15.08.2012

	Description		: Add column TOPLEFT, TOPCENTER, TOPRIGHT, BOTTOMLEFT, BOTTOMCENTER and BOTTOMRIGHT to KMINTERFACEPROFILE
	
	
	Tables affected	: KMINTERFACEPROFILE
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='TOPLEFT')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD TOPLEFT INT NULL

END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='TOPCENTER')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD TOPCENTER INT NULL

END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='TOPRIGHT')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD TOPRIGHT INT NULL

END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='BOTTOMLEFT')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD BOTTOMLEFT INT NULL

END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='BOTTOMCENTER')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD BOTTOMCENTER INT NULL

END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='BOTTOMRIGHT')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD BOTTOMRIGHT INT NULL

END
GO
