/*

	Incident No.	: 18003
	Responsible		: Olga Kristjánsdóttir
	Sprint			: LS Retail .NET 2013\Mercury
	Date created	: 09.08.2012

	Description		: Add DataAreaID to POSISRFIDTABLE
	
	
	Tables affected	: PURCHASEORDERLINE
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERLINE') AND NAME='RECEIVEDQUANTITY')
BEGIN
	ALTER TABLE dbo.PURCHASEORDERLINE ADD RECEIVEDQUANTITY DECIMAL(24,6) NULL

END
GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('PURCHASEORDERLINE') AND NAME='RECEIVEDQUANTITY')
BEGIN
	ALTER TABLE dbo.PURCHASEORDERLINE DROP COLUMN RECEIVEDQUANTITY

END
GO
