/*

	Incident No.	: xxx
	Responsible		: Sigfús Jóhannesson
	Sprint			: LS Retail .NET 2013\Mercury
	Date created	: 27.08.2012

	Description		: Add column LOCALLYSAVED
	
	
	Tables affected	: CUSTTABLE
						
*/
USE LSPOSNET
GO
  
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('CUSTTABLE') AND NAME='LOCALLYSAVED')
BEGIN
	IF EXISTS (SELECT * FROM SYSCONSTRAINTS WHERE CONSTID=OBJECT_ID('DF_CUSTTABLE_LOCALLYSAVED'))
	BEGIN
		ALTER TABLE dbo.CUSTTABLE DROP CONSTRAINT DF_CUSTTABLE_LOCALLYSAVED
	END
	ALTER TABLE dbo.CUSTTABLE add LOCALLYSAVED TINYINT NOT NULL CONSTRAINT DF_CUSTTABLE_LOCALLYSAVED DEFAULT '0'
END

GO
