/*

	Incident No.	: xxx
	Responsible		: Guðbjörn Einarsson
	Sprint			: LS Retail .NET 2013\Mercury
	Date created	: 27.08.2012

	Description		: Add column BUMPEDSTYLEID, VOIDEDSTYLEID, STARTEDSTYLEID, MODIFIEDITEMSTYLEID to KMINTERFACEPROFILE
	
	
	Tables affected	: KMINTERFACEPROFILE
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='BUMPEDSTYLEID')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD BUMPEDSTYLEID nvarchar(20) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='VOIDEDSTYLEID')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD VOIDEDSTYLEID nvarchar(20) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='STARTEDSTYLEID')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD STARTEDSTYLEID nvarchar(20) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='MODIFIEDITEMSTYLEID')
BEGIN
	ALTER TABLE dbo.KMINTERFACEPROFILE ADD MODIFIEDITEMSTYLEID nvarchar(20) NULL
END
GO
