/*

	Incident No.	: XXX
	Responsible		: Sigfus Johannesson
	Sprint			: LS Retail .NET 2013\Earth
	Date created	: 17.09.2012

	Description		: Adding the columns; CUSTOMERADDDEFAULTTAXGROUP and CUSTOMERADDDEFAULTTAXGROUPNAME
	
	
	Tables affected	: KMINTERFACEPROFILE
						
*/
USE LSPOSNET
GO
  
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSTRANSACTIONSERVICEPROFILE') AND NAME='CUSTOMERADDDEFAULTTAXGROUP')
BEGIN
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ADD CUSTOMERADDDEFAULTTAXGROUP NVARCHAR(20) NULL
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSTRANSACTIONSERVICEPROFILE') AND NAME='CUSTOMERADDDEFAULTTAXGROUPNAME')
BEGIN
	ALTER TABLE POSTRANSACTIONSERVICEPROFILE ADD CUSTOMERADDDEFAULTTAXGROUPNAME NVARCHAR(60) NULL
END
GO
