/*

	Incident No.	: 18602
	Responsible		: Erna Guðrún Sigurðardóttir
	Sprint			: LS Retail .NET 2013\Mercury
	Date created	: 17.09.2012

	Description		: Add column ITEMMODIFIERSPREFIX to table KMINTERFACEPROFILE
	
	
	Tables affected	: KMINTERFACEPROFILE
						
*/
USE LSPOSNET
GO
  
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='ITEMMODIFIERSPREFIX')
BEGIN
	ALTER TABLE KMINTERFACEPROFILE ADD ITEMMODIFIERSPREFIX nvarchar(50) NULL
END	
GO
