/*

	Incident No.	: XXX
	Responsible		: Oskar Bjarnason
	Sprint			: LS Retail .NET 2013\Earth
	Date created	: 17.09.2012

	Description		: Removing column ORDERTIMEDISPLAY and adding TimeFormat column to table KMINTERFACEPROFILE
	
	
	Tables affected	: KMINTERFACEPROFILE
						
*/
USE LSPOSNET
GO
  
IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='ORDERTIMEDISPLAY')
BEGIN
	ALTER TABLE KMINTERFACEPROFILE Drop column [ORDERTIMEDISPLAY]
END	
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('KMINTERFACEPROFILE') AND NAME='TIMEFORMAT')
BEGIN
	ALTER TABLE KMINTERFACEPROFILE ADD [TIMEFORMAT] nvarchar(10) NULL
END	
GO
