/*

	Incident No.	: PBI #8921
	Responsible		: Tobias Helmer
	Sprint			: 2012 - Sprint Baldur
	Date created	: 06.07.2011

	Description		: Created new table for blank operations			

	Logic scripts   : N.A.
	
	Table affected	: POSISBLANKOPERATIONS
						
						
*/

USE LSPOSNET
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[DBO].[POSISBLANKOPERATIONS]') AND TYPE IN ('U'))
BEGIN
CREATE TABLE [dbo].[POSISBLANKOPERATIONS](
	[OPERATIONNUMBER] [nvarchar](20) NOT NULL,
	[OPERATIONPARAMETER] [nvarchar](20) NULL,
	[OPERATIONDESCRIPTION] [varchar](50) NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
 CONSTRAINT [PK_POSISBLANKOPERATIONS] PRIMARY KEY CLUSTERED 
(
	[OPERATIONNUMBER] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
SET ANSI_PADDING OFF
ALTER TABLE [dbo].[POSISBLANKOPERATIONS] ADD  CONSTRAINT [DF_POSISBLANKOPERATIONS_OPERATIONPARAMETER]  DEFAULT ('') FOR [OPERATIONPARAMETER]
ALTER TABLE [dbo].[POSISBLANKOPERATIONS] ADD  CONSTRAINT [DF_POSISBLANKOPERATIONS_OPERATIONDESCRIPTION]  DEFAULT ('') FOR [OPERATIONDESCRIPTION]
END
GO