/*

	Incident No.	: PBI #8921
	Responsible		: Tobias Helmer
	Sprint			: 2012 - Sprint Baldur
	Date created	: 22.07.2011

	Description		: Column name change

	Logic scripts   : N.A.
	
	Table affected	: POSISBLANKOPERATIONS
						
						
*/

USE LSPOSNET

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSISBLANKOPERATIONS') AND NAME='OPERATIONNUMBER')
BEGIN
	EXECUTE sp_rename N'dbo.POSISBLANKOPERATIONS.OPERATIONNUMBER', N'Tmp_OPERATIONID', 'COLUMN' 
	EXECUTE sp_rename N'dbo.POSISBLANKOPERATIONS.Tmp_OPERATIONID', N'ID', 'COLUMN' 
END
GO

IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSISBLANKOPERATIONS') AND NAME='MGRPERMISSIONREQ')
BEGIN
	ALTER TABLE dbo.POSISBLANKOPERATIONS ADD MGRPERMISSIONREQ tinyint NOT NULL CONSTRAINT DF_POSISBLANKOPERATIONS_MGRPERMISSIONREQ DEFAULT 0
END
GO

