/*

	Incident No.	: 9327/9191/8647
	Responsible		: Tobias Helmer
	Sprint			: LS Retail.Net 2012\Sprint 1
	Date created	: 19.08.2011

	Description		: Change translations text

	Logic scripts   : No stored procedures added or changed
	
-- 	Tables affected	: PosisLanguageText
						
*/

USE LSPOSNET
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 10061)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '10061','Safe Drop Reversal Receipt',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Safe Drop Reversal Receipt', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 10061
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 10066)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '10066','Bank Drop Reversal Receipt',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Bank Drop Reversal Receipt', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 10066
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 10062)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '10062','Operator ID...:',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Operator ID...:', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 10062
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 10063)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '10063','Date.:',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Date.:', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 10063
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 10064)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '10064','Store ID......:',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Store ID......:', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 10064
GO

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 10065)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '10065','Time.:',0, '8.1.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Time.:', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 10065
GO
