
/*

	Incident No.	: 11380
	Responsible		: Guðbjörn Einarsson
	Sprint			: LS Retail .NET 2012/Tyr
	Date created	: 19.09.2001

	Description		: Add discount fields to PURCHASEORDERS table

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: PURCHASEORDERS	-	Add DEFAULTDISCOUNTPERCENTAGE
											Add  DEFAULTDISCOUNTAMOUNT
						
*/

USE LSPOSNET

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PURCHASEORDERS' AND COLUMN_NAME='DEFAULTDISCOUNTPERCENTAGE')
Begin
	Alter table PURCHASEORDERS 
	Add DEFAULTDISCOUNTPERCENTAGE decimal(24,6) Null
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PURCHASEORDERS' AND COLUMN_NAME='DEFAULTDISCOUNTAMOUNT')
Begin
	Alter table PURCHASEORDERS 
	Add DEFAULTDISCOUNTAMOUNT decimal(24,6) Null
END
GO




