
/*

	Incident No.	: 11718
	Responsible		: Hörður Kristjánsson
	Sprint			: LS Retail .NET 2012/Tyr
	Date created	: 13.09.2001

	Description		: Add translation texts

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: RboGiftCardTable			- fields added, default values added to fields
						
*/

USE LSPOSNET

GO




-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55407)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55407','Gift card balance is to low, current balance is:',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gift card balance is to low, current balance is:', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55407
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55407)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55407','Staða gjafakorts er of lág, núverandi staða er:',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Staða gjafakorts er of lág, núverandi staða er:', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55407

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55408)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55408','This gift card is not active',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'This gift card is not active', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55408
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55408)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55408','Þetta gjafakort er ekki virkt',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Þetta gjafakort er ekki virkt', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55408

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55409)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55409','Gift card not found',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gift card not found', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55409
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55409)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55409','Gjafakort fannst ekki',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gjafakort fannst ekki', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55409

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55410)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55410','Gift card validation successful',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gift card validation successful', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55410
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55410)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55410','Gjafakort heimilað',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gjafakort heimilað', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55410

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55411)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55411','Unknown error occurred during validation',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Unknown error occurred during validation', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55411
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55411)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55411','Óþekkt villa kom upp við heimilun gjafakorts',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Óþekkt villa kom upp við heimilun gjafakorts', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55411

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55500)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55500','Issue gift card',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Issue gift card', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55500
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55500)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55500','Gefa út gjafakort',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gefa út gjafakort', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55500

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55501)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55501','Ok',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Ok', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55501
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55501)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55501','Í lagi',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Í lagi', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55501

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55502)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55502','Cancel',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Cancel', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55502
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55502)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55502','Hætta við',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Hætta við', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55502

-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'en-US' and TEXTID = 55503)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('en-US', '55503','Gift card ID',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Gift card ID', DateUpdated = GetDate() where LANGUAGEID = 'en-US' AND TEXTID = 55503
-- IF NOT EXISTS (SELECT * FROM POSISLANGUAGETEXT WHERE LANGUAGEID = 'is-IS' and TEXTID = 55503)
-- INSERT INTO POSISLANGUAGETEXT (LANGUAGEID, TEXTID, TEXT, ERRORTEXT, FIRSTINVERSION) VALUES ('is-IS', '55503','Númer gjafakorts',0, '8.2.0.0')
-- UPDATE POSISLANGUAGETEXT SET TEXT = 'Númer gjafakorts', DateUpdated = GetDate() where LANGUAGEID = 'is-IS' AND TEXTID = 55503

GO



