/*

	Incident No.	: 
	Responsible		: Tobias Helmer
	Sprint			: 
	Date created	: 22.09.2011

	Description		: PBI #12057 added 5 checkboxes within the options-group of the functionality profile; this required dropping one column and adding 5 columns 

	Logic scripts   : No stored procedures added or changed
	
	Tables affected	: POSFUNCTIONALITYPROFILE					  
						
*/

USE LSPOSNET

GO

IF EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILE') AND NAME='CASHCOUNTINGUSESNUMPAD')
BEGIN
	IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POSFUNCTIONALITYPROFILE_CASHCOUNTINGUSESNUMPAD]') AND type = 'D')
	ALTER TABLE [dbo].[POSFUNCTIONALITYPROFILE] DROP CONSTRAINT [DF_POSFUNCTIONALITYPROFILE_CASHCOUNTINGUSESNUMPAD]
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE DROP COLUMN CASHCOUNTINGUSESNUMPAD
END
GO
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILE') AND NAME='SAFEDROPUSESNUMPAD')	
BEGIN
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD SAFEDROPUSESNUMPAD tinyint NULL
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_SAFEDROPUSESNUMPAD DEFAULT 0 FOR SAFEDROPUSESNUMPAD
END
GO
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILE') AND NAME='SAFEDROPREVUSESNUMPAD')	
BEGIN
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD SAFEDROPREVUSESNUMPAD tinyint NULL
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_SAFEDROPREVUSESNUMPAD DEFAULT 0 FOR SAFEDROPREVUSESNUMPAD
END
GO
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILE') AND NAME='BANKDROPUSESNUMPAD')
BEGIN
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD BANKDROPUSESNUMPAD tinyint NULL
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_BANKDROPUSESNUMPAD DEFAULT 0 FOR BANKDROPUSESNUMPAD
END
GO
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILE') AND NAME='BANKDROPREVUSESNUMPAD')
BEGIN
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD BANKDROPREVUSESNUMPAD tinyint NULL
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_BANKDROPREVUSESNUMPAD DEFAULT 0 FOR BANKDROPREVUSESNUMPAD
END
GO
IF NOT EXISTS (SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('POSFUNCTIONALITYPROFILE') AND NAME='TENDERDECLUSESNUMPAD')
BEGIN
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD TENDERDECLUSESNUMPAD tinyint NULL
	ALTER TABLE dbo.POSFUNCTIONALITYPROFILE ADD CONSTRAINT DF_POSFUNCTIONALITYPROFILE_TENDERDECLUSESNUMPAD DEFAULT 0 FOR TENDERDECLUSESNUMPAD
END
GO
	